sas-core/main/default/objects/IRR_DelayLog__c/IRR_DelayLog__c.object-meta.xml
<CustomObject>
    <description>Stores a list of previously communicated delays for flights</description>
    <label>Delay Log</label>
    <nameField>
        <displayFormat>DLOG-{000000}</displayFormat>
        <label>Delay Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_DelayLog__c/fields/IRR_DelayMinutes__c.field-meta.xml
<CustomField>
    <fullName>IRR_DelayMinutes__c</fullName>
    <label>Delay Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_DelayLog__c/fields/IRR_FlightId__c.field-meta.xml
<CustomField>
    <fullName>IRR_FlightId__c</fullName>
    <externalId>true</externalId>
    <label>Flight Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_DelayLogsSelector_Test.cls
/**
* @author Niklas Lundkvist, Deloitte
* @date 2020
*
* @description Test class for Delay Logs selector.
*/

@IsTest
private class IRR_SEL_DelayLogsSelector_Test {

    @IsTest
    static void testGetLatestDelayByFlightIds() {
        //Given
        List<IRR_DelayLog__c> delayLogs = new List<IRR_DelayLog__c>{
                new IRR_DelayLog__c(IRR_FlightId__c='TEST_FLIGHT', IRR_DelayMinutes__c=10)
        };
        insert delayLogs;

        //When
        Map<String, Integer> flightDelayByIds = IRR_SEL_DelayLogsSelector.newInstance()
                .getLatestDelayByFlightIds(new Set<String>{'TEST_FLIGHT', 'OTHER_FLIGHT'});

        //Then
        System.assert(!flightDelayByIds.containsKey('OTHER_FLIGHT'), 'Other flight has no delay logs');
        System.assert(flightDelayByIds.containsKey('TEST_FLIGHT'), 'Result should contain delay for TEST_FLIGHT');
        System.assertEquals(10 ,flightDelayByIds.get('TEST_FLIGHT'), 'Latest delay should be 10 for TEST_FLIGHT');
    }
}