sas-core/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBBalance__c.field-meta.xml
<CustomField>
    <fullName>EBBalance__c</fullName>
    <description>EuroBonus Balance for customer</description>
    <label>EuroBonus Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuroBonus level/tier for customer</description>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/EBMbrshipLvlStatusEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBMbrshipLvlStatusEndDate__c</fullName>
    <description>End of current status level for customer&#39;s EuroBonus engagement</description>
    <label>EB Level End Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBMbrshipLvlStatusStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBMbrshipLvlStatusStartDate__c</fullName>
    <description>Start of membership level for customer EuroBonus engagement</description>
    <label>EB Level Start Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer became a EuroBonus member</description>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBReachesNextLevelPoints__c.field-meta.xml
<CustomField>
    <fullName>EBReachesNextLevelPoints__c</fullName>
    <description>Amount of points when the EuroBonus customer reaches the next EuroBonus level</description>
    <label>Reaches Next Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>Base</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Silver</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Gold</label>
            </value>
			<value>
                <fullName>D</fullName>
                <label>Diamond</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Pandion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/FrequentFlyer__x.object-meta.xml
<CustomObject>
    <description>External object used to hold data from SAS source systems regarding customer</description>
    <externalDataSource>SAS_External_Systems</externalDataSource>
    <externalName>FrequentFlyers</externalName>
    <label>Frequent Flyer</label>
    <pluralLabel>Frequent Flyers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/FrequentFlyer__x/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>First line if a customers physical address</description>
    <externalDeveloperName>AddressLine1</externalDeveloperName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <description>Second line if a customers physical address</description>
    <externalDeveloperName>HomeAddressLine2</externalDeveloperName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/AddressLine3__c.field-meta.xml
<CustomField>
    <fullName>AddressLine3__c</fullName>
    <description>Third line of a customers physical address</description>
    <externalDeveloperName>addressLine3</externalDeveloperName>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <externalDeveloperName>BirthDate</externalDeveloperName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City of customer</description>
    <externalDeveloperName>city</externalDeveloperName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEB0__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB0__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</description>
    <externalDeveloperName>ConsentEB0</externalDeveloperName>
    <inlineHelpText>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</inlineHelpText>
    <label>Consent EuroBonus0</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEB__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to EuroBonus</description>
    <externalDeveloperName>consentEB</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to EuroBonus</inlineHelpText>
    <label>Consent EuroBonus</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <externalDeveloperName>consentEmail</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive Email</inlineHelpText>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <externalDeveloperName>ConsentSMS</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive SMS</inlineHelpText>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <externalDeveloperName>consentTelemarketing</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to Telemarketing</inlineHelpText>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country of customer</description>
    <externalDeveloperName>CountryCode</externalDeveloperName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/CountyState__c.field-meta.xml
<CustomField>
    <fullName>CountyState__c</fullName>
    <description>County or state that customer lives in</description>
    <externalDeveloperName>HomeCountyState</externalDeveloperName>
    <label>County/State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBBalance__c.field-meta.xml
<CustomField>
    <fullName>EBBalance__c</fullName>
    <description>EuroBonus Balance of customer</description>
    <externalDeveloperName>euroBonusBalance</externalDeveloperName>
    <label>EuroBonus Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuruBonus Level of customer</description>
    <externalDeveloperName>euroBonusLevel</externalDeveloperName>
    <label>EuroBonus Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBMbrshipLvlStatusEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBMbrshipLvlStatusEndDate__c</fullName>
    <description>End of current status level for customer&#39;s EuroBonus engagement</description>
    <externalDeveloperName>MbrshipLvlStatusEndPeriod</externalDeveloperName>
    <label>EB Level End Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBMbrshipLvlStatusStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBMbrshipLvlStatusStartDate__c</fullName>
    <description>Start of membership level for customer EuroBonus engagement</description>
    <externalDeveloperName>MbrshipLvlStatusStartPeriod</externalDeveloperName>
    <label>EB Level Start Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer first became a EuroBonus member</description>
    <externalDeveloperName>EnrollmentDate</externalDeveloperName>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus Number of customer</description>
    <externalDeveloperName>euroBonusNumber</externalDeveloperName>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EmailPersonal__c.field-meta.xml
<CustomField>
    <fullName>EmailPersonal__c</fullName>
    <description>Personal email to customer</description>
    <externalDeveloperName>VirtualAddressLineEmail</externalDeveloperName>
    <label>Email - Personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of customer</description>
    <externalDeveloperName>firstName</externalDeveloperName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <externalDeveloperName>Gender</externalDeveloperName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last Name of customer</description>
    <externalDeveloperName>LastName</externalDeveloperName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>Mobile phone number of customer</description>
    <externalDeveloperName>HomeMobile</externalDeveloperName>
    <label>Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Full name of customer</description>
    <externalDeveloperName>FullName</externalDeveloperName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of customer, not mobile number</description>
    <externalDeveloperName>HomePhone</externalDeveloperName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/globalValueSets/EuroBonusLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Base</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Silver</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Gold</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Diamond</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Pandion</label>
    </customValue>
    <masterLabel>EuroBonus Level</masterLabel>
</GlobalValueSet>

sas-core/main/default/classes/IdentifyCustomerComponentController.cls
/**
 * @author Anton Norell
 * @date 2019-10-01
 * @description Controller for component used to identify a customer from a Salesforce record. Includes methods
 * to retrieve data and create data.
 */
public with sharing class IdentifyCustomerComponentController {
    /**
     * Used to handle request to fins a customer from the component. A list of frequent flyer record is fetched by
     * a query, and then the first record in the list is synced to a corresponding account record in Salesforce.
     * If the account already exists it is updated, otherwise created.
     * @param searchField Field on Frequent Flyer object to use as filter to retrieve customer, e.g. EBNumber__c
     * @param searchValue Value for the search field, e.g. a EuroBonus number
     * @return If an account is found it is returned, otherwise null,
     */
    @AuraEnabled
    public static Account findCustomer(String searchField, String searchValue){
        String query = 'SELECT Id, ExternalId, AddressLine1__c, AddressLine2__c, AddressLine3__c, BirthDate__c, ' +
                        'City__c, ConsentTelemarketing__c, ConsentEB0__c, ConsentSMS__c, ConsentEB__c, ConsentEmail__c, ' +
                        'CountryCode__c, CountyState__c, EmailPersonal__c, EBBalance__c, EBLevel__c, EBNumber__c, ' +
                        'FirstName__c, LastName__c, Gender__c, EBMemberSinceDate__c, Mobile__c, Name__c, Phone__c, ' +
                        'EBMbrshipLvlStatusStartDate__c, EBMbrshipLvlStatusEndDate__c, EBReachesNextLevelPoints__c, ' +
                        'SubscriptionId__c, TPAccountNumber__c, ZipCode__c, CompanyName__c, Title__c, MiddleName__c, Salutation__c ' +
                        'FROM FrequentFlyer__x ' +
                        'WHERE ' + searchField + ' = \'' + searchValue + '\'';
        List<FrequentFlyer__x> externalData = Database.query(query);
        return createAccountRecordBasedOnFrequentFlyers(externalData);
    }

    /**
     * Used to create an account based on a Frequent Flyer record. If additional fields are added in the mapping
     * below, they also have to be added to the query retrieving the frequent flyer record.
     * @param frequentFlyers List of Frequent Flyer record to generate accounts for
     * @return List of account generated
     */
    @TestVisible
    private static Account createAccountRecordBasedOnFrequentFlyers(List<FrequentFlyer__x> frequentFlyers){
        List<Account> accounts = new List<Account>();
        for(FrequentFlyer__x ff:frequentFlyers){
            Account newAccount = new Account(
                    RecordTypeId = RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
                    CODSId__c = ff.ExternalId,
                    FrequentFlyer__c = ff.ExternalId,
                    PersonMailingStreet = ff.AddressLine1__c,
                    PersonMailingCity = ff.City__c,
                    PersonMailingPostalCode = ff.ZipCode__c,
                    PersonMailingCountry = ff.CountryCode__c,
                    PersonMailingState = ff.CountyState__c,
                    PersonBirthdate = ff.BirthDate__c != null ? Date.valueOf(ff.BirthDate__c) : null,
                    ConsentEmail__c = ff.ConsentEmail__c,
                    ConsentEuroBonus__c = ff.ConsentEB__c,
                    ConsentSMS__c = ff.ConsentSMS__c,
                    ConsentSiteProfile__c = ff.ConsentEB0__c,
                    ConsentTelemarketing__c = ff.ConsentTelemarketing__c,
                    PersonEmail = ff.EmailPersonal__c,
                    EBBalance__c = ff.EBBalance__c,
                    EBLevel__c = ff.EBLevel__c,
                    EBNumber__c = ff.EBNumber__c,
                    FirstName = ff.FirstName__c,
                    Gender__c = ff.Gender__c,
                    LastName = ff.LastName__c,
                    EBMemberSinceDate__c = ff.EBMemberSinceDate__c != null ? Date.valueOf(ff.EBMemberSinceDate__c) : null,
                    PersonMobilePhone = ff.Mobile__c,
                    PersonHomePhone = ff.Phone__c,
                    EBMbrshipLvlStatusEndDate__c = ff.EBMbrshipLvlStatusEndDate__c != null ? Date.valueOf(ff.EBMbrshipLvlStatusEndDate__c) : null,
                    EBMbrshipLvlStatusStartDate__c = ff.EBMbrshipLvlStatusStartDate__c != null ? Date.valueOf(ff.EBMbrshipLvlStatusStartDate__c) : null,
                    EBReachesNextLevelPoints__c = ff.EBReachesNextLevelPoints__c,
                    SubscriptionId__c = ff.SubscriptionId__c,
                    TPAccountNumber__c = ff.TPAccountNumber__c,
                    CompanyName__c = ff.CompanyName__c,
                    PersonTitle = ff.Title__c,
                    Salutation = ff.Salutation__c,
                    MiddleName = ff.MiddleName__c,
                    LastRetrievedFromSource__c = Datetime.now()
            );
            accounts.add(newAccount);
        }
        if(!accounts.isEmpty()){
            upsert accounts[0] CODSId__c;
            return accounts[0];
        }
        return null;
    }

    /**
     * Used to retrieve case data for the case record that the controller is called from.
     * @param caseId Id for case to retrieve data
     * @return Case record corresponding to the supplied Id
     */
    @AuraEnabled(Cacheable=true)
    public static Case getCaseData(Id caseId){
        return [SELECT Id, AccountId, EBNumber__c, TPAccountNumber__c, Account.FrequentFlyer__c, Account.LastRetrievedFromSource__c FROM Case WHERE Id = :caseId];
    }
}