sas-core/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBBalance__c.field-meta.xml
<CustomField>
    <fullName>EBBalance__c</fullName>
    <description>EuroBonus Balance for customer</description>
    <label>EuroBonus Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuroBonus level/tier for customer</description>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer became a EuroBonus member</description>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBQualifyingPeriodEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBQualifyingPeriodEndDate__c</fullName>
    <description>End date for the customer&#39;s current qualifying period for EuroBonus</description>
    <label>Qualifying Period End</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBQualifyingPeriodStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBQualifyingPeriodStartDate__c</fullName>
    <description>Start of qualifying period for customer EuroBonus engagement</description>
    <label>Qualifying Period Start</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/LastRetrievedFromSource__c.field-meta.xml
<CustomField>
    <fullName>LastRetrievedFromSource__c</fullName>
    <description>Datetime for when this account was last retrieved from source system. Used to determine if customer should be retrieved at certain points in time, e.g. when opening a case.</description>
    <label>Last Retrieved From Source</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Account/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>Base</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Silver</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Gold</label>
            </value>
			<value>
                <fullName>D</fullName>
                <label>Diamond</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Pandion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&#39;s Travel Pass account</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Information.recordType-meta.xml
<RecordType>
    <fullName>Information</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Information</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/objects/FrequentFlyer__x/FrequentFlyer__x.object-meta.xml
<CustomObject>
    <description>External object used to hold data from SAS source systems regarding customer</description>
    <externalDataSource>SAS_External_Systems</externalDataSource>
    <externalName>FrequentFlyers</externalName>
    <label>Frequent Flyer</label>
    <pluralLabel>Frequent Flyers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/FrequentFlyer__x/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>First line if a customers physical address</description>
    <externalDeveloperName>AddressLine1</externalDeveloperName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <externalDeveloperName>BirthDate</externalDeveloperName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City of customer</description>
    <externalDeveloperName>city</externalDeveloperName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEB0__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB0__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</description>
    <externalDeveloperName>ConsentEB0</externalDeveloperName>
    <inlineHelpText>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</inlineHelpText>
    <label>Consent EuroBonus0</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEB__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to EuroBonus</description>
    <externalDeveloperName>consentEB</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to EuroBonus</inlineHelpText>
    <label>Consent EuroBonus</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <externalDeveloperName>consentEmail</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive Email</inlineHelpText>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <externalDeveloperName>ConsentSMS</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive SMS</inlineHelpText>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <externalDeveloperName>consentTelemarketing</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to Telemarketing</inlineHelpText>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country of customer</description>
    <externalDeveloperName>CountryCode</externalDeveloperName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/CountyState__c.field-meta.xml
<CustomField>
    <fullName>CountyState__c</fullName>
    <description>County or state that customer lives in</description>
    <externalDeveloperName>HomeCountyState</externalDeveloperName>
    <label>County/State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBBalance__c.field-meta.xml
<CustomField>
    <fullName>EBBalance__c</fullName>
    <description>EuroBonus Balance of customer</description>
    <externalDeveloperName>euroBonusBalance</externalDeveloperName>
    <label>EuroBonus Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuruBonus Level of customer</description>
    <externalDeveloperName>euroBonusLevel</externalDeveloperName>
    <label>EuroBonus Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer first became a EuroBonus member</description>
    <externalDeveloperName>EnrollmentDate</externalDeveloperName>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus Number of customer</description>
    <externalDeveloperName>euroBonusNumber</externalDeveloperName>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBQualifyingPeriodEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBQualifyingPeriodEndDate__c</fullName>
    <description>End of qualifying period for customer EuroBonus engagement</description>
    <externalDeveloperName>MbrshipLvlStatusEndPeriod</externalDeveloperName>
    <label>Qualifying Period End</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/EmailPersonal__c.field-meta.xml
<CustomField>
    <fullName>EmailPersonal__c</fullName>
    <description>Personal email to customer</description>
    <externalDeveloperName>VirtualAddressLineEmail</externalDeveloperName>
    <label>Email - Personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of customer</description>
    <externalDeveloperName>firstName</externalDeveloperName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <externalDeveloperName>Gender</externalDeveloperName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last Name of customer</description>
    <externalDeveloperName>LastName</externalDeveloperName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>Mobile phone number of customer</description>
    <externalDeveloperName>HomeMobile</externalDeveloperName>
    <label>Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of customer, not mobile number</description>
    <externalDeveloperName>HomePhone</externalDeveloperName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&#39;s Travel Pass account</description>
    <externalDeveloperName>TravelPassAccountNumber</externalDeveloperName>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>Zip Code of customer</description>
    <externalDeveloperName>ZipCode</externalDeveloperName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/globalValueSets/EuroBonusLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Base</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Silver</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Gold</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Diamond</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Pandion</label>
    </customValue>
    <masterLabel>EuroBonus Level</masterLabel>
</GlobalValueSet>

sas-core/main/default/classes/IdentifyCustomerComponentController_Test.cls
/**
 * @author Anton Norell
 * @date 2019-12-05
 * @description Test class for controller IdentifyCustomerComponentController
 */
@IsTest
private class IdentifyCustomerComponentController_Test {
    /**
     * Asserts that the correct case and fields are retrieved from method in controller
     */
    @IsTest
    static void shouldReturnCaseBasedOnCaseId(){
        Account acc = new Account(
                RecordTypeId = RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
                LastName = 'Last Name'
        );
        insert acc;
        Case originalCase = new Case(
                AccountId = acc.Id,
                EBNumber__c = '123',
                TPAccountNumber__c = '321'
        );
        insert originalCase;

        Case retrievedCase = IdentifyCustomerComponentController.getCaseData(originalCase.Id);

        System.assertNotEquals(null, retrievedCase);
        System.assertEquals(originalCase.EBNumber__c, retrievedCase.EBNumber__c);
        System.assertEquals(acc.Id, retrievedCase.AccountId);
        System.assertEquals(null, retrievedCase.Account.LastRetrievedFromSource__c);
    }

    /**
     * Asserts that the controller maps information from a frequent flyer record to an account record correctly.
     * Checks both valid values and null values.
     */
    @IsTest
    static void shouldReturnAccountBasedOnFrequentFlyer(){
        FrequentFlyer__x ff = new FrequentFlyer__x(
                ExternalId = '123',
                AddressLine1__c = 'AddressLine1',
                City__c = 'City',
                ZipCode__c = 'ZipCode',
                CountryCode__c = 'Country',
                CountyState__c = 'State',
                BirthDate__c = Date.today().addYears(-2),
                ConsentEmail__c = true,
                ConsentEB__c = false,
                ConsentSMS__c = true,
                ConsentEB0__c = false,
                ConsentTelemarketing__c = true,
                EmailPersonal__c = 'email@email.com',
                EBBalance__c = 1000,
                EBLevel__c = null,
                EBNumber__c = '321',
                FirstName__c = 'First Name',
                Gender__c = 'F',
                LastName__c = 'Last Name',
                EBMemberSinceDate__c = null,
                Mobile__c = '0701234567',
                Phone__c = null,
                EBQualifyingPeriodEndDate__c = Date.today().addYears(1),
                EBQualifyingPeriodStartDate__c = Date.today(),
                EBReachesNextLevelPoints__c = null,
                SubscriptionId__c = null,
                TPAccountNumber__c = '678',
                CompanyName__c = 'Company Name',
                MiddleName__c = 'Middle',
                Salutation__c = 'Salutation',
                Title__c = 'Title'
        );

        Account account = IdentifyCustomerComponentController.createAccountRecordBasedOnFrequentFlyers(
                new List<FrequentFlyer__x>{ff}
        );

        System.assertNotEquals(null, account, 'Method did not return expected account');
        System.assertEquals(RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER, account.RecordTypeId);
        System.assertEquals(ff.ExternalId, account.FrequentFlyer__c);
        System.assertEquals(ff.AddressLine1__c, account.PersonMailingStreet);
        System.assertEquals(ff.City__c, account.PersonMailingCity);
        System.assertEquals(ff.ZipCode__c, account.PersonMailingPostalCode);
        System.assertEquals(ff.CountryCode__c, account.PersonMailingCountry);
        System.assertEquals(ff.CountyState__c, account.PersonMailingState);
        System.assertEquals(ff.BirthDate__c, account.PersonBirthdate);
        System.assertEquals(ff.ConsentEmail__c, account.ConsentEmail__c);
        System.assertEquals(ff.ConsentEB__c, account.ConsentEuroBonus__c);
        System.assertEquals(ff.ConsentEB0__c, account.ConsentSiteProfile__c);
        System.assertEquals(ff.ConsentSMS__c, account.ConsentSMS__c);
        System.assertEquals(ff.ConsentTelemarketing__c, account.ConsentTelemarketing__c);
        System.assertEquals(ff.EmailPersonal__c, account.PersonEmail);
        System.assertEquals(ff.EBBalance__c, account.EBBalance__c);
        System.assertEquals(ff.EBLevel__c, account.EBLevel__c);
        System.assertEquals(ff.EBNumber__c, account.EBNumber__c);
        System.assertEquals(ff.FirstName__c, account.FirstName);
        System.assertEquals(ff.Gender__c, account.Gender__c);
        System.assertEquals(ff.LastName__c, account.LastName);
        System.assertEquals(ff.EBMemberSinceDate__c, account.EBMemberSinceDate__c);
        System.assertEquals(ff.EBQualifyingPeriodEndDate__c, account.EBQualifyingPeriodEndDate__c);
        System.assertEquals(ff.EBQualifyingPeriodStartDate__c, account.EBQualifyingPeriodStartDate__c);
        System.assertEquals(ff.EBReachesNextLevelPoints__c, account.EBReachesNextLevelPoints__c);
        System.assertEquals(ff.SubscriptionId__c, account.SubscriptionId__c);
        System.assertEquals(ff.TPAccountNumber__c, account.TPAccountNumber__c);
        System.assertEquals(ff.CompanyName__c, account.CompanyName__c);
        System.assertEquals(ff.Title__c, account.PersonTitle);
        System.assertEquals(ff.Salutation__c, account.Salutation);
        System.assertEquals(ff.MiddleName__c, account.MiddleName);
        System.assert(account.LastRetrievedFromSource__c > DateTime.now().addMinutes(-5)
                && account.LastRetrievedFromSource__c < DateTime.now().addMinutes(5));
    }

    /**
     * Asserts that an account record is inserted based on a provided Frequent Flyer record provided to controller
     */
    @IsTest
    static void shouldInsertBasedOnFrequentFlyer(){
        FrequentFlyer__x ff = new FrequentFlyer__x(
                ExternalId = '123',
                AddressLine1__c = 'AddressLine1',
                City__c = 'City',
                ZipCode__c = 'ZipCode',
                CountryCode__c = 'Country',
                CountyState__c = 'State',
                BirthDate__c = Date.today().addYears(-2),
                ConsentEmail__c = true,
                ConsentEB__c = false,
                ConsentSMS__c = true,
                ConsentEB0__c = false,
                ConsentTelemarketing__c = true,
                EmailPersonal__c = 'email@email.com',
                EBBalance__c = 1000,
                EBLevel__c = null,
                EBNumber__c = '321',
                FirstName__c = 'First Name',
                Gender__c = 'F',
                LastName__c = 'Last Name',
                EBMemberSinceDate__c = null,
                Mobile__c = '0701234567',
                Phone__c = null,
                EBQualifyingPeriodEndDate__c = Date.today().addYears(1),
                EBQualifyingPeriodStartDate__c = Date.today(),
                EBReachesNextLevelPoints__c = null,
                SubscriptionId__c = null,
                TPAccountNumber__c = '678',
                CompanyName__c = 'Company Name',
                MiddleName__c = 'Middle',
                Salutation__c = 'Salutation',
                Title__c = 'Title'
        );

        IdentifyCustomerComponentController.createAccountRecordBasedOnFrequentFlyers(new List<FrequentFlyer__x>{ff});

        System.assertEquals(1, [SELECT Id FROM Account].size(), 'Expected 1 account to be inserted based on Frequent Flyer');
    }

    /**
     * Asserts that the controller can handle an empty return when querying for Frequent Flyer
     */
    @IsTest
    static void shouldReturnNullIfFrequentFlyerListIfEmpty(){
        Account account = IdentifyCustomerComponentController.createAccountRecordBasedOnFrequentFlyers(
                new List<FrequentFlyer__x>()
        );

        System.assertEquals(null, account);
    }

    /**
     * Asserts that the query for the external object Frequent Flyer can run correctly. As external object queries
     * are not supported in test context, the test should return a null result.
     */
    @IsTest
    static void shouldReturnNullResultDueToNoSupportForQuery(){
        Account account = IdentifyCustomerComponentController.findCustomer('EBNumber__c', '700001423');

        System.assertEquals(null, account);
    }

    /**
     * Asserts that the query for the external object Frequent Flyer can run correctly. As external object queries
     * are not supported in test context, the test catches the expected exception and verifies the message.
     *//*
    @IsTest
    static void shouldThrowExceptionDueToUnsupportedExternalObjectQuery(){
        Exception returnedException;
        try{
            Account account = IdentifyCustomerComponentController.findCustomer('EBNumber__c', '700001423');

        } catch (QueryException e){
            returnedException = e;
        }
        System.assertNotEquals(null, returnedException, 'Expected a QueryException to be thrown');
        System.assertEquals('entity type FrequentFlyer__x does not support query',
                returnedException.getMessage(),
                'Expected the exception to contain another message. Check that used query is not malformed. '
        );
    }*/
}