sas-core/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuroBonus level/tier for customer</description>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer became a EuroBonus member</description>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Account/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <description>Unique identifier for customer in CODA. Corresponds to ExternalId on Frequent Flyer.</description>
    <externalId>true</externalId>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBLevel__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBLevel__c</fullName>
    <description>Current EuroBonus level/tier for customer</description>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <externalId>true</externalId>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/SubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionId__c</fullName>
    <description>Unique identifier for customer&#39;s subscription engagement</description>
    <externalId>true</externalId>
    <label>Subscription Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/C_GeneralSetting__mdt/C_GeneralSetting__mdt.object-meta.xml
<CustomObject>
    <description>General purpose settings metadata where group of settins can stored for different purposes.</description>
    <label>General Setting</label>
    <pluralLabel>General Settings</pluralLabel>
</CustomObject>

sas-core/main/default/objects/C_GeneralSetting__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>The group which the setting is associated with.</description>
    <inlineHelpText>The group which the setting is associated with.</inlineHelpText>
    <label>Group</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/C_GeneralSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of the setting. If boolean this value should be true/false.</description>
    <label>Value</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>Base</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Silver</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Gold</label>
            </value>
			<value>
                <fullName>D</fullName>
                <label>Diamond</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Pandion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBLevel__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBLevel__c</fullName>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&apos;s Travel Pass account</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&#39;s Travel Pass account</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Used to manage all chat related cases</description>
    <label>Chat</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Information.recordType-meta.xml
<RecordType>
    <fullName>Information</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Information</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/objects/FCS_FrequentFlyer__x/FCS_FrequentFlyer__x.object-meta.xml
<CustomObject>
    <description>External object used to hold data from SAS source systems regarding customer</description>
    <externalDataSource>SAS_External_Systems</externalDataSource>
    <externalName>FrequentFlyers</externalName>
    <label>Frequent Flyer</label>
    <pluralLabel>Frequent Flyers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>First line if a customers physical address</description>
    <externalDeveloperName>HomeAddressLine1</externalDeveloperName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of customer</description>
    <externalDeveloperName>BirthDate</externalDeveloperName>
    <label>Birth Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City of customer</description>
    <externalDeveloperName>HomeCityName</externalDeveloperName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/ConsentEB0__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB0__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</description>
    <externalDeveloperName>ConsentEB0</externalDeveloperName>
    <inlineHelpText>Indicates that customer has not given consent to EuroBonus, but to having a SAS portal account</inlineHelpText>
    <label>Consent EuroBonus0</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/ConsentEB__c.field-meta.xml
<CustomField>
    <fullName>ConsentEB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to EuroBonus</description>
    <externalDeveloperName>ConsentEB</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to EuroBonus</inlineHelpText>
    <label>Consent EuroBonus</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/ConsentEmail__c.field-meta.xml
<CustomField>
    <fullName>ConsentEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive Email</description>
    <externalDeveloperName>ConsentEMail</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive Email</inlineHelpText>
    <label>Consent Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/ConsentSMS__c.field-meta.xml
<CustomField>
    <fullName>ConsentSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to receive SMS</description>
    <externalDeveloperName>ConsentSMS</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to receive SMS</inlineHelpText>
    <label>Consent SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/ConsentTelemarketing__c.field-meta.xml
<CustomField>
    <fullName>ConsentTelemarketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that customer has given consent to Telemarketing</description>
    <externalDeveloperName>ConsentTelemarketing</externalDeveloperName>
    <inlineHelpText>Indicates that customer has given consent to Telemarketing</inlineHelpText>
    <label>Consent Telemarketing</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/EBLevel__c.field-meta.xml
<CustomField>
    <fullName>EBLevel__c</fullName>
    <description>Current EuruBonus Level of customer</description>
    <externalDeveloperName>IncentiveLevel</externalDeveloperName>
    <label>EuroBonus Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/EBMemberSinceDate__c.field-meta.xml
<CustomField>
    <fullName>EBMemberSinceDate__c</fullName>
    <description>Date when customer first became a EuroBonus member</description>
    <externalDeveloperName>EnrollmentDate</externalDeveloperName>
    <label>Member Since</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus Number of customer</description>
    <externalDeveloperName>EuroBonusNumber</externalDeveloperName>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of customer</description>
    <externalDeveloperName>FirstName</externalDeveloperName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FCS_FrequentFlyer__x/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of customer, not mobile number</description>
    <externalDeveloperName>HomePhone</externalDeveloperName>
    <label>Phone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LiveChatTranscript/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus Number of the person contacting SAS</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LiveChatTranscript/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <description>The customers related CODS Id. Mostly used for Customers who has a login but arent EuroBonus members</description>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LiveChatTranscript/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus Number of the person contacting SAS</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/globalValueSets/EuroBonusLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Base</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Silver</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Gold</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Diamond</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Pandion</label>
    </customValue>
    <masterLabel>EuroBonus Level</masterLabel>
</GlobalValueSet>

sas-core/main/default/classes/FCS_IdentifyCustomerController_Test.cls
/**
 * @author Anton Norell
 * @date 2019-12-05
 * @description Test class for controller FCS_IdentifyCustomerController
 */
@IsTest
private class FCS_IdentifyCustomerController_Test {
  /**
   * Setting up setup objects in setup method
   */
  @TestSetup
  static void createTestData() {
    insert new MessagingChannel(
      DeveloperName = 'FacebookChannel4',
      MasterLabel = 'Facebook4',
      MessagingPlatformKey = '456',
      MessageType = 'Facebook'
    );
    C_Settings.SETTINGS_OVERRIDE = new List<C_GeneralSetting__mdt>{
      new C_GeneralSetting__mdt(
        MasterLabel = 'APIM_Subscription_Key',
        Value__c = 'TESTKEY',
        Group__c = 'APIM'
      )
    };
  }

  /**
   * Asserts that the correct case and fields are retrieved from method in controller.
   */
  @IsTest
  static void shouldReturnRecordDataBasedOnCaseId() {
    Account acc = new Account(
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      LastName = 'Last Name'
    );
    insert acc;
    Case originalCase = new Case(
      AccountId = acc.Id,
      FCS_EBNumber__c = '123',
      FCS_EBLevel__c = 'S',
      FCS_TPAccountNumber__c = '321'
    );
    insert originalCase;

    FCS_IdentifyCustomerController.ComponentRecordData retrievedData = FCS_IdentifyCustomerController.getRecordData(
      originalCase.Id
    );

    System.assertNotEquals(null, retrievedData);
    System.assertEquals(
      originalCase.FCS_EBNumber__c,
      retrievedData.euroBonusNumber
    );
    System.assertEquals(acc.Id, retrievedData.accountId);
    System.assertEquals(null, retrievedData.lastRetrievedFromSource);
  }

  /**
   * Asserts that the correct LiveChatTranscript and fields are retrieved from method in controller
   */
  @IsTest
  static void shouldReturnRecordDataBasedOnLiveChatTranscriptId() {
    Account acc = new Account(
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      LastName = 'Last Name'
    );
    insert acc;
    acc = [SELECT Id, PersonContactId FROM Account WHERE Id = :acc.Id];
    Case originalCase = new Case(
      AccountId = acc.Id,
      FCS_EBNumber__c = '123',
      FCS_TPAccountNumber__c = '321'
    );
    insert originalCase;
    LiveChatVisitor visitor = new LiveChatVisitor();
    insert visitor;
    LiveChatTranscript transcript = new LiveChatTranscript(
      LiveChatVisitorId = visitor.Id,
      CaseId = originalCase.Id,
      AccountId = acc.Id,
      ContactId = acc.PersonContactId,
      FCS_EBNumber__c = '123',
      FCS_CODSId__c = '321'
    );
    insert transcript;

    FCS_IdentifyCustomerController.ComponentRecordData retrievedData = FCS_IdentifyCustomerController.getRecordData(
      transcript.Id
    );

    System.assertNotEquals(null, retrievedData);
    System.assertEquals(
      transcript.FCS_EBNumber__c,
      retrievedData.euroBonusNumber
    );
    System.assertEquals(acc.Id, retrievedData.accountId);
    System.assertEquals(transcript.FCS_CODSId__c, retrievedData.codsId);
    System.assertEquals(acc.PersonContactId, retrievedData.personContactId);
    System.assertEquals(null, retrievedData.lastRetrievedFromSource);
  }

  /**
   * Asserts that the correct MessagingSession and fields are retrieved from method in controller
   */
  @IsTest
  static void shouldReturnRecordDataBasedOnMessagingSession() {
    Account acc = new Account(
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      LastName = 'Last Name'
    );
    insert acc;
    acc = [SELECT Id, PersonContactId FROM Account WHERE Id = :acc.Id];
    Case originalCase = new Case(
      AccountId = acc.Id,
      FCS_EBNumber__c = '123',
      FCS_TPAccountNumber__c = '321'
    );
    insert originalCase;
    List<MessagingChannel> messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel4'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123',
      AccountId = acc.Id,
      ContactId = acc.PersonContactId
    );
    insert messagingEndUser1;
    MessagingSession session = new MessagingSession(
      Origin = 'InboundInitiated',
      MessagingEndUserId = messagingEndUser1.Id,
      Status = 'New',
      MessagingChannelId = messagingChannel[0].Id,
      CaseId = originalCase.Id
    );
    insert session;

    FCS_IdentifyCustomerController.ComponentRecordData retrievedData = FCS_IdentifyCustomerController.getRecordData(
      session.Id
    );

    System.assertNotEquals(null, retrievedData);
    System.assertEquals(acc.Id, retrievedData.accountId);
    System.assertEquals(acc.PersonContactId, retrievedData.personContactId);
    System.assertEquals(null, retrievedData.lastRetrievedFromSource);
  }

  /**
   * Asserts that the controller can update a chat transcript record based on a supplied JSON string with record id and data
   */
  @IsTest
  static void shouldUpdateLiveChatTranscriptBasedOnSuppliedJSONData() {
    LiveChatVisitor visitor = new LiveChatVisitor();
    insert visitor;
    LiveChatTranscript transcript = new LiveChatTranscript(
      LiveChatVisitorId = visitor.Id
    );
    insert transcript;

    String jsonData =
      '{"recordId": "' +
      transcript.Id +
      '", "euroBonusNumber": "123"}';
    FCS_IdentifyCustomerController.updateRecordDataWithApex(jsonData);

    System.assertEquals(
      '123',
      [
        SELECT Id, FCS_EBNumber__c
        FROM LiveChatTranscript
        WHERE Id = :transcript.Id
      ]
      .FCS_EBNumber__c,
      'The method did not update the underlying transcript correctly. Expected FCS_EBNumber__ to be updated.'
    );
  }

  /**
   * Asserts that the controller can update a chat transcript record based on a supplied JSON string with,
   * record id and data as well as updating a related case record
   */
  @IsTest
  static void shouldUpdateLiveChatTranscriptAndRelatedRecordsBasedOnSuppliedJSONData() {
    Case originalCase = new Case();
    insert originalCase;
    LiveChatVisitor visitor = new LiveChatVisitor();
    insert visitor;
    LiveChatTranscript transcript = new LiveChatTranscript(
      LiveChatVisitorId = visitor.Id,
      CaseId = originalCase.Id
    );
    insert transcript;

    String jsonData =
      '{"recordId": "' +
      transcript.Id +
      '", "euroBonusNumber": "123", "caseId": "' +
      originalCase.Id +
      '"  }';
    FCS_IdentifyCustomerController.updateRecordDataWithApex(jsonData);

    System.assertEquals(
      '123',
      [
        SELECT Id, FCS_EBNumber__c
        FROM LiveChatTranscript
        WHERE Id = :transcript.Id
      ]
      .FCS_EBNumber__c,
      'The method did not update the underlying transcript correctly. Expected FCS_EBNumber__ to be updated.'
    );
    System.assertEquals(
      '123',
      [SELECT Id, FCS_EBNumber__c FROM Case WHERE Id = :originalCase.Id]
      .FCS_EBNumber__c,
      'The method did not update the related case correctly. Expected FCS_EBNumber__ to be updated.'
    );
  }

  /**
   * Asserts that the controller can update a case record based on a supplied JSON string with record id and data
   */
  @IsTest
  static void shouldUpdateCaseAndRelatedRecordsBasedOnSuppliedJSONData() {
    Case originalCase = new Case();
    insert originalCase;
    LiveChatVisitor visitor = new LiveChatVisitor();
    insert visitor;
    LiveChatTranscript transcript = new LiveChatTranscript(
      LiveChatVisitorId = visitor.Id,
      CaseId = originalCase.Id
    );
    insert transcript;

    String jsonData =
      '{"recordId": "' +
      originalCase.Id +
      '", "euroBonusNumber": "123"}';
    FCS_IdentifyCustomerController.updateRecordDataWithApex(jsonData);

    System.assertEquals(
      '123',
      [SELECT Id, FCS_EBNumber__c FROM Case WHERE Id = :originalCase.Id]
      .FCS_EBNumber__c,
      'The method did not update the underlying case correctly. Expected FCS_EBNumber__ to be updated.'
    );
    System.assertEquals(
      '123',
      [
        SELECT Id, FCS_EBNumber__c
        FROM LiveChatTranscript
        WHERE Id = :transcript.Id
      ]
      .FCS_EBNumber__c,
      'The method did not update the related chat transcript correctly. Expected FCS_EBNumber__ to be updated.'
    );
  }

  /**
   * Asserts that the controller can update a MassagingSession record based on a supplied JSON string with record id and data
   */
  @IsTest
  static void shouldUpdateMessagingSessionAndRelatedRecordsBasedOnSuppliedJSONData() {
    Case originalCase = new Case();
    insert originalCase;
    List<MessagingChannel> messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel4'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    MessagingSession session = new MessagingSession(
      Origin = 'InboundInitiated',
      MessagingEndUserId = messagingEndUser1.Id,
      Status = 'New',
      MessagingChannelId = messagingChannel[0].Id,
      CaseId = originalCase.Id
    );
    insert session;

    Account account = new Account(
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      LastName = 'Name'
    );
    insert account;

    String jsonData =
      '{"recordId": "' +
      session.Id +
      '", "euroBonusNumber": "123", "caseId": "' +
      originalCase.Id +
      '", "accountId": "' +
      account.Id +
      '"}';
    FCS_IdentifyCustomerController.updateRecordDataWithApex(jsonData);

    System.assertEquals(
      '123',
      [
        SELECT Id, AccountId, FCS_EBNumber__c
        FROM Case
        WHERE Id = :originalCase.Id
      ]
      .FCS_EBNumber__c,
      'The method did not update the related case correctly. Expected EBNumber__ to be updated.'
    );
    System.assertEquals(
      account.Id,
      [
        SELECT Id, EndUserAccountId, MessagingEndUser.AccountId
        FROM MessagingSession
        WHERE Id = :session.Id
      ]
      .MessagingEndUser.AccountId,
      'The method did not update the related End User Account correctly. Expected AccountId to be updated.'
    );
  }

  /**
   * Asserts that the controller maps information from a frequent flyer record to an account record correctly.
   * Checks both valid values and null values.
   */
  @IsTest
  static void shouldReturnAccountBasedOnFrequentFlyer() {
    FCS_FrequentFlyer__x ff = new FCS_FrequentFlyer__x(
      ExternalId = '123',
      AddressLine1__c = 'AddressLine1',
      City__c = 'City',
      ZipCode__c = 'ZipCode',
      CountryCode__c = 'Country',
      CountyState__c = 'State',
      BirthDate__c = String.valueOf(Date.today().addYears(-2)),
      ConsentEmail__c = true,
      ConsentEB__c = false,
      ConsentSMS__c = true,
      ConsentEB0__c = false,
      ConsentTelemarketing__c = true,
      EmailPersonal__c = 'email@email.com',
      EBLevel__c = null,
      EBNumber__c = '321',
      FirstName__c = 'First Name',
      Gender__c = 'F',
      LastName__c = 'Last Name',
      EBMemberSinceDate__c = null,
      Mobile__c = '0701234567',
      Phone__c = null,
      SubscriptionId__c = null,
      TPAccountNumber__c = '678',
      CompanyName__c = 'Company Name',
      CMP__c = '123',
      MiddleName__c = 'Middle',
      Salutation__c = 'Salutation',
      Title__c = 'Title'
    );
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Account account = FCS_IdentifyCustomerController.createAccountRecordBasedOnFrequentFlyers(
      new List<FCS_FrequentFlyer__x>{ ff }
    );
    Test.stopTest();

    System.assertNotEquals(
      null,
      account,
      'Method did not return expected account'
    );
    System.assertEquals(
      C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      account.RecordTypeId
    );
    System.assertEquals(ff.ExternalId, account.FCS_FrequentFlyer__c);
    System.assertEquals(ff.AddressLine1__c, account.PersonMailingStreet);
    System.assertEquals(ff.City__c, account.PersonMailingCity);
    System.assertEquals(ff.ZipCode__c, account.PersonMailingPostalCode);
    System.assertEquals(ff.CountryCode__c, account.PersonMailingCountry);
    System.assertEquals(ff.CountyState__c, account.PersonMailingState);
    System.assertEquals(Date.valueOf(ff.BirthDate__c), account.PersonBirthdate);
    System.assertEquals(ff.ConsentEmail__c, account.FCS_ConsentEmail__c);
    System.assertEquals(ff.ConsentEB__c, account.FCS_ConsentEuroBonus__c);
    System.assertEquals(ff.ConsentEB0__c, account.FCS_ConsentSiteProfile__c);
    System.assertEquals(ff.ConsentSMS__c, account.FCS_ConsentSMS__c);
    System.assertEquals(
      ff.ConsentTelemarketing__c,
      account.FCS_ConsentTelemarketing__c
    );
    System.assertEquals(ff.EmailPersonal__c, account.PersonEmail);
    System.assertEquals(ff.EBLevel__c, account.FCS_EBLevel__c);
    System.assertEquals(ff.EBNumber__c, account.FCS_EBNumber__c);
    System.assertEquals(ff.FirstName__c, account.FirstName);
    System.assertEquals(ff.Gender__c, account.FCS_Gender__c);
    System.assertEquals(ff.LastName__c, account.LastName);
    System.assertEquals(null, account.FCS_EBMemberSinceDate__c);
    System.assertEquals(ff.SubscriptionId__c, account.FCS_SubscriptionId__c);
    System.assertEquals(ff.TPAccountNumber__c, account.FCS_TPAccountNumber__c);
    System.assertEquals(ff.CompanyName__c, account.FCS_CompanyName__c);
    System.assertEquals(ff.CMP__c, account.FCS_CMP__c);
    System.assertEquals(ff.Title__c, account.PersonTitle);
    System.assertEquals(ff.Salutation__c, account.Salutation);
    System.assertEquals(ff.MiddleName__c, account.MiddleName);
    System.assert(
      account.FCS_LastRetrievedFromSource__c > DateTime.now().addMinutes(-5) &&
      account.FCS_LastRetrievedFromSource__c < DateTime.now().addMinutes(5)
    );
  }
  @IsTest
  static void shouldReturnAccountBasedOnFrequentFlyerForSASInternalUser() {
    FCS_FrequentFlyer__x ff = new FCS_FrequentFlyer__x(
      ExternalId = '123',
      AddressLine1__c = 'AddressLine1',
      City__c = 'City',
      ZipCode__c = 'ZipCode',
      CountryCode__c = 'Country',
      CountyState__c = 'State',
      BirthDate__c = String.valueOf(Date.today().addYears(-2)),
      ConsentEmail__c = true,
      ConsentEB__c = false,
      ConsentSMS__c = true,
      ConsentEB0__c = false,
      ConsentTelemarketing__c = true,
      EmailPersonal__c = 'email@sas.se',
      EBLevel__c = null,
      EBNumber__c = '321',
      FirstName__c = 'First Name',
      Gender__c = 'F',
      LastName__c = 'Last Name',
      EBMemberSinceDate__c = null,
      Mobile__c = '0701234567',
      Phone__c = null,
      SubscriptionId__c = null,
      TPAccountNumber__c = '678',
      CompanyName__c = 'Company Name',
      CMP__c = '123',
      MiddleName__c = 'Middle',
      Salutation__c = 'Salutation',
      Title__c = 'Title'
    );

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    Account account = FCS_IdentifyCustomerController.createAccountRecordBasedOnFrequentFlyers(
      new List<FCS_FrequentFlyer__x>{ ff }
    );
    Test.stopTest();

    System.assertNotEquals(
      null,
      account,
      'Method did not return expected account'
    );
    System.assertEquals(
      C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      account.RecordTypeId
    );
    System.assertEquals(ff.ExternalId, account.FCS_FrequentFlyer__c);
    System.assertEquals(ff.AddressLine1__c, account.PersonMailingStreet);
    System.assertEquals(ff.City__c, account.PersonMailingCity);
    System.assertEquals(ff.ZipCode__c, account.PersonMailingPostalCode);
    System.assertEquals(ff.CountryCode__c, account.PersonMailingCountry);
    System.assertEquals(ff.CountyState__c, account.PersonMailingState);
    System.assertEquals(Date.valueOf(ff.BirthDate__c), account.PersonBirthdate);
    System.assertEquals(ff.ConsentEmail__c, account.FCS_ConsentEmail__c);
    System.assertEquals(ff.ConsentEB__c, account.FCS_ConsentEuroBonus__c);
    System.assertEquals(ff.ConsentEB0__c, account.FCS_ConsentSiteProfile__c);
    System.assertEquals(ff.ConsentSMS__c, account.FCS_ConsentSMS__c);
    System.assertEquals(
      ff.ConsentTelemarketing__c,
      account.FCS_ConsentTelemarketing__c
    );
    System.assertEquals(null, account.PersonEmail);
    System.assertEquals(ff.EBLevel__c, account.FCS_EBLevel__c);
    System.assertEquals(ff.EBNumber__c, account.FCS_EBNumber__c);
    System.assertEquals(ff.FirstName__c, account.FirstName);
    System.assertEquals(ff.Gender__c, account.FCS_Gender__c);
    System.assertEquals(ff.LastName__c, account.LastName);
    System.assertEquals(null, account.FCS_EBMemberSinceDate__c);
    System.assertEquals(ff.SubscriptionId__c, account.FCS_SubscriptionId__c);
    System.assertEquals(ff.TPAccountNumber__c, account.FCS_TPAccountNumber__c);
    System.assertEquals(ff.CompanyName__c, account.FCS_CompanyName__c);
    System.assertEquals(ff.CMP__c, account.FCS_CMP__c);
    System.assertEquals(ff.Title__c, account.PersonTitle);
    System.assertEquals(ff.Salutation__c, account.Salutation);
    System.assertEquals(ff.MiddleName__c, account.MiddleName);
    System.assert(
      account.FCS_LastRetrievedFromSource__c > DateTime.now().addMinutes(-5) &&
      account.FCS_LastRetrievedFromSource__c < DateTime.now().addMinutes(5)
    );
  }

  /**
   * Asserts that an account record is inserted based on a provided Frequent Flyer record provided to controller
   */
  @IsTest
  static void shouldInsertBasedOnFrequentFlyer() {
    FCS_FrequentFlyer__x ff = new FCS_FrequentFlyer__x(
      ExternalId = '123',
      AddressLine1__c = 'AddressLine1',
      City__c = 'City',
      ZipCode__c = 'ZipCode',
      CountryCode__c = 'Country',
      CountyState__c = 'State',
      BirthDate__c = String.valueOf(Date.today().addYears(-2)),
      ConsentEmail__c = true,
      ConsentEB__c = false,
      ConsentSMS__c = true,
      ConsentEB0__c = false,
      ConsentTelemarketing__c = true,
      EmailPersonal__c = 'email@email.com',
      EBLevel__c = null,
      EBNumber__c = '321',
      FirstName__c = 'First Name',
      Gender__c = 'F',
      LastName__c = 'Last Name',
      EBMemberSinceDate__c = null,
      Mobile__c = '0701234567',
      Phone__c = null,
      SubscriptionId__c = null,
      TPAccountNumber__c = '678',
      CompanyName__c = 'Company Name',
      CMP__c = '123',
      MiddleName__c = 'Middle',
      Salutation__c = 'Salutation',
      Title__c = 'Title'
    );

    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    FCS_IdentifyCustomerController.createAccountRecordBasedOnFrequentFlyers(
      new List<FCS_FrequentFlyer__x>{ ff }
    );
    Test.stopTest();

    System.assertEquals(
      1,
      [SELECT Id FROM Account].size(),
      'Expected 1 account to be inserted based on Frequent Flyer'
    );
  }

  /**
   * Asserts that the controller can handle an empty return when querying for Frequent Flyer
   */
  @IsTest
  static void shouldReturnNullIfFrequentFlyerListIfEmpty() {
    Account account = FCS_IdentifyCustomerController.createAccountRecordBasedOnFrequentFlyers(
      new List<FCS_FrequentFlyer__x>()
    );

    System.assertEquals(null, account);
  }

  /**
   * Asserts that en exception is thrown if component is placed on an unsupported object
   */
  @IsTest
  static void shouldThrowExceptionIfNotSupportedObject() {
    Opportunity opp = new Opportunity(
      Name = 'Name',
      StageName = 'New',
      CloseDate = Date.today()
    );
    insert opp;

    FCS_IdentifyCustomerController.IdentifyCustomerComponentException catchedException;
    try {
      FCS_IdentifyCustomerController.getRecordData(opp.Id);
    } catch (FCS_IdentifyCustomerController.IdentifyCustomerComponentException e) {
      catchedException = e;
    }

    System.assertNotEquals(
      null,
      catchedException,
      'Expected exception for unsupported object. Check that object is still unsupported.'
    );
  }

  @IsTest
  static void findCustomerShouldNotFetchAccountForSASEmails() {
    Account account = FCS_IdentifyCustomerController.findCustomer(
      'EmailPersonal__c',
      'test@sas.se'
    );
    System.assertEquals(
      null,
      account,
      'SAS emails should not cause a fetch for an account.'
    );
  }

  /*
    @IsTest
    static void shouldThrowExceptionDueToUnsupportedExternalObjectQuery(){
        Exception returnedException;
        try{
            Account account = FCS_IdentifyCustomerController.findCustomer('FCS_EBNumber__c', '700001423');

        } catch (QueryException e){
            returnedException = e;
        }
        System.assertNotEquals(null, returnedException, 'Expected a QueryException to be thrown');
        System.assertEquals('entity type FCS_FrequentFlyer__x does not support query',
                returnedException.getMessage(),
                'Expected the exception to contain another message. Check that used query is not malformed. '
        );
    }*/

  /**
   * Asserts that the query for the external object Frequent Flyer can run correctly. As external object queries
   * are not supported in test context, the test should return a null result.
   */
  /*
    @IsTest
    static void shouldReturnNullResultDueToNoSupportForQuery(){
        Account account = FCS_IdentifyCustomerController.findCustomer('FCS_EBNumber__c', '700001423');

        System.assertEquals(null, account);
    }
*/
  /**
   * Asserts that the query for the external object Frequent Flyer can run correctly. As external object queries
   * are not supported in test context, the test catches the expected exception and verifies the message.
   */
}