sas-core/main/default/objects/Account/fields/CustomerIdentifier__c.field-meta.xml
<CustomField>
    <fullName>CustomerIdentifier__c</fullName>
    <description>Customer Identifier in SAS source systems</description>
    <externalId>true</externalId>
    <label>Customer Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FrequentFlyer__c.field-meta.xml
<CustomField>
    <fullName>FrequentFlyer__c</fullName>
    <description>Reference to external Frequent Flyer record holding data from SAS source systems</description>
    <inlineHelpText>External Frequent Flyer record holding data from SAS source systems</inlineHelpText>
    <label>Frequent Flyer</label>
    <length>255</length>
    <referenceTo>FrequentFlyer__x</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

sas-core/main/default/objects/Account/fields/LastRetrievedFromSource__c.field-meta.xml
<CustomField>
    <fullName>LastRetrievedFromSource__c</fullName>
    <description>Datetime for when this account was last retrieved from source system. Used to determine if customer should be retrieved at certain points in time, e.g. when opening a case.</description>
    <label>Last Retrieved From Source</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Account/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&#39;s Travel Pass account</description>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/FrequentFlyer__x.object-meta.xml
<CustomObject>
    <description>External object used to hold data from SAS source systems regarding customer</description>
    <externalDataSource>SAS_External_Systems</externalDataSource>
    <externalName>FrequentFlyers</externalName>
    <label>Frequent Flyer</label>
    <pluralLabel>Frequent Flyers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/FrequentFlyer__x/fields/EBNumber__c.field-meta.xml
<CustomField>
    <fullName>EBNumber__c</fullName>
    <description>EuroBonus Number of customer</description>
    <externalDeveloperName>euroBonusNumber</externalDeveloperName>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of customer</description>
    <externalDeveloperName>firstName</externalDeveloperName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last Name of customer</description>
    <externalDeveloperName>LastName</externalDeveloperName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FrequentFlyer__x/fields/TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>TPAccountNumber__c</fullName>
    <description>Unique identifier for customer&#39;s Travel Pass account</description>
    <externalDeveloperName>TravelPassAccountNumber</externalDeveloperName>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IdentifyCustomerFromCaseController.cls
public with sharing class IdentifyCustomerFromCaseController {


    @AuraEnabled
    public static Account findCustomer(String searchField, String searchValue){
        String query = 'SELECT ExternalId, EBNumber__c, FirstName__c, LastName__c FROM FrequentFlyer__x WHERE ' + searchField + ' = \'' + searchValue + '\'';
        System.debug('Query: ' + query);
        List<FrequentFlyer__x> externalData = Database.query(query);
        if(!externalData.isEmpty()){
            FrequentFlyer__x data = externalData[0];
            Account acc = new Account();
            acc.FirstName = data.FirstName__c;
            acc.LastName = data.LastName__c;
            acc.EBNumber__c = '700001043';
            acc.TPAccountNumber__c = '700001042';
            acc.FrequentFlyer__c = data.ExternalId;
            acc.CustomerIdentifier__c = data.ExternalId;
            acc.LastRetrievedFromSource__c = Datetime.now();

            upsert acc CustomerIdentifier__c;
            return acc;
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Case getCaseData(String caseId){
        return [SELECT Id, AccountId, EBNumber__c, TPAccountNumber__c, Account.FrequentFlyer__c, Account.LastRetrievedFromSource__c FROM Case WHERE Id = :caseId];
    }
}