sas-core/main/default/objects/Account/fields/FCS_CMP__c.field-meta.xml
<CustomField>
    <fullName>FCS_CMP__c</fullName>
    <description>CMP code for customer</description>
    <label>Company Code (CMP)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <externalId>true</externalId>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/Travel_Pass_Product__c.object-meta.xml
<CustomObject>
    <label>Travel Pass Product</label>
    <nameField>
        <label>Travel Pass Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Pass Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account whose product this is.</description>
    <inlineHelpText>The account whose product this is.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Travel Pass Products</relationshipLabel>
    <relationshipName>Travel_Pass_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/tests/integration/TravelPass_IntegrationTest.cls
@IsTest
public with sharing class TravelPass_IntegrationTest {
  @IsTest
  public static void itShouldBePossibleToRefreshTPProductInfo() {
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Account newAccount = new Account(
      FCS_TPAccountNumber__c = 'TEST12',
      FCS_CMP__c = 'TEST12',
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      FirstName = 'Test',
      LastName = 'Account'
    );
    insert newAccount;

    TravelPassService.fetchTravelPassAccount('TEST12', newAccount.Id);
    TravelPassService.refreshTravelPassAccount(newAccount.Id);
    Test.stopTest();

    List<Travel_Pass_Product__c> associatedTPProducts = [
      SELECT Id, Account__c
      FROM Travel_Pass_Product__c
      WHERE Account__c = :newAccount.Id
    ];

    System.assert(
      associatedTPProducts.size() == 2,
      'There should be two TP products associated with the account as the mock response contains two products.'
    );
  }
  @IsTest
  public static void updatingTPAccountDataShouldNotCreateDuplicateProducts() {
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Account newAccount = new Account(
      FCS_TPAccountNumber__c = 'TEST12',
      FCS_CMP__c = 'TEST12',
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      FirstName = 'Test',
      LastName = 'Account'
    );
    insert newAccount;
    TravelPassService.fetchTravelPassAccount('TEST12', newAccount.Id);
    Test.stopTest();

    List<Travel_Pass_Product__c> associatedTPProducts = [
      SELECT Id, Account__c
      FROM Travel_Pass_Product__c
      WHERE Account__c = :newAccount.Id
    ];

    System.assert(
      associatedTPProducts.size() == 2,
      'There should be two TP products associated with the account as the mock response contains two products.'
    );
  }
}