sas-core/main/default/objects/Account/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <description>Unique identifier for customer in CODA. Corresponds to ExternalId on Frequent Flyer.</description>
    <externalId>true</externalId>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/SasAccount_Test.cls
@IsTest
public class SasAccount_Test {
    
    private static string EB_NUMBER = '12345';
    
    @IsTest 
    static void getId_Found() {
        // Create test account
        Account acc = new Account(
            RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
            LastName = 'Last Name',
            FCS_CODSId__c = '123',
            FCS_EBNumber__c = EB_NUMBER
        );
        insert acc;
        
        List<Account> accounts = SasAccount.getId(new List<String>{EB_NUMBER});
        Assert.areEqual(1, accounts.size());
        Assert.areEqual(acc.id, accounts[0].Id);
    }
    /*
    @IsTest 
    static void getId_NotFound() {
        // Create test account
        Account acc = new Account(
            RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
            LastName = 'Last Name',
            FCS_CODSId__c = '123',
            FCS_EBNumber__c = EB_NUMBER
        );
        insert acc;
        
        List<String> accountIds = SasAccount.getId(new List<String>{'EB_NOT_FOUND'});
        Assert.areEqual(1, accountIds.size());
        Assert.isNotNull(accountIds[0]);
    }*/
}