sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether this booking has been cancelled.</description>
    <inlineHelpText>Whether this booking has been cancelled.</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the passenger record has an EB number, this field is populated with the corresponding person account.</description>
    <inlineHelpText>If the passenger record has an EB number, this field is populated with the corresponding person account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>PassengerRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/tests/integration/Bookings_IntegrationTest.cls
@IsTest
public with sharing class Bookings_IntegrationTest {
  public static String bookingReferenceOnlyInTEDS = 'TEDS12';
  public static String invalidBookingReference = 'AAAAAA';
  public static String ebNumberWithBookings = 'TEST123456';
  public static String ebNumberWithoutBookings = 'TEST654321';

  public static BookingsSelector bookings = (BookingsSelector) SAS_Service_Application.Selector.newInstance(
    Booking__c.SObjectType
  );

  @IsTest
  public static void itsPossibleToAddBookingInTEDSToCase() {
    // Given
    Case testCase = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      null,
      null
    )[0];

    insert testCase;

    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new TEDSBookingSingleAndFlightSuccessMock()
    );
    // When
    CustomerCardController.addBookingToCase(
      testCase.Id,
      bookingReferenceOnlyInTEDS
    );
    Test.stopTest();

    // Then
    Booking__c bookingFromDB = bookings.selectByCaseId(
      new Set<Id>{ testCase.Id }
    )[0];

    System.assertEquals(
      bookingReferenceOnlyInTEDS,
      bookingFromDB.Booking_Reference__c,
      'Booking should be found by case Id and have the same reference'
    );
  }

  @IsTest
  public static void itsPossibleToRemoveABookingFromCase() {
    // Given
    Case testCase = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      null,
      null
    )[0];

    insert testCase;

    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new TEDSBookingSingleAndFlightSuccessMock()
    );

    // When
    CustomerCardController.addBookingToCase(
      testCase.Id,
      bookingReferenceOnlyInTEDS
    );
    CustomerCardController.removeBookingFromCase(
      testCase.Id,
      bookingReferenceOnlyInTEDS
    );
    Test.stopTest();

    // Then
    List<Booking__c> bookingsByCaseId = bookings.selectByCaseId(
      new Set<Id>{ testCase.Id }
    );

    System.assertEquals(
      bookingsByCaseId.size(),
      0,
      'Booking should not be found by case Id'
    );
  }

  @IsTest
  public static void invalidBookingReferenceFailsGracefully() {
    // Given
    Case testCase = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      null,
      null
    )[0];

    insert testCase;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new TEDSBookingSingle404Mock());

    // When
    CustomerCardController.addBookingToCase(
      testCase.Id,
      invalidBookingReference
    );
    Test.stopTest();

    // Then
    List<Booking__c> bookingsFromDB = bookings.selectByCaseId(
      new Set<Id>{ testCase.Id }
    );

    System.assert(
      bookingsFromDB.size() == 0,
      'No bookings should exist for the case'
    );
  }

  @IsTest
  public static void itsPossibleToFetchBookingsByEBNumber() {
    // Given
    Account testAccount = FCS_TestDataFactory.createFrequentFlyers(1)[0];
    testAccount.FCS_EBNumber__c = ebNumberWithBookings;
    insert testAccount;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new TEDSBookingQuerySuccessMock());
    // When
    CustomerCardController.getBookingsForEBCustomer(ebNumberWithBookings);
    Test.stopTest();

    // Then
    Booking__c bookingFromDB = bookings.selectByAccountId(
      new Set<Id>{ testAccount.Id }
    )[0];

    System.assertEquals(
      testAccount.Id,
      bookingFromDB.Passengers__r[0].Account__c,
      'There should be a new passenger record linking the booking and account.'
    );
  }

  @IsTest
  public static void noBookingsForEBNumberFailsGracefully() {
    // Given
    Account testAccount = FCS_TestDataFactory.createFrequentFlyers(1)[0];
    testAccount.FCS_EBNumber__c = ebNumberWithoutBookings;
    insert testAccount;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new TEDSBookingQueryNFMock());
    // When
    List<Booking__c> bookingsFromCustomerCard = CustomerCardController.getBookingsForEBCustomer(
      ebNumberWithoutBookings
    );
    Test.stopTest();

    // Then
    List<Booking__c> bookingsFromDB = bookings.selectByAccountId(
      new Set<Id>{ testAccount.Id }
    );

    System.assert(
      bookingsFromCustomerCard.size() == 0,
      'No bookings should be return by the controller.'
    );

    System.assert(
      bookingsFromDB.size() == 0,
      'No bookings should be found in the DB for EB number.'
    );
  }

  @IsTest
  public static void itsPossibleToUpdateExistingBookings() {
    // Given
    Account testAccount = FCS_TestDataFactory.createFrequentFlyers(1)[0];
    testAccount.FCS_EBNumber__c = ebNumberWithBookings;
    insert testAccount;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new TEDSBookingQuerySuccessMock());
    // When
    CustomerCardController.getBookingsForEBCustomer(ebNumberWithBookings);
    Test.setMock(
      HttpCalloutMock.class,
      new TEDSBookingQuerySuccessAnotherMock()
    );
    CustomerCardController.getBookingsForEBCustomer(ebNumberWithBookings);
    Test.stopTest();

    // Then
    List<Booking__c> bookingsForAccount = bookings.selectByAccountId(
      new Set<Id>{ testAccount.Id }
    );

    System.assert(
      bookingsForAccount.size() == 1,
      'There should be only one booking for the account.'
    );

    System.assert(
      bookingsForAccount[0].Is_Cancelled__c == true,
      'Booking should have been updated changed between the calls.'
    );
  }
}