sas-core/main/default/objects/Account/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <description>Unique identifier for customer in CODA. Corresponds to ExternalId on Frequent Flyer.</description>
    <externalId>true</externalId>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBLevel__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBLevel__c</fullName>
    <description>Current EuroBonus level/tier for customer</description>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_FrequentFlyer__c.field-meta.xml
<CustomField>
    <fullName>FCS_FrequentFlyer__c</fullName>
    <description>Reference to external Frequent Flyer record holding data from SAS source systems</description>
    <inlineHelpText>External Frequent Flyer record holding data from SAS source systems</inlineHelpText>
    <label>Frequent Flyer</label>
    <length>255</length>
    <referenceTo>FCS_FrequentFlyer__x</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_Gender__c.field-meta.xml
<CustomField>
    <fullName>FCS_Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</description>
    <inlineHelpText>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DayReturn</fullName>
            </value>
            <value>
                <fullName>MultiCity</fullName>
            </value>
            <value>
                <fullName>OneWay</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseReason__c</fullName>
    <complianceGroup>PIIExtract;WipeRetain</complianceGroup>
    <description>Second level categorization for cases.</description>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 day refund guarantee</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Award travel</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Service</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Bank Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Boozt Attack</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBLevel__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBLevel__c</fullName>
    <label>EuroBonus Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EuroBonusLevel</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Vendor__c.field-meta.xml
<CustomField>
    <fullName>FCS_Vendor__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <description>The vendor of the case owner (that is a user)</description>
    <inlineHelpText>The vendor of the case owner (that is a user)</inlineHelpText>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FCS_Vendor</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the passenger record has an EB number, this field is populated with the corresponding person account.</description>
    <inlineHelpText>If the passenger record has an EB number, this field is populated with the corresponding person account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>PassengerRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this passenger in this booking. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this passenger in this booking. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Vendor__c.field-meta.xml
<CustomField>
    <fullName>FCS_Vendor__c</fullName>
    <description>The vendor of the social post owner (that is a user).</description>
    <inlineHelpText>The vendor of the social post owner (that is a user).</inlineHelpText>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FCS_Vendor</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/User/fields/FCS_Vendor__c.field-meta.xml
<CustomField>
    <fullName>FCS_Vendor__c</fullName>
    <description>The vendor which the user belongs to.</description>
    <inlineHelpText>The vendor which the user belongs to.</inlineHelpText>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FCS_Vendor</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/globalValueSets/EuroBonusLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Base</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Silver</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Gold</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Diamond</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Pandion</label>
    </customValue>
    <masterLabel>EuroBonus Level</masterLabel>
</GlobalValueSet>

sas-core/main/default/globalValueSets/FCS_Vendor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sutherland</fullName>
    </customValue>
    <customValue>
        <fullName>Sykes</fullName>
    </customValue>
    <customValue>
        <fullName>SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Student Consulting</fullName>
    </customValue>
    <description>The vendor of the user or record owner (that is a user)</description>
    <masterLabel>FCS Vendor</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/FCS_TestDataFactory.cls
/**
 * @author Sanna Sörberg
 * @date 2019-11-27
 * @description Factory class used to generate commonly used test metadata
 */

public class FCS_TestDataFactory {
    /**
        Sequence number used to seed unique fields to ensure no collisions occur
    */
    public static Integer SEQ_NUM = 0;

    /**
    * Creates cases with minimal info, as well as Account and Contact if supplied number of case + record type
    * @param numCases Number of cases to be created
    * @param accId Id for account to create case with (null is acceptable)
    * @param conId Id for contact to create case with (null is acceptable)
    * @param rtId Id of the record type to be created (null is acceptable)
    * @param reason String of the case reason. Default value: Baggage (null is acceptable)
    *
    * @return list of new cases
    */
    public static Case[] createCases(Integer numCases, Id accId, Id conId, Id rtId, String reason) {
        List<Case> newCases = new List<Case>();
        for (Integer i = 0, sz = numCases; i < sz; i++) {
            Case c = new Case();
            c.Subject = 'c';
            c.AccountId = accId;
            c.ContactId = conId;
            if (rtId != null)c.RecordTypeId = rtId;
            c.Reason = reason == null ? 'Baggage' : reason;
            c.FCS_CaseReason__c = reason == null ? 'Baggage' : reason;
            newCases.add(c);
        }
        return newCases;
    }

    /**
    * Creates social post with minimal info
    * @param numSocialPosts Number of social posts to be created
    * @return list of social posts
    */
    public static SocialPost[] createSocialPosts(Integer numSocialPosts) {
        List<SocialPost> newSocialPosts = new List<SocialPost>();
        for (Integer i = 0, sz = numSocialPosts; i < sz; i++) {
            SocialPost sp = new SocialPost (Name = 'Test' + i, Headline = 'TestHeadLine' + i, Posted = system.now());
            newSocialPosts.add(sp);
        }
        return newSocialPosts;
    }

    /**
        Creates frequent flyers which cna be used in the test methods
        @param numAccounts The number of accounts to create
        @return The list of accounts (Not Saved)
    */
    public static Account[] createFrequentFlyers(Integer numAccounts) {
        Account[] accs = new Account[numAccounts];
        for (Integer i = 0; i < numAccounts; i++) {
            Account acc = new Account();
            acc.RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER;
            acc.FirstName = 'TestFirstName';
            acc.LastName = 'TestLastName';
            acc.FCS_CODSId__c = 'TEST' + SEQ_NUM;
            acc.PersonEmail = 'test@test.com';
            acc.PersonMobilePhone = '+46701234567';
            acc.PersonHomePhone = '+4681234567';
            acc.FCS_Gender__c = (SEQ_NUM & 1) > 0 ? 'F' : 'M';
            acc.FCS_FrequentFlyer__c = acc.FCS_CODSId__c;
            acc.PersonBirthDate = Date.newInstance(1990 - Math.mod(SEQ_NUM, 50), Math.mod(SEQ_NUM, 12) + 1, Math.mod(SEQ_NUM, 29) + 1);
            acc.FCS_EBNumber__c = 'EBTEST' + SEQ_NUM;
            acc.FCS_EBLevel__c = (SEQ_NUM & 3) < 2 ? 'B' : (SEQ_NUM & 3) < 3 ? 'S' : 'G';
            SEQ_NUM++;
            accs[i] = acc;
        }
        return accs;
    }

    public static User[] createUsers(Integer numUsers) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        List<User> users = new List<User>();
        double random = Math.random() * 10000;
        Integer rnd =random.intValue();     
        for (Integer i = rnd, sz = numUsers+rnd; i < sz; i++) {
            User u = new User(
                    Alias = 'user' + i,
                    Email = 'testUser' + i + '@test.com',
                    EmailEncodingKey = 'UTF-8',
                    LastName = 'user' + i,
                    LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'sv_SE',
                    ProfileId = p.Id,
                    TimeZoneSidKey = 'Europe/Paris',
                    UserName = 'testUser' + i + '@test.com.flysas',
                    FCS_Vendor__c = 'Sykes');
            users.add(u);
        }
        return users;
    }
    /**
    * Creates Booking with minimal info
    * @param  numBookings Number of bookings to be created
    * @return list of bookings
    */
    public static Booking__c[] createBookings(Integer numBookings, String type) {
        List<Booking__c> newBookings = new List<Booking__c>();
        for (Integer i = 0, sz = numBookings; i < sz; i++) {
            Booking__c sp = new Booking__c (Name = 'Test' + i, Booking_Reference__c = 'Test1' + i, TEDS_Identifier__c = 'Manual-'+i, Type__c = type);
            newBookings.add(sp);
        }
        return newBookings;
    }
     /**
    * Creates Flight with  info
    * @param  arrival departure airport, arrival departure time,Teds identifier flight to be created
    * @return flight
    */
    public static Flight__c createFlights(String arrival, String departure, DateTime arrivalTime, DateTime departureTime,String Identifier) {
        
        String flightName= 'SK174-'+arrival+'-'+departure+'-'+departureTime;
        Flight__c fg = new Flight__c (Name = flightName,
                                      Arrival_Airport__c = arrival, Departure_Airport__c = departure,
                                      Scheduled_Arrival_Time__c = arrivalTime, Scheduled_Departure_Time__c =departureTime,
                                      TEDS_Identifier__c = Identifier);
       return fg;   
       }  
   /**
    * Creates passengers with minimal info
    * @param  numpassengers,Account and booking for passengers to be created
    * @return list of passengers
    */
    public static Passenger__c[] createPassengerss(Integer numPassengers,String accountId,String bookingId) {
        List<Passenger__c> newPassengers = new List<Passenger__c>();
        for (Integer i = 0, sz = numPassengers; i < sz; i++) {
            Passenger__c pg = new Passenger__c(First_Name__c = 'Test',Last_Name__c='i',Account__c=AccountId,
                                               Booking__c=bookingId,Email__c='Test87'+i+'@sas.se',Identifier__c='abc-'+i);
            newPassengers.add(pg);
        }
        return newPassengers;
    }    
     /**
    * Creates passengers with minimal info
    * @param  numpassengers,Account and booking for passengers to be created
    * @return list of passengers
    */
    public static Segment__c createSegment(String bookingId, String flightId) {
       
            Segment__c sg = new Segment__c(Booking__c  =bookingId,Flight__c=flightId,Identifier__c='STI');           
              return sg;
    }                          
       
}