sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the passenger record has an EB number, this field is populated with the corresponding person account.</description>
    <inlineHelpText>If the passenger record has an EB number, this field is populated with the corresponding person account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>PassengerRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/Passengers.cls
public with sharing class Passengers extends fflib_SObjectDomain {
  public Passengers(List<SObject> records) {
    super(records);
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Passengers(records);
    }
  }

  public override void onApplyDefaults() {
    for (Passenger__c passenger : (List<Passenger__c>) Records) {
      if (passenger.Name == null) {
        passenger.Name = passenger.Last_Name__c;
      }
    }
  }

  public override void onBeforeInsert() {
    associateWithExistingEBAccountsNoUpdate();
  }

  /**
   * Associates a passenger record with an EB account if one already exists
   * in Salesforce. Doesn't try to fetch EB account data from outside of SF
   * if it doesn't already exist in there.
   */
  public void associateWithExistingEBAccounts() {
    associateWithExistingEBAccountsNoUpdate();
    upsert Records;
  }

  private void associateWithExistingEBAccountsNoUpdate() {
    AccountsSelector accounts = (AccountsSelector) SAS_Service_Application.Selector.newInstance(
      Account.SObjectType
    );

    Set<String> euroBonusNumbers = new Set<String>();

    for (Passenger__c passenger : (List<Passenger__c>) Records) {
      if (passenger.EuroBonus_Number__c != null) {
        euroBonusNumbers.add(passenger.EuroBonus_Number__c);
      }
    }

    List<Account> accountsFromSF = accounts.selectByEuroBonusNumber(
      euroBonusNumbers
    );

    for (Passenger__c passenger : (List<Passenger__c>) Records) {
      if (passenger.EuroBonus_Number__c != null) {
        for (Account account : accountsFromSF) {
          if (account.FCS_EBNumber__c == passenger.EuroBonus_Number__c) {
            passenger.Account__c = account.Id;
          }
        }
      }
    }
  }
}