sas-core/main/default/objects/Account/fields/FCS_CMP__c.field-meta.xml
<CustomField>
    <fullName>FCS_CMP__c</fullName>
    <description>CMP code for customer</description>
    <label>Company Code (CMP)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Account/fields/FCS_TPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_TPAccountNumber__c</fullName>
    <description>Travel Pass Account Number for customer</description>
    <externalId>true</externalId>
    <label>Travel Pass Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Travel_Pass_Product__c/Travel_Pass_Product__c.object-meta.xml
<CustomObject>
    <label>Travel Pass Product</label>
    <nameField>
        <label>Travel Pass Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Pass Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account whose product this is.</description>
    <inlineHelpText>The account whose product this is.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Travel Pass Products</relationshipLabel>
    <relationshipName>Travel_Pass_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/tests/integration/Accounts_IntegrationTest.cls
@IsTest
public with sharing class Accounts_IntegrationTest {
  public static String bookingReference = 'SF1234';
  public static String euroBonusNumber = '123456789098';

  public static BookingsSelector bookings = (BookingsSelector) SAS_Service_Application.Selector.newInstance(
    Booking__c.SObjectType
  );

  @IsTest
  public static void whenEBAccountIsCreatedBookingsAreCreated() {
    // Given
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    TEDSIntegrationService mockTEDSService = (TEDSIntegrationService) mocks.mock(
      TEDSIntegrationService.class
    );
    mocks.startStubbing();
    List<List<String>> query = new List<List<String>>{
      new List<String>{ 'euroBonusNumber', euroBonusNumber }
    };
    mocks.when(mockTEDSService.fetchBookingsByQuery(query))
      .thenReturn(
        TestDataFactories.createParsedBookingData(
          bookingReference,
          euroBonusNumber
        )
      );
    mocks.stopStubbing();
    SAS_Service_Application.Service.setMock(
      TEDSIntegrationService.class,
      mockTEDSService
    );

    Test.startTest();
    // When
    Account newAccount = new Account(
      FCS_EBNumber__c = euroBonusNumber,
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      FirstName = 'Test',
      LastName = 'Account'
    );
    insert newAccount;
    Test.stopTest();

    // Then
    List<Booking__c> bookingsFromDB = bookings.selectByAccountId(
      new Set<Id>{ newAccount.Id }
    );
    System.assert(
      bookingsFromDB.size() > 0,
      'There should be a new booking related to the account'
    );
  }

  @IsTest
  public static void insertingAnAccountShouldFetchTPProducts() {
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Account newAccount = new Account(
      FCS_TPAccountNumber__c = 'TEST12',
      FCS_CMP__c = 'TEST12',
      RecordTypeId = C_RecordTypeHelper.ACCOUNT_PERSON_EBCUSTOMER,
      FirstName = 'Test',
      LastName = 'Account'
    );
    insert newAccount;
    Test.stopTest();

    List<Travel_Pass_Product__c> associatedTPProducts = [
      SELECT Id, Account__c
      FROM Travel_Pass_Product__c
      WHERE Account__c = :newAccount.Id
    ];

    System.assert(
      associatedTPProducts.size() == 2,
      'There should be two TP products associated with the account as the mock response contains two products.'
    );
  }
}