sas-core/main/default/objects/Account/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <externalId>true</externalId>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseReason__c</fullName>
    <complianceGroup>PIIExtract;WipeRetain</complianceGroup>
    <description>Second level categorization for cases.</description>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 day refund guarantee</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Award travel</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Service</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Bank Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Boozt Attack</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <description>Third level categorization for cases.</description>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseReason__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Groups</fullName>
            </value>
            <value>
                <fullName>Agent - Agreement related Question</fullName>
            </value>
            <value>
                <fullName>Agent - Other</fullName>
            </value>
            <value>
                <fullName>Agent - TravelPass</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Booking</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass CC update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Contact Update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Receipt</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Sell</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Statistics</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass wrong deb</fullName>
            </value>
            <value>
                <fullName>Agreement related question*</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport service locations</fullName>
            </value>
            <value>
                <fullName>Allergies</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Alternatives</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX 2 for 1</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Ancillary error</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>ATC refund flow</fullName>
            </value>
            <value>
                <fullName>Author</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseTags__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseTags__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Additional Case Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Conditions of carriage</fullName>
            </value>
            <value>
                <fullName>Contacts-Country</fullName>
            </value>
            <value>
                <fullName>Contacts-partners</fullName>
            </value>
            <value>
                <fullName>Contacts R</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Corporate product</fullName>
            </value>
            <value>
                <fullName>Corporate R</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>CR requests</fullName>
            </value>
            <value>
                <fullName>Customer Care R</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
                <label>Delayed/damaged baggage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>For all the cases related to a voice call</description>
    <label>Call</label>
</RecordType>

sas-core/main/default/objects/FCS_CaseTag__c/FCS_CaseTag__c.object-meta.xml
<CustomObject>
    <description>Object used to store records about case reason to be able to report on multiple reasons</description>
    <label>Case Tag</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CaseReason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseId__c</fullName>
    <description>The id of the case that the tag belong to</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Tags</relationshipLabel>
    <relationshipName>Case_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseTag__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseTag__c</fullName>
    <description>The tag for why the customer was contacting customer support</description>
    <label>Case Tag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Conditions of carriage</fullName>
            </value>
            <value>
                <fullName>Contacts-Country</fullName>
            </value>
            <value>
                <fullName>Contacts-partners</fullName>
            </value>
            <value>
                <fullName>Contacts R</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Corporate product</fullName>
            </value>
            <value>
                <fullName>Corporate R</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>CR requests</fullName>
            </value>
            <value>
                <fullName>Customer Care R</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged baggage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_CaseCreated__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post has a case created from it</description>
    <label>Case Created</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>FCS_ClosedDate__c</fullName>
    <description>The date when the social post was marked as done</description>
    <inlineHelpText>The date when the social post was marked as done</inlineHelpText>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Done__c.field-meta.xml
<CustomField>
    <fullName>FCS_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post fulfills the criteria of being handled</description>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SurveyInvitation/fields/FCS_RelatedCase__c.field-meta.xml
<CustomField>
    <fullName>FCS_RelatedCase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Related_Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/FCS_CaseHandler.cls
/**
 * @author Sanna Sörberg
 * @date 2019-11-27
 * @description Handler class for operations performed on case object.
 */
public class FCS_CaseHandler extends C_TriggerHandler {
    /**
    Static variable for the Case Tag type Main
    */
    @TestVisible private static final String MAIN_TAG = 'Main';
    /**
   Static variable for the Case Tag type Sub
   */
    @TestVisible private static final String SUB_MAIN_TAG = 'Sub';
    /**
   Static variable for the Case Tag type Additional
   */
    @TestVisible private static final String ADDITIONAL_TAG = 'Additional';
    /**
    Static variable for the Social Post review status "Reviewed"
    */
    @TestVisible private static final String SP_STATUS_REVIEWED = 'Reviewed';
    /**
   Static variable for the Case status "Closed"
   */
    @TestVisible private static final String CASE_STATUS_CLOSED = 'Closed';

    /**
    Trigger variables
    */
    private Map < Id, Case > newCaseMap;
    private List < Case > newCaseList;
    private Map < Id, Case > oldCaseMap;
    private List < Case > oldCaseList;
    /**
   Set variables
   */
    public FCS_CaseHandler() {
        this.newCaseMap = (Map < Id, Case > ) Trigger.newMap;
        this.newCaseList = (List < Case > ) Trigger.new;
        this.oldCaseMap = (Map < Id, Case > ) Trigger.oldMap;
        this.oldCaseList = (List < Case > ) Trigger.old;
    }
    /**
   Used to call the trigger in the before insert context
   */
    public override void beforeInsert() {
        assignOwnerFromSoMe(newCaseList);
        //assignEurobonusAccountToCase(newCaseList);
        validateCaseTags(newCaseList);
    }
    /**
  Used to call the trigger in the before update context
  */
    public override void beforeUpdate() {
        validateCaseTags(newCaseList);
    }
    /**
   Used to call the trigger in the after insert context
   */
    public override void afterInsert() {
        manageCaseTagRecords(newCaseList, newCaseMap);
        updateSocialPost(newCaseList);
    }

    /**
    Used to call the trigger in the after update context
    */
    public override void afterUpdate() {
        manageCaseTagRecords(newCaseList, newCaseMap);
    }

    /**
    Used to call the trigger in the after delete context
    */
    public override void afterDelete() {
        //Make sure that related Survey Invitations are deleted upon case deletion
        delete[SELECT Id FROM SurveyInvitation WHERE FCS_RelatedCase__c IN: oldCaseMap.keySet()];
    }

    /**
    Method to set owner on case created from SoMe-post quick actions
    @param newCaseList The list of new version of the case i.e. the Trigger.new variable
    */
    private static void assignOwnerFromSoMe(List < Case > newCaseList) {
        Set < Id > socialPostIds = new Set < Id > ();
        List < Case > caseInScope = new List < Case > ();
        for (Case c: newCaseList) {
            Boolean infoTag = (c.Origin == 'Facebook' || c.Origin == 'Twitter') && (c.SourceId != null && c.SourceId.getSOBjectType() == SocialPost.SObjectType && c.Status == CASE_STATUS_CLOSED && c.RecordTypeId == C_RecordTypeHelper.CASE_INFORMATION);
            Boolean supportTag = (c.Origin == 'Facebook' || c.Origin == 'Twitter') && (c.SourceId != null && c.SourceId.getSOBjectType() == SocialPost.SObjectType && c.Status == CASE_STATUS_CLOSED && c.RecordTypeId == C_RecordTypeHelper.CASE_SUPPORT);
            Boolean feedbackTag = (c.Origin == 'Facebook' || c.Origin == 'Twitter') && (c.SourceId != null && c.SourceId.getSOBjectType() == SocialPost.SObjectType && c.Status == CASE_STATUS_CLOSED && c.RecordTypeId == C_RecordTypeHelper.CASE_FEEDBACK);
            if ((infoTag || supportTag || feedbackTag)) {
                socialPostIds.add(c.SourceId);
                caseInScope.add(c);
            }
        }
        Map < Id, SocialPost > socialPostsByIds = new Map < Id, SocialPost > ([SELECT Id, OwnerId FROM SocialPost WHERE Id =: socialPostIds]);
        for (Case c: caseInScope) {
            if (socialPostsByIds.containsKey(c.SourceId)) {
                if (socialPostsByIds.get(c.SourceId).OwnerId.getSObjectType() == User.SObjectType) {
                    c.OwnerId = socialPostsByIds.get(c.SourceId).OwnerId;
                } else {
                    c.addError('The Social Post needs to be assign to a user before tagging the post');
                }
            }
        }
    }

    /**
    Method to update parent social post with status fields when case is created
    @param newCaseList The list of new version of the case i.e. the Trigger.new variable
    */
    private static void updateSocialPost(List < Case > newCaseList) {
        Map < Id, Case > caseBySoMeIds = new Map < Id, Case > ();
        for (Case c: newCaseList) {
            if (c.SourceId != null && c.SourceId.getSobjectType() == SocialPost.SObjectType) {
                caseBySoMeIds.put(c.SourceId, c);
            }
        }
        if (!caseBySoMeIds.isEmpty()) {
            List < SocialPost > sps = [SELECT Id FROM SocialPost WHERE Id =: caseBySoMeIds.keySet() AND ParentId = null];
            List < SocialPost > spToUpdate = new List < SocialPost > ();
            for (SocialPost sp: sps) {
                sp.ParentId = caseBySoMeIds.get(sp.Id).Id;
                if (caseBySoMeIds.get(sp.Id).Status != CASE_STATUS_CLOSED) {
                    sp.FCS_CaseCreated__c = true;
                    sp.FCS_Done__c = true;
                    sp.FCS_ClosedDate__c = system.now();
                    sp.ReviewedStatus = SP_STATUS_REVIEWED;
                }
                spToUpdate.add(sp);
            }
            update spToUpdate;
        }
    }

    /**
    Method to make sure Case Reason and Case Tags is not the same value
    @param newCaseList The list of new version of the case i.e. the Trigger.new variable
    */
    private static void validateCaseTags(List < Case > newCaseList) {
        Integer cSize = newCaseList.size();
        for (Integer i = 0; i < cSize; i++) {
            Case newC = newCaseList[i];
            List < String > caseTagString = newC.FCS_CaseTags__c != null ? newC.FCS_CaseTags__c.split(';') : null;
            if (caseTagString != null) {
                for (String s: CaseTagString) {
                    if (s == newC.FCS_CaseReason__c) {
                        newC.addError('You can not provide the same additional reason (case tag) as the Case Reason');

                    }
                }
            }
        }
    }

    /**
     * Creates/updates/delete case tag records when tags (Case Reason, Case SubReason or Case Tag) is updated on case
     * @param newCaseMap The map between the id and the new version of the case i.e. the Trigger.newMap variable
     */
    private static void manageCaseTagRecords(List < Case > newCaseList, Map < Id, Case > newCaseMap) {
        Map < String, FCS_CaseTag__c > newTagByKeyId = createToBeCaseTagMap(newCaseList);
        Map < String, FCS_CaseTag__c > oldTagByKeyId = createCurrentCaseTagMap(newCaseMap);
        List < FCS_CaseTag__c > deleteCaseTags = new List < FCS_CaseTag__c > ();
        List < FCS_CaseTag__c > createCaseTags = new List < FCS_CaseTag__c > ();

        for (String keyId: newTagByKeyId.keySet()) {
            if (oldTagByKeyId.containsKey(keyId)) oldTagByKeyId.remove(keyId);
            else if (!oldTagByKeyId.containsKey(keyId)) createCaseTags.add(newTagByKeyId.get(keyId));
        }
        deleteCaseTags = oldTagByKeyId.values();
        if (createCaseTags != null) upsert createCaseTags;
        if (deleteCaseTags != null) delete deleteCaseTags;
    }
    /**
     * Returns a map containing the current (old) case tags records that needs to be evaluate agianst the new version of the case, FCS_CaseId__c+CaseTag+Type as key
     * @param newCaseMap The map between the id and the new version of the case i.e. the Trigger.newMap variable
     * @return caseTagsByKeyId Map with existing case tag records (FCS_CaseTag__c) with FCS_CaseId__c+Tag+Type as key
     */
    public static Map < String, FCS_CaseTag__c > createCurrentCaseTagMap(Map < Id, Case > newCaseMap) {
        List < FCS_CaseTag__c > caseTagRecords = [SELECT Id, FCS_CaseTag__c, FCS_Type__c, FCS_CaseId__c FROM FCS_CaseTag__c WHERE FCS_CaseId__c =: newCaseMap.keySet()];
        Map < String, FCS_CaseTag__c > caseTagsByKeyId = new Map < String, FCS_CaseTag__c > ();
        if (!caseTagRecords.isEmpty()) {
            for (FCS_CaseTag__c ct: caseTagRecords) {
                if (!caseTagsByKeyId.containsKey(ct.FCS_CaseId__c + ct.FCS_CaseTag__c + ct.FCS_Type__c)) caseTagsByKeyId.put(ct.FCS_CaseId__c + ct.FCS_CaseTag__c + ct.FCS_Type__c, ct);
            }
        }
        return caseTagsByKeyId;
    }

    /**
     * Returns a map containg the updated version (new) of the case tags records with FCS_CaseId__c+CaseTag+Type as key
     * @param newCaseList The list of the new version of the case i.e. the Trigger.new variable
     * @return newTagsByKeyId Map with new case tags on Case with FCS_CaseId__c+Tag+Type as key
     */
    public static Map < String, FCS_CaseTag__c > createToBeCaseTagMap(List < Case > newCaseList) {
        Integer cSize = newCaseList.size();
        Map < String, FCS_CaseTag__c > newTagsByKeyId = new Map < String, FCS_CaseTag__c > ();
        for (Integer i = 0; i < cSize; i++) {
            Case newC = newCaseList == null ? null : newCaseList[i];
            List < String > caseTagString = newC.FCS_CaseTags__c != null ? newC.FCS_CaseTags__c.split(';') : null;
            if (newC.FCS_CaseReason__c != null) newTagsByKeyId.put(newC.Id + newC.FCS_CaseReason__c + MAIN_TAG, new FCS_CaseTag__c(FCS_CaseId__c = newC.Id, FCS_CaseTag__c = newC.FCS_CaseReason__c, FCS_Type__c = MAIN_TAG));
            if (newC.FCS_CaseSubReason__c != null) newTagsByKeyId.put(newC.Id + newC.FCS_CaseSubReason__c + SUB_MAIN_TAG, new FCS_CaseTag__c(FCS_CaseId__c = newC.Id, FCS_CaseTag__c = newC.FCS_CaseSubReason__c, FCS_Type__c = SUB_MAIN_TAG));
            if (caseTagString != null) {
                for (String s: CaseTagString) {
                    newTagsByKeyId.put(newC.Id + s + ADDITIONAL_TAG, new FCS_CaseTag__c(FCS_CaseId__c = newC.Id, FCS_CaseTag__c = s, FCS_Type__c = ADDITIONAL_TAG));
                }
            }
        }
        return newTagsByKeyId;
    }
    public static void assignEurobonusAccountToCase(List < Case > newCaseList) {
        List < String > lstEmailAddress = new List < String > ();
        List < Account > lstAccount = New List < Account > ();
        Map < String, Account > mapEmailToEurobonsAcc = new Map < String, Account > ();
        for (Case cse: newCaseList) {
            lstEmailAddress.add(cse.SuppliedEmail);
        }
        lstAccount = [SELECT
                        Id,
                        Name,
                        PersonEmail,
                        FCS_EBNumber__c
                        FROM
                        Account
                        Where
                        IsPersonAccount = true
                        AND
                        PersonEmail =: lstEmailAddress
                    ];

        if (!lstAccount.isEmpty()) {
            for (Account acc: lstAccount) {
                mapEmailToEurobonsAcc.put(acc.PersonEmail, acc);
            }
        }

        if (mapEmailToEurobonsAcc.size() > 0) {
            for (Case cse: newCaseList) {
                if (mapEmailToEurobonsAcc.containsKey(cse.SuppliedEmail)) {
                    cse.FCS_EBNumber__c = mapEmailToEurobonsAcc.get(cse.SuppliedEmail).FCS_EBNumber__c;
                    cse.AccountId = mapEmailToEurobonsAcc.get(cse.SuppliedEmail).Id;
                }
            }
        }


    }

}