sas-core/main/default/objects/Account/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <description>Unique identifier for customer in CODA. Corresponds to ExternalId on Frequent Flyer.</description>
    <externalId>true</externalId>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Account/fields/GDPR_Wiped__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Wiped__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set when the account has been wiped from the system.</description>
    <label>Wiped</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Account/fields/GDPR_WipedSoft__c.field-meta.xml
<CustomField>
    <fullName>GDPR_WipedSoft__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the data has been softly wiped from the account. I.e. the data may be restored since the account still has an identifier which enables the information to be refetched for the account.</description>
    <label>Wiped Soft</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CODSId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CODSId__c</fullName>
    <label>CODS Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/GDPR_Wiped__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Wiped__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the case data has been cleared from identifiable information and related interactions have been deleted.</description>
    <label>Wiped</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Information.recordType-meta.xml
<RecordType>
    <fullName>Information</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Information</label>
</RecordType>

sas-core/main/default/classes/GDPR_WipeAccountService.cls
/**
    Service used to privde the ability to fully wipe a customer
    from the system. Only the system fields of the accouint will remain as well
    as the wiped case information.
    @author Peter Södergren
*/
global with sharing class GDPR_WipeAccountService {
    /**
        Retrieves the account fields to clear based where the fields 
        stored in the general setting group AWRF are removed
        @param keepReference Whether to keep a reference to account to be able to refetch data at a later point
        @return The list fo fields which should be wiped from the case
    */
    global static String[] getAccountFieldsToClear(Boolean keepReference){
        Set<String> retainedFields = new Set<String>();
        //TODO When issue related to retrieving multiple field definitions in on transaction os solved, remove Case filted from this query
        FieldDefinition[] fdList = [SELECT QualifiedAPIName,ComplianceGroup, EntityDefinitionId FROM FieldDefinition WHERE (EntityDefinitionId ='Account' OR EntityDefinitionId ='Case') AND ComplianceGroup!=null];
        for(FieldDefinition fd : fdList){
            if(fd.EntityDefinitionId == 'Account' && fd.ComplianceGroup.split(';').contains('WipeRetain'))retainedFields.add(fd.QualifiedAPIName);
        }
        //Add fields for which compliance cannot be set
        retainedFields.add('MasterRecordId');
        retainedFields.add('RecordTypeId');
        //Name is not removed since it cannot be edited for person accounts
        retainedFields.add('Name');
        if(keepReference)retainedFields.add(Account.FCS_CodsId__c+'');

        List<String> fieldsToClear = new List<String>();
        Map<String,Schema.SObjectField> fMap = Account.getSObjectType().getDescribe().fields.getMap();
        for(String k : fMap.keySet()){
            Schema.SObjectField f = fMap.get(k);
            if(!retainedFields.contains(f+'')){
                Schema.DescribeFieldResult dfr = f.getDescribe();
                if(dfr.isNillable() && dfr.getType()!=Schema.DisplayType.ADDRESS && dfr.isUpdateable())fieldsToClear.add(k);
            }
        }
        return fieldsToClear;
    }

    /**
        Retrieves the wiped account name from the GDPR settings
        @return The name to use for wiped accounts
    */
    global static String getWipedAccountName(){
        C_Settings.SettingsGroup sg = C_Settings.getSettings('GDPR');
        return sg.get('AccountDataWipeName');
    }
    /**
        Wipes the provided customer ids from the system clearing the account data.
        @param accIds The account ids to wipe
        @param fieldsToClear The fields to wipe on the account
        @param wipedAccountName The name to give the account after wiping the account
        @param hardWipe Whether the wiped information is removed in such a way that the identity of the account cannot be recovered
        @param wipeRelated Whether to wipe related case and communication data in addition to the account data
    */
    global static void wipeAccounts(Id[] accIds, String[] fieldsToClear, String wipedAccountName, Boolean hardWipe, Boolean wipeRelated){
        Integer sz = accIds.size();
        Account[] accList = new Account[sz];
        for(Integer i=0;i<sz;i++){
            Account acc = new Account(Id=accIds[i]);
            for(Integer j=0,jSz=fieldsToClear.size();j<jSz;j++){
                acc.put(fieldsToClear[j],null);
            }
            acc.GDPR_WipedSoft__c = true;
            if(hardWipe)acc.GDPR_Wiped__c = true;
            acc.FirstName = null;
            acc.LastName = wipedAccountName;
            accList[i] = acc;
        }
        update accList;
        if(wipeRelated){
            Case[] cList = [SELECT Id FROM Case WHERE AccountId IN :accIds];
            if(!cList.isEmpty())GDPR_WipeCaseService.wipeCases(cList);
        }
    }

    /**
        Wipes the provided customer ids from the system clearing the account data
        and wiping the cases.
        @param accIds The account ids to wipe
    */
    global static void wipeAccounts(Id[] accIds){
        wipeAccounts(accIds, getAccountFieldsToClear(false),getWipedAccountName(),true, true);
    }
}