sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CaseToBooking__c/CaseToBooking__c.object-meta.xml
<CustomObject>
    <label>CaseToBooking</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CaseToBooking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CasesToBookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CaseToBooking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/CaseToBooking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/selectors/CaseToBookingsSelector.cls
public inherited sharing class CaseToBookingsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      CaseToBooking__c.Id,
      CaseToBooking__c.Booking__c,
      CaseToBooking__c.Case__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return CaseToBooking__c.SObjectType;
  }

  public static CaseToBookingsSelector newInstance() {
    return (CaseToBookingsSelector) SAS_Service_Application.Selector.newInstance(
      CaseToBooking__c.SObjectType
    );
  }

  public List<CaseToBooking__c> selectById(Set<Id> ids) {
    return (List<CaseToBooking__c>) selectSObjectsById(ids);
  }

  public List<CaseToBooking__c> selectByCaseId(Set<Id> caseIds) {
    if (caseIds.contains(null)) {
      return new List<CaseToBooking__c>();
    }
    return (List<CaseToBooking__c>) Database.query(
      newQueryFactory().setCondition('Case__c in :caseIds').toSOQL()
    );
  }

  public List<CaseToBooking__c> selectByBookingReference(
    Set<String> bookingReferences
  ) {
    return (List<CaseToBooking__c>) Database.query(
      newQueryFactory()
        .setCondition('Booking__r.Booking_Reference__c in :bookingReferences')
        .toSOQL()
    );
  }

  public List<CaseToBooking__c> selectByCaseIdAndBookingReference(
    Id caseId,
    String bookingReference
  ) {
    return (List<CaseToBooking__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'Case__c =:caseId AND Booking__r.Booking_Reference__c =:bookingReference'
        )
        .toSOQL()
    );
  }

  public override String getOrderBy() {
    return 'Name';
  }
}