sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Initially_Provided_PNR__c.field-meta.xml
<CustomField>
    <fullName>Initially_Provided_PNR__c</fullName>
    <description>PNR provided by the customer at chat.</description>
    <inlineHelpText>PNR provided by the customer at chat.</inlineHelpText>
    <label>Initially Provided PNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Refund_Request__c.field-meta.xml
<CustomField>
    <fullName>Refund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund Request</label>
    <referenceTo>Refund_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
	<complianceGroup>Lookup</complianceGroup>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/Refund_Request__c.object-meta.xml
<CustomObject>
    <label>Refund Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Refund Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Refund_Request__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/tests/integration/Refunds_IntegrationTest.cls
@IsTest
public with sharing class Refunds_IntegrationTest {
  public static String bookingReferenceOnlyInTEDS = 'TEDS12';
  public static String invalidBookingReference = 'AAAAAA';
  public static String ebNumberWithBookings = 'TEST123456';
  public static String ebNumberWithoutBookings = 'TEST654321';

  public static BookingsSelector bookings = (BookingsSelector) SAS_Service_Application.Selector.newInstance(
    Booking__c.SObjectType
  );

  public static Refund_RequestsSelector refundRequests = (Refund_RequestsSelector) SAS_Service_Application.Selector.newInstance(
    Refund_Request__c.SObjectType
  );

  @IsTest
  public static void insertingCaseWithRefundFetchesRelatedBooking() {
    // Given

    Refund_Request__c refund = new Refund_Request__c(
      PNR__c = bookingReferenceOnlyInTEDS
    );

    insert refund;

    Case testCase = FCS_TestDataFactory.createCases(1, null, null, null)[0];

    testCase.Refund_Request__c = refund.Id;
    testCase.Initially_Provided_PNR__c = bookingReferenceOnlyInTEDS;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    // When
    insert testCase;
    Test.stopTest();

    // Then
    Booking__c bookingFromDB = bookings.selectByCaseId(
      new Set<Id>{ testCase.Id }
    )[0];

    System.assertEquals(
      bookingReferenceOnlyInTEDS,
      bookingFromDB.Booking_Reference__c,
      'Booking should be found by case Id of the refund case and have the same reference'
    );
  }

  @IsTest
  public static void pnrShouldAlwaysBeUppercase() {
    Refund_Request__c refund = new Refund_Request__c(PNR__c = 'abc123');

    Test.startTest();

    insert refund;
    Refund_Request__c refundRequestAfterInsert = refundRequests.selectById(
      new Set<Id>{ refund.Id }
    )[0];
    System.assertEquals(
      'ABC123',
      refundRequestAfterInsert.PNR__c,
      'Refund request PNR should be uppercase after insert.'
    );

    refund.PNR__c = 'def456';
    update refund;
    Refund_Request__c refundRequestAfterUpdate = refundRequests.selectById(
      new Set<Id>{ refund.Id }
    )[0];
    System.assertEquals(
      'DEF456',
      refundRequestAfterUpdate.PNR__c,
      'Refund request PNR should be uppercase after update.'
    );

    Test.stopTest();
  }
}