sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the passenger record has an EB number, this field is populated with the corresponding person account.</description>
    <inlineHelpText>If the passenger record has an EB number, this field is populated with the corresponding person account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>PassengerRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this passenger in this booking. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this passenger in this booking. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/bookings/Passenger.cls
public without sharing class Passenger extends AbstractSObjectWrapper {
  public Passenger__c underlyingSObject { get; private set; }

  public Id accountId;
  public Id bookingId;

  public String email;
  public String euroBonusNumber;
  public String firstName;
  public String identifier;
  public String lastName;
  public String phone;

  public String normalizedFullName {
    get {
      return normalizeName(this.firstName + ' ' + this.lastName);
    }
  }

  @TestVisible
  private Passenger() {
    this.underlyingSObject = new Passenger__c();
  }

  public Passenger(Passenger__c p) {
    super(p);
    this.underlyingSObject = p;

    this.accountId = p.Account__c;
    this.bookingId = p.Booking__c;
    this.email = p.Email__c;
    this.euroBonusNumber = p.EuroBonus_Number__c;
    this.firstName = p.First_Name__c;
    this.identifier = p.Identifier__c;
    this.lastName = p.Last_Name__c;
    this.phone = p.Phone__c;
  }

  public override void updateSObjectFields() {
    this.underlyingSObject.Account__c = this.accountId;
    this.underlyingSObject.Booking__c = this.bookingId;
    this.underlyingSObject.Email__c = this.email;
    this.underlyingSObject.EuroBonus_Number__c = this.euroBonusNumber;
    this.underlyingSObject.First_Name__c = this.firstName;
    this.underlyingSObject.Identifier__c = this.identifier;
    this.underlyingSObject.Last_Name__c = this.lastName;
    this.underlyingSObject.Phone__c = this.phone;
  }

  public static String normalizeName(String name) {
    return StringUtils.removeWhitespace(StringUtils.scandicsToASCII(name))
      .replaceAll('-', '')
      .toLowerCase();
  }

  /**
   * Creates a new Passengers instance based on the response from EDW
   * @param passengerData List of passengers from the parsed EDW data
   */
  public static Passengers createFromEDWData(
    List<FetchEDWBookingResponse.Passenger> passengerData
  ) {
    List<Passenger__c> toReturn = new List<Passenger__c>();
    for (FetchEDWBookingResponse.Passenger passenger : passengerData) {
      Passenger p = new Passenger(new Passenger__c());
      p.firstName = passenger.firstName;
      p.lastName = passenger.surName;
      p.euroBonusNumber = String.valueOf(passenger.ebNumber);
      p.email = passenger.email;
      p.phone = String.valueOf(passenger.mobile);
      p.identifier = 'PT' + passenger.passengerTattoo;
      p.updateSObjectFields();
      toReturn.add(p.underlyingSObject);
    }
    return Passengers.newInstance(toReturn);
  }
}