sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Baggage_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Baggage_Quantity__c</fullName>
    <label>Baggage Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Check_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Status__c</fullName>
    <label>Check In Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>NotAccepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>StandBy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Fare Basis</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Fare_Price__c.field-meta.xml
<CustomField>
    <fullName>Fare_Price__c</fullName>
    <label>Fare Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Is_Boarded__c.field-meta.xml
<CustomField>
    <fullName>Is_Boarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Boarded</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Segment_Status__c.field-meta.xml
<CustomField>
    <fullName>Segment_Status__c</fullName>
    <description>Status of this segment in the booking. Should be the same for all passengers for a given segment.</description>
    <inlineHelpText>Status of this segment in the booking. Should be the same for all passengers for a given segment.</inlineHelpText>
    <label>Segment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>CallToConfirm</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>SpaceAvailable</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Segment_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Segment_Status_Code__c</fullName>
    <description>Two letter code describing the segment status.</description>
    <inlineHelpText>Two letter code describing the segment status.</inlineHelpText>
    <label>Segment Status Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Service_Class__c.field-meta.xml
<CustomField>
    <fullName>Service_Class__c</fullName>
    <label>Service Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Special_Service_Requests__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Requests__c</fullName>
    <description>Special service codes for this segment. Separated by commas.</description>
    <inlineHelpText>Special service codes for this segment. Separated by commas.</inlineHelpText>
    <label>Special Service Requests</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <label>Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/bookings/Segment.cls
public without sharing class Segment extends AbstractSObjectWrapper implements Comparable {
  public Segment__c underlyingSObject { get; private set; }

  public Id bookingId;
  public Id flightId;

  public Decimal baggageQuantity;
  public String bookingClass;
  public String checkInStatus;
  public String fareBasis;
  public Decimal farePrice;
  public String identifier;
  public Boolean isBoarded = false;
  public String seat;
  public String segmentStatus;
  public String segmentStatusCode;
  public String serviceClass;
  public String specialServiceRequests;
  public String ticketNumber;
  public String ticketType;
  public String tripType;

  public Flight flight;

  public List<SegmentEvent> events; // Todo: handle initialization

  private Segment() {
    this.underlyingSObject = new Segment__c();
  }

  public Segment(Segment__c s) {
    super(s);
    this.underlyingSObject = s;

    this.bookingId = s.Booking__c;
    this.flightId = s.Flight__c;
    this.baggageQuantity = s.Baggage_Quantity__c;
    this.bookingClass = s.Booking_Class__c;
    this.checkInStatus = s.Check_In_Status__c;
    this.fareBasis = s.Fare_Basis__c;
    this.farePrice = s.Fare_Price__c;
    this.identifier = s.Identifier__c;
    this.isBoarded = s.Is_Boarded__c;
    this.seat = s.Seat__c;
    this.segmentStatus = s.Segment_Status__c;
    this.segmentStatusCode = s.Segment_Status_Code__c;
    this.serviceClass = s.Service_Class__c;
    this.specialServiceRequests = s.Special_Service_Requests__c;
    this.ticketNumber = s.Ticket_Number__c;
    this.ticketType = s.Ticket_Type__c;
    this.tripType = s.Trip_Type__c;

    if (s.Flight__r != null) {
      this.flight = new Flight(s.Flight__r);
    }
  }

  public override void updateSObjectFields() {
    this.underlyingSObject.Baggage_Quantity__c = this.baggageQuantity;
    this.underlyingSObject.Booking__c = this.bookingId;
    this.underlyingSObject.Booking_Class__c = this.bookingClass;
    this.underlyingSObject.Check_In_Status__c = this.checkInStatus;
    this.underlyingSObject.Fare_Basis__c = this.fareBasis;
    this.underlyingSObject.Fare_Price__c = this.farePrice;
    this.underlyingSObject.Flight__c = this.flightId;
    this.underlyingSObject.Identifier__c = this.identifier;
    this.underlyingSObject.Is_Boarded__c = this.isBoarded;
    this.underlyingSObject.Seat__c = this.seat;
    this.underlyingSObject.Segment_Status__c = this.segmentStatus;
    this.underlyingSObject.Segment_Status_Code__c = this.segmentStatusCode;
    this.underlyingSObject.Service_Class__c = this.serviceClass;
    this.underlyingSObject.Special_Service_Requests__c = this.specialServiceRequests;
    this.underlyingSObject.Ticket_Number__c = this.ticketNumber;
    this.underlyingSObject.Ticket_Type__c = this.ticketType;
    this.underlyingSObject.Trip_Type__c = this.tripType;
  }

  public Integer compareTo(Object other) {
    Segment otherSegment = (Segment) other;

    Integer toReturn = 0;

    if (other == null) {
      return 1;
    }

    if (this.flight == null || otherSegment.flight == null) {
      return 0;
    }

    if (
      this.flight.scheduledDepartureTime >
      otherSegment.flight.scheduledDepartureTime
    ) {
      return 1;
    } else if (
      this.flight.scheduledDepartureTime <
      otherSegment.flight.scheduledDepartureTime
    ) {
      return -1;
    } else {
      return 0;
    }
  }

  public Boolean isActive(Datetime theTime) {
    events.sort();
    Boolean confirmed = false;
    for (SegmentEvent se : events) {
      if (se.updateDate > theTime) {
        break;
      }
      SegmentEvent.StatusCode newStatus = SegmentEvent.STATUS_PICKLIST_VALUE_TO_ENUM.get(
        se.newStatus
      );
      if (newStatus == SegmentEvent.StatusCode.C_HK) {
        // Holds confirmed
        confirmed = true;
      }
      if (newStatus == SegmentEvent.StatusCode.C_UN) {
        // Unable - no flight
        return false;
      }
    }
    return confirmed;
  }

  public Boolean isActive() {
    events.sort();
    Boolean confirmed = false;
    for (SegmentEvent se : events) {
      SegmentEvent.StatusCode newStatus = SegmentEvent.STATUS_PICKLIST_VALUE_TO_ENUM.get(
        se.newStatus
      );
      if (newStatus == SegmentEvent.StatusCode.C_HK) {
        // Holds confirmed
        confirmed = true;
      }
      if (newStatus == SegmentEvent.StatusCode.C_UN) {
        // Unable - no flight
        return false;
      }
    }
    return confirmed;
  }
}