sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time_Local__c</fullName>
    <label>Actual Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time__c</fullName>
    <label>Actual Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time_Local__c</fullName>
    <label>Actual Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Aircraft_Registration__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Registration__c</fullName>
    <description>Flight Registration for the Aircraft used for this flight</description>
    <label>Aircraft Registration</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Delayed_Minutes__c</fullName>
    <label>Arrival Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Gate__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Gate__c</fullName>
    <label>Arrival Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Status__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Arrival Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Terminal__c</fullName>
    <label>Arrival Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Departure_Delayed_Minutes__c</fullName>
    <label>Departure Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Gate__c.field-meta.xml
<CustomField>
    <fullName>Departure_Gate__c</fullName>
    <label>Departure Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Departure_Terminal__c</fullName>
    <label>Departure Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Time__c</fullName>
    <label>Estimated Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Time_Local__c</fullName>
    <label>Estimated Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_Time__c</fullName>
    <label>Estimated Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_Time_Local__c</fullName>
    <label>Estimated Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operational_Control_Center__c.field-meta.xml
<CustomField>
    <fullName>Operational_Control_Center__c</fullName>
    <label>Operational Control Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time_Local__c</fullName>
    <label>Scheduled Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time_Local__c</fullName>
    <label>Scheduled Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/selectors/FlightsSelector.cls
public inherited sharing class FlightsSelector extends fflib_SObjectSelector {
  // TODO: Make the airports lookups
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Flight__c.Id,
      Flight__c.Name,
      Flight__c.CreatedDate,
      Flight__c.LastModifiedDate,
      Flight__c.Aircraft_Registration__c,
      Flight__c.Actual_Arrival_Time__c,
      Flight__c.Actual_Arrival_Time_Local__c,
      Flight__c.Actual_Departure_Time__c,
      Flight__c.Actual_Departure_Time_Local__c,
      Flight__c.Arrival_Airport__c,
      Flight__c.Arrival_Delayed_Minutes__c,
      Flight__c.Arrival_Gate__c,
      Flight__c.Arrival_Status__c,
      Flight__c.Arrival_Terminal__c,
      Flight__c.Departure_Airport__c,
      Flight__c.Departure_Delayed_Minutes__c,
      Flight__c.Departure_Gate__c,
      Flight__c.Departure_Status__c,
      Flight__c.Departure_Terminal__c,
      Flight__c.Estimated_Arrival_Time__c,
      Flight__c.Estimated_Arrival_Time_Local__c,
      Flight__c.Estimated_Departure_Time__c,
      Flight__c.Estimated_Departure_Time_Local__c,
      Flight__c.Operating_Carrier__c,
      Flight__c.Operational_Control_Center__c,
      Flight__c.Scheduled_Arrival_Time__c,
      Flight__c.Scheduled_Arrival_Time_Local__c,
      Flight__c.Scheduled_Departure_Time__c,
      Flight__c.Scheduled_Departure_Time_Local__c,
      Flight__c.TEDS_Identifier__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Flight__c.SObjectType;
  }

  public static FlightsSelector newInstance() {
    return (FlightsSelector) SAS_Service_Application.Selector.newInstance(
      Flight__c.SObjectType
    );
  }

  public List<Flight__c> selectById(Set<Id> ids) {
    return (List<Flight__c>) selectSObjectsById(ids);
  }

  public List<Flight__c> selectByTEDSId(Set<String> flightIds) {
    return (List<Flight__c>) Database.query(
      newQueryFactory()
        .setCondition('TEDS_Identifier__c IN :flightIds')
        .toSOQL()
    );
  }

  public List<Flight__c> selectByFlightNumberAndDate(
    String flightNumber,
    Date departureDate
  ) {
    String flightLikeId =
      Flight.constructTEDSFlightNumberDate(flightNumber, departureDate) +
      '-___-___';

    return (List<Flight__c>) Database.query(
      newQueryFactory()
        .setCondition('TEDS_Identifier__c LIKE :flightLikeId')
        .toSOQL()
    );
  }

  /**
   * Selects all flights linked to the given bookings through segments.
   */
  public List<Flight__c> selectByBookingIds(Set<Id> bookingIds) {
    List<Booking__c> bookings = BookingsSelector.newInstance()
      .selectByIdFull(bookingIds);

    if (bookings == null || bookings.size() == 0) {
      return new List<Flight__c>();
    }

    Set<Id> flightIds = new Set<Id>();

    for (Booking__c booking : bookings) {
      for (Segment__c segment : booking.Segments__r) {
        flightIds.add(segment.Flight__c);
      }
    }

    return selectById(flightIds);
  }

  public List<Flight__c> selectBybookingReference(
    Set<String> bookingReference
  ) {
    List<Booking__c> bookings = BookingsSelector.newInstance()
      .selectByBookingReference(bookingReference);
    List<Flight__c> toReturn = new List<Flight__c>{};
    for (Booking__c b : bookings) {
      for (Segment__c s : b.Segments__r) {
        toReturn.add(s.Flight__r);
      }
    }

    return toReturn;
  }

  public override String getOrderBy() {
    return 'TEDS_Identifier__c';
  }
}