sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/tests/utils/PassengerFactory.cls
public with sharing class PassengerFactory {
  public static Passenger create() {
    Booking b = new Booking(new Booking__c());
    return create(b);
  }

  public static Passenger create(Booking b) {
    return create(b, 1)[0];
  }

  public static List<Passenger> create(Booking b, Integer noPassengers) {
    List<Passenger> passengers = new List<Passenger>{};
    for (Integer i = 0; i < noPassengers; i++) {
      Passenger p = new Passenger(new Passenger__c());
      p.accountId = Id.valueOf('001xa000003DIlo'); // TODO: fix;
      p.bookingId = b.id;
      p.email = 'test' + String.valueOf(i) + '@gmail.com';
      p.euroBonusNumber = StringUtils.padWithZeros(String.valueOf(i), 9);
      p.firstName = 'Test' + String.valueOf(i);
      p.lastName = 'Testsson' + String.valueOf(i);
      p.identifier = 'PT' + String.valueOf(i);
      p.phone = StringUtils.padWithZeros(String.valueOf(i), 10);
      passengers.add(p);
    }

    return passengers;
  }

  public static Passenger create(Booking b, ClaimCustomer cc) {
    Passenger p = create(b, 1)[0];
    p.firstName = cc.firstName;
    p.lastName = cc.lastName;
    return p;
  }
}