sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Baggage_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Baggage_Quantity__c</fullName>
    <label>Baggage Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Check_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Status__c</fullName>
    <label>Check In Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>NotAccepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>StandBy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Fare Basis</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Is_Boarded__c.field-meta.xml
<CustomField>
    <fullName>Is_Boarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Boarded</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Service_Class__c.field-meta.xml
<CustomField>
    <fullName>Service_Class__c</fullName>
    <label>Service Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Special_Service_Requests__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Requests__c</fullName>
    <description>Special service codes for this segment. Separated by commas.</description>
    <inlineHelpText>Special service codes for this segment. Separated by commas.</inlineHelpText>
    <label>Special Service Requests</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <label>Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/SegmentsSelector.cls
public inherited sharing class SegmentsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Segment__c.Id,
      Segment__c.Baggage_Quantity__c,
      Segment__c.Booking__c,
      Segment__c.Booking_Class__c,
      Segment__c.Check_In_Status__c,
      Segment__c.Fare_Basis__c,
      Segment__c.Flight__c,
      Segment__c.Identifier__c,
      Segment__c.Is_Boarded__c,
      Segment__c.Seat__c,
      Segment__c.Service_Class__c,
      Segment__c.Special_Service_Requests__c,
      Segment__c.Ticket_Number__c,
      Segment__c.Ticket_Type__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Segment__c.SObjectType;
  }

  public List<Segment__c> selectById(Set<Id> ids) {
    return (List<Segment__c>) selectSObjectsById(ids);
  }

  public override String getOrderBy() {
    return 'Booking__c, Identifier__c';
  }
}