sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Status__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Arrival Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/domain/bookings/Bookings_Test.cls
@IsTest
public with sharing class Bookings_Test {
  private static BookingsSelector bookingsSel = BookingsSelector.newInstance();
  @IsTest
  public static void bookingWithDelayedFlightsShouldReturnTrue() {
    Flight__c flight1 = new Flight__c(
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK1',
      Arrival_Status__c = 'delayed',
      Departure_Status__c = 'ontime'
    );
    Flight__c flight2 = new Flight__c(
      Operating_Carrier__c = 'AY',
      TEDS_Identifier__c = 'AY1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'delayed'
    );
    Booking__c booking = new Booking__c(
      Booking_Reference__c = 'ABC123',
      TEDS_Identifier__c = 'ABC123'
    );
    insert new List<SObject>{ booking, flight1, flight2 };

    Segment__c seg1 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight1.Id
    );
    Segment__c seg2 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight2.Id
    );
    insert new List<SObject>{ seg1, seg2 };
    Booking__c bookingToTest = bookingsSel.selectByIdFull(
      new Set<Id>{ booking.Id }
    )[0];
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Bookings b = Bookings.newInstance(new List<Booking__c>{ bookingToTest })
      .reloadFullBookingData();
    Boolean result = b.objects[0].hasDelayedOrCancelledFlights();
    Test.stopTest();
    System.assert(
      result,
      'Booking should be marked as containing delayed flights'
    );
  }
  @IsTest
  public static void bookingWithCancelledFlightsShouldReturnTrue() {
    Flight__c flight1 = new Flight__c(
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK1',
      Arrival_Status__c = 'cancelled',
      Departure_Status__c = 'cancelled'
    );
    Flight__c flight2 = new Flight__c(
      Operating_Carrier__c = 'AY',
      TEDS_Identifier__c = 'AY1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'ontime'
    );
    Booking__c booking = new Booking__c(
      Booking_Reference__c = 'ABC123',
      TEDS_Identifier__c = 'ABC123'
    );
    insert new List<SObject>{ booking, flight1, flight2 };

    Segment__c seg1 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight1.Id
    );
    Segment__c seg2 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight2.Id
    );
    insert new List<SObject>{ seg1, seg2 };

    Booking__c bookingToTest = bookingsSel.selectByIdFull(
      new Set<Id>{ booking.Id }
    )[0];
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Bookings b = Bookings.newInstance(new List<Booking__c>{ bookingToTest })
      .reloadFullBookingData();
      Boolean result = b.objects[0].hasDelayedOrCancelledFlights();
    Test.stopTest();
    System.assert(
      result,
      'Booking should be marked as containing cancelled flights'
    );
  }
  @IsTest
  public static void bookingWithoutIrregularitiesShouldReturnFalse() {
    Flight__c flight1 = new Flight__c(
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'ontime'
    );
    Flight__c flight2 = new Flight__c(
      Operating_Carrier__c = 'AY',
      TEDS_Identifier__c = 'AY1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'ontime'
    );
    Booking__c booking = new Booking__c(
      Booking_Reference__c = 'ABC123',
      TEDS_Identifier__c = 'ABC123'
    );
    insert new List<SObject>{ booking, flight1, flight2 };

    Segment__c seg1 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight1.Id
    );
    Segment__c seg2 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight2.Id
    );
    insert new List<SObject>{ seg1, seg2 };
    Booking__c bookingToTest = bookingsSel.selectByIdFull(
      new Set<Id>{ booking.Id }
    )[0];
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Bookings b = Bookings.newInstance(new List<Booking__c>{ bookingToTest })
      .reloadFullBookingData();
      Boolean result = b.objects[0].hasDelayedOrCancelledFlights();
    Test.stopTest();
    System.assert(
      !result,
      'Booking should not be marked as containing delayed flights'
    );
  }

  @IsTest
  public static void invalidPnrsShouldBeIdentifiedCorrectly() {
    List<String> pnrs = new List<String>{
      'ABCD',
      '',
      null,
      '"abcde',
      'ÖABCDE'
    };

    for (String pnr : pnrs) {
      System.assert(
        !Booking.isValidBookingReference(pnr),
        'PNR: ' +
        pnr +
        ' should be invalid.'
      );
    }
  }

  @IsTest
  public static void validPnrsShouldBeIdentifiedCorrectly() {
    List<String> pnrs = new List<String>{
      'ABCDE',
      'ABCDEF',
      '234DER',
      'A2B4C8',
      '12345'
    };

    for (String pnr : pnrs) {
      System.assert(
        Booking.isValidBookingReference(pnr),
        'PNR: ' +
        pnr +
        ' should be valid.'
      );
    }
  }

  @IsTest
  public static void bookingShouldContainPassengerFlight() {
    Case c = TestDataFactories.createCasesWithClaims(
        1,
        null,
        new Map<Schema.SObjectField, Object>{
          LIA_Claim__c.Liability_PNR__c => APIMMock.DEFAULT_VALID_TEDS_PNR,
          LIA_Claim__c.Flight_Number__c => 'SK0402',
          LIA_Claim__c.Flight_Date__c => Date.valueOf('2021-04-20')
        }
      )
      .cases[0];

    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    BookingService.addBookingToCase(c.Id, APIMMock.DEFAULT_VALID_TEDS_PNR);
    Bookings b = Bookings.newInstance(
        BookingsSelector.newInstance()
          .selectByBookingReference(APIMMock.DEFAULT_VALID_TEDS_PNR)
      )
      .reloadFullBookingData();
    Test.stopTest();
    Booking currentBooking = b.objects[0];
    System.assert(
      currentBooking.containsFlight('SK0402-20210420'),
      'Flight should have been found in the booking'
    );
    System.assert(
      currentBooking.containsPassenger('TESTSSON'),
      'Passenger should have been found in the booking'
    );
    System.assert(
      !currentBooking.containsFlight('SK9999-20190620'),
      'Flight should not have been found in the booking'
    );
    System.assert(
      !currentBooking.containsPassenger('OtherTestsson'),
      'Passenger should not have been found in the booking'
    );
  }

  @IsTest
  public static void shouldReloadDataProperly() {
    Case c = TestDataFactories.createCasesWithClaims(
        1,
        null,
        new Map<Schema.SObjectField, Object>{
          LIA_Claim__c.Liability_PNR__c => APIMMock.DEFAULT_VALID_TEDS_PNR,
          LIA_Claim__c.Flight_Number__c => 'SK0402',
          LIA_Claim__c.Flight_Date__c => Date.valueOf('2021-04-20')
        }
      )
      .cases[0];
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    BookingService.addBookingToCase(c.Id, APIMMock.DEFAULT_VALID_TEDS_PNR);
    Bookings b = Bookings.newInstance(
        BookingsSelector.newInstance()
          .selectByBookingReference(APIMMock.DEFAULT_VALID_TEDS_PNR)
      )
      .reloadFullBookingData();
    Test.stopTest();
    System.assertNotEquals(b.fullRecords, null);
  }
}