sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/objects/Fetch_CARE_Data__e/Fetch_CARE_Data__e.object-meta.xml
<CustomObject>
    <description>Event for fetching CARE data from EDW.</description>
    <label>Fetch CARE Data</label>
    <pluralLabel>Fetch CARE Data</pluralLabel>
</CustomObject>

sas-core/main/default/objects/Fetch_CARE_Data__e/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>Booking reference to search EDW with. E.g. ABC123.</description>
    <label>Booking Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Fetch_CARE_Data__e/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <description>Id of the claim the duplicate should be tied to, if found.</description>
    <label>Claim Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Claims_Exist_In_CARE_For_PNR__c.field-meta.xml
<CustomField>
    <fullName>Claims_Exist_In_CARE_For_PNR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether claims exist in CARE for this claim&apos;s PNR.</description>
    <inlineHelpText>Whether claims exist in CARE for this claim&apos;s PNR.</inlineHelpText>
    <label>Claims Exist In CARE For PNR</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/recordTypes/CompensationCard.recordType-meta.xml
<RecordType>
    <fullName>CompensationCard</fullName>
    <active>true</active>
    <description>Record type to differentiate the customer claims</description>
    <label>CompensationCard</label>
</RecordType>

sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Customer&apos;s Bank Account Number</description>
    <inlineHelpText>Bank account number that will receive the monetary payment</inlineHelpText>
    <label>Bank Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability or Customer Claim</description>
    <inlineHelpText>This settlement is related to this Liability or Customer claim</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Liability_Claim__c.field-meta.xml
<CustomField>
    <fullName>Liability_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim</description>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/domain/claims/Claims.cls
public without sharing class Claims extends fflib_SObjectDomain {
  public Claims(List<SObject> records) {
    super(records);
    Configuration.disableTriggerCRUDSecurity();

    this.instanceRecords = (List<LIA_Claim__c>) Records;

    List<Claim> claimObjects = new List<Claim>();
    for (LIA_Claim__c c : this.instanceRecords) {
      claimObjects.add(new Claim(c));
    }

    this.objects = claimObjects;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Claims(records);
    }
  }

  public static Claims newInstance(List<LIA_Claim__c> sObjectList) {
    return (Claims) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  public List<Claim> objects;

  public List<LIA_Claim__c> instanceRecords;

  public override void onAfterInsert() {
    checkIfExistsInCARE();
    fetchCAREClaims();
    updateParentCaseBookings();
  }

  public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
    checkIfExistsInCARE((Map<Id, LIA_Claim__c>) existingRecords);
    fetchCAREClaims((Map<Id, LIA_Claim__c>) existingRecords);
    updateParentCaseBookings((Map<Id, LIA_Claim__c>) existingRecords);
    // TODO: We should also update EB accounts correctly. Requires fixing of the entire EB accounts fetching flow.
  }

  public override void onBeforeInsert() {
    normalizeFields();
  }

  public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    clearClaimInCareField();
    normalizeFields();
  }

  /**
   * A claim can be prorated if it is a baggage claim and has at least one
   * leg with an operating carrier which is not a part of Star Alliance. It
   * must also have at least one paid out settlement.
   *
   * Proration of a claim is splitting costs related to a baggage claim between
   * the airlines in the booking the claims is about. See Confluence for more
   * details.
   *
   * @return A map from claim id to whether that claim can be prorated.
   */
  public Map<Id, Boolean> canBeProrated() {
    Set<Id> parentCaseIds = new Set<Id>();
    for (Claim cl : objects) {
      Boolean isABaggageCaseWithSettlements =
        cl.category == Claim.Category.Baggage &&
        !cl.underlyingSObject.Settlements__r.isEmpty();

      if (isABaggageCaseWithSettlements) {
        parentCaseIds.add(cl.parentCaseId);
      }
    }

    Map<Id, Boolean> bookingIdsToProrationStatus = new Map<Id, Boolean>();
    List<Booking__c> bookingsForInstanceClaims = new List<Booking__c>();

    if (parentCaseIds.size() > 0) {
      bookingsForInstanceClaims = BookingsSelector.newInstance()
        .selectByCaseId(parentCaseIds);

      // Claim can potentially be prorated if the booking it is about
      // has an operating carrier which is not a part of Star Alliance.
      bookingIdsToProrationStatus = Bookings.newInstance(
          bookingsForInstanceClaims
        )
        .haveNonStarAllianceOperatingCarriers();
    }

    Map<Id, Boolean> claimIdsToProrationStatus = new Map<Id, Boolean>();

    for (Claim cl : objects) {
      claimIdsToProrationStatus.put(cl.underlyingSObject.Id, false);
      if (cl.category == Claim.Category.Baggage) {
        for (Booking__c booking : bookingsForInstanceClaims) {
          if (booking.Booking_Reference__c == cl.bookingReference) {
            claimIdsToProrationStatus.put(
              cl.id,
              bookingIdsToProrationStatus.get(booking.Id)
            );
            break;
          }
        }
      }
    }

    return claimIdsToProrationStatus;
  }

  /**
   * Settles the given instance claims. The claims will be approved
   * automatically and skip control.
   *
   * Settlements must already exist for the claims for this to succeed.
   *
   * If settling fails, sets the settlements as failed and keeps the case in
   * progress.
   */
  public Claims settle(fflib_ISObjectUnitOfWork uow) {
    List<Settlement__c> settlementsForClaims = SettlementsSelector.newInstance()
      .selectByClaimId((new Map<Id, LIA_Claim__c>(instanceRecords)).keySet());

    Set<Id> caseIds = new Set<Id>();
    for (Claim cl : objects) {
      caseIds.add(cl.parentCaseId);
    }
    List<Case> casesForClaims = CasesSelector.newInstance().selectById(caseIds);

    Settlements.newInstance(settlementsForClaims)
      .validate()
      .approve(uow)
      .lock();

    return this;
  }

  public Claims createFromCompensationCardForm(CaseFormJSON2Apex formData) {
    List<LIA_Claim__c> claimsToCreate = new List<LIA_Claim__c>();

    LIA_Claim__c newClaim = new LIA_Claim__c();

    return newInstance(new List<LIA_Claim__c>{ newClaim });
  }

  private void checkIfExistsInCARE(Map<Id, LIA_Claim__c> existingRecords) {
    for (LIA_Claim__c claim : instanceRecords) {
      if (claim.Liability_PNR__c != null) {
        Boolean shouldCheckEDW =
          existingRecords.get(claim.Id).Liability_PNR__c !=
          claim.Liability_PNR__c;
        if (shouldCheckEDW) {
          EventBus.publish(
            new Fetch_CARE_Data__e(
              Claim_Id__c = claim.Id,
              Booking_Reference__c = claim.Liability_PNR__c
            )
          );
        }
      }
    }
  }

  private void checkIfExistsInCARE() {
    for (LIA_Claim__c claim : instanceRecords) {
      if (claim.Liability_PNR__c != null) {
        EventBus.publish(
          new Fetch_CARE_Data__e(
            Claim_Id__c = claim.Id,
            Booking_Reference__c = claim.Liability_PNR__c
          )
        );
      }
    }
  }

  private void clearClaimInCareField() {
    for (LIA_Claim__c claim : instanceRecords) {
      if (claim.Liability_PNR__c == null) {
        claim.Claims_Exist_In_CARE_For_PNR__c = false;
      }
    }
  }

  private void updateParentCaseBookings() {
    if (objects.size() == 1) {
      Claim cl = objects[0];
      // TODO: Fix this when we can support several bookings at once
      if (
        cl.bookingReference != null &&
        cl.recordType != Claim.RecordType.CompensationCard &&
        cl.parentCaseId != null
      ) {
        System.enqueueJob(
          new BookingService.AddBookingToCaseAsync(
            cl.parentCaseId,
            cl.bookingReference
          )
        );
      }
    }
  }

  private void updateParentCaseBookings(Map<Id, LIA_Claim__c> existingRecords) {
    if (objects.size() == 1) {
      Claim cl = objects[0];
      Claim oldRecord = new Claim(existingRecords.get(cl.id));
      // TODO: Fix this when we can support several bookings at once
      if (
        cl.bookingReference != null &&
        oldRecord.bookingReference != cl.bookingReference &&
        cl.recordType != Claim.RecordType.CompensationCard
      ) {
        BookingService.removeBookingFromCase(
          cl.parentCaseId,
          oldRecord.bookingReference
        );
        System.enqueueJob(
          new BookingService.AddBookingToCaseAsync(
            cl.parentCaseId,
            cl.bookingReference
          )
        );
      }
    }
  }

  private void normalizeFields() {
    for (LIA_Claim__c claim : instanceRecords) {
      if (!String.isBlank(claim.Liability_PNR__c)) {
        claim.Liability_PNR__c = StringUtils.removeWhitespace(
          claim.Liability_PNR__c.toUpperCase()
        );
      }
      if (!String.isBlank(claim.BIC_Swift__c)) {
        claim.BIC_Swift__c = StringUtils.removeWhitespace(
          claim.BIC_Swift__c.toUpperCase()
        );
      }
      if (!String.isBlank(claim.Bank_Account_Number__c)) {
        claim.Bank_Account_Number__c = StringUtils.removeWhitespace(
          claim.Bank_Account_Number__c.toUpperCase()
        );
      }
      if (!String.isBlank(claim.Flight_Number__c)) {
        claim.Flight_Number__c = StringUtils.removeWhitespace(
          claim.Flight_Number__c.toUpperCase()
        );
      }
    }
  }

  private void fetchCAREClaims(Map<Id, LIA_Claim__c> existingRecords) {
    if (objects.size() == 1) {
      Claim newRecord = objects[0];
      Claim oldRecord = new Claim(existingRecords.get(newRecord.id));

      Boolean hasChangedPNROrPIR =
        oldRecord.bookingReference != newRecord.bookingReference ||
        oldRecord.pir != newRecord.pir;

      if (hasChangedPNROrPIR) {
        fetchCAREClaims();
      }
    }
  }

  private void fetchCAREClaims() {
    if (objects.size() == 1) {
      System.enqueueJob(
        new ClaimService.FetchCAREClaimsFromEDWAsync(
          objects[0].bookingReference,
          objects[0].pir,
          null
        )
      );
    }
  }
}