sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether this booking has been cancelled.</description>
    <inlineHelpText>Whether this booking has been cancelled.</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</description>
    <inlineHelpText>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DayReturn</fullName>
            </value>
            <value>
                <fullName>MultiCity</fullName>
            </value>
            <value>
                <fullName>OneWay</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this passenger in this booking. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this passenger in this booking. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Special_Service_Requests__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Requests__c</fullName>
    <description>Special service codes for this segment. Separated by commas.</description>
    <inlineHelpText>Special service codes for this segment. Separated by commas.</inlineHelpText>
    <label>Special Service Requests</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/controllers/BookingJSON.cls
global class BookingJSON implements Comparable {
  @AuraEnabled
  public String bookingReference { get; set; }
  @AuraEnabled
  public Boolean isCancelled { get; set; }
  @AuraEnabled
  public String type { get; set; }

  @AuraEnabled
  public List<Flight> flights { get; set; }
  @AuraEnabled
  public List<Passenger> passengers { get; set; }

  global class Flight implements Comparable {
    @AuraEnabled
    public String arrivalAirport { get; set; }
    @AuraEnabled
    public String bookingClass { get; set; }
    @AuraEnabled
    public String departureAirport { get; set; }
    @AuraEnabled
    public String flightNumber { get; set; }
    @AuraEnabled
    public Datetime scheduledArrivalTime { get; set; }
    @AuraEnabled
    public Datetime scheduledDepartureTime { get; set; }

    public Flight(Segment__c s) {
      arrivalAirport = s.Flight__r.Arrival_Airport__c;
      bookingClass = s.Booking_Class__c;
      departureAirport = s.Flight__r.Departure_Airport__c;
      flightNumber = s.Flight__r.TEDS_Identifier__c.substringBefore('-');
      scheduledArrivalTime = s.Flight__r.Scheduled_Arrival_Time__c;
      scheduledDepartureTime = s.Flight__r.Scheduled_Departure_Time__c;
    }

    global Integer compareTo(Object other) {
      BookingJSON.Flight otherFlight = (BookingJSON.Flight) other;

      Integer toReturn = 0;
      if (scheduledDepartureTime > otherFlight.scheduledDepartureTime) {
        toReturn = 1;
      } else if (scheduledDepartureTime < otherFlight.scheduledDepartureTime) {
        toReturn = -1;
      }

      return toReturn;
    }
  }

  global class Passenger implements Comparable {
    @AuraEnabled
    public String euroBonusNumber { get; set; }
    @AuraEnabled
    public String firstName { get; set; }
    @AuraEnabled
    public String identifier { get; set; }
    @AuraEnabled
    public String lastName { get; set; }
    @AuraEnabled
    public List<String> specialServiceRequests { get; set; }

    public Passenger(Passenger__c p, List<String> SSRs) {
      euroBonusNumber = p.EuroBonus_Number__c;
      firstName = p.First_Name__c;
      identifier = p.Identifier__c;
      lastName = p.Last_Name__c;
      specialServiceRequests = SSRs;
    }

    global Integer compareTo(Object other) {
      BookingJSON.Passenger otherPassenger = (BookingJSON.Passenger) other;
      Integer thisOrder = Integer.valueOf(identifier.substringAfter('PT'));
      Integer otherOrder = Integer.valueOf(
        otherPassenger.identifier.substringAfter('PT')
      );

      Integer toReturn = 0;
      if (thisOrder > otherOrder) {
        toReturn = 1;
      } else if (thisOrder < otherOrder) {
        toReturn = -1;
      }

      return toReturn;
    }
  }

  public BookingJSON(Booking__c booking) {
    bookingReference = booking.Booking_Reference__c;
    isCancelled = booking.Is_Cancelled__c;
    type = booking.Type__c;
    List<BookingJSON.Flight> tempFlights = new List<BookingJSON.Flight>();
    List<BookingJSON.Passenger> tempPassengers = new List<BookingJSON.Passenger>();

    Map<String, List<String>> specialServiceRequests = new Map<String, List<String>>();

    String firstPassengerIdHandled;

    // Constructing the flights of this booking from segments.
    // Each passenger has the same flights, so we'll collect flights from only one.
    for (Segment__c s : booking.Segments__r) {
      String segmentId = s.Identifier__c.substringBetween('ST', 'PT');
      String passengerId = s.Identifier__c.substringAfter('PT');

      List<String> existingSSRs = specialServiceRequests.get(passengerId);
      if (existingSSRs == null) {
        specialServiceRequests.put(
          passengerId,
          new List<String>{ s.Special_Service_Requests__c }
        );
      } else {
        existingSSRs.add(s.Special_Service_Requests__c);
        specialServiceRequests.put(passengerId, existingSSRs);
      }

      if (firstPassengerIdHandled == null) {
        firstPassengerIdHandled = passengerId;
        tempFlights.add(new BookingJSON.Flight(s));
      } else if (firstPassengerIdHandled == passengerId) {
        tempFlights.add(new BookingJSON.Flight(s));
      }
    }

    for (Passenger__c p : booking.Passengers__r) {
      tempPassengers.add(
        new BookingJSON.Passenger(
          p,
          specialServiceRequests.get(p.Identifier__c.substringAfter('PT'))
        )
      );
    }

    tempFlights.sort();
    tempPassengers.sort();

    flights = tempFlights;
    passengers = tempPassengers;
  }

  global Integer compareTo(Object other) {
    BookingJSON otherBooking = (BookingJSON) other;

    Integer toReturn = 0;
    if (
      flights[0].scheduledDepartureTime >
      otherBooking.flights[0].scheduledDepartureTime
    ) {
      toReturn = 1;
    } else if (
      flights[0].scheduledDepartureTime <
      otherBooking.flights[0].scheduledDepartureTime
    ) {
      toReturn = -1;
    }

    return toReturn;
  }
}