sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team of the first case owner (that is a user)</description>
    <inlineHelpText>The team of the first case owner (that is a user)</inlineHelpText>
    <label>Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/CaseToBooking__c/CaseToBooking__c.object-meta.xml
<CustomObject>
    <label>CaseToBooking</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CaseToBooking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CasesToBookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CaseToBooking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/CaseToBooking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/Flight_Delay_Certificate_Request__c.object-meta.xml
<CustomObject>
    <description>Object to store information about a request. Used to generate the actual Flight Delay Certificate as a PDF</description>
    <label>Flight Delay Certificate Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Flight Delay Certificate Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Delay Certificate Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flight Delay Certificate Requests</relationshipLabel>
    <relationshipName>Flight_Delay_Certificate_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/FlightDelayCertificateRequests_Test.cls
@IsTest
private class FlightDelayCertificateRequests_Test {
  @IsTest
  public static void updatingBookingReferenceShouldUpdateBookingOnCase() {
    String newBookingReference = 'TEST21';
    Case c = new Case(
      Department__c = 'Customer Claim',
      Team__c = 'Flight Delay Certificate',
      RecordTypeId = Cases.getRecordTypeId(Cases.RecordType.CustomerClaim)
    );
    insert c;

    Flight_Delay_Certificate_Request__c fdcr = new Flight_Delay_Certificate_Request__c(
      Booking_Reference__c = '123457',
      Case__c = c.Id,
      Contact_First_Name__c = 'Test',
      Contact_Last_Name__c = 'Testsson'
    );
    insert fdcr;

    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    fdcr.Booking_Reference__c = newBookingReference;
    update fdcr;
    Test.stopTest();
    List<CaseToBooking__c> ctb = CaseToBookingsSelector.newInstance()
      .selectByCaseId(new Set<Id>{ c.Id });
    List<Booking__c> bookings = BookingsSelector.newInstance()
      .selectByBookingReference(newBookingReference);
    System.assert(
      ctb.size() > 0,
      'There should have been a case to booking created for this case'
    );
    System.assertEquals(
      bookings[0].Id,
      ctb[0].Booking__c,
      'Booking should be linked to the case related to the Flight Delay Certificate Request'
    );
  }
}