sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Created_at_Travel_Office_Id__c.field-meta.xml
<CustomField>
    <fullName>Created_at_Travel_Office_Id__c</fullName>
    <description>Office Id where this booking was created. Based on audit.created.officeId TEDS field.</description>
    <inlineHelpText>Office Id where this booking was created.</inlineHelpText>
    <label>Created at Travel Office Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether this booking has been cancelled.</description>
    <inlineHelpText>Whether this booking has been cancelled.</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</description>
    <inlineHelpText>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DayReturn</fullName>
            </value>
            <value>
                <fullName>MultiCity</fullName>
            </value>
            <value>
                <fullName>OneWay</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time_Local__c</fullName>
    <label>Scheduled Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time_Local__c</fullName>
    <label>Scheduled Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Passenger__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this passenger in this booking. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this passenger in this booking. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Baggage_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Baggage_Quantity__c</fullName>
    <label>Baggage Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Check_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Status__c</fullName>
    <label>Check In Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>NotAccepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>StandBy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Fare Basis</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Is_Boarded__c.field-meta.xml
<CustomField>
    <fullName>Is_Boarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Boarded</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Segment_Status__c.field-meta.xml
<CustomField>
    <fullName>Segment_Status__c</fullName>
    <description>Status of this segment in the booking. Should be the same for all passengers for a given segment.</description>
    <inlineHelpText>Status of this segment in the booking. Should be the same for all passengers for a given segment.</inlineHelpText>
    <label>Segment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>CallToConfirm</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>SpaceAvailable</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Segment_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Segment_Status_Code__c</fullName>
    <description>Two letter code describing the segment status.</description>
    <inlineHelpText>Two letter code describing the segment status.</inlineHelpText>
    <label>Segment Status Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Service_Class__c.field-meta.xml
<CustomField>
    <fullName>Service_Class__c</fullName>
    <label>Service Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Special_Service_Requests__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Requests__c</fullName>
    <description>Special service codes for this segment. Separated by commas.</description>
    <inlineHelpText>Special service codes for this segment. Separated by commas.</inlineHelpText>
    <label>Special Service Requests</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <label>Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/bookings/Bookings.cls
public without sharing class Bookings extends ApplicationDomain {
  public Bookings(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<Booking__c>) Records;

    List<Booking> bookingObjects = new List<Booking>();
    for (Booking__c b : this.instanceRecords) {
      bookingObjects.add(new Booking(b));
    }

    this.objects = bookingObjects;
  }

  public List<Booking__c> instanceRecords;
  public List<Booking> objects;

  // fullRecords exist only when an instance has been created from TEDS
  // response data.
  public List<FullBookingData> fullRecords;
  // edwBookings exist only when an instance has been created from EDW
  // response data.
  public List<EDWBooking> edwBookings;

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Bookings(records);
    }
  }

  public static Bookings newInstance(List<Booking__c> sObjectList) {
    return (Bookings) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  public static Bookings createFromTEDSData(
    List<IRR_MOD_TedsBooking> bookingData
  ) {
    List<FullBookingData> toReturn = new List<FullBookingData>();
    List<Booking__c> allBookings = new List<Booking__c>();

    for (IRR_MOD_TedsBooking booking : bookingData) {
      Booking__c bookingToCreate = new Booking__c(
        Booking_Reference__c = booking.reference,
        Created_at_Travel_Office_Id__c = booking?.audit?.created?.officeId ==
          null
          ? ''
          : booking.audit.created.officeId,
        Name = booking.id,
        TEDS_Identifier__c = booking.id,
        Type__c = booking.type,
        Is_Cancelled__c = booking.isCancelled
      );
      allBookings.add(bookingToCreate);

      Map<String, Flight__c> flightsProcessed = new Map<String, Flight__c>();
      Map<String, List<Segment__c>> segmentsToCreate = new Map<String, List<Segment__c>>();

      // Create passengers
      List<Passenger__c> passengersToCreate = new List<Passenger__c>();
      for (IRR_MOD_TedsBooking.Passenger p : booking.passengers) {
        Passenger__c newPassenger = new Passenger__c(
          First_Name__c = p.firstName,
          Identifier__c = p.id,
          Last_Name__c = p.lastName
        );

        if (p.frequentTraveler.euroBonus.size() > 0) {
          newPassenger.EuroBonus_Number__c = p.frequentTraveler.euroBonus[0]
            .number_x;
        }

        if (p.contact.phone.size() > 0) {
          newPassenger.Phone__c = p.contact.phone[0].number_x;
        }

        if (
          p.contact.email.size() > 0 &&
          StringUtils.isEmailAddress(p.contact.email[0].address)
        ) {
          newPassenger.Email__c = p.contact.email[0].address;
        }

        passengersToCreate.add(newPassenger);
      }

      for (IRR_MOD_TedsBooking.Trip trip : booking.trips) {
        for (IRR_MOD_TedsBooking.SegmentTrip segmentTrip : trip.segments) {
          String flightId = segmentTrip.flight.id.trim().toUpperCase();

          // Create flights
          Datetime arrivalDate = Datetime.valueOf(
            segmentTrip.flight.arrival.scheduledTime.utc.replace('T', ' ')
              .replace('Z', '')
          );
          Datetime departureDate = Datetime.valueOf(
            segmentTrip.flight.departure.scheduledTime.utc.replace('T', ' ')
              .replace('Z', '')
          );
          String scheduledArrivalDateLocal = segmentTrip.flight.arrival.scheduledTime
            ?.local
            ?.replace('Z', '');

          String scheduledDepartureDateLocal = segmentTrip.flight.departure.scheduledTime
            ?.local
            ?.replace('Z', '');

          Flight__c newFlight = new Flight__c(
            Name = flightId,
            Arrival_Airport__c = segmentTrip.flight.arrival.station,
            Departure_Airport__c = segmentTrip.flight.departure.station,
            Operating_Carrier__c = segmentTrip.flight.operatingCarrier,
            Scheduled_Arrival_Time__c = arrivalDate,
            Scheduled_Arrival_Time_Local__c = scheduledArrivalDateLocal,
            Scheduled_Departure_Time__c = departureDate,
            Scheduled_Departure_Time_Local__c = scheduledDepartureDateLocal,
            TEDS_Identifier__c = flightId
          );

          flightsProcessed.put(flightId, newFlight);

          // Create segments
          // Create one segment per passenger per flight in the booking.
          for (Passenger__c p : passengersToCreate) {
            IRR_MOD_TedsBooking.Passenger passengerData;
            IRR_MOD_TedsBooking.Segment segmentPassenger;
            String ssrs = '';

            for (IRR_MOD_TedsBooking.Passenger pData : booking.passengers) {
              if (pData != null && pData.id == p.Identifier__c) {
                passengerData = pData;
                break;
              }
            }
            for (IRR_MOD_TedsBooking.Segment pSeg : passengerData.segments) {
              if (pSeg.segmentId == segmentTrip.id) {
                segmentPassenger = pSeg;
                break;
              }
            }

            for (
              IRR_MOD_TedsBooking.SpecialServiceRequests ssr : passengerData.specialServiceRequests
            ) {
              for (String segId : ssr.segmentIds) {
                if (segId == segmentTrip.id) {
                  ssrs += ssrs.length() > 0 ? ',' + ssr.code : ssr.code;
                  break;
                }
              }
            }

            Integer baggage = (segmentPassenger.baggage != null) &&
              (segmentPassenger.baggage.quantity != null)
              ? segmentPassenger.baggage.quantity.allowed +
                segmentPassenger.baggage.quantity.extra
              : 0;

            Segment__c newSegment = new Segment__c(
              Baggage_Quantity__c = baggage,
              Booking_Class__c = segmentTrip.bookingClass,
              Check_In_Status__c = segmentPassenger.checkin == null
                ? 'Unknown'
                : segmentPassenger.checkin.status,
              Fare_Basis__c = segmentPassenger.fare == null
                ? ''
                : segmentPassenger.fare.basis,
              Identifier__c = segmentTrip.id + p.Identifier__c,
              Is_Boarded__c = segmentPassenger.isBoarded,
              Name = segmentTrip.flight.id,
              Seat__c = segmentPassenger.seat,
              Segment_Status__c = segmentTrip.status,
              Segment_Status_Code__c = segmentTrip.statusCode,
              Service_Class__c = segmentTrip.serviceClass,
              Special_Service_Requests__c = ssrs,
              Ticket_Number__c = segmentPassenger.ticket == null
                ? ''
                : segmentPassenger.ticket.number_x,
              Ticket_Type__c = segmentPassenger.ticket == null
                ? ''
                : segmentPassenger.ticket.type,
              Trip_Type__c = trip.type
            );

            if (segmentsToCreate.get(flightId) == null) {
              segmentsToCreate.put(flightId, new List<Segment__c>());
            }
            segmentsToCreate.get(flightId).add(newSegment);
          }
        }
      }

      List<Flight__c> flightsToCreate = flightsProcessed.values();

      toReturn.add(
        new FullBookingData(
          bookingToCreate,
          flightsToCreate,
          passengersToCreate,
          segmentsToCreate
        )
      );
    }

    Bookings newBookingObject = Bookings.newInstance(allBookings);
    newBookingObject.fullRecords = toReturn;

    return newBookingObject;
  }

  public static Bookings createFromEDWData(
    List<FetchEDWDataResponse.Reservation> reservations
  ) {
    List<EDWBooking> edwBookings = new List<EDWBooking>();
    List<Booking__c> createdBookings = new List<Booking__c>();
    for (FetchEDWDataResponse.Reservation reservation : reservations) {
      String bookingIdentifier = String.format(
        '{0}-{1}',
        new List<Object>{
          reservation.reservationNumber,
          Datetime.newInstance(reservation.createdDate).format('yyyyMMdd')
        }
      );
      //create booking
      Booking b = new Booking(new Booking__c(Name = bookingIdentifier));
      b.bookingReference = reservation.reservationNumber;
      b.tedsIdentifier = bookingIdentifier;
      b.updateSObjectFields();
      //create flights
      Flights createdFlights = Flights.createFromEDWData(
        reservation.irregularityList.irregularity
      );
      //create passengers
      Passengers createdPassengers = Passengers.createFromEDWData(
        reservation.passengerList.passenger
      );
      Segments createdSegments = Segments.createFromEDWData(
        reservation.segmentList.segment,
        createdPassengers.instanceRecords
      );
      createdBookings.add(b.underlyingSObject);
      edwBookings.add(
        new EDWBooking(b, createdFlights, createdSegments, createdPassengers)
      );
    }
    Bookings bookingsInstance = Bookings.newInstance(createdBookings);
    bookingsInstance.edwBookings = edwBookings;
    bookingsInstance.upsertEDWDataToDB();
    return bookingsInstance;
  }

  public Bookings upsertEDWDataToDB() {
    for (EDWBooking edwb : edwBookings) {
      upsert edwb.booking.underlyingSObject TEDS_Identifier__c;
      edwb.flights.upsertToDB();
      for (Passenger__c p : edwb.passengers.instanceRecords) {
        p.Booking__c = edwb.booking.underlyingSObject.Id;
      }
      List<Passenger__c> existingPassengers = PassengersSelector.newInstance()
        .selectByBookingId(new Set<Id>{ edwb.booking.underlyingSObject.Id });
      List<Segment__c> existingSegments = SegmentsSelector.newInstance()
        .selectByBookingId(new Set<Id>{ edwb.booking.underlyingSObject.Id });
      List<SObject> toDelete = new List<SObject>();
      if (existingPassengers.size() > 0) {
        toDelete.addAll(existingPassengers);
      }
      if (existingSegments.size() > 0) {
        toDelete.addAll(existingSegments);
      }
      delete toDelete;
      insert edwb.passengers.instanceRecords;
      edwb.segments.addBookingReference(edwb.booking.underlyingSObject.Id)
        .addFlightReferences(edwb.flights.instanceRecords)
        .upsertToDB(edwb.passengers.instanceRecords);
    }
    return this;
  }

  public class EDWBooking {
    public Booking booking { get; private set; }
    public Segments segments { get; private set; }
    public Flights flights { get; private set; }
    public Passengers passengers { get; private set; }
    public EDWBooking(Booking b, Flights f, Segments s, Passengers p) {
      this.booking = b;
      this.segments = s;
      this.flights = f;
      this.passengers = p;
    }
  }

  /**
   * Inserts all booking related objects to the DB and constructs the lookups
   * between them.
   *
   * Because upserts by external id are not supported by fflib, this method has
   * to have its own DML statements.
   */
  public Bookings upsertToDB() {
    List<Booking__c> bookingsToUpsert = new List<Booking__c>();
    Map<String, Flight__c> uniqueFlightsToUpsert = new Map<String, Flight__c>();

    Set<String> bookingTedsIds = new Set<String>();
    for (FullBookingData b : fullRecords) {
      bookingTedsIds.add(b.booking.TEDS_Identifier__c);
      bookingsToUpsert.add(b.booking);
      for (Flight__c f : b.flights) {
        if (uniqueFlightsToUpsert.get(f.TEDS_Identifier__c) == null) {
          uniqueFlightsToUpsert.put(f.TEDS_Identifier__c, f);
        }
      }
    }

    List<Booking__c> bookingsFromDB = BookingsSelector.newInstance()
      .selectByTEDSIdFull(bookingTedsIds);

    if (bookingsFromDB.size() > 0) {
      List<Passenger__c> passengersToDelete = new List<Passenger__c>();
      List<Segment__c> segmentsToDelete = new List<Segment__c>();
      for (Booking__c existingBooking : bookingsFromDB) {
        for (Passenger__c existingPassenger : existingBooking.Passengers__r) {
          passengersToDelete.add(existingPassenger);
        }
        for (Segment__c existingSegment : existingBooking.Segments__r) {
          segmentsToDelete.add(existingSegment);
        }
      }

      List<SObject> toDelete = new List<SObject>();
      toDelete.addAll(passengersToDelete);
      toDelete.addAll(segmentsToDelete);

      try {
        delete toDelete;
      } catch (DMLException e) {
        if (e.getDmlType(0) == StatusCode.ENTITY_IS_DELETED) {
          // A parallel thread may have deleted the entities. Let's just ignore.
        } else {
          throw e;
        }
      }
    }

    // Upsert bookings
    // The upsert operation seems to fail due to a race condition between two threads
    // trying to upsert the records simultaneously. One thread succeeds and the other
    // fails with a duplicate value exception.
    try {
      upsert bookingsToUpsert TEDS_Identifier__c;
    } catch (DMLException e) {
      if (e.getDmlType(0) == StatusCode.DUPLICATE_VALUE) {
        upsert bookingsToUpsert TEDS_Identifier__c;
      }
    }

    // Upsert flights
    (new Flights(uniqueFlightsToUpsert.values())).upsertToDB();

    List<SObject> passengersToInsert = new List<SObject>();
    List<SObject> segmentsToInsert = new List<SObject>();

    for (FullBookingData b : fullRecords) {
      for (Passenger__c p : b.passengers) {
        p.Booking__c = b.booking.Id;
        passengersToInsert.add(p);
      }
      for (Flight__c f : b.flights) {
        for (Segment__c s : b.segments.get(f.TEDS_Identifier__c)) {
          s.Booking__c = b.booking.Id;
          s.Flight__c = f.Id;
          segmentsToInsert.add(s);
        }
      }
    }

    List<SObject> toInsert = new List<SObject>();
    toInsert.addAll(passengersToInsert);
    toInsert.addAll(segmentsToInsert);

    insert toInsert;

    return this;
  }

  /**
   * Loads Passenger, Flight, Segment data for instance of domain that was not
   * created as part of retrieving data from TEDS.
   * Stores the data in the same FullBookingData format as if domain instance was
   * created from call to TEDS
   *
   * TODO: Move me to the service class, or somewhere.
   */
  public Bookings reloadFullBookingData() {
    Set<Id> bookingIds = new Map<Id, Booking__c>(instanceRecords).keySet();
    Map<Id, Flight__c> idsToFlights = new Map<Id, Flight__c>(
      FlightsSelector.newInstance().selectByBookingIds(bookingIds)
    );
    List<Passenger__c> allPassengers = PassengersSelector.newInstance()
      .selectByBookingId(bookingIds);
    List<Segment__c> allSegments = SegmentsSelector.newInstance()
      .selectByBookingId(bookingIds);

    Map<String, List<Segment__c>> flightIdToSegments = new Map<String, List<Segment__c>>();
    Map<Id, List<Flight__c>> bookingIdToFlights = new Map<Id, List<Flight__c>>();

    //Sort Segments for TEDS Flight Id
    //Sort Flights by Booking
    for (Segment__c segment : allSegments) {
      Flight__c flightForSegment = idsToFlights.get(segment.Flight__c);
      if (bookingIdToFlights.get(segment.Booking__c) == null) {
        bookingIdToFlights.put(segment.Booking__c, new List<Flight__c>());
      }
      if (flightForSegment != null) {
        bookingIdToFlights.get(segment.Booking__c).add(flightForSegment);
      }

      if (flightIdToSegments.get(flightForSegment.TEDS_Identifier__c) == null) {
        flightIdToSegments.put(
          flightForSegment.TEDS_Identifier__c,
          new List<Segment__c>()
        );
      }
      flightIdToSegments.get(flightForSegment.TEDS_Identifier__c).add(segment);
    }
    Map<Id, List<Passenger__c>> bookingIdToPassengers = new Map<Id, List<Passenger__c>>();
    //Sort passenger by booking Id
    for (Passenger__c passenger : allPassengers) {
      if (bookingIdToPassengers.get(passenger.Booking__c) == null) {
        bookingIdToPassengers.put(
          passenger.Booking__c,
          new List<Passenger__c>()
        );
      }
      bookingIdToPassengers.get(passenger.Booking__c).add(passenger);
    }

    if (fullRecords == null) {
      fullRecords = new List<FullBookingData>();
    }
    for (Booking__c booking : instanceRecords) {
      FullBookingData fbd = new FullBookingData(
        booking,
        bookingIdToFlights.get(booking.Id),
        bookingIdToPassengers.get(booking.Id),
        flightIdToSegments
      );
      fullRecords.add(fbd);
    }
    return this;
  }

  public class FullBookingData {
    public Booking__c booking { get; set; }
    public List<Flight__c> flights { get; set; }
    public List<Passenger__c> passengers { get; set; }
    public Map<String, List<Segment__c>> segments { get; set; } // TEDS FlightId => List of segments

    public FullBookingData(
      Booking__c booking,
      List<Flight__c> flights,
      List<Passenger__c> passengers,
      Map<String, List<Segment__c>> segments // Flight id to segment
    ) {
      this.booking = booking;
      this.flights = flights;
      this.passengers = passengers;
      this.segments = segments;
    }
  }
}