sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/domain/Bookings.cls
public without sharing class Bookings extends fflib_SObjectDomain {
  public Bookings(List<SObject> records) {
    super(records);
    Configuration.disableTriggerCRUDSecurity();
    this.instanceRecords = (List<Booking__c>) Records;
  }

  private List<Booking__c> instanceRecords;

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Bookings(records);
    }
  }

  public static Bookings newInstance(List<Booking__c> sObjectList) {
    return (Bookings) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  /**
   * Whether the bookings have a non Star Alliance operating carrier for at
   * least one leg in the booking.
   *
   * @return A map from booking id to whether that booking has non Star
   * Alliance operating carriers as a part of the journey.
   */
  public Map<Id, Boolean> haveNonStarAllianceOperatingCarriers() {
    Set<Id> bookingIds = (new Map<Id, Booking__c>(instanceRecords)).keySet();

    Map<Id, Boolean> flightIdToOperatedByStarAlliance = Flights.newInstance(
        FlightsSelector.newInstance().selectByBookingIds(bookingIds)
      )
      .operatedByStarAlliance();

    Map<Id, Boolean> toReturn = new Map<Id, Boolean>();
    for (Booking__c booking : instanceRecords) {
      Boolean hasNonStarAllianceOperators = false;
      for (Segment__c segment : booking.Segments__r) {
        Boolean flightOperatedByStarAlliance = flightIdToOperatedByStarAlliance.get(
          segment.Flight__c
        );
        if (!flightOperatedByStarAlliance) {
          hasNonStarAllianceOperators = true;
          break;
        }
      }
      toReturn.put(booking.Id, hasNonStarAllianceOperators);
    }

    return toReturn;
  }
}