sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Status__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Arrival Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/Flight_Delay_Certificate_Request__c.object-meta.xml
<CustomObject>
    <description>Object to store information about a request. Used to generate the actual Flight Delay Certificate as a PDF</description>
    <label>Flight Delay Certificate Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Flight Delay Certificate Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Delay Certificate Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flight Delay Certificate Requests</relationshipLabel>
    <relationshipName>Flight_Delay_Certificate_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Full_Name__c</fullName>
    <formula>Contact_First_Name__c  &amp; &apos; &apos;  &amp;  Contact_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Full Name</label>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/tests/integration/FlightDelayCertificates_IntegrationTest.cls
@IsTest
public with sharing class FlightDelayCertificates_IntegrationTest {
  @IsTest
  public static void incomingRequestShouldCreateCaseAndQueueableJob() {
    CaseFormJSONV2 requestBody = CaseFormJSONV2.parse(
      '{ ' +
      '  "formData\": {' +
      '    "type": "delay-certificate",' +
      '    "contact": {' +
      '      "firstName": "Test",' +
      '      "lastName": "Testsson",' +
      '      "email": "test@example.com"' +
      '    },' +
      '    "claim": {' +
      '      "bookingReference": "DELAY1",' +
      '      "departureDate": "2022-03-02",' +
      '      "flightNumber": "SK0903"' +
      '    }' +
      '  },' +
      '  "metaData": {' +
      '    "market": "en-us"' +
      '  }' +
      '}'
    );

    // Create email templates to use for testing
    // Handling the requests requires certain templates to be present
    // and we ideally do not want these to be stored in version control
    // Runs as thisUser to avoid mixed DML Operation errors
    User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    System.runAs(thisUser) {
      BrandTemplate bt = [
        SELECT Id
        FROM BrandTemplate
        WHERE DeveloperName = 'SAS_Logo'
      ];

      EmailTemplate et1 = new EmailTemplate(
        Subject = 'Test',
        HtmlValue = '<html>test</html>',
        Body = 'test',
        Name = 'bookingExists',
        DeveloperName = 'test1',
        BrandTemplateId = bt.Id,
        TemplateStyle = 'freeForm',
        TemplateType = 'html',
        FolderId = UserInfo.getUserId()
      );
      EmailTemplate et2 = new EmailTemplate(
        Subject = 'Test',
        HtmlValue = '<html>test</html>',
        Body = 'test',
        Name = 'bookingDoesNotExist',
        DeveloperName = 'test2',
        BrandTemplateId = bt.Id,
        TemplateStyle = 'freeForm',
        TemplateType = 'html',
        FolderId = UserInfo.getUserId()
      );
      insert new List<EmailTemplate>{ et1, et2 };
    }
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    CaseFormV2.createCase(requestBody);
    Test.stopTest();
    String insertedEmailAddress = 'test@example.com';
    Case c = [
      SELECT Id, Flight_Number__c
      FROM Case
      WHERE SuppliedEmail = :insertedEmailAddress
    ];
    String statusToCheck = 'delayed';

    List<AsyncApexJob> aaj = [
      SELECT Id
      FROM AsyncApexJob
      WHERE JobType = 'Queueable'
    ];
    System.assertNotEquals(
      null,
      c,
      'Case should have been created for this request'
    );
    System.assertEquals(
      'SK0903',
      c.Flight_Number__c,
      'Case data should match form data'
    );
    System.assertNotEquals(
      0,
      aaj.size(),
      'Should have created a queueable apex job'
    );
  }

  @IsTest
  public static void createdAttachmentShouldHaveCorrectFileNameAndContentType() {
    Case c = new Case(Flight_Number__c = 'SK0903');
    Flight__c flight1 = new Flight__c(
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'ontime'
    );
    Flight__c flight2 = new Flight__c(
      Operating_Carrier__c = 'AY',
      TEDS_Identifier__c = 'AY1',
      Arrival_Status__c = 'ontime',
      Departure_Status__c = 'ontime'
    );
    Booking__c booking = new Booking__c(
      Booking_Reference__c = 'ABC123',
      TEDS_Identifier__c = 'ABC123'
    );
    insert new List<SObject>{ c, booking, flight1, flight2 };

    Segment__c seg1 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight1.Id
    );
    Segment__c seg2 = new Segment__c(
      Booking__c = booking.Id,
      Flight__c = flight2.Id
    );

    Flight_Delay_Certificate_Request__c req = new Flight_Delay_Certificate_Request__c(
      Booking_Reference__c = 'ABC123',
      Contact_First_Name__c = 'Test',
      Contact_Last_Name__c = 'Testsson',
      Flight_Number__c = 'SK1234',
      Case__c = c.Id
    );
    insert new List<SObject>{ seg1, seg2, req };
    Booking__c bookingToTest = [
      SELECT Id, Booking_Reference__c, (SELECT Id, Flight__c FROM Segments__r)
      FROM Booking__c
      WHERE Id = :booking.Id
    ];

    FlightDelayCertificateRequests requests = FlightDelayCertificateRequests.newInstance(
      FlightDelayCertificateRequestsSelector.newInstance()
        .selectByIdFull(new Set<Id>{ req.Id })
    );
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Blob pdf = requests.generateFlightDelayCertificate(bookingToTest.Id);
    Messaging.EmailFileAttachment createdAttachment = EmailMessages.createEmailAttachmentFromBlob(
      pdf,
      requests.instanceRecords[0].Contact_Full_Name__c +
      '_' +
      requests.instanceRecords[0].Booking_Reference__c,
      'application/pdf'
    );
    Test.stopTest();
    System.assertEquals(
      'Test Testsson_ABC123',
      createdAttachment.getFilename(),
      'Filename should be [passengerName].pdf'
    );
    System.assertEquals(
      'application/pdf',
      createdAttachment.getContentType(),
      'Content-Type for the created attachment should be application/pdf'
    );
  }
}