sas-core/main/default/objects/FCS_Audit_Trail__c/FCS_Audit_Trail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to set the Date and other detais to send audit trails details to Admin</description>
    <label>FCS_Audit Trail</label>
</CustomObject>

sas-core/main/default/objects/FCS_Audit_Trail__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <label>From Date</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/classes/FCS_SendMetadataChangeNotification_Test.cls
@isTest
private class FCS_SendMetadataChangeNotification_Test {
    @TestSetup
    static void setUpData(){
        // insert custom setting for Audit trial from date
        FCS_Audit_Trail__c fcsAuditTrilCustSetting =  New  FCS_Audit_Trail__c();
        fcsAuditTrilCustSetting.Name = 'Fcs Audit trial Date';
        fcsAuditTrilCustSetting.From_Date__c = System.now().addDays(-1);
        insert fcsAuditTrilCustSetting;  
        
    }  
    static testMethod void TestAuditTrail(){
        Test.startTest();
        Database.executeBatch(new FCS_SendMetadataChangeNotification_Batch());         
        Test.stopTest();
        
    } 
}