sas-core/main/default/objects/IRR_RecipientWhitelist__mdt/IRR_RecipientWhitelist__mdt.object-meta.xml
<CustomObject>
    <description>Provides a Recipient whitelist for Email and SMS for use in Sanbox environments</description>
    <label>Recipient Whitelist</label>
    <pluralLabel>Recipient Whitelists</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_RecipientWhitelist__mdt/fields/IRR_Recipient__c.field-meta.xml
<CustomField>
    <fullName>IRR_Recipient__c</fullName>
    <label>Recipient</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/classes/IRR_SEL_RecipientWhitelistSelector_Test.cls
/**
* @author Niklas Lundkvist, Deloitte
* @date 2020
*
* @description Unit test class for the Recipient Whitelist selector class.
*/

@IsTest
private class IRR_SEL_RecipientWhitelistSelector_Test {

    @IsTest
    static void testSelectAllWhitelistedRecipients() {
        Set<String> whitelistedRecipients = IRR_SEL_RecipientWhitelistSelector.newInstance()
                .getAllWhitelistedRecipients();
        List<IRR_RecipientWhitelist__mdt> recipientWhitelists = [SELECT IRR_Recipient__c FROM IRR_RecipientWhitelist__mdt];
        for (IRR_RecipientWhitelist__mdt whitelist : recipientWhitelists) {
            System.assert(whitelistedRecipients.contains(whitelist.IRR_Recipient__c));
        }
        System.assertEquals(recipientWhitelists.size(), whitelistedRecipients.size());
    }
}