sas-core/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>Customer(s) in a customer claim</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Customer__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <inlineHelpText>It is the Liability or Customer claim to which this customer is related to</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/domain/claims/ClaimCustomer.cls
public without sharing class ClaimCustomer extends AbstractSObjectWrapper {
  public Customer__c underlyingSObject { get; private set; }

  public Id parentClaimId;
  public String firstName;
  public String lastName;

  public String fullName {
    get {
      return firstName + ' ' + lastName;
    }
  }

  public override void updateSObjectFields() {
    this.underlyingSObject.First_Name__c = this.firstName;
    this.underlyingSObject.Last_Name__c = this.lastName;
    this.underlyingSObject.Claim__c = this.parentClaimId;
  }

  @TestVisible
  private ClaimCustomer() {
    this.underlyingSObject = new Customer__c();
  }

  public ClaimCustomer(Claim parentClaim) {
    this();
    this.parentClaimId = parentClaim.id;
  }

  public ClaimCustomer(Customer__c c) {
    super(c);
    this.underlyingSObject = c;
    this.firstName = c.First_Name__c;
    this.lastName = c.Last_Name__c;
    this.parentClaimId = c.Claim__c;
  }
}