sas-core/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>Customer(s) in a customer claim</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Customer__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <inlineHelpText>It is the Liability or Customer claim to which this customer is related to</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/classes/domain/claims/Customers_Test.cls
@IsTest
private class Customers_Test {
  @IsTest
  static void customerNameShouldBeEqualToFirstLast() {
    LIA_Claim__c cl = new LIA_Claim__c();
    insert cl;

    Customer__c c = new Customer__c(
      First_Name__c = 'Test',
      Last_Name__c = 'Testsson',
      Claim__c = cl.Id
    );

    insert c;

    Customer__c customerAfterInsert = [
      SELECT Id, Name
      FROM Customer__c
      WHERE Id = :c.Id
    ];

    System.assertEquals(
      'Test Testsson',
      customerAfterInsert.Name,
      'Customer Name should set as first name followed by last name.'
    );
  }
}