sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/IRR_Icoupon_Voucher__mdt.object-meta.xml
<CustomObject>
    <label>IRR_Icoupon_Voucher</label>
    <pluralLabel>IRR_Icoupon_Vouchers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/AirportCode__c.field-meta.xml
<CustomField>
    <fullName>AirportCode__c</fullName>
    <label>Airport Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/CoupanValue__c.field-meta.xml
<CustomField>
    <fullName>CoupanValue__c</fullName>
    <label>Coupan Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>EUR</label>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/Max_Delay__c.field-meta.xml
<CustomField>
    <fullName>Max_Delay__c</fullName>
    <label>Max Delay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/Min_Delay__c.field-meta.xml
<CustomField>
    <fullName>Min_Delay__c</fullName>
    <label>Min Delay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/ReasonComment__c.field-meta.xml
<CustomField>
    <fullName>ReasonComment__c</fullName>
    <label>Reason Comment</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Icoupon_Voucher__mdt/fields/Service_Class_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Class_Code__c</fullName>
    <label>Service Class Code</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_IcouponVoucherSelector.cls
/**
* @author Gaurav Singh, Coforge
* @date 2022
*
* @description Selector class for the IRR Icoupon Voucher metadata object.
*/

public class IRR_SEL_IcouponVoucherSelector extends fflib_SObjectSelector implements IRR_SEL_IIcouponVoucherSelector  {
    
    public static IRR_SEL_IIcouponVoucherSelector newInstance() 
    {

        return (IRR_SEL_IIcouponVoucherSelector) IRR_Application.Selector.newInstance(
            IRR_Icoupon_Voucher__mdt.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {

        return new List<Schema.SObjectField> 
        { 

            IRR_Icoupon_Voucher__mdt.DeveloperName,
            IRR_Icoupon_Voucher__mdt.MasterLabel,
            IRR_Icoupon_Voucher__mdt.AirportCode__c,
            IRR_Icoupon_Voucher__mdt.CoupanValue__c,
            IRR_Icoupon_Voucher__mdt.Currency__c,
            IRR_Icoupon_Voucher__mdt.Min_Delay__c,
            IRR_Icoupon_Voucher__mdt.Max_Delay__c,
            IRR_Icoupon_Voucher__mdt.ReasonComment__c,
            IRR_Icoupon_Voucher__mdt.Service_Class_Code__c

        };

    }

    public Schema.SObjectType getSObjectType() {

        return IRR_Icoupon_Voucher__mdt.SobjectType ;
    }

    public List<IRR_Icoupon_Voucher__mdt> getIcouponVoucher(){

         return Database.query(newQueryFactory().toSOQL());
               
    }

}