sas-core/main/default/objects/IRR_ManualOverride__c/IRR_ManualOverride__c.object-meta.xml
<CustomObject>
    <label>Manual Override</label>
    <nameField>
        <displayFormat>MO-{000000}</displayFormat>
        <label>Manual Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_DepartureDate__c.field-meta.xml
<CustomField>
    <fullName>IRR_DepartureDate__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_FlightId__c.field-meta.xml
<CustomField>
    <fullName>IRR_FlightId__c</fullName>
    <inlineHelpText>Enter Flight Id in format SK1238-20200213-ARN-CPH. Flight Id cannot be combined with other filters.</inlineHelpText>
    <label>Flight Id</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>IRR_FlightNumber__c</fullName>
    <inlineHelpText>Enter Flight Number in format SK1238</inlineHelpText>
    <label>Flight Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StartBlockDate__c.field-meta.xml
<CustomField>
    <fullName>IRR_StartBlockDate__c</fullName>
    <inlineHelpText>Enter start date for block period in UTC. Automatic communication will be blocked from this date according to the filters set.</inlineHelpText>
    <label>Start Block Date (UTC)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StartBlockTime__c.field-meta.xml
<CustomField>
    <fullName>IRR_StartBlockTime__c</fullName>
    <inlineHelpText>Enter start time for block period in UTC. Automatic communication will be blocked from this time according to the filters set.</inlineHelpText>
    <label>Start Block Time (UTC)</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StationArrival__c.field-meta.xml
<CustomField>
    <fullName>IRR_StationArrival__c</fullName>
    <label>Station Arrival</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StationDeparture__c.field-meta.xml
<CustomField>
    <fullName>IRR_StationDeparture__c</fullName>
    <label>Station Departure</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StopBlockDate__c.field-meta.xml
<CustomField>
    <fullName>IRR_StopBlockDate__c</fullName>
    <inlineHelpText>Enter stop date for block period in UTC. Automatic communication will be blocked until this date according to the filters set.</inlineHelpText>
    <label>Stop Block Date (UTC)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/IRR_ManualOverride__c/fields/IRR_StopBlockTime__c.field-meta.xml
<CustomField>
    <fullName>IRR_StopBlockTime__c</fullName>
    <inlineHelpText>Enter stop time for block period in UTC. Automatic communication will be blocked until this time according to the filters set.</inlineHelpText>
    <label>Stop Block Time (UTC)</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_ManualOverridesSelector_Test.cls
/**
* @author Niklas Lundkvist, Deloitte
* @date 2020
*
* @description TODO
*/

@IsTest
private class IRR_SEL_ManualOverridesSelector_Test {

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_NoActive_FlightId() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_InActive = new IRR_ManualOverride__c(
                IRR_FlightId__c = 'SK1429-20191104-ARN-CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-2).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(-1).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_FlightId__c = 'AA1425-20191104-ARN-CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_NoMatch_Active, manualOverride_Match_InActive};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(0, manualOverrides.size(), 'No results expected');
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_FlightId() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_FlightId__c = 'SK1429-20191104-ARN-CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_FlightId__c = 'AA1425-20191104-ARN-CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_FlightNumber() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'SK1429',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'AA1425',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_DepartureDate() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_DepartureDate__c = Date.newInstance(2019, 11, 4),
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_DepartureDate__c = Date.newInstance(2019, 12, 4),
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_StationArrival() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_StationArrival__c = 'CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_StationArrival__c = 'ARN',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_StationDeparture() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_StationDeparture__c = 'ARN',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_StationDeparture__c = 'CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_Combined() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'SK1429',
                IRR_DepartureDate__c = Date.newInstance(2019, 11, 4),
                IRR_StationArrival__c = 'CPH',
                IRR_StationDeparture__c = 'ARN',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'AA1429',
                IRR_DepartureDate__c = Date.newInstance(2019, 12, 4),
                IRR_StationArrival__c = 'ARN',
                IRR_StationDeparture__c = 'CPH',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }

    @IsTest
    static void testSelectActiveManualOverridesByFlightId_Active_Overlap() {
        //Given
        Datetime now = Datetime.now();
        IRR_ManualOverride__c manualOverride_Match_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'SK1429',
                IRR_DepartureDate__c = Date.newInstance(2019, 11, 4),
                IRR_StationArrival__c = 'CPH',
                IRR_StationDeparture__c = 'ARN',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        IRR_ManualOverride__c manualOverride_NoMatch_Active = new IRR_ManualOverride__c(
                IRR_FlightNumber__c = 'SK1429',
                IRR_DepartureDate__c = Date.newInstance(2019, 12, 4),
                IRR_StationArrival__c = 'CPH',
                IRR_StationDeparture__c = 'ARN',
                IRR_StartBlockDate__c = now.dateGmt(),
                IRR_StartBlockTime__c = now.addHours(-1).timeGmt(),
                IRR_StopBlockDate__c = now.dateGmt(),
                IRR_StopBlockTime__c = now.addHours(2).timeGmt()
        );
        insert new List<IRR_ManualOverride__c>{manualOverride_Match_Active, manualOverride_NoMatch_Active};

        //When
        List<IRR_ManualOverride__c> manualOverrides = IRR_SEL_ManualOverridesSelector.newInstance()
                .selectActiveManualOverridesByFlightId('SK1429-20191104-ARN-CPH');

        //Then
        System.assertEquals(manualOverride_Match_Active.Id, manualOverrides[0].Id);
        System.assertEquals(1, manualOverrides.size());
    }
}