sas-core/main/default/objects/C_GeneralSetting__mdt/C_GeneralSetting__mdt.object-meta.xml
<CustomObject>
    <description>General purpose settings metadata where group of settins can stored for different purposes.</description>
    <label>General Setting</label>
    <pluralLabel>General Settings</pluralLabel>
</CustomObject>

sas-core/main/default/objects/C_GeneralSetting__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>The group which the setting is associated with.</description>
    <inlineHelpText>The group which the setting is associated with.</inlineHelpText>
    <label>Group</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/C_GeneralSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of the setting. If boolean this value should be true/false.</description>
    <label>Value</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/objects/SocialPost/fields/FCS_CaseCreated__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post has a case created from it</description>
    <label>Case Created</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>FCS_ClosedDate__c</fullName>
    <description>The date when the social post was marked as done</description>
    <inlineHelpText>The date when the social post was marked as done</inlineHelpText>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Done__c.field-meta.xml
<CustomField>
    <fullName>FCS_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post fulfills the criteria of being handled</description>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostHidden__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostHidden__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is hidden from its source e.g Facebook or Twitter</description>
    <inlineHelpText>Checked if the post is hidden from its source e.g Facebook or Twitter</inlineHelpText>
    <label>Hidden</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostIgnored__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostIgnored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the action taken on the post is ignore</description>
    <label>Ignored</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostLiked__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostLiked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is liked from SF e.g Facebook or Twitter</description>
    <label>Liked</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostReplied__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostReplied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is replied to from SF to  e.g Facebook or Twitter</description>
    <label>Replied</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Reopened__c.field-meta.xml
<CustomField>
    <fullName>FCS_Reopened__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marked true if the social post is reopened</description>
    <inlineHelpText>Marked true if the social post is reopened</inlineHelpText>
    <label>Reopened</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_SASPost__c.field-meta.xml
<CustomField>
    <fullName>FCS_SASPost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is posted by SAS</description>
    <label>SAS Post</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/domain/SocialPosts_Test.cls
/**
 * @author Sanna Sörberg
 * @date 2019-12-20
 * @description Test class for social post handler which includes operations performed on social posts
 */

@isTest
private class SocialPosts_Test {
  /**
Test method for generation of test data used in more than one method
*/
  @TestSetup
  static void createTestData() {
    List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(4);
    insert socialPosts;
    List<Case> newCases = FCS_TestDataFactory.createCases(1, null, null, null);
    newCases[0].Subject = 'TestCase 2';
    newCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL;
    newCases[0].Department__c = 'SoMe Support';
    newCases[0].FCS_CaseType__c = 'Baggage';
    newCases[0].FCS_Case_Reason__c = 'Allowance';
    insert newCases;
  }

  /**
    Test method to test to that status fields and checkboxes are updated when hiding/unhiding an post
     */
  @isTest
  static void testHideAndUnhidePost() {
    SocialPost sp = [SELECT Id, FCS_PostHidden__c FROM SocialPost LIMIT 1];
    sp.Status = SocialPosts.STATUS_HIDDEN;
    update sp;
    SocialPost hiddenSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_ClosedDate__c,
        FCS_Reopened__c
      FROM SocialPost
      LIMIT 1
    ];
    system.assertEquals(true, hiddenSp.FCS_PostHidden__c);
    system.assertEquals(SocialPosts.STATUS_REVIEWED, hiddenSp.ReviewedStatus);
    system.assertEquals(true, hiddenSp.FCS_Done__c);
    system.assertEquals(false, hiddenSp.FCS_PostReplied__c);
    system.assertEquals(false, hiddenSp.FCS_PostIgnored__c);
    system.assertEquals(false, hiddenSp.FCS_PostLiked__c);
    system.assertEquals(
      true,
      hiddenSp.FCS_ClosedDate__c < system.now().addSeconds(10) &&
      hiddenSp.FCS_ClosedDate__c > system.now().addSeconds(-10)
    );
    system.assertEquals(false, hiddenSp.FCS_Reopened__c);
    hiddenSp.Status = null;
    update hiddenSp;
    SocialPost unhiddenSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_ClosedDate__c,
        FCS_Reopened__c
      FROM SocialPost
      LIMIT 1
    ];
    system.assertEquals(false, unhiddenSp.FCS_PostHidden__c);
    system.assertEquals(SocialPosts.STATUS_NEEDED, unhiddenSp.ReviewedStatus);
    system.assertEquals(false, unhiddenSp.FCS_Done__c);
    system.assertEquals(false, unhiddenSp.FCS_PostReplied__c);
    system.assertEquals(false, unhiddenSp.FCS_PostIgnored__c);
    system.assertEquals(false, unhiddenSp.FCS_PostLiked__c);
    system.assertEquals(null, unhiddenSp.FCS_ClosedDate__c);
    system.assertEquals(true, unhiddenSp.FCS_Reopened__c);
  }

  /**
   Test method to test to that status fields and checkboxes are updated when ignoring a post
    */
  @isTest
  static void testIgnorePost() {
    SocialPost sp = [SELECT Id, FCS_PostIgnored__c FROM SocialPost LIMIT 1];
    sp.ReviewedStatus = SocialPosts.STATUS_IGNORE;
    update sp;
    SocialPost ignoredSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_ClosedDate__c,
        FCS_Reopened__c
      FROM SocialPost
      LIMIT 1
    ];
    system.assertEquals(false, ignoredSp.FCS_PostHidden__c);
    system.assertEquals(SocialPosts.STATUS_REVIEWED, ignoredSp.ReviewedStatus);
    system.assertEquals(true, ignoredSp.FCS_Done__c);
    system.assertEquals(false, ignoredSp.FCS_PostReplied__c);
    system.assertEquals(true, ignoredSp.FCS_PostIgnored__c);
    system.assertEquals(false, ignoredSp.FCS_PostLiked__c);
    system.assertEquals(
      true,
      ignoredSp.FCS_ClosedDate__c < system.now().addSeconds(10) &&
      ignoredSp.FCS_ClosedDate__c > system.now().addSeconds(-10)
    );
    system.assertEquals(false, ignoredSp.FCS_Reopened__c);
  }

  /**
   Test method to test to that status fields and checkboxes are updated when liking a post
    */
  @isTest
  static void testLikePost() {
    SocialPost sp = [SELECT Id FROM SocialPost LIMIT 1];
    sp.Recipient = 'Test1';
    sp.LikedBy = 'Test1';
    update sp;
    SocialPost likedSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_ClosedDate__c,
        FCS_Reopened__c
      FROM SocialPost
      LIMIT 1
    ];
    system.assertEquals(false, likedSp.FCS_PostHidden__c);
    system.assertEquals(SocialPosts.STATUS_REVIEWED, likedSp.ReviewedStatus);
    system.assertEquals(true, likedSp.FCS_Done__c);
    system.assertEquals(false, likedSp.FCS_PostReplied__c);
    system.assertEquals(false, likedSp.FCS_PostIgnored__c);
    system.assertEquals(true, likedSp.FCS_PostLiked__c);
    system.assertEquals(
      true,
      likedSp.FCS_ClosedDate__c < system.now().addSeconds(10) &&
      likedSp.FCS_ClosedDate__c > system.now().addSeconds(-10)
    );
    system.assertEquals(false, likedSp.FCS_Reopened__c);
  }

  /**
   Test method to test to that parent post is updated with correct status when replying
    */
  @isTest
  static void replyToPost() {
    SocialPost replyToSp = [SELECT Id FROM SocialPost LIMIT 1];
    List<SocialPost> spList = FCS_TestDataFactory.createSocialPosts(1);
    spList[0].ReplyToId = replyToSp.Id;
    spList[0].IsOutbound = true;
    insert spList;
    SocialPost repliedSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_ClosedDate__c
      FROM SocialPost
      WHERE Id = :replyToSp.Id
      LIMIT 1
    ];
    system.assertEquals(false, repliedSp.FCS_PostHidden__c);
    system.assertEquals(SocialPosts.STATUS_REVIEWED, repliedSp.ReviewedStatus);
    system.assertEquals(true, repliedSp.FCS_Done__c);
    system.assertEquals(true, repliedSp.FCS_PostReplied__c);
    system.assertEquals(false, repliedSp.FCS_PostIgnored__c);
    system.assertEquals(false, repliedSp.FCS_PostLiked__c);
    system.assertEquals(
      true,
      repliedSp.FCS_ClosedDate__c < system.now().addSeconds(10) &&
      repliedSp.FCS_ClosedDate__c > system.now().addSeconds(-10)
    );
  }

  /**
  Test method to test to that status fields and checkboxes are updated when deleting the parent case
   */
  @isTest
  static void testDeleteParentCase() {
    List<SocialPost> socialPosts = [SELECT Id FROM SocialPost];
    List<User> users = [SELECT Id FROM User];
    for (Integer i = 0, sz = socialPosts.size(); i < sz; i++) {
      socialPosts[i].OwnerId = users[i].Id;
    }
    List<Case> newCase = FCS_TestDataFactory.createCases(1, null, null, null);
    newCase[0].Subject = 'TestCase12';
    newCase[0].Status = 'New';
    newCase[0].SourceId = socialPosts[0].Id;
    newCase[0].Department__c = 'SoMe Support';
    newCase[0].FCS_CaseType__c = 'Baggage';
    newCase[0].FCS_Case_Reason__c = 'Allowance';
    newCase[0].RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL;
    insert newCase;
    System.AssertEquals(
      true,
      [
        SELECT Id, FCS_CaseCreated__c
        FROM SocialPost
        WHERE Id = :newCase[0].SourceId
      ][0]
      .FCS_CaseCreated__c
    );
    SocialPost sp = [
      SELECT Id, FCS_CaseCreated__c, ParentId
      FROM SocialPost
      LIMIT 1
    ];
    sp.ParentId = null;
    update sp;
    SocialPost parentDeletedSp = [
      SELECT
        Id,
        FCS_PostHidden__c,
        ReviewedStatus,
        FCS_Done__c,
        FCS_PostReplied__c,
        FCS_PostIgnored__c,
        FCS_PostLiked__c,
        FCS_CaseCreated__c,
        FCS_ClosedDate__c,
        FCS_Reopened__c
      FROM SocialPost
      LIMIT 1
    ];
    system.assertEquals(false, parentDeletedSp.FCS_PostHidden__c);
    system.assertEquals(false, parentDeletedSp.FCS_CaseCreated__c);
    system.assertEquals(false, parentDeletedSp.FCS_Done__c);
    system.assertEquals(false, parentDeletedSp.FCS_PostReplied__c);
    system.assertEquals(false, parentDeletedSp.FCS_PostIgnored__c);
    system.assertEquals(false, parentDeletedSp.FCS_PostLiked__c);
    system.assertEquals(null, parentDeletedSp.FCS_ClosedDate__c);
    system.assertEquals(true, parentDeletedSp.FCS_Reopened__c);
  }

  /**
    Test method to test to that posts posted from SAS-own site is set with the correct statuses
    */
  @isTest
  static void insertSASPost() {
    List<C_GeneralSetting__mdt> socialPages = [
      SELECT Value__c
      FROM C_GeneralSetting__mdt
      WHERE Group__c = 'Social Accounts'
    ];
    List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(1);
    socialPosts[0].MessageType = 'Post';
    //   socialPosts[0].Provider = socialAccs[0].Provider__c;
    socialPosts[0].Handle = socialPages[0].Value__c;
    insert socialPosts;
    List<SocialPost> updatedSocialPosts = [
      SELECT Id, IsOutbound, FCS_SASPost__c, ReviewedStatus
      FROM SocialPost
      WHERE Handle = :socialPosts[0].Handle
    ];
    system.assertEquals(true, updatedSocialPosts[0].IsOutbound);
    system.assertEquals(true, updatedSocialPosts[0].FCS_SASPost__c);
    system.assertEquals(null, updatedSocialPosts[0].ReviewedStatus);
  }

  /**
   Test method to test to that post inserted never gets attached to a case
   */
  @isTest
  static void insertCustomerPost() {
    List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(1);
    socialPosts[0].MessageType = 'Post';
    socialPosts[0].Headline = 'TestPost1';
    socialPosts[0].ParentId = [SELECT Id FROM Case LIMIT 1].Id;
    insert socialPosts;
    List<SocialPost> updatedSocialPosts = [
      SELECT Id, ParentId, ReviewedStatus
      FROM SocialPost
      WHERE Headline = 'TestPost1'
    ];
    system.assertEquals(null, updatedSocialPosts[0].ParentId);
  }
}