sas-core/main/default/objects/Case/fields/CaseReason__c.field-meta.xml
<CustomField>
    <fullName>CaseReason__c</fullName>
    <complianceGroup>PIIExtract</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseReason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage delivery</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Booking confirmation</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>Campaign booking</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Card replacement</fullName>
            </value>
            <value>
                <fullName>Car rental</fullName>
            </value>
            <value>
                <fullName>CBBG</fullName>
            </value>
            <value>
                <fullName>Change profile</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Chat lost</fullName>
            </value>
            <value>
                <fullName>Check-in</fullName>
            </value>
            <value>
                <fullName>Co2</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>Connection time</fullName>
            </value>
            <value>
                <fullName>Content and Dangerous goods</fullName>
            </value>
            <value>
                <fullName>Control status</fullName>
            </value>
            <value>
                <fullName>Create case</fullName>
            </value>
            <value>
                <fullName>Customer hangs up</fullName>
            </value>
            <value>
                <fullName>Damaged baggage status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/TestDataFactory_Test.cls
@isTest
private class TestDataFactory_Test {
   /* 
@isTest	
	static void insertCaseRecords () {
       List<Case> newCase = TestDataFactory.createDefaultCases(1, null, null, null, null);
        System.assertEquals('c', newCase[0].subject); 
		System.assertEquals (null,newCase[0].accountId);
		System.assertEquals (null,newCase[0].contactId);
		System.assertEquals ('baggage', newCase[0].reason);
		}
@isTest		
	static void insertAccountCase(){
		accountId accId = new accountId (); 
		insert accId; 
		newCase[0].accountId = [select ID FROM Account Limit 1][0].id; 
		List<Case> newCase = TestDataFactory.createDefaultCases(1, newCase[0].accountId, null, null, null);
		System.assertEquals('c', newCase[0].subject); 
		System.assertEquals (accountId, newCase[0].accountId);
		System.assertEquals (null,newCase[0].contactId);
		System.assertEquals ('baggage', newCase[0].reason);
		}
@isTest		
	static void insertContactCase(){
		contactId conId = new contactId (); 
		insert conId; 
		newCase[0].conId = [select ID FROM Contact Limit 1][0].id; 
		List<Case> newCase = TestDataFactory.createDefaultCases(1, null, newCase[0].contactId, null, null);
		System.assertEquals('c', newCase[0].subject); 
		System.assertEquals (null, newCase[0].accountId);
		System.assertEquals (conId, newCase[0].contactId);
		System.assertEquals ('baggage', newCase[0].reason);
		}
@isTest
	static void insertReasonCase(){
		Case c1 = new Case (); 
		insert c1;
        newCase[0].CaseReason__c = 'TestReason 1';
        newCase[0].CaseSubReason__c = 'TestSubReason 1';
		
		List<Case> newCase = TestDataFactory.createDefaultCases(1, null, null, null, newCase[0].CaseReason__c);
		System.assertEquals('c', newCase[0].subject); 
		System.assertEquals (null,newCase[0].accountId);
		System.assertEquals (null,newCase[0].contactId);
		System.assertEquals ('TestReason 1', newCase[0].CaseReason__c);
		}	
	
@isTest 
	static void createSocialPosts 	
      */     
    }
	