sas-core/main/default/objects/Case/fields/CaseReason__c.field-meta.xml
<CustomField>
    <fullName>CaseReason__c</fullName>
    <complianceGroup>PIIExtract</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseReason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage delivery</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Booking confirmation</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>Campaign booking</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Card replacement</fullName>
            </value>
            <value>
                <fullName>Car rental</fullName>
            </value>
            <value>
                <fullName>CBBG</fullName>
            </value>
            <value>
                <fullName>Change profile</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Chat lost</fullName>
            </value>
            <value>
                <fullName>Check-in</fullName>
            </value>
            <value>
                <fullName>Co2</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>Connection time</fullName>
            </value>
            <value>
                <fullName>Content and Dangerous goods</fullName>
            </value>
            <value>
                <fullName>Control status</fullName>
            </value>
            <value>
                <fullName>Create case</fullName>
            </value>
            <value>
                <fullName>Customer hangs up</fullName>
            </value>
            <value>
                <fullName>Damaged baggage status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/CaseTags__c.field-meta.xml
<CustomField>
    <fullName>CaseTags__c</fullName>
    <label>Case Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/CaseTag__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <description>The id of the case that the tag belong to</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Tags</relationshipLabel>
    <relationshipName>Case_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/CaseTag__c/fields/CaseTag__c.field-meta.xml
<CustomField>
    <fullName>CaseTag__c</fullName>
    <description>The tag for why the customer was contacting customer support</description>
    <label>Case Tag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/CaseTag__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines the weather the tag is Main, Sub or Additional</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Sub</fullName>
            </value>
            <value>
                <fullName>Additional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/CaseHandler_Test.cls
/**
* @author Sanna Sörberg
* @date 2019-12-01
* @description Test class for case handler case which includes operations performed on a case
*/

@isTest
private class CaseHandler_Test {
    private static final String MAIN_TAG = 'Main';
    private static final String SUB_MAIN_TAG = 'Sub';
    private static final String ADDITIONAL_TAG = 'Additional';


    @TestSetup static void createTestData(){
        List<SocialPost> socialPosts = TestDataFactory.createSocialPosts(2);
        insert socialPosts;
    }

    /**
    Test method for generation of case tag records from case
   */

    @isTest
    static void manageCaseTagRecords() {
        // Test if case tag records is created on insert of new Case
        List<Case> newCases = TestDataFactory.createCases(1, null, null, null, null);
        newCases[0].CaseReason__c = 'TestReason 1';
        newCases[0].CaseSubReason__c = 'TestSubReason 1';
        newCases[0].CaseTags__c = 'TestTag1;TestTag2';
        newCases[0].Subject = 'TestCase';
        insert newCases;
        Case c = [SELECT Id FROM CASE WHERE Subject = 'TestCase'];
        System.AssertEquals('TestReason 1', [SELECT Id, CaseTag__c From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:MAIN_TAG Limit 1][0].CaseTag__c);
        System.AssertEquals('TestSubReason 1', [SELECT Id, CaseTag__c From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:SUB_MAIN_TAG Limit 1][0].CaseTag__c);
        System.AssertEquals(2, [SELECT Id From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:ADDITIONAL_TAG].Size());
        System.AssertEquals(4, [SELECT Id From CaseTag__c WHERE CaseId__c =: c.Id].size());

        //Test if case tag records is updated when a case is updated
        newCases[0].CaseReason__c ='UpdatedTestReason 1';
        newCases[0].CaseTags__c ='TestTag2';
        update newCases;
        System.AssertEquals('UpdatedTestReason 1', [SELECT Id, CaseTag__c From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:MAIN_TAG Limit 1][0].CaseTag__c);
        System.AssertEquals('TestSubReason 1', [SELECT Id, CaseTag__c From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:SUB_MAIN_TAG Limit 1][0].CaseTag__c);
        System.AssertEquals(1, [SELECT Id From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:MAIN_TAG].Size());
        System.AssertEquals(1, [SELECT Id From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:SUB_MAIN_TAG].Size());
        System.AssertEquals(1, [SELECT Id From CaseTag__c Where CaseId__c =: c.Id AND Type__c=:ADDITIONAL_TAG].Size());
        System.AssertEquals(3, [SELECT Id From CaseTag__c WHERE CaseId__c =: c.Id].size());
        System.AssertEquals(0, [SELECT Id From CaseTag__c WHERE CaseId__c !=: c.Id].size());

        //Test if case tag records is deleted if case is deleted
        delete newCases;
        System.AssertEquals(0, [SELECT Id From CaseTag__c WHERE CaseId__c =: c.Id].size());
    }

    /**
        Test methods for AssignOwnerFromSoMe-Post
    */
    @isTest
    static void newSocialMediaCases(){
        List<SocialPost> socialPosts = [Select Id FROM SocialPost LIMIT 2];
        Case c1 = new Case (Status='New', Origin='Facebook', SourceId=socialPosts[0].Id);
        Case c2 = new Case (Status='New', Origin='Twitter', SourceId=socialPosts[1].Id);
        List<Case> SoMeCases = new List<Case>();
        SoMeCases.add(c1);
        SoMeCases.add(c2);
        insert SoMeCases;
        System.assertEquals([SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'GlobalSupportSoMe'].Id, [SELECT OwnerId FROM Case WHERE Id = :c1.Id].OwnerId);
        System.assertEquals([SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'GlobalSupportSoMe'].Id, [SELECT OwnerId FROM Case WHERE Id = :c2.Id].OwnerId);

    }

}