sas-core/main/default/objects/Case/fields/CaseReason__c.field-meta.xml
<CustomField>
    <fullName>CaseReason__c</fullName>
    <complianceGroup>PIIExtract</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseReason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage delivery</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Booking confirmation</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>Campaign booking</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Card replacement</fullName>
            </value>
            <value>
                <fullName>Car rental</fullName>
            </value>
            <value>
                <fullName>CBBG</fullName>
            </value>
            <value>
                <fullName>Change profile</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Chat lost</fullName>
            </value>
            <value>
                <fullName>Check-in</fullName>
            </value>
            <value>
                <fullName>Co2</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>Connection time</fullName>
            </value>
            <value>
                <fullName>Content and Dangerous goods</fullName>
            </value>
            <value>
                <fullName>Control status</fullName>
            </value>
            <value>
                <fullName>Create case</fullName>
            </value>
            <value>
                <fullName>Customer hangs up</fullName>
            </value>
            <value>
                <fullName>Damaged baggage status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/CaseTags__c.field-meta.xml
<CustomField>
    <fullName>CaseTags__c</fullName>
    <label>Case Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital support</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eurobonus</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Rules</fullName>
            </value>
            <value>
                <fullName>Fares</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Flight info</fullName>
            </value>
            <value>
                <fullName>Group booking - direct groups</fullName>
            </value>
            <value>
                <fullName>Inflight / Onboard</fullName>
            </value>
            <value>
                <fullName>Irregularity / Schedule change</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Name change</fullName>
            </value>
            <value>
                <fullName>New booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/ManagedSocialAccounts__mdt.object-meta.xml
<CustomObject>
    <description>Setting used to identify weather the post/tweet had been posted by SAS or by other account</description>
    <label>Managed Social Account</label>
    <pluralLabel>Managed Social Accounts</pluralLabel>
</CustomObject>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the social account corresponding to the Social Handle</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Represents the provider of the page which name is represented in Name field</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/SASPost__c.field-meta.xml
<CustomField>
    <fullName>SASPost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAS Post</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/SocialPostHandler_Test.cls
/**
* @author Sanna Sörberg
* @date 2019-12-20
* @description Test class for social post handler which includes operations performed on social posts
*/

@isTest
private class SocialPostHandler_Test {

/**
Test method for generation of test data used in more than one method
*/
    @TestSetup static void createTestData() {

        List<Case> newCases = FCS_TestDataFactory.createCases(1, null, null, null, null);
        newCases[0].CaseReason__c = 'TestReason 1';
        newCases[0].Subject = 'TestCase 2';
        newCases[0].CaseSubReason__c = 'TestSubReason 1';
        newCases[0].CaseTags__c = 'CommonTestTag1;CommonTestTag2';
        insert newCases;
    }
    /**
       Test method for setting field on insert of Social Posts
      */

    @isTest
    static void insertSASPost() {
        List<ManagedSocialAccounts__mdt> socialAccs = [SELECT Id, DeveloperName, Name__c, Provider__c From ManagedSocialAccounts__mdt];
        List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(1);
        socialPosts[0].MessageType = 'Post';
        socialPosts[0].Provider = socialAccs[0].Provider__c;
        socialPosts[0].Handle = socialAccs[0].Name__c;
        insert socialPosts;

        List<SocialPost> updatedSocialPosts = [SELECT Id, IsOutbound, SASPost__c, ReviewedStatus FROM SocialPost];

        system.assertEquals(true, updatedSocialPosts[0].IsOutbound);
        system.assertEquals(true,  updatedSocialPosts[0].SASPost__c);
        system.assertEquals(null, updatedSocialPosts[0].ReviewedStatus);

    }


}