sas-core/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Claim related to the case</description>
    <inlineHelpText>Claim related to the case</inlineHelpText>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Proactivity__c.field-meta.xml
<CustomField>
    <fullName>Proactivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use to manually link a case to a proactivity</description>
    <inlineHelpText>Use to manually link a case to a proactivity</inlineHelpText>
    <label>Proactivity</label>
    <referenceTo>Proactivity__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EU261</fullName>
            </value>
            <value>
                <fullName>Downgrading/Denied boarding</fullName>
            </value>
            <value>
                <fullName>Ticket refund, personal injury</fullName>
            </value>
            <value>
                <fullName>Unruly passenger</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>sales information</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>PRM</fullName>
            </value>
            <value>
                <fullName>UM</fullName>
            </value>
            <value>
                <fullName>Travel extras</fullName>
            </value>
            <value>
                <fullName>Care costs</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case related to this claim</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/Proactivity__c.object-meta.xml
<CustomObject>
    <description>Information notice to be shown when a claim matches the criteria defined for the proactivity.</description>
    <label>Proactivity</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Proactivity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proactivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Proactivity__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <description>The message to be displayed for matching claims.</description>
    <inlineHelpText>The message to be displayed for matching claims.</inlineHelpText>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>For differentiating between the different types of proactivities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Major Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability or Customer Claim</description>
    <inlineHelpText>This settlement is related to this Liability or Customer claim</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/controllers/ProactivitiesController.cls
public without sharing class ProactivitiesController {
  public class Proactivity {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public String note;
    @AuraEnabled
    public String matchingReasons;
    @AuraEnabled
    public String type;

    Proactivity(Proactivity__c proactivity, LIA_Claim__c claim, String reason) {
      this.id = proactivity.Id;
      this.note = proactivity.Note__c;
      this.type = proactivity.Type__c;
      this.matchingReasons = reason;
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Proactivity> getProactivitiesForRecord(
    String recordId,
    String objectApiName // Case or Settlement__c
  ) {
    String caseId = recordId;
    if (objectApiName == 'Settlement__c') {
      caseId = SettlementsSelector.newInstance()
          .selectByIdWithClaimFields(new Set<Id>{ recordId })[0]
        .Claim__r.Case__c;
    }

    ProactivitiesSelector proactivities = ProactivitiesSelector.newInstance();
    List<Proactivity> proactivitiesWithMatchingReason = new List<Proactivity>();
    Map<Proactivity__c, String> proactivityToReason = proactivities.selectByCaseIdWithMatchingReasons(
      caseId
    ); //
    List<Proactivity__c> proactivitiesFound = new List<Proactivity__c>(
      proactivityToReason.keySet()
    );

    if (proactivitiesFound.size() > 0) {
      ClaimsSelector claims = ClaimsSelector.newInstance();

      LIA_Claim__c claim = claims.selectByCaseIdWithCustomers(
        new Set<Id>{ caseId }
      )[0];

      for (Proactivity__c p : proactivitiesFound) {
        String reasons = proactivityToReason.get(p);
        proactivitiesWithMatchingReason.add(new Proactivity(p, claim, reasons));
      }
    }

    return proactivitiesWithMatchingReason;
  }

  @AuraEnabled(cacheable=true)
  public static List<Case> getCasesForProactivity(String proactivityId) {
    CasesSelector cases = CasesSelector.newInstance();

    return cases.selectByProactivityId(proactivityId);
  }
}