sas-core/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Claim related to the case</description>
    <inlineHelpText>Claim related to the case</inlineHelpText>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Concerns_a_person_with_reduced_mobility__c.field-meta.xml
<CustomField>
    <fullName>Concerns_a_person_with_reduced_mobility__c</fullName>
    <description>It marks that the case is related to a reduced mobility person</description>
    <formula>LIA_Claim__r.Concerns_a_person_with_reduced_mobility__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that the claim concerns a person with special assistance needs</inlineHelpText>
    <label>Concerns a person with reduced mobility</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Concerns_an_unaccompanied_minor__c.field-meta.xml
<CustomField>
    <fullName>Concerns_an_unaccompanied_minor__c</fullName>
    <formula>LIA_Claim__r.Concerns_an_unaccompanied_minor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concerns an unaccompanied minor</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/Claim__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/Claim_Expense__c.object-meta.xml
<CustomObject>
    <description>A single expense claimed by a customer when submitting a claim.</description>
    <label>Claim Expense</label>
    <nameField>
        <displayFormat>CEN-{00000000}</displayFormat>
        <label>Claim Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The claim this expense is linked to.</description>
    <inlineHelpText>The claim this expense is linked to.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Claim_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/Claim_Rebooked_Flight__c.object-meta.xml
<CustomObject>
    <description>The flights to a which customer claims they were rebooked to.</description>
    <label>Claim Rebooked Flight</label>
    <nameField>
        <displayFormat>CBF-{00000000}</displayFormat>
        <label>Claim Rebooked Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Rebooked Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Rebooked Flights</relationshipLabel>
    <relationshipName>Claim_Rebooked_Flights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>E.g. SK1234</description>
    <inlineHelpText>E.g. SK1234</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>Customer(s) in a customer claim</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Customer__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <inlineHelpText>It is the Liability or Customer claim to which this customer is related to</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Daily exchange rates for currency conversion calculations</description>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Exchange_Rate__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date on which this exchange rate is valid</description>
    <inlineHelpText>Date on which this exchange rate is valid</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/From_Currency__c.field-meta.xml
<CustomField>
    <fullName>From_Currency__c</fullName>
    <label>From Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/To_Currency__c.field-meta.xml
<CustomField>
    <fullName>To_Currency__c</fullName>
    <label>To Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_line_1__c</fullName>
    <label>Address line 1</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Concerns_a_person_with_reduced_mobility__c.field-meta.xml
<CustomField>
    <fullName>Concerns_a_person_with_reduced_mobility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the customer claim is related to a person with reduced mobility</description>
    <label>Concerns a person with reduced mobility</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Concerns_an_unaccompanied_minor__c.field-meta.xml
<CustomField>
    <fullName>Concerns_an_unaccompanied_minor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concerns an unaccompanied minor</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
        <controllingField>Bank_Country__c</controllingField>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/EU261_Handling_Status__c.field-meta.xml
<CustomField>
    <fullName>EU261_Handling_Status__c</fullName>
    <label>EU261 Handling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unhandled</fullName>
                <default>true</default>
                <label>Unhandled</label>
            </value>
            <value>
                <fullName>Eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation</fullName>
            </value>
            <value>
                <fullName>Unable to handle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Preferred_Compensation_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Compensation_Method__c</fullName>
    <label>Preferred Compensation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroBonus Points</fullName>
            </value>
            <value>
                <fullName>Monetary</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Preferred_Reimbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Reimbursement_Method__c</fullName>
    <label>Preferred Reimbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroBonus Points</fullName>
            </value>
            <value>
                <fullName>Monetary</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/recordTypes/CompensationCard.recordType-meta.xml
<RecordType>
    <fullName>CompensationCard</fullName>
    <active>true</active>
    <description>Record type to differentiate the customer claims</description>
    <label>CompensationCard</label>
</RecordType>

sas-core/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finland</fullName>
        <default>true</default>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

sas-core/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GPB</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>Currencies available</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/tests/integration/CaseFormV2Test.cls
@isTest
private class CaseFormV2Test {
  @IsTest
  public static void shouldCreateClaimCasesWithAllFields() {
    // Add exchange rate for claim expense calculations
    Decimal rate = 10.3;
    Exchange_Rate__c newRate = new Exchange_Rate__c(
      From_Currency__c = 'USD',
      To_Currency__c = 'SEK',
      Rate__c = rate,
      Date__c = Date.valueOf('2022-08-02'),
      Name = 'USD-SEK'
    );

    // Create attachments
    ContentVersion powerOfAttorneyFile = new ContentVersion(
      Title = 'Power of attorney',
      PathOnClient = 'Power of attorney.txt',
      VersionData = Blob.valueOf('Test Content 1'),
      IsMajorVersion = true
    );
    ContentVersion receiptFile1 = new ContentVersion(
      Title = 'Receipt',
      PathOnClient = 'Receipt 1.txt',
      VersionData = Blob.valueOf('Test Content 2'),
      IsMajorVersion = true
    );
    ContentVersion receiptFile2 = new ContentVersion(
      Title = 'Receipt',
      PathOnClient = 'Receipt 2.txt',
      VersionData = Blob.valueOf('Test Content 3'),
      IsMajorVersion = true
    );
    ContentVersion boardingPassFile1 = new ContentVersion(
      Title = 'Boarding pass',
      PathOnClient = 'Boarding pass 1.txt',
      VersionData = Blob.valueOf('Test Content 4'),
      IsMajorVersion = true
    );
    ContentVersion boardingPassFile2 = new ContentVersion(
      Title = 'Boarding pass',
      PathOnClient = 'Boarding pass 2.txt',
      VersionData = Blob.valueOf('Test Content 5'),
      IsMajorVersion = true
    );
    insert new List<SObject>{
      powerOfAttorneyFile,
      receiptFile1,
      receiptFile2,
      boardingPassFile1,
      boardingPassFile2,
      newRate
    };

    // Construct request JSON manually.
    String contactJson =
      '{' +
      '  "type": "private",' +
      '  "companyName": "Test Aktiebolag",' +
      '  "companyCode": "ABC",' +
      '  "firstName": "Test",' +
      '  "lastName": "Testsson",' +
      '  "email": "test@example.com",' +
      '  "phone": "000000000",' +
      '  "address": "Frösundaviks allé 1",' +
      '  "postalCode": "16970",' +
      '  "city": "Solna",' +
      '  "country": "SE",' +
      '  "euroBonusNumber": "000000000"' +
      '}';

    String compensationDetailsJson =
      '{' +
      '  "bankAccountHolderName": "Test Testsson",' +
      '  "bankAccountNumber": "FI0000000000000000",' +
      '  "bankCountry": "FI",' +
      '  "bankName": "S-Pankki",' +
      '  "bankBic": "SBANFIHH",' +
      '  "preferredCurrency": "EUR",' +
      '  "preferredCompensationMethod": "eurobonus",' +
      '  "preferredReimbursementMethod": "monetary",' +
      '  "referenceNumber": "1234567890"' +
      '}';

    String travelersJson =
      '[' +
      '  { "firstName": "Test", "lastName": "Testsson"},' +
      '  { "firstName": "Test", "lastName": "Testsdottir"}' +
      ']';

    String expensesJson =
      '[' +
      '  {' +
      '    "expenseType": "food",' +
      '    "expenseCurrency": "NOK",' +
      '    "amount": 250.55,' +
      '    "contentVersionIds": ["' +
      receiptFile1.Id +
      '"]' +
      '  },' +
      '  {' +
      '    "expenseType": "transportation",' +
      '    "expenseCurrency": "USD",' +
      '    "amount": 399,' +
      '    "contentVersionIds": ["' +
      receiptFile2.Id +
      '"]' +
      '  }' +
      ']';

    String rebookedFlightsJson =
      '[' +
      '  {' +
      '    "departureDate": "2022-02-20",' +
      '    "flightNumber": "SK1",' +
      '    "contentVersionIds": ["' +
      boardingPassFile1.Id +
      '"]' +
      '  },' +
      '  {' +
      '    "departureDate": "2022-02-22",' +
      '    "flightNumber": "SK1000",' +
      '    "contentVersionIds": ["' +
      boardingPassFile2.Id +
      '"]' +
      '  }' +
      ']';

    String claimJson =
      '{' +
      '  "category": "flight-disruptions",' +
      '  "type": "flight-delay",' +
      '  "delayLength": "2-3",' +
      '  "unaccompaniedMinor": true,' +
      '  "personWithReducedMobility": true,' +
      '  "bookingReference": "TEST12",' +
      '  "departureDate": "2022-03-02",' +
      '  "flightNumber": "SK1234",' +
      '  "passengerIrregularityReportNumber": "TEST13",' +
      '  "comment": "An angry comment.",' +
      '  "travelers": ' +
      travelersJson +
      ',' +
      '  "expenses": ' +
      expensesJson +
      ',' +
      '  "rebookedFlights": ' +
      rebookedFlightsJson +
      '}';

    String input =
      '{' +
      '  "formData": {' +
      '    "type": "claim",' +
      '    "contact": ' +
      contactJson +
      ',' +
      '    "claim": ' +
      claimJson +
      ',' +
      '    "compensationDetails": ' +
      compensationDetailsJson +
      ',' +
      '    "contentVersionIds": ["' +
      powerOfAttorneyFile.Id +
      '"]' +
      '  },' +
      '  "metaData": {' +
      '    "market": "dk-da"' +
      '  }' +
      '}';

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    CaseFormJSONV2 requestBody = CaseFormJSONV2.parse(input);
    CaseFormResponse response = CaseFormV2.createCase(requestBody);
    Test.StopTest();
    Case c = [
      SELECT Id, Origin, Department__c
      FROM Case
      WHERE CaseNumber = :response.caseNumber
    ];

    LIA_Claim__c cl = [
      SELECT
        Id,
        Address_line_1__c,
        Bank_Country__c,
        Country__c,
        Concerns_a_person_with_reduced_mobility__c,
        Concerns_an_unaccompanied_minor__c,
        Currency__c,
        Liability_PNR__c,
        Preferred_Compensation_Method__c,
        Preferred_Reimbursement_Method__c,
        Flight_Date__c,
        Flight_Number__c,
        EU261_Handling_Status__c,
        External_Data_Status__c
      FROM LIA_Claim__c
      WHERE Case__c = :c.Id
    ];

    System.assertNotEquals(
      null,
      c,
      'Should have found a case with the case number returned from create case.'
    );
    System.assertEquals(
      'Form - Claims DK',
      c.Origin,
      'Origin should be set correctly for Denmark.'
    );
    System.assertEquals(
      'Customer Claim',
      c.Department__c,
      'Department should be set correctly for Denmark.'
    );
    System.assertEquals(
      'Unhandled',
      cl.EU261_Handling_Status__c,
      'EU261_Handling_Status__c Status should be updated'
    );
    System.assertEquals(
      'Not Started',
      cl.External_Data_Status__c,
      'External_Data_Status__c Should be updated'
    );
    System.assertNotEquals(
      null,
      cl,
      'Should have found a claim linked to the case.'
    );
    System.assertEquals(
      'Finland',
      cl.Bank_Country__c,
      'Should have set bank country correctly.'
    );
    System.assertEquals(
      'Frösundaviks allé 1',
      cl.Address_line_1__c,
      'Should have set contact address correctly.'
    );
    System.assertEquals(
      'Sweden',
      cl.Country__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      true,
      cl.Concerns_a_person_with_reduced_mobility__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      true,
      cl.Concerns_an_unaccompanied_minor__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      'EUR',
      cl.Currency__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      'TEST12',
      cl.Liability_PNR__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      'EuroBonus Points',
      cl.Preferred_Compensation_Method__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      'Monetary',
      cl.Preferred_Reimbursement_Method__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      Date.parse('2022-03-02'),
      cl.Flight_Date__c,
      'Should have set contact country correctly.'
    );
    System.assertEquals(
      'SK1234',
      cl.Flight_Number__c,
      'Should have set contact country correctly.'
    );

    List<Claim_Expense__c> expenses = [
      SELECT Amount__c, Currency__c, Type__c, Claim_Expense_Amount_In_SEK__c
      FROM Claim_Expense__c
      WHERE Claim__c = :cl.Id
    ];

    System.assertEquals(
      2,
      expenses.size(),
      'There should be 2 expenses linked to the claim.'
    );

    for (Claim_Expense__c e : expenses) {
      if (e.Type__c == 'transportation') {
        System.assertEquals('USD', e.Currency__c);
        System.assertEquals(399, e.Amount__c);
        System.assertEquals(399 * rate, e.Claim_Expense_Amount_In_SEK__c);
      } else {
        System.assertEquals('NOK', e.Currency__c);
        System.assertEquals(250.55, e.Amount__c);
      }
    }

    List<Customer__c> travellers = [
      SELECT First_Name__c, Last_Name__c
      FROM Customer__c
      WHERE Claim__c = :cl.Id
    ];

    System.assertEquals(
      2,
      travellers.size(),
      'There should be 2 travellers linked to the claim.'
    );

    for (Customer__c cust : travellers) {
      System.assertEquals('Test', cust.First_Name__c);
    }

    List<Claim_Rebooked_Flight__c> rebookedFlights = [
      SELECT Departure_Date__c, Flight_Number__c
      FROM Claim_Rebooked_Flight__c
      WHERE Claim__c = :cl.Id
    ];

    for (Claim_Rebooked_Flight__c f : rebookedFlights) {
      if (f.Flight_Number__c == 'SK0001') {
        System.assertEquals(f.Departure_Date__c, Date.parse('2022-02-20'));
      } else {
        System.assertEquals(f.Departure_Date__c, Date.parse('2022-02-22'));
      }
    }

    System.assertEquals(
      2,
      travellers.size(),
      'There should be 2 rebooked flights linked to the claim.'
    );

    List<ContentDocumentLink> linksToClaim = [
      SELECT ContentDocumentId
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :cl.Id
    ];
    System.assertEquals(
      5,
      linksToClaim.size(),
      'There should be 5 files linked to the claim.'
    );

    List<ContentDocumentLink> linksToExpense = [
      SELECT ContentDocumentId
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :expenses[0].Id
    ];
    System.assertEquals(
      1,
      linksToExpense.size(),
      'There should be 1 file linked to each expense.'
    );

    List<ContentDocumentLink> linksToRebookedFlight = [
      SELECT ContentDocumentId
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :rebookedFlights[0].Id
    ];
    System.assertEquals(
      1,
      linksToRebookedFlight.size(),
      'There should be 1 file linked to each rebooked flight.'
    );

    List<ContentVersion> expenseFileFromQuery = [
      SELECT Title
      FROM ContentVersion
      WHERE ContentDocumentId = :linksToExpense[0].ContentDocumentId
    ];
    System.assertEquals(
      'Receipt',
      expenseFileFromQuery[0].Title,
      'Title for linked file to expense should match receipt file.'
    );

    List<ContentVersion> boardingPassFileFromQuery = [
      SELECT Title
      FROM ContentVersion
      WHERE ContentDocumentId = :linksToRebookedFlight[0].ContentDocumentId
    ];
    System.assertEquals(
      'Boarding pass',
      boardingPassFileFromQuery[0].Title,
      'Title for linked file to rebooked flight should match boarding pass file.'
    );
  }

  @IsTest
  public static void shouldCreateClaimCasesWithMinimalFields() {
    // Construct request JSON manually.
    String contactJson =
      '{' +
      '  "type": "private",' +
      '  "firstName": "Test",' +
      '  "lastName": "Testsson",' +
      '  "email": "test@example.com",' +
      '  "phone": "000000000",' +
      '  "address": "Frösundaviks allé 1",' +
      '  "postalCode": "16970",' +
      '  "city": "Solna",' +
      '  "country": "SE"' +
      '}';

    String compensationDetailsJson =
      '{' +
      '  "preferredCompensationMethod": "voucher"' +
      '}';

    String claimJson =
      '{' +
      '  "category": "accident-and-injury",' +
      '  "type": "other",' +
      '  "delayLength": "2-3",' +
      '  "bookingReference": "TEST12",' +
      '  "departureDate": "2022-03-02",' +
      '  "flightNumber": "SK1234"' +
      '}';

    String input =
      '{' +
      '  "formData": {' +
      '    "type": "claim",' +
      '    "contact": ' +
      contactJson +
      ',' +
      '    "claim": ' +
      claimJson +
      ',' +
      '    "compensationDetails": ' +
      compensationDetailsJson +
      '  },' +
      '  "metaData": {' +
      '    "market": "dk-da"' +
      '  }' +
      '}';

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    CaseFormJSONV2 requestBody = CaseFormJSONV2.parse(input);
    CaseFormResponse response = CaseFormV2.createCase(requestBody);
    Test.StopTest();
    Case c = [
      SELECT Id, Origin
      FROM Case
      WHERE CaseNumber = :response.caseNumber
    ];
    // TODO: Check all fields correctly when it's possible.
    LIA_Claim__c cl = [SELECT Id FROM LIA_Claim__c WHERE Case__c = :c.Id];
    System.assertNotEquals(
      null,
      c,
      'Should have found a case with the case number returned from create case.'
    );
    System.assertEquals(
      'Form - Claims DK',
      c.Origin,
      'Origin should be set correctly for Denmark.'
    );
    System.assertNotEquals(
      null,
      cl,
      'Should have found a claim linked to the case.'
    );
  }

  @IsTest
  public static void shouldCreateBaggageClaimCases() {
    // Construct request JSON manually.
    String contactJson =
      '{' +
      '  "type": "private",' +
      '  "firstName": "Test",' +
      '  "lastName": "Testsson",' +
      '  "email": "test@example.com",' +
      '  "phone": "000000000",' +
      '  "address": "Frösundaviks allé 1",' +
      '  "postalCode": "16970",' +
      '  "city": "Solna",' +
      '  "country": "SE"' +
      '}';

    String compensationDetailsJson =
      '{' +
      '  "preferredCompensationMethod": "voucher"' +
      '}';

    String claimJson =
      '{' +
      '  "category": "baggage",' +
      '  "type": "baggage-delayed",' +
      '  "baggageDelayTime": "less-than-21-days",' +
      '  "bookingReference": "TEST12",' +
      '  "passengerIrregularityReportNumber": "ARNSK12345",' +
      '  "baggagePurchasePrice": 500,' +
      '  "baggagePurchaseYear": 2021,' +
      '  "departureDate": "2022-03-02",' +
      '  "flightNumber": "SK1234"' +
      '}';

    String input =
      '{' +
      '  "formData": {' +
      '    "type": "claim",' +
      '    "contact": ' +
      contactJson +
      ',' +
      '    "claim": ' +
      claimJson +
      ',' +
      '    "compensationDetails": ' +
      compensationDetailsJson +
      '  },' +
      '  "metaData": {' +
      '    "market": "dk-da"' +
      '  }' +
      '}';

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    CaseFormJSONV2 requestBody = CaseFormJSONV2.parse(input);
    CaseFormResponse response = CaseFormV2.createCase(requestBody);
    Test.StopTest();
    Case c = [
      SELECT Id, Origin
      FROM Case
      WHERE CaseNumber = :response.caseNumber
    ];
    LIA_Claim__c cl = [
      SELECT
        Id,
        Customer_Claim_Type__c,
        Delay_Length__c,
        Purchase_Price__c,
        Purchase_Year__c
      FROM LIA_Claim__c
      WHERE Case__c = :c.Id
    ];
    System.assertNotEquals(
      null,
      c,
      'Should have found a case with the case number returned from create case.'
    );
    System.assertEquals(
      'Form - Claims DK',
      c.Origin,
      'Origin should be set correctly for Denmark.'
    );
    System.assertNotEquals(
      null,
      cl,
      'Should have found a claim linked to the case.'
    );
    System.assertEquals(
      'Baggage delayed/lost',
      cl.Customer_Claim_Type__c,
      'Should have set claim type correctly.'
    );
    System.assertEquals(
      'Less than 21 days',
      cl.Delay_Length__c,
      'Should have set delay length correctly.'
    );
    System.assertEquals(
      500,
      cl.Purchase_Price__c,
      'Should have set purchase price correctly.'
    );
    System.assertEquals(
      2021,
      cl.Purchase_Year__c,
      'Should have set purchase year correctly.'
    );
  }

  @IsTest
  public static void shouldCreateCompensationCardClaims() {
    // Given
    TestDataFactories.insertEmailTemplates(
      new Set<String>{
        ClaimService.COMPENSATION_CARD_FAILURE_EMAIL_TEMPLATE_NAME,
        ClaimService.COMPENSATION_CARD_SUCCESS_EMAIL_TEMPLATE_NAME
      }
    );

    // Construct request JSON manually.
    String contactJson =
      '{' +
      '  "type": "private",' +
      '  "firstName": "Test",' +
      '  "lastName": "Testsson",' +
      '  "email": "test@example.com",' +
      '  "phone": "000000000",' +
      '  "address": "Frösundaviks allé 1",' +
      '  "postalCode": "16970",' +
      '  "city": "Solna",' +
      '  "country": "SE"' +
      '}';

    String compensationDetailsJson =
      '{' +
      '  "preferredCompensationMethod": "voucher"' +
      '}';

    String input =
      '{' +
      '  "formData": {' +
      '    "bookingReference": "TEST12",' +
      '    "compensationCardNumber": "0012345678",' +
      '    "contact": ' +
      contactJson +
      ',' +
      '    "compensationDetails": ' +
      compensationDetailsJson +
      '  },' +
      '  "metaData": {' +
      '    "market": "dk-da"' +
      '  }' +
      '}';

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    RedeemCompensationCardJSON requestBody = RedeemCompensationCardJSON.parse(
      input
    );
    CaseFormResponse response = RedeemCompensationCard.redeem(requestBody);
    Test.StopTest();

    Case c = [
      SELECT Id, Status
      FROM Case
      WHERE CaseNumber = :response.caseNumber
    ];
    LIA_Claim__c cl = [
      SELECT Id, RecordTypeId, Compensation_Card_Number__c, Liability_PNR__c
      FROM LIA_Claim__c
      WHERE Case__c = :c.Id
    ];

    System.assertEquals(
      Claim.getRecordTypeIdByEnum(Claim.RecordType.CompensationCard),
      cl.RecordTypeId,
      'Record type should be set to compensation card.'
    );

    System.assertEquals(
      '0012345678',
      cl.Compensation_Card_Number__c,
      'Compensation Card Number should be set.'
    );

    System.assertEquals(
      'TEST12',
      cl.Liability_PNR__c,
      'Compensation Card Number should be set.'
    );

    System.assertEquals(
      Cases.STATUS_CLOSED,
      c.Status,
      'Case should have been set to closed.'
    );
  }
}