sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseReason__c</fullName>
    <complianceGroup>PIIExtract;WipeRetain</complianceGroup>
    <description>Second level categorization for cases.</description>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 day refund guarantee</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Award travel</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Service</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Bank Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Boozt Attack</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <description>Third level categorization for cases.</description>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseReason__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Groups</fullName>
            </value>
            <value>
                <fullName>Agent - Agreement related Question</fullName>
            </value>
            <value>
                <fullName>Agent - Other</fullName>
            </value>
            <value>
                <fullName>Agent - TravelPass</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Booking</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass CC update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Contact Update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Receipt</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Sell</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Statistics</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass wrong deb</fullName>
            </value>
            <value>
                <fullName>Agreement related question*</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport service locations</fullName>
            </value>
            <value>
                <fullName>Allergies</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Alternatives</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX 2 for 1</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Ancillary error</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>ATC refund flow</fullName>
            </value>
            <value>
                <fullName>Author</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/OldCaseTagtoNewCaseTags__c/OldCaseTagtoNewCaseTags__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is creating mainly for migrating the old case tags to new case tags</description>
    <label>OldCaseTagtoNewCaseTags</label>
</CustomObject>

sas-core/main/default/objects/OldCaseTagtoNewCaseTags__c/fields/Old_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Old_Case_Reason__c</fullName>
    <label>Old Case Reason</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/OldCaseTagtoNewCaseTags__c/fields/Old_Case_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Old_Case_Sub_Reason__c</fullName>
    <label>Old Case Sub Reason</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/MigrateCaseTagsBatch.cls
global class MigrateCaseTagsBatch extends SBS_ScheduledBatch {
  public String caseOrigin;
  public String caseDepartment;
  public String caseRecordType;
  
  public Map<String,OldCaseTagtoNewCaseTags__c> mapOldToNewCaseTags;
  
  global MigrateCaseTagsBatch ( String cseOrigin, String cseDepartment, String cseRecordType) {
   mapOldToNewCaseTags = new Map<String,OldCaseTagtoNewCaseTags__c>();
   List<OldCaseTagtoNewCaseTags__c> lstOldcaseTags = OldCaseTagtoNewCaseTags__c.getall().values();
   for(OldCaseTagtoNewCaseTags__c cussetting :lstOldcaseTags  )
   {
     String key;
     if(cussetting.Old_Case_Sub_Reason__c!='' && cussetting.Old_Case_Sub_Reason__c!=null)
     {
         key = cussetting.Old_Case_Reason__c+'@'+cussetting.Old_Case_Sub_Reason__c;
     }
     else
     {
       key = cussetting.Old_Case_Reason__c;
     }
     
     if(mapOldToNewCaseTags.containsKey(key))
     {
       // nothing
     }
     else
     {
       mapOldToNewCaseTags.put(key,cussetting);   
     }
   }
    caseOrigin = cseOrigin;
    caseDepartment = cseDepartment;
    caseRecordType = cseRecordType;
  }

  global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'Select Id,FCS_CaseReason__c,FCS_CaseSubReason__c,FCS_Case_Reason__c,FCS_CaseType__c FROM Case where Origin = :caseOrigin and Department__c = :caseDepartment and RecordType.Name =:caseRecordType and FCS_Case_Reason__c=null and FCS_CaseReason__c!=null LIMIT 10000'
    );
  }

  global override void executeScope(
    Database.BatchableContext bc,
    SObject[] sObjScope
  ) {
    List<Case> lstcase = (List<Case>) sObjScope;
    for (Case cse : lstcase) {
     if(cse.FCS_CaseReason__c!='' && cse.FCS_CaseReason__c!=null)
     { string key;
        if(cse.FCS_CaseSubReason__c!='' && cse.FCS_CaseSubReason__c!=null)
        {
         key = cse.FCS_CaseReason__c+'@'+cse.FCS_CaseSubReason__c;
        }
        else
        {
          key = cse.FCS_CaseReason__c;
        }
          System.debug('key***'+key);
          cse.FCS_Case_Reason__c =mapOldToNewCaseTags.get(key).New_Case_Reason__c;
          cse.FCS_CaseType__c = mapOldToNewCaseTags.get(key).New_Case_Type__c;
          
        if(mapOldToNewCaseTags.get(key).New_Case_Reason__c == 'Other')
        {
        
          
          cse.FCS_CaseResolutionDetails__c = mapOldToNewCaseTags.get(key).Old_Case_Sub_Reason__c;
        
        }
     }
   }
    update lstcase;
  }
}