sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseReason__c</fullName>
    <complianceGroup>PIIExtract;WipeRetain</complianceGroup>
    <description>Second level categorization for cases.</description>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 day refund guarantee</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Award travel</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Service</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Bank Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Boozt Attack</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseResolution__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseResolution__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_Case_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>According to rules</fullName>
            </value>
            <value>
                <fullName>Acquirer</fullName>
            </value>
            <value>
                <fullName>Activate Profile</fullName>
            </value>
            <value>
                <fullName>Add travel pass</fullName>
            </value>
            <value>
                <fullName>Agreement related question</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Authorities</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Big/Supersale</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
            <value>
                <fullName>Booking flow</fullName>
            </value>
            <value>
                <fullName>Booking related</fullName>
            </value>
            <value>
                <fullName>Booking rules</fullName>
            </value>
            <value>
                <fullName>Bug/User story created</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>CC Update</fullName>
            </value>
            <value>
                <fullName>Changed dates</fullName>
            </value>
            <value>
                <fullName>Changed destination</fullName>
            </value>
            <value>
                <fullName>Changed email</fullName>
            </value>
            <value>
                <fullName>Changed name</fullName>
            </value>
            <value>
                <fullName>Changed phone number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseResolutionDetails__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseResolutionDetails__c</fullName>
    <label>Case Resolution Details</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LiveChatTranscript/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus Number of the person contacting SAS</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/CasesSelector.cls
public inherited sharing class CasesSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Case.Id,
      Case.AccountId,
      Case.CaseNumber,
      Case.CreatedDate,
      Case.FCS_CaseReason__c,
      Case.FCS_EBNumber__c,
      Case.FCS_Case_Reason__c,
      case.RecordTypeId,
      Case.Status,
      case.Department__c,
      Case.FCS_CaseType__c,
      Case.FCS_CaseResolution__c,
      Case.FCS_CaseResolutionDetails__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Case.SObjectType;
  }

  public List<Case> selectById(Set<Id> ids) {
    return (List<Case>) selectSObjectsById(ids);
  }

  public List<Case> selectByAccountId(Set<Id> accountIds) {
    fflib_QueryFactory casesQF = newQueryFactory()
      .setCondition('AccountId in :accountIds');
    return (List<Case>) Database.query(casesQF.toSOQL());
  }
  public List<Case> selectByChatId(Set<Id> chatIds) {
    ChatTranscriptsSelector chatTranscripts = (ChatTranscriptsSelector) SAS_Service_Application.Selector.newInstance(
      LiveChatTranscript.SObjectType
    );

    Set<Id> caseIds = new Set<Id>();
    for (LiveChatTranscript ct : chatTranscripts.selectById(chatIds)) {
      caseIds.add(ct.caseId);
    }
    return (List<Case>) this.selectSObjectsById(caseIds);
  }
  public List<Case> selectBySocialPostId(Set<Id> socialPostIds) {
    SocialPostsSelector socialPosts = (SocialPostsSelector) SAS_Service_Application.Selector.newInstance(
      SocialPost.SObjectType
    );
    Set<Id> caseIds = new Set<Id>();
    for (SocialPost sp : socialPosts.selectById(socialPostIds)) {
      caseIds.add(sp.parentId);
    }
    return (List<Case>) this.selectSObjectsById(caseIds);
  }
  public List<Case> selectByMessagingId(Set<Id> messagingsessionsId) {
    MessagingSessionsSelector messagingSessions = (MessagingSessionsSelector) SAS_Service_Application.Selector.newInstance(
      MessagingSession.SObjectType
    );
    Set<Id> caseIds = new Set<Id>();
    for (
      MessagingSession ms : messagingSessions.selectById(messagingsessionsId)
    ) {
      caseIds.add(ms.caseId);
    }
    return (List<Case>) this.selectSObjectsById(caseIds);
  }
  public override String getOrderBy() {
    return 'CaseNumber';
  }
}