sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/IsRedirected__c.field-meta.xml
<CustomField>
    <fullName>IsRedirected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate that the case has been redirected to another department/team</description>
    <inlineHelpText>To indicate that the case has been redirected to another department/team</inlineHelpText>
    <label>IsRedirected</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team of the first case owner (that is a user)</description>
    <inlineHelpText>The team of the first case owner (that is a user)</inlineHelpText>
    <label>Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/FCS_MassRedirection.cls
/**
@author Thippeswamy Aravinda
@date June-10-2021
@description : invoked from mass redirection flow 
*/

public class FCS_MassRedirection {
  @InvocableMethod(label='Get redirection Cases')
  public static List<Responsecase> getRedirectionCases(
    List<Requestcase> requestCases
  ) {
    List<Case> lstCses = [
      SELECT
        Id,
        Department__c,
        Team__c,
        IsRedirected__c,
        RecordTypeId,
        OwnerId,
        Status,
        CaseNumber
      FROM Case
      WHERE Id = :requestCases[0].caseIds
    ];

    Responsecase resCase = new Responsecase();
    resCase.lstCases = lstCses;
    List<Responsecase> lstresCases = new List<Responsecase>();
    lstresCases.add(resCase);
    return lstresCases;
  }

  public class Requestcase {
    @InvocableVariable
    public List<Id> caseIds;
  }

  public class Responsecase {
    @InvocableVariable
    public List<Case> lstCases;
  }
}