sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team of the first case owner (that is a user)</description>
    <inlineHelpText>The team of the first case owner (that is a user)</inlineHelpText>
    <label>Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Used to manage all chat related cases</description>
    <label>Chat</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/classes/ChangeCaseRecordTypeBatch.cls
global class ChangeCaseRecordTypeBatch extends SBS_ScheduledBatch {
  public String caseOrigin;
  public List<String> caseRecordTypes;

  global ChangeCaseRecordTypeBatch(
    String cseOrigin,
    List<String> cseRecordTypes
  ) {
    caseRecordTypes = cseRecordTypes;
    caseOrigin = cseOrigin;
  }

  global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'Select Id, Department__c,Origin,RecordTypeId,Team__c FROM Case where Origin = :caseOrigin and RecordType.Name =:caseRecordTypes'
    );
  }

  global override void executeScope(
    Database.BatchableContext bc,
    SObject[] sObjScope
  ) {
    List<Case> lstcase = (List<Case>) sObjScope;
    for (Case cse : lstcase) {
      if (cse.origin == 'Chat') {
        cse.Department__c = 'SoMe Support';
        cse.Team__c = 'Chat';
        cse.RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
      }
      if (cse.origin == 'Facebook Messenger') {
        cse.Department__c = 'SoMe Support';
        cse.Team__c = 'Facebook Messenger';
        cse.RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
      }
      if (cse.origin == 'Facebook' || cse.origin == 'Twitter') {
        cse.Department__c = 'SoMe Support';
        cse.Team__c = 'SoMe';
        cse.RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL;
      }
    }

    update lstcase;
  }
}