sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Group_Travel_Request__c.field-meta.xml
<CustomField>
    <fullName>Group_Travel_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>for relating the case with Group travel request</description>
    <label>Group Travel Request</label>
    <referenceTo>Group_Travel_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Group_Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Group Travel Request</label>
    <nameField>
        <label>Group Travel Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <label>Departure date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Invoice_agreement_with_SAS__c.field-meta.xml
<CustomField>
    <fullName>Invoice_agreement_with_SAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice agreement with SAS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/tests/integration/GroupTravelRequestTest.cls
@IsTest
private class GroupTravelRequestTest {
  @IsTest
  public static void shouldCreateGroupTravelRequests() {
    GroupTravelJsonToApex requestBody = GroupTravelJsonToApex.parse(
      '{ ' +
      '  "formData": {' +
      '    "groupName": "Group Travel Group",' +
      '    "email": "example@example.com",' +
      '    "phone": "110000000000",' +
      '    "haveCompanyCode":true,' +
      '    "companyCode": "123456A",' +
      '    "firstName": "test",' +
      '    "lastName": "test1",' +
      '    "city": "Test",' +
      '    "tripType": "round-trip",' +
      '    "groupType": "youth",' +
      '    "fromAirport": "BNG",' +
      '    "toAirport": "ARN",' +
      '    "differentReturnCityAirport": "HYH",' +
      '    "departureTime": "evening",' +
      '    "departureDate": "2021-09-21",' +
      '    "returnTime": "morning",' +
      '    "returnDate": "2012-09-23",' +
      '    "alternativeDates":true,' +
      '    "alternateDepartureTime": "midmorning",' +
      '    "alternateReturnTime": "any-time",' +
      '    "alternateReturnDate": "2021-09-26",' +
      '    "proposeAlternativeDestinations": false,' +
      '    "otherDestinationsOfInterest": "testtetetsstst",' +
      '    "numberOfAdults": 2,' +
      '    "numberOfChildren": 1,' +
      '    "numberOfInfants": 0,' +
      '    "travelClass": "sas-plus",' +
      '    "wheelchairs": true,' +
      '    "numberOfWheelchairs": 1, ' +
      '    "visualOrHearingAssistance": true,' +
      '    "formOfPayment": "sas-invoice",' +
      '    "invoiceAgreementWithSAS": true,' +
      '    "comments": "teststestst"' +
      '  },' +
      '  "metaData": {' +
      '    "market": "fr-fr"' +
      '  }' +
      '}'
    );

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    GroupTravelRequestForm.createGroupTravelRequest(requestBody);
    Test.StopTest();

    Group_Travel_Request__c req = [
      SELECT Id, Departure_Date__c, Invoice_Agreement_With_SAS__c
      FROM Group_Travel_Request__c
      WHERE Phone__c = '110000000000'
    ];
    Case c = [
      SELECT Id, Department__c, Origin
      FROM Case
      WHERE Group_Travel_Request__c = :req.Id
    ];

    System.assertEquals(
      true,
      req.Invoice_Agreement_With_SAS__c,
      'Form data should be parsed correctly into picklists.'
    );

    System.assertEquals(
      Date.valueOf('2021-09-21'),
      req.Departure_Date__c,
      'Form data should be parsed correctly into dates.'
    );

    System.assertEquals(
      'Form - Group Travel FR',
      c.Origin,
      'Case Origin should be set according to market and form type.'
    );

    System.assertEquals(
      'Group Sales',
      c.Department__c,
      'Case Department should be set by Case Origin to refunds.'
    );
  }
}