sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Refund_Request__c.field-meta.xml
<CustomField>
    <fullName>Refund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund Request</label>
    <referenceTo>Refund_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
	<complianceGroup>Lookup</complianceGroup>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/Refund_Request__c.object-meta.xml
<CustomObject>
    <label>Refund Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Refund Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Refund_Request__c/fields/Cancel_Entire_Booking__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Entire_Booking__c</fullName>
    <label>Cancel Entire Booking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Already Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Refund_Not_Claimed_Elsewhere__c.field-meta.xml
<CustomField>
    <fullName>Refund_Not_Claimed_Elsewhere__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether customer has checked the box &quot;I have not received or claimed a refund from others or my Travel Agent&quot; when submitting a refund claim on the website.</description>
    <inlineHelpText>Whether customer has checked the box &quot;I have not received or claimed a refund from others or my Travel Agent&quot; when submitting a refund claim on the website.</inlineHelpText>
    <label>Refund Not Claimed Elsewhere</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/tests/integration/RefundRequestFormTest.cls
@IsTest
public class RefundRequestFormTest {
  @IsTest
  public static void shouldCreateCustomerRefundCases() {
    RefundJsonToApex requestBody = RefundJsonToApex.parse(
      '{  ' +
      '  "formData": {' +
      '    "countryOfPurchase": "Sweden",' +
      '    "email": "example@example.com",' +
      '    "phone": "0000098000000",' +
      '    "passengerNames": [' +
      '      "Example Examplesson", ' +
      '      "Example Examplesdottir"' +
      '    ],' +
      '    "cancelEntireBooking": "already-cancelled",' +
      '    "cancelAllPassengers": "no",' +
      '    "cancelDirection": "return",' +
      '    "bookedTripVia": "sas-website",' +
      '    "bookingReference":"TEST12",' +
      '    "ticketNumber": "123-TEST567890",' +
      '    "type": "normal"' +
      '  },' +
      '  "metaData": {' +
      '    "market": "se-sv"' +
      '  }' +
      '}'
    );
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    RefundRequestForm.createRefundRequest(requestBody);
    Test.StopTest();

    Refund_Request__c req = [
      SELECT Id, Cancel_Entire_Booking__c
      FROM Refund_Request__c
      WHERE Phone__c = '0000098000000'
    ];
    Case c = [
      SELECT Id, Department__c, Origin
      FROM Case
      WHERE Refund_Request__c = :req.Id
    ];

    System.assertEquals(
      'Already Cancelled',
      req.Cancel_Entire_Booking__c,
      'Form data should be parsed correctly into picklists.'
    );

    System.assertEquals(
      'Form - Refunds Customer SE',
      c.Origin,
      'Case Origin should be set according to market and form type.'
    );

    System.assertEquals(
      'Refunds',
      c.Department__c,
      'Case Department should be set by Case Origin to refunds.'
    );
  }

  @IsTest
  public static void shouldCreateTravelAgentRefundCases() {
    RefundJsonToApex requestBody = RefundJsonToApex.parse(
      '{  ' +
      '  "formData": {' +
      '    "countryOfPurchase": "Sweden",' +
      '    "email": "example@example.com",' +
      '    "phone": "0000098700000",' +
      '    "passengerNames": [' +
      '      "Example Examplesson", ' +
      '      "Example Examplesdottir"' +
      '    ],' +
      '    "cancelEntireBooking": "already-cancelled",' +
      '    "cancelAllPassengers": "no",' +
      '    "cancelDirection": "return",' +
      '    "bookedTripVia": "sas-website",' +
      '    "bookingReference":"TEST12",' +
      '    "notClaimedElsewhere": true,' +
      '    "ticketNumber": "123-TEST567890",' +
      '    "type": "travel-agent"' +
      '  },' +
      '  "metaData": {' +
      '    "market": "no-no"' +
      '  }' +
      '}'
    );
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    Test.startTest();
    RefundRequestForm.createRefundRequest(requestBody);
    Test.StopTest();

    Refund_Request__c req = [
      SELECT Id, Refund_Not_Claimed_Elsewhere__c
      FROM Refund_Request__c
      WHERE Phone__c = '0000098700000'
    ];
    Case c = [
      SELECT Id, Department__c, Origin
      FROM Case
      WHERE Refund_Request__c = :req.Id
    ];

    System.assertEquals(
      true,
      req.Refund_Not_Claimed_Elsewhere__c,
      'Form data should be parsed correctly into checklists.'
    );

    System.assertEquals(
      'Form - Refunds Travel Agent NO',
      c.Origin,
      'Case Origin should be set according to market and form type.'
    );

    System.assertEquals(
      'Refunds',
      c.Department__c,
      'Case Department should be set by Case Origin to refunds.'
    );
  }
}