sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Disconnected customer</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseResolution__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseResolution__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_Case_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>According to rules</fullName>
            </value>
            <value>
                <fullName>Acquirer</fullName>
            </value>
            <value>
                <fullName>Activate Profile</fullName>
            </value>
            <value>
                <fullName>Add travel pass</fullName>
            </value>
            <value>
                <fullName>Agreement related question</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Authorities</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Big/Supersale</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
            <value>
                <fullName>Booking flow</fullName>
            </value>
            <value>
                <fullName>Booking related</fullName>
            </value>
            <value>
                <fullName>Booking rules</fullName>
            </value>
            <value>
                <fullName>Bug/User story created</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>CC Update</fullName>
            </value>
            <value>
                <fullName>Changed dates</fullName>
            </value>
            <value>
                <fullName>Changed destination</fullName>
            </value>
            <value>
                <fullName>Changed email</fullName>
            </value>
            <value>
                <fullName>Changed name</fullName>
            </value>
            <value>
                <fullName>Changed phone number</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Referred to phone</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Used to manage all chat related cases</description>
    <label>Chat</label>
</RecordType>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/classes/FCS_CloseFBMessgerCaseAfter24hr_Test.cls
@isTest
public class FCS_CloseFBMessgerCaseAfter24hr_Test {
  /**
   * Setting up setup objects in setup method
   */
  @TestSetup
  static void createTestData() {
    insert new MessagingChannel(
      DeveloperName = 'FacebookChannel28',
      MasterLabel = 'Facebook232',
      MessagingPlatformKey = '123',
      MessageType = 'Facebook'
    );
  }
  /*
           scenario : If the customer contacts after 24 hours once the chat ended, Old Case will be closed  with Case tag
           If in case, case is not tagged
        */
  public static testMethod void testAutoCloseCaseWithoutCaseTag() {
    List<Case> lstCases = FCS_TestDataFactory.createCases(1, null, null, null);
    lstCases[0].Origin = 'Facebook Messenger';
    lstCases[0].status = 'New';
    lstCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
    lstCases[0].FCS_Case_Reason__c = null;
    insert lstCases;

    MessagingChannel[] messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel28'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    Datetime lastRetentionDate = DateTime.newInstance(
      Date.today().addDays(-2),
      Time.newInstance(0, 0, 0, 0)
    );
    MessagingSession[] sessions = new List<MessagingSession>{};
    sessions.add(
      new MessagingSession(
        Origin = 'InboundInitiated',
        MessagingEndUserId = messagingEndUser1.Id,
        Status = 'Ended',
        caseid = lstCases[0].Id,
        MessagingChannelId = messagingChannel[0].Id,
        EndTime = lastRetentionDate
      )
    );

    insert sessions;
    FCS_CloseFBMessgerCaseAfter24hr_Batch fcsCloseFBMessgr = new FCS_CloseFBMessgerCaseAfter24hr_Batch();
    fcsCloseFBMessgr.setVariables('Case', 1, null, null, null, null);
    Test.StartTest();
    Database.executeBatch(fcsCloseFBMessgr);
    Test.StopTest();
    Case cse = [SELECT Id, Status FROM Case WHERE Id = :lstCases[0].Id];
    System.assertEquals('Closed', cse.Status);
  }
  /*
            scenario : If the customer contacts after 24 hours once the chat ended, Old Case will be closed  
         */
  public static testMethod void testAutoCloseCaseWithCaseTag() {
    List<Case> lstCases = FCS_TestDataFactory.createCases(1, null, null, null);

    lstCases[0].Origin = 'Facebook Messenger';
    lstCases[0].status = 'New';
    lstCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
    lstCases[0].Department__c = 'SoMe Support';
    lstCases[0].FCS_CaseType__c = 'Baggage';
    lstCases[0].FCS_Case_Reason__c = 'Allowance';
    lstCases[0].FCS_CaseResolution__c = 'Referred to phone';
    insert lstCases;

    MessagingChannel[] messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel28'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    Datetime lastRetentionDate = DateTime.newInstance(
      Date.today().addDays(-3),
      Time.newInstance(0, 0, 0, 0)
    );
    MessagingSession[] sessions = new List<MessagingSession>{};
    sessions.add(
      new MessagingSession(
        Origin = 'InboundInitiated',
        MessagingEndUserId = messagingEndUser1.Id,
        Status = 'Ended',
        caseid = lstCases[0].Id,
        MessagingChannelId = messagingChannel[0].Id,
        EndTime = lastRetentionDate
      )
    );
    insert sessions;
    FCS_CloseFBMessgerCaseAfter24hr_Batch fcsCloseFBMessgr = new FCS_CloseFBMessgerCaseAfter24hr_Batch();
    fcsCloseFBMessgr.setVariables('Case', 1, null, null, null, null);
    Test.StartTest();
    Database.executeBatch(fcsCloseFBMessgr);
    Test.StopTest();
    Case cse = [SELECT Id, Status FROM Case WHERE Id = :lstCases[0].Id];
    System.assertEquals('Closed', cse.Status);
  }
  /**
          If the customer contacts with in 24 hours then case will not be in closed
        */
  public static testMethod void testFBMessangerWithin24hours() {
    List<Case> lstCases = FCS_TestDataFactory.createCases(1, null, null, null);
    lstCases[0].Origin = 'Facebook Messenger';
    lstCases[0].status = 'New';
    lstCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
    insert lstCases;

    lstCases[0].FCS_CaseType__c = 'Baggage';
    lstCases[0].FCS_Case_Reason__c = 'Other';
    update lstCases;

    MessagingChannel[] messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel28'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    Datetime lastRetentionDate = DateTime.newInstance(
      Date.today(),
      Time.newInstance(0, 0, 0, 0)
    );
    MessagingSession[] sessions = new List<MessagingSession>{};
    sessions.add(
      new MessagingSession(
        Origin = 'InboundInitiated',
        MessagingEndUserId = messagingEndUser1.Id,
        Status = 'Ended',
        caseid = lstCases[0].Id,
        MessagingChannelId = messagingChannel[0].Id,
        EndTime = lastRetentionDate
      )
    );

    insert sessions;
    Test.StartTest();
    Database.executeBatch(new FCS_CloseFBMessgerCaseAfter24hr_Batch());
    Test.StopTest();
    Case cse = [SELECT Id, Status FROM Case WHERE Id = :lstCases[0].Id];
    System.assertEquals('New', cse.Status);
  }
  /**
          If the Agent not able to reply due to problem in Chat 
          then case will close after 24 hours
        */
  public static testMethod void testChatEndedDueToError() {
    List<Case> lstCases = FCS_TestDataFactory.createCases(1, null, null, null);
    lstCases[0].Origin = 'Facebook Messenger';
    lstCases[0].status = 'New';
    lstCases[0].FCS_CaseType__c = 'Error';
    lstCases[0].FCS_Case_Reason__c = 'Disconnected customer';
    lstCases[0].FCS_CaseResolution__c = 'Completed';
    lstCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
    insert lstCases;

    MessagingChannel[] messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel28'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    Datetime lastRetentionDate = DateTime.newInstance(
      Date.today().addDays(-2),
      Time.newInstance(0, 0, 0, 0)
    );
    MessagingSession[] sessions = new List<MessagingSession>{};
    sessions.add(
      new MessagingSession(
        Origin = 'InboundInitiated',
        MessagingEndUserId = messagingEndUser1.Id,
        Status = 'Active',
        caseid = lstCases[0].Id,
        MessagingChannelId = messagingChannel[0].Id,
        AcceptTime = lastRetentionDate
      )
    );

    insert sessions;
    FCS_CloseFBMessgerCaseAfter24hr_Batch fcsCloseFBMessgr = new FCS_CloseFBMessgerCaseAfter24hr_Batch();
    fcsCloseFBMessgr.setVariables('Case', 1, null, null, null, null);
    Test.StartTest();
    Database.executeBatch(fcsCloseFBMessgr);
    Test.StopTest();
    Case cse = [SELECT Id, Status FROM Case WHERE Id = :lstCases[0].Id];
    System.assertEquals('Closed', cse.Status);
  }
  /**
    If the Agent contact with in 24 hours then case will not be closed
  */
  public static testMethod void testFBMessangerActive() {
    List<Case> lstCases = FCS_TestDataFactory.createCases(1, null, null, null);
    lstCases[0].Origin = 'Facebook Messenger';
    lstCases[0].status = 'New';
    lstCases[0].FCS_Case_Reason__c = 'Disconnected customer';
    lstCases[0].FCS_CaseType__c = 'Error';
    lstCases[0].FCS_CaseResolution__c = 'Completed';
    lstCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
    insert lstCases;

    MessagingChannel[] messagingChannel = [
      SELECT Id
      FROM MessagingChannel
      WHERE DeveloperName = 'FacebookChannel28'
    ];
    MessagingEndUser messagingEndUser1 = new MessagingEndUser(
      MessagingChannelId = messagingChannel[0].Id,
      Name = 'User1',
      MessageType = 'Facebook',
      MessagingPlatformKey = '123'
    );
    insert messagingEndUser1;
    Datetime lastRetentionDate = DateTime.newInstance(
      Date.today(),
      Time.newInstance(0, 0, 0, 0)
    );
    MessagingSession[] sessions = new List<MessagingSession>{};
    sessions.add(
      new MessagingSession(
        Origin = 'InboundInitiated',
        MessagingEndUserId = messagingEndUser1.Id,
        Status = 'Active',
        caseid = lstCases[0].Id,
        MessagingChannelId = messagingChannel[0].Id,
        AcceptTime = lastRetentionDate
      )
    );

    insert sessions;
    Test.StartTest();
    Database.executeBatch(new FCS_CloseFBMessgerCaseAfter24hr_Batch());
    Test.StopTest();
    Case cse = [SELECT Id, Status FROM Case WHERE Id = :lstCases[0].Id];
    System.assertEquals('New', cse.Status);
  }
}