sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/IsEscalated__c.field-meta.xml
<CustomField>
    <fullName>IsEscalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether or not the case has been escalated using to other department action</description>
    <inlineHelpText>Indicates whether or not the case has been escalated using to other department action</inlineHelpText>
    <label>IsEscalated</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/IsRedirected__c.field-meta.xml
<CustomField>
    <fullName>IsRedirected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate that the case has been redirected to another department/team</description>
    <inlineHelpText>To indicate that the case has been redirected to another department/team</inlineHelpText>
    <label>IsRedirected</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team of the first case owner (that is a user)</description>
    <inlineHelpText>The team of the first case owner (that is a user)</inlineHelpText>
    <label>Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>Use for chat and facebook messanger</description>
    <label>Support</label>
</RecordType>

sas-core/main/default/objects/From_email_based_on_Dept_and_Teams__c/From_email_based_on_Dept_and_Teams__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>used to configure the from email address while replying to Case feed emails based on Department and Teams</description>
    <label>From email  based on Dept and Teams</label>
</CustomObject>

sas-core/main/default/objects/From_email_based_on_Dept_and_Teams__c/fields/From_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Email__c</fullName>
    <label>From_Email</label>
    <type>Email</type>
</CustomField>

sas-core/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team the User belongs to.</description>
    <inlineHelpText>The team the User belongs to.</inlineHelpText>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team 1</fullName>
            </value>
            <value>
                <fullName>Team 2</fullName>
            </value>
            <value>
                <fullName>Team 3</fullName>
            </value>
            <value>
                <fullName>Team 4</fullName>
            </value>
            <value>
                <fullName>Team 5</fullName>
            </value>
            <value>
                <fullName>Team 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/FCS_EmailPublisherAction_Test.cls
/**
 * @author Philip Ossler
 * @date 2020-04-14
 * @description Test class for FCS_EmailPublisherAction class
 */
@isTest
private class FCS_EmailPublisherAction_Test {
  // default address for redirected Cases
  @isTest
  static void defaultFromAddressforRedirctedCase() {
    From_email_based_on_Dept_and_Teams__c CSFromEmail = new From_email_based_on_Dept_and_Teams__c();
      CSFromEmail.Name = 'Group Sales-ACE';
      CSFromEmail.From_Email__c = 'groupsalestest@sas.se';
    insert CSFromEmail;

    List<Case> Cases = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      C_RecordTypeHelper.CASE_CHANNEL,
      null
    );
    cases[0].origin = 'Email - EuroBonus Name Change';
    insert Cases;

    // redirect the cases
    cases[0].IsRedirected__c = true;
    cases[0].Department__c = 'Group Sales';
    cases[0].Team__c = 'ACE';
    update cases;

    EmailMessage email = new EmailMessage();
    email.ToAddress = 'groupsalestest@sas.se';
    email.ParentId = cases[0].Id;
    insert email;

    //create QuickActionDefaults
    List<Map<String, Object>> defaultSettingAsObject = new List<Map<String, Object>>{
      new Map<String, Object>{
        'targetSObject' => new EmailMessage(),
        'contextId' => cases[0].Id,
        'actionType' => 'Email',
        'actionName' => 'Case.Email',
        'fromAddressList' => new List<String>{ email.ToAddress }
      }
    };

    List<QuickAction.SendEmailQuickActionDefaults> defaultsSettings = (List<QuickAction.SendEmailQuickActionDefaults>) JSON.deserialize(
      JSON.serialize(defaultSettingAsObject),
      List<QuickAction.SendEmailQuickActionDefaults>.class
    );
    Test.startTest();
    (new FCS_EmailPublisherAction()).onInitDefaults(defaultsSettings);
    Test.stopTest();

    System.assertEquals(
      CSFromEmail.From_Email__c,
      ((EmailMessage) defaultsSettings[0].getTargetSObject())
        .ValidatedFromAddress
    );
  }
  // user to default the from address if more than email-to-case present for escalated cases
  @isTest
  static void defaultFromAddressEscalatedCase() {
    From_email_based_on_Dept_and_Teams__c CSFromEmail = new From_email_based_on_Dept_and_Teams__c();
    CSFromEmail.Name = 'Corporate-Support International';
    CSFromEmail.From_Email__c = 'coporateinternationtest@sas.se';
    insert CSFromEmail;

    List<Case> Cases = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      C_RecordTypeHelper.CASE_CHANNEL,
      null
    );
    cases[0].origin = 'Email - Pandion DK';
    insert Cases;

    // Escalate the cases
    cases[0].IsEscalated__c = true;
    cases[0].status = 'Escalated';
    cases[0].Department__c = 'Corporate';
    cases[0].Team__c = 'Support International';
    update cases;

    EmailMessage email = new EmailMessage();
    email.ToAddress = 'coporateinternationtest@sas.se';
    email.ParentId = cases[0].Id;
    insert email;

    //create QuickActionDefaults
    List<Map<String, Object>> defaultSettingAsObject = new List<Map<String, Object>>{
      new Map<String, Object>{
        'targetSObject' => new EmailMessage(),
        'contextId' => cases[0].Id,
        'actionType' => 'Email',
        'actionName' => 'Case.Email',
        'fromAddressList' => new List<String>{ email.ToAddress }
      }
    };

    List<QuickAction.SendEmailQuickActionDefaults> defaultsSettings = (List<QuickAction.SendEmailQuickActionDefaults>) JSON.deserialize(
      JSON.serialize(defaultSettingAsObject),
      List<QuickAction.SendEmailQuickActionDefaults>.class
    );
    Test.startTest();
    (new FCS_EmailPublisherAction()).onInitDefaults(defaultsSettings);
    Test.stopTest();

    System.assertEquals(
      CSFromEmail.From_Email__c,
      ((EmailMessage) defaultsSettings[0].getTargetSObject())
        .ValidatedFromAddress
    );
  }
}