sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseResolution__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseResolution__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_Case_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>According to rules</fullName>
            </value>
            <value>
                <fullName>Acquirer</fullName>
            </value>
            <value>
                <fullName>Activate Profile</fullName>
            </value>
            <value>
                <fullName>Add travel pass</fullName>
            </value>
            <value>
                <fullName>Agreement related question</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Authorities</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>AVIH/PETC</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Big/Supersale</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
            <value>
                <fullName>Booking flow</fullName>
            </value>
            <value>
                <fullName>Booking related</fullName>
            </value>
            <value>
                <fullName>Booking rules</fullName>
            </value>
            <value>
                <fullName>Bug/User story created</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>CC Update</fullName>
            </value>
            <value>
                <fullName>Changed dates</fullName>
            </value>
            <value>
                <fullName>Changed destination</fullName>
            </value>
            <value>
                <fullName>Changed email</fullName>
            </value>
            <value>
                <fullName>Changed name</fullName>
            </value>
            <value>
                <fullName>Changed phone number</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/FCS_CaseTag__c/FCS_CaseTag__c.object-meta.xml
<CustomObject>
    <description>Object used to store records about case reason to be able to report on multiple reasons</description>
    <label>Case Tag</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CaseReason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseId__c</fullName>
    <description>The id of the case that the tag belong to</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Tags</relationshipLabel>
    <relationshipName>Case_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseTag__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseTag__c</fullName>
    <description>The tag for why the customer was contacting customer support</description>
    <label>Case Tag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Conditions of carriage</fullName>
            </value>
            <value>
                <fullName>Contacts-Country</fullName>
            </value>
            <value>
                <fullName>Contacts-partners</fullName>
            </value>
            <value>
                <fullName>Contacts R</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Corporate product</fullName>
            </value>
            <value>
                <fullName>Corporate R</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>CR requests</fullName>
            </value>
            <value>
                <fullName>Customer Care R</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged baggage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/FCS_CaseTag_Controller_Test.cls
@isTest
public class FCS_CaseTag_Controller_Test {
  @TestSetup
  static void testDataSetUP() {
    List<Case> newCases = FCS_TestDataFactory.createCases(
      1,
      null,
      null,
      null,
      null
    );
    newCases[0].Subject = 'TestCase 2';
    newCases[0].RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL;
    insert newCases;
    LiveChatVisitor lcv = new LiveChatVisitor();
    insert lcv;
    LiveChatTranscript lct = new LiveChatTranscript();
    lct.LiveChatVisitorId = lcv.Id;
    lct.caseId = newcases[0].Id;
    insert lct;
  }

  static testMethod void testCaseTag() {
    List<Case> lstnewCases = [
      SELECT Id, FCS_Case_Reason__c, Department__c, FCS_CaseType__c
      FROM Case
    ];
    Case cse = new Case(
      Id = lstnewCases[0].Id,
      Department__c = 'Fraud',
      FCS_CaseType__c = 'Fraud',
      FCS_Case_Reason__c = 'CAR',
      FCS_CaseResolution__c = 'Completed'
    );
    update cse;

    LiveChatTranscript chatTrans = [
      SELECT Id, caseId
      FROM LiveChatTranscript
      LIMIT 1
    ];
    Test.startTest();
    FCS_CaseTag__c caseTag = FCS_CaseTag_Controller.findCaseTag(cse.Id);
    System.AssertEquals(caseTag.FCS_CaseId__c, cse.Id);

    FCS_CaseTag__c chatTransCaseTag = FCS_CaseTag_Controller.findCaseTag(
      chatTrans.Id
    );
    System.AssertEquals(chatTransCaseTag.FCS_CaseId__c, chatTrans.CaseId);

    Test.stopTest();
  }
  static testMethod void testfindcase() {
    LiveChatTranscript chatTrans = [
      SELECT Id, caseId
      FROM LiveChatTranscript
      LIMIT 1
    ];
    Test.startTest();

    Case cse = FCS_CaseTag_Controller.findCase(chatTrans.Id);
    System.AssertEquals(cse.Id, chatTrans.CaseId);

    Test.stopTest();
  }
}