sas-core/main/default/objects/Case/fields/FCS_CaseReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseReason__c</fullName>
    <complianceGroup>PIIExtract;WipeRetain</complianceGroup>
    <description>Second level categorization for cases.</description>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 day refund guarantee</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Award travel</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Service</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Bank Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Boozt Attack</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseSubReason__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseSubReason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <description>Third level categorization for cases.</description>
    <label>Case Sub-reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseReason__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add EB in booking</fullName>
            </value>
            <value>
                <fullName>Add infant in booking</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Groups</fullName>
            </value>
            <value>
                <fullName>Agent - Agreement related Question</fullName>
            </value>
            <value>
                <fullName>Agent - Other</fullName>
            </value>
            <value>
                <fullName>Agent - TravelPass</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Booking</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass CC update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Contact Update</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Receipt</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Sell</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass Statistics</fullName>
            </value>
            <value>
                <fullName>Agent - Travel Pass wrong deb</fullName>
            </value>
            <value>
                <fullName>Agreement related question*</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airport service locations</fullName>
            </value>
            <value>
                <fullName>Allergies</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>Alternatives</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX 2 for 1</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Ancillary error</fullName>
            </value>
            <value>
                <fullName>Arrival information</fullName>
            </value>
            <value>
                <fullName>ATC refund flow</fullName>
            </value>
            <value>
                <fullName>Author</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseTags__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseTags__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Additional Case Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Conditions of carriage</fullName>
            </value>
            <value>
                <fullName>Contacts-Country</fullName>
            </value>
            <value>
                <fullName>Contacts-partners</fullName>
            </value>
            <value>
                <fullName>Contacts R</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Corporate product</fullName>
            </value>
            <value>
                <fullName>Corporate R</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>CR requests</fullName>
            </value>
            <value>
                <fullName>Customer Care R</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged luggage</fullName>
                <label>Delayed/damaged baggage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/ManagedSocialAccounts__mdt.object-meta.xml
<CustomObject>
    <description>Setting used to identify weather the post/tweet had been posted by SAS or by other account</description>
    <label>Managed Social Account</label>
    <pluralLabel>Managed Social Accounts</pluralLabel>
</CustomObject>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the social account corresponding to the Social Handle</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Represents the provider of the page which name is represented in Name field</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_CaseCreated__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post has a case created from it</description>
    <label>Case Created</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>FCS_ClosedDate__c</fullName>
    <description>The date when the social post was marked as done</description>
    <inlineHelpText>The date when the social post was marked as done</inlineHelpText>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Done__c.field-meta.xml
<CustomField>
    <fullName>FCS_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post fulfills the criteria of being handled</description>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostHidden__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostHidden__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is hidden from its source e.g Facebook or Twitter</description>
    <inlineHelpText>Checked if the post is hidden from its source e.g Facebook or Twitter</inlineHelpText>
    <label>Hidden</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostIgnored__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostIgnored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the action taken on the post is ignore</description>
    <label>Ignored</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostLiked__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostLiked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is liked from SF e.g Facebook or Twitter</description>
    <label>Liked</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_PostReplied__c.field-meta.xml
<CustomField>
    <fullName>FCS_PostReplied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is replied to from SF to  e.g Facebook or Twitter</description>
    <label>Replied</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_Reopened__c.field-meta.xml
<CustomField>
    <fullName>FCS_Reopened__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marked true if the social post is reopened</description>
    <inlineHelpText>Marked true if the social post is reopened</inlineHelpText>
    <label>Reopened</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/FCS_SASPost__c.field-meta.xml
<CustomField>
    <fullName>FCS_SASPost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is posted by SAS</description>
    <label>SAS Post</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/FCS_SocialPostHandler_Test.cls
/**
* @author Sanna Sörberg
* @date 2019-12-20
* @description Test class for social post handler which includes operations performed on social posts
*/

@isTest
private class FCS_SocialPostHandler_Test {

/**
Test method for generation of test data used in more than one method
*/
    @TestSetup static void createTestData() {
        List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(4);
        insert socialPosts;
        List<Case> newCases = FCS_TestDataFactory.createCases(1, null, null, null, null);
        newCases[0].FCS_CaseReason__c = 'TestReason 1';
        newCases[0].Subject = 'TestCase 2';
        newCases[0].FCS_CaseSubReason__c = 'TestSubReason 1';
        newCases[0].FCS_CaseTags__c = 'CommonTestTag1;CommonTestTag2';
        insert newCases;
    }

    /**
    Test method to test to that status fields and checkboxes are updated when hiding/unhiding an post
     */
    @isTest static void testHideAndUnhidePost() {
        SocialPost sp = [SELECT Id, FCS_PostHidden__c FROM SocialPost LIMIT 1];
        sp.Status= FCS_SocialPostHandler.STATUS_HIDDEN;
        update sp;
        SocialPost hiddenSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_ClosedDate__c, FCS_Reopened__c FROM SocialPost LIMIT 1];
        system.assertEquals(true, hiddenSp.FCS_PostHidden__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_REVIEWED, hiddenSp.ReviewedStatus);
        system.assertEquals(true, hiddenSp.FCS_Done__c);
        system.assertEquals(false, hiddenSp.FCS_PostReplied__c);
        system.assertEquals(false, hiddenSp.FCS_PostIgnored__c);
        system.assertEquals(false, hiddenSp.FCS_PostLiked__c);
        system.assertEquals(true, hiddenSp.FCS_ClosedDate__c < system.now().addSeconds(10) && hiddenSp.FCS_ClosedDate__c > system.now().addSeconds(-10));
        system.assertEquals(false, hiddenSp.FCS_Reopened__c);
        hiddenSp.Status=null;
        update hiddenSp;
        SocialPost unhiddenSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_ClosedDate__c, FCS_Reopened__c FROM SocialPost LIMIT 1];
        system.assertEquals(false, unhiddenSp.FCS_PostHidden__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_NEEDED, unhiddenSp.ReviewedStatus);
        system.assertEquals(false, unhiddenSp.FCS_Done__c);
        system.assertEquals(false, unhiddenSp.FCS_PostReplied__c);
        system.assertEquals(false, unhiddenSp.FCS_PostIgnored__c);
        system.assertEquals(false, unhiddenSp.FCS_PostLiked__c);
        system.assertEquals(null, unhiddenSp.FCS_ClosedDate__c);
        system.assertEquals(true, unhiddenSp.FCS_Reopened__c);
    }

    /**
   Test method to test to that status fields and checkboxes are updated when ignoring a post
    */
    @isTest static void testIgnorePost() {
        SocialPost sp = [SELECT Id, FCS_PostIgnored__c FROM SocialPost LIMIT 1];
        sp.ReviewedStatus= FCS_SocialPostHandler.STATUS_IGNORE;
        update sp;
        SocialPost ignoredSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_ClosedDate__c, FCS_Reopened__c FROM SocialPost LIMIT 1];
        system.assertEquals(false, ignoredSp.FCS_PostHidden__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_REVIEWED, ignoredSp.ReviewedStatus);
        system.assertEquals(true, ignoredSp.FCS_Done__c);
        system.assertEquals(false, ignoredSp.FCS_PostReplied__c);
        system.assertEquals(true, ignoredSp.FCS_PostIgnored__c);
        system.assertEquals(false, ignoredSp.FCS_PostLiked__c);
        system.assertEquals(true, ignoredSp.FCS_ClosedDate__c < system.now().addSeconds(10) && ignoredSp.FCS_ClosedDate__c > system.now().addSeconds(-10));
        system.assertEquals(false, ignoredSp.FCS_Reopened__c);
    }



    /**
   Test method to test to that status fields and checkboxes are updated when liking a post
    */
    @isTest static void testLikePost() {
        SocialPost sp = [SELECT Id FROM SocialPost LIMIT 1];
        sp.Recipient='Test1';
        sp.LikedBy='Test1';
        update sp;
        SocialPost likedSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_ClosedDate__c, FCS_Reopened__c FROM SocialPost LIMIT 1];
        system.assertEquals(false, likedSp.FCS_PostHidden__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_REVIEWED, likedSp.ReviewedStatus);
        system.assertEquals(true, likedSp.FCS_Done__c);
        system.assertEquals(false, likedSp.FCS_PostReplied__c);
        system.assertEquals(false, likedSp.FCS_PostIgnored__c);
        system.assertEquals(true, likedSp.FCS_PostLiked__c);
        system.assertEquals(true, likedSp.FCS_ClosedDate__c < system.now().addSeconds(10) && likedSp.FCS_ClosedDate__c > system.now().addSeconds(-10));
        system.assertEquals(false, likedSp.FCS_Reopened__c);
    }

    /**
   Test method to test to that parent post is updated with correct status when replying
    */
    @isTest static void replyToPost() {
        SocialPost replyToSp = [SELECT Id FROM SocialPost LIMIT 1];
        List<SocialPost> spList = FCS_TestDataFactory.createSocialPosts(1);
        spList[0].ReplyToId=replyToSp.Id;
        spList[0].IsOutbound=true;
        insert spList;
        SocialPost repliedSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_ClosedDate__c FROM SocialPost WHERE Id=:replyToSp.Id LIMIT 1];
        system.assertEquals(false, repliedSp.FCS_PostHidden__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_REVIEWED, repliedSp.ReviewedStatus);
        system.assertEquals(true, repliedSp.FCS_Done__c);
        system.assertEquals(true, repliedSp.FCS_PostReplied__c);
        system.assertEquals(false, repliedSp.FCS_PostIgnored__c);
        system.assertEquals(false, repliedSp.FCS_PostLiked__c);
        system.assertEquals(true, repliedSp.FCS_ClosedDate__c < system.now().addSeconds(10) && repliedSp.FCS_ClosedDate__c > system.now().addSeconds(-10));
    }

    /**
  Test method to test to that status fields and checkboxes are updated when deleting the parent case
   */
    @isTest static void testDeleteParentCase() {
        List<SocialPost> socialPosts = [SELECT Id FROM SocialPost];
        List<User> users = [SELECT Id FROM User];
        for (Integer i = 0, sz = socialPosts.size(); i < sz; i++) {
            socialPosts[i].OwnerId=users[i].Id;
        }
        List<Case> newCase = FCS_TestDataFactory.createCases(1, null, null, null, null);
        newCase[0].FCS_CaseReason__c = 'TestReason 12';
        newCase[0].FCS_CaseSubReason__c = 'TestSubReason 12';
        newCase[0].FCS_CaseTags__c = 'TestTag12;TestTag22';
        newCase[0].Subject = 'TestCase12';
        newCase[0].Status = 'New';
        newCase[0].SourceId = socialPosts[0].Id;
        insert newCase;
        System.AssertEquals(true, [SELECT Id, FCS_CaseCreated__c FROM SocialPost WHERE Id =:newCase[0].SourceId][0].FCS_CaseCreated__c);
        SocialPost sp = [SELECT Id, FCS_CaseCreated__c, ParentId FROM SocialPost LIMIT 1];
        sp.ParentId=null;
        update sp;
        SocialPost parentDeletedSp = [SELECT Id, FCS_PostHidden__c , ReviewedStatus, FCS_Done__c, FCS_PostReplied__c, FCS_PostIgnored__c, FCS_PostLiked__c, FCS_CaseCreated__c, FCS_ClosedDate__c, FCS_Reopened__c FROM SocialPost LIMIT 1];
        system.assertEquals(false, parentDeletedSp.FCS_PostHidden__c);
        system.assertEquals(false, parentDeletedSp.FCS_CaseCreated__c);
        system.assertEquals(FCS_SocialPostHandler.STATUS_NEEDED, parentDeletedSp.ReviewedStatus);
        system.assertEquals(false, parentDeletedSp.FCS_Done__c);
        system.assertEquals(false, parentDeletedSp.FCS_PostReplied__c);
        system.assertEquals(false, parentDeletedSp.FCS_PostIgnored__c);
        system.assertEquals(false, parentDeletedSp.FCS_PostLiked__c);
        system.assertEquals(null, parentDeletedSp.FCS_ClosedDate__c);
        system.assertEquals(true, parentDeletedSp.FCS_Reopened__c);
    }


    /**
    Test method to test to that posts posted from SAS-own site is set with the correct statuses
    */
    @isTest static void insertSASPost() {
        List<ManagedSocialAccounts__mdt> socialAccs = [SELECT Id, DeveloperName, Name__c, Provider__c From ManagedSocialAccounts__mdt];
        List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(1);
        socialPosts[0].MessageType = 'Post';
        socialPosts[0].Provider = socialAccs[0].Provider__c;
        socialPosts[0].Handle = socialAccs[0].Name__c;
        insert socialPosts;
        List<SocialPost> updatedSocialPosts = [SELECT Id, IsOutbound, FCS_SASPost__c, ReviewedStatus FROM SocialPost WHERE Provider=:socialAccs[0].Provider__c AND Handle=: socialPosts[0].Handle];
        system.assertEquals(true, updatedSocialPosts[0].IsOutbound);
        system.assertEquals(true,  updatedSocialPosts[0].FCS_SASPost__c);
        system.assertEquals(null, updatedSocialPosts[0].ReviewedStatus);
    }

/**
   Test method to test to that post inserted never gets attached to a case
   */
    @isTest static void insertCustomerPost() {
        List<SocialPost> socialPosts = FCS_TestDataFactory.createSocialPosts(1);
        socialPosts[0].MessageType = 'Post';
        socialPosts[0].Headline = 'TestPost1';
        socialPosts[0].ParentId = [SELECT Id From Case Limit 1].Id;
        insert socialPosts;
        List<SocialPost> updatedSocialPosts = [SELECT Id, ParentId, ReviewedStatus FROM SocialPost WHERE Headline = 'TestPost1'];
        system.assertEquals(null, updatedSocialPosts[0].ParentId);
        system.assertEquals(FCS_SocialPostHandler.STATUS_NEEDED,  updatedSocialPosts[0].ReviewedStatus);
    }
}