sas-core/main/default/objects/Case/fields/FCS_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>FCS_Case_Reason__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access rights</fullName>
            </value>
            <value>
                <fullName>Add Animals</fullName>
            </value>
            <value>
                <fullName>Add Baggage</fullName>
            </value>
            <value>
                <fullName>Add Bike</fullName>
            </value>
            <value>
                <fullName>Add Biofuel</fullName>
            </value>
            <value>
                <fullName>Add EB in Booking</fullName>
            </value>
            <value>
                <fullName>Add Golfbag</fullName>
            </value>
            <value>
                <fullName>Add Infant in Booking</fullName>
            </value>
            <value>
                <fullName>Add Meals</fullName>
            </value>
            <value>
                <fullName>Add Musical Instrument</fullName>
            </value>
            <value>
                <fullName>Add Seating</fullName>
            </value>
            <value>
                <fullName>Add Skis</fullName>
            </value>
            <value>
                <fullName>Add Special Assistance</fullName>
            </value>
            <value>
                <fullName>Add weapon</fullName>
            </value>
            <value>
                <fullName>Add Wheelchair</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>AliPay</fullName>
            </value>
            <value>
                <fullName>Allowance</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Arrival info</fullName>
            </value>
            <value>
                <fullName>Assist with check-in</fullName>
            </value>
            <value>
                <fullName>ATO Account Takeover</fullName>
            </value>
            <value>
                <fullName>Availability/Inquiry</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage Content</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_CaseType__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseType__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Error Handling</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>EuroBonus Partner</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Irregularities</fullName>
            </value>
            <value>
                <fullName>New Booking</fullName>
            </value>
            <value>
                <fullName>Non-SAS Products</fullName>
            </value>
            <value>
                <fullName>Plusgrade</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Receive Customer Documentation</fullName>
            </value>
            <value>
                <fullName>Refund Handling</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAS for Business</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Special Service Request</fullName>
            </value>
            <value>
                <fullName>Ticketless</fullName>
            </value>
            <value>
                <fullName>Travel Information</fullName>
            </value>
            <value>
                <fullName>Travel Pass</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Voucher Handling</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/MessagingSessions.cls
public without sharing class MessagingSessions extends ApplicationDomain {
  public MessagingSessions(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<MessagingSession>) Records;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new MessagingSessions(records);
    }
  }

  private List<MessagingSession> instanceRecords;

  public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    createCasesForMessagingSessions();
  }

  /**
   * Used to create cases for inbound MessageSessions. Only creates a new case if a case is not supplied in insert.
   */
  private void createCasesForMessagingSessions() {
    DateTime lastRetentionDate = DateTime.newInstance(
      Date.today().addDays(-1),
      Time.newInstance(0, 0, 0, 0)
    );

    List<String> lstChannelEndUserKey = new List<String>();
    List<Case> casesToInsert = new List<Case>();
    Boolean oldCaseClosed = false;
    Set<Id> messagingEndUserIds = new Set<Id>();
    for (MessagingSession s : instanceRecords) {
      messagingEndUserIds.add(s.MessagingEndUserId);
      lstChannelEndUserKey.add(s.ChannelEndUserFormula);
    }
    List<MessagingSession> lstMessingSesions = new List<MessagingSession>(
      [
        SELECT Id, CaseId, Case.status, ChannelEndUserFormula, EndTime
        FROM MessagingSession
        WHERE
          ChannelEndUserFormula = :lstChannelEndUserKey[0]
          AND status != 'Active'
          AND status != 'Waiting'
          AND CaseId != ''
        ORDER BY EndTime DESC
        LIMIT 1
      ]
    );
    Map<Id, MessagingEndUser> meuMap = new Map<Id, MessagingEndUser>(
      [
        SELECT Id, AccountId, ContactId
        FROM MessagingEndUser
        WHERE Id IN :messagingEndUserIds
      ]
    );
    Case cse;
    if (!lstMessingSesions.isEmpty()) {
      cse = [
        SELECT
          FCS_Case_Reason__c,
          FCS_CaseType__c,
          RecordTypeId,
          Type,
          Subject,
          Description,
          AccountId,
          ContactId
        FROM Case
        WHERE Id = :lstMessingSesions[0].CaseId
        LIMIT 1
      ];
    }
    for (MessagingSession session : instanceRecords) {
      if (!lstMessingSesions.isEmpty()) {
        if (
          session.CaseId == null &&
          session.Status == 'Active' &&
          session.Origin == 'InboundInitiated'
        ) {
          if (lstMessingSesions[0].Case.Status != 'Closed') {
            session.CaseId = lstMessingSesions[0].CaseId;
            casesToInsert.add(
              new Case(
                Id = lstMessingSesions[0].CaseId,
                Status = 'New Response'
              )
            );
          } else if (
            lstMessingSesions[0].Case.Status == 'Closed' &&
            lstMessingSesions[0].EndTime > lastRetentionDate
          ) {
            session.CaseId = lstMessingSesions[0].CaseId;
            casesToInsert.add(
              new Case(
                Id = lstMessingSesions[0].CaseId,
                Status = 'New Response'
              )
            );
          } else {
            oldCaseClosed = true;
            Case cCloneCase = cse.clone(false, false, false, false);
            cCloneCase.RecordTypeId = C_RecordTypeHelper.CASE_CHAT;
            cCloneCase.Origin = 'Facebook Messenger';
            casesToInsert.add(cCloneCase);
          }
        }
      } else {
        if (
          session.CaseId == null &&
          session.Status == 'Active' &&
          session.Origin == 'InboundInitiated'
        ) {
          oldCaseClosed = true;
          casesToInsert.add(
            new Case(
              Status = 'New',
              Origin = 'Facebook Messenger',
              RecordTypeId = C_RecordTypeHelper.CASE_CHAT,
              AccountId = meuMap.get(session.MessagingEndUserId).AccountId,
              ContactId = meuMap.get(session.MessagingEndUserId).ContactId
            )
          );
        }
      }
    }
    if (!casesToInsert.IsEmpty()) {
      upsert casesToInsert;
    }
    if (oldCaseClosed)
      for (Integer i = 0; i < instanceRecords.size(); i++) {
        if (
          instanceRecords[i].CaseId == null &&
          instanceRecords[i].Status == 'Active' &&
          instanceRecords[i].Origin == 'InboundInitiated'
        ) {
          instanceRecords[i].CaseId = casesToInsert[i].Id;
        }
      }
  }
}