sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/Flight_Delay_Certificate_Request__c.object-meta.xml
<CustomObject>
    <description>Object to store information about a request. Used to generate the actual Flight Delay Certificate as a PDF</description>
    <label>Flight Delay Certificate Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Flight Delay Certificate Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Delay Certificate Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flight Delay Certificate Requests</relationshipLabel>
    <relationshipName>Flight_Delay_Certificate_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Full_Name__c</fullName>
    <formula>Contact_First_Name__c  &amp; &apos; &apos;  &amp;  Contact_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Full Name</label>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight_Delay_Certificate_Request__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/FlightDelayCertificateRequestsSelector.cls
public with sharing class FlightDelayCertificateRequestsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Flight_Delay_Certificate_Request__c.Id,
      Flight_Delay_Certificate_Request__c.Booking_Reference__c,
      Flight_Delay_Certificate_Request__c.Case__c,
      Flight_Delay_Certificate_Request__c.Contact_First_Name__c,
      Flight_Delay_Certificate_Request__c.Contact_Last_Name__c,
      Flight_Delay_Certificate_Request__c.Contact_Full_Name__c,
      Flight_Delay_Certificate_Request__c.Flight_Number__c,
      Flight_Delay_Certificate_Request__c.Flight_Date__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Flight_Delay_Certificate_Request__c.SObjectType;
  }

  public static FlightDelayCertificateRequestsSelector newInstance() {
    return (FlightDelayCertificateRequestsSelector) SAS_Service_Application.Selector.newInstance(
      Flight_Delay_Certificate_Request__c.SObjectType
    );
  }

  public List<Flight_Delay_Certificate_Request__c> selectById(Set<Id> ids) {
    return (List<Flight_Delay_Certificate_Request__c>) selectSObjectsById(ids);
  }
  public List<Flight_Delay_Certificate_Request__c> selectByIdFull(Set<Id> ids) {
    fflib_QueryFactory fdcrQF = newQueryFactory().setCondition('Id in :ids');
    CasesSelector.newInstance().configureQueryFactoryFields(fdcrQF, 'Case__r');
    return (List<Flight_Delay_Certificate_Request__c>) Database.query(
      fdcrQF.toSOQL()
    );
  }
}