sas-core/main/default/objects/Case/fields/Group_Travel_Request__c.field-meta.xml
<CustomField>
    <fullName>Group_Travel_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>for relating the case with Group travel request</description>
    <label>Group Travel Request</label>
    <referenceTo>Group_Travel_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Group_Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Group Travel Request</label>
    <nameField>
        <label>Group Travel Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Alternate_Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Departure_date__c</fullName>
    <label>Alternate Departure date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Alternate_Departure_time__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Departure_time__c</fullName>
    <label>Alternate Departure time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Midmorning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Alternate_Return_date__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Return_date__c</fullName>
    <label>Alternate Return date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Alternate_Return_time__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Return_Time__c</fullName>
    <label>Alternate Return Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Midmorning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Alternative_Dates__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Dates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alternative Dates</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/C_o_Address__c.field-meta.xml
<CustomField>
    <fullName>C_o_Address__c</fullName>
    <label>C/o Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Comments_From_Customer__c.field-meta.xml
<CustomField>
    <fullName>Comments_From_Customer__c</fullName>
    <label>Comments From Customer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <label>Departure date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Departure_time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Time__c</fullName>
    <label>Departure Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Midmorning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Different_Return_City_Airport__c.field-meta.xml
<CustomField>
    <fullName>Different_Return_City_Airport__c</fullName>
    <label>Different Return City Airport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Extra_Bags__c.field-meta.xml
<CustomField>
    <fullName>Extra_Bags__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extra Bags</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Form_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Form_of_payment__c</fullName>
    <label>Form of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>SAS Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/From_Airport__c.field-meta.xml
<CustomField>
    <fullName>From_Airport__c</fullName>
    <label>From Airport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Youth</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/have_company_Code__c.field-meta.xml
<CustomField>
    <fullName>have_company_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>have company Code</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Invoice_agreement_with_SAS__c.field-meta.xml
<CustomField>
    <fullName>Invoice_agreement_with_SAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice agreement with SAS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Adults__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Adults__c</fullName>
    <label>Number Of Adults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Children__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Children__c</fullName>
    <label>Number Of Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Extra_Bags__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Extra_Bags__c</fullName>
    <label>Number Of Extra Bags</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Infants__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Infants__c</fullName>
    <label>Number Of Infants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Special_Baggage__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Special_Baggage__c</fullName>
    <label>Number Of Special Baggage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Travellers__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Travellers__c</fullName>
    <label>Number Of Travellers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Number_Of_Wheelchairs__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Wheelchairs__c</fullName>
    <label>Number Of Wheelchairs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Other_destinations_of_interest__c.field-meta.xml
<CustomField>
    <fullName>Other_destinations_of_interest__c</fullName>
    <label>Other destinations of interest</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Propose_alternative_destinations__c.field-meta.xml
<CustomField>
    <fullName>Propose_alternative_destinations__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Propose alternative destinations</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Return_date__c.field-meta.xml
<CustomField>
    <fullName>Return_date__c</fullName>
    <label>Return date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Return_time__c.field-meta.xml
<CustomField>
    <fullName>Return_time__c</fullName>
    <label>Return time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Midmorning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Special_Baggage__c.field-meta.xml
<CustomField>
    <fullName>Special_Baggage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Baggage</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Special_Baggage_Note__c.field-meta.xml
<CustomField>
    <fullName>Special_Baggage_Note__c</fullName>
    <label>Special Baggage Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/To_Airport__c.field-meta.xml
<CustomField>
    <fullName>To_Airport__c</fullName>
    <label>To Airport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Travel_Class__c.field-meta.xml
<CustomField>
    <fullName>Travel_Class__c</fullName>
    <label>Travel Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS Go</fullName>
            </value>
            <value>
                <fullName>SAS Plus</fullName>
            </value>
            <value>
                <fullName>SAS Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One way</fullName>
            </value>
            <value>
                <fullName>Round Trip</fullName>
            </value>
            <value>
                <fullName>Return From Another City</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Visual_or_hearing_assistance__c.field-meta.xml
<CustomField>
    <fullName>Visual_or_hearing_assistance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visual or hearing assistance</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Group_Travel_Request__c/fields/Wheelchairs__c.field-meta.xml
<CustomField>
    <fullName>Wheelchairs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wheelchairs</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/services/GroupTravelService.cls
public class GroupTravelService {
  private static Map<String, String> marketToOrigin = new Map<String, String>{
    'dk-da' => 'Form - Group Travel DK',
    'no-no' => 'Form - Group Travel NO',
    'se-sv' => 'Form - Group Travel SE',
    'be-en' => 'Form - Group Travel BE',
    'fi-en' => 'Form - Group Travel FI',
    'fr-fr' => 'Form - Group Travel FR',
    'de-de' => 'Form - Group Travel DE',
    'ie-en' => 'Form - Group Travel IE',
    'it-en' => 'Form - Group Travel IT',
    'nl-en' => 'Form - Group Travel NL',
    'pl-en' => 'Form - Group Travel PL',
    'ru-ru' => 'Form - Group Travel RU',
    'es-es' => 'Form - Group Travel ES',
    'ch-de' => 'Form - Group Travel CH-de',
    'ch-fr' => 'Form - Group Travel CH-fr',
    'gb-en' => 'Form - Group Travel GB',
    'us-en' => 'Form - Group Travel US',
    'lu-en' => 'Form - Group Travel LU',
    'default' => 'Form - Group Travel GB'
  };

  public static String createGroupTravelForm(
    GroupTravelJsonToApex groupTravelForm
  ) {
    Case cse;
    try {
      GroupTravelJsonToApex.FormData travelRequest = groupTravelForm.formData;
      Group_Travel_Request__c grpTravelRequest = createGroupTravelRequestInstance(
        travelRequest
      );

      insert grpTravelRequest;

      String caseOrigin = marketToOrigin.get('default');

      if (marketToOrigin.get(groupTravelForm.metaData.market) != null) {
        caseOrigin = marketToOrigin.get(groupTravelForm.metaData.market);
      }

      cse = new Case(
        Origin = caseOrigin,
        RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL,
        Subject = 'Group Travel Request: ' + travelRequest.groupName,
        SuppliedEmail = travelRequest.email,
        SuppliedPhone = travelRequest.phone
      );

      insert cse;
    } catch (Exception e) {
      C_Log.logException(e, 'GroupTravelRequest', null);
      return e.getMessage();
    }

    return cse.Id;
  }
  static Group_Travel_Request__c createGroupTravelRequestInstance(
    GroupTravelJsonToApex.FormData travelRequest
  ) {
    Group_Travel_Request__c grpTravelRequest = new Group_Travel_Request__c();

    grpTravelRequest.Name = travelRequest.groupName;
    grpTravelRequest.From_Airport__c = travelRequest.fromAirport;
    grpTravelRequest.To_Airport__c = travelRequest.ToAirport;
    grpTravelRequest.Departure_time__c = travelRequest.departureTime;
    grpTravelRequest.Departure_date__c = Date.valueOf(
      travelRequest.departureDate
    );
    grpTravelRequest.Return_date__c = Date.valueOf(travelRequest.returndate);
    grpTravelRequest.Return_time__c = travelRequest.returnTime;

    grpTravelRequest.Email__c = travelRequest.email;
    grpTravelRequest.Phone__c = travelRequest.phone;
    grpTravelRequest.First_Name__c = travelRequest.firstName;
    grpTravelRequest.Last_Name__c = travelRequest.lastName;
    grpTravelRequest.Address__c = travelRequest.address;
    grpTravelRequest.C_o_Address__c = travelRequest.coAddress;
    grpTravelRequest.City__c = travelRequest.city;
    grpTravelRequest.Postal_Code__c = travelRequest.postalCode;
    grpTravelRequest.Country__c = travelRequest.country;

    grpTravelRequest.Number_Of_Adults__c = travelRequest.numberOfAdults;
    grpTravelRequest.Number_Of_Children__c = travelRequest.numberOfChildren;
    grpTravelRequest.Number_Of_Infants__c = travelRequest.numberOfInfants;

    grpTravelRequest.Invoice_agreement_with_SAS__c = travelRequest.invoiceAgreementWithSAS;
    grpTravelRequest.Travel_Class__c = travelRequest.travelClass;
    grpTravelRequest.Form_of_payment__c = travelRequest.formOfPayment;
    grpTravelRequest.Comments_From_Customer__c = travelRequest.comments;
    grpTravelRequest.Group_Type__c = travelRequest.groupType;

    if (travelRequest.haveCompanyCode) {
      grpTravelRequest.Have_Company_Code__c = travelRequest.haveCompanyCode;
      grpTravelRequest.Company_Code__c = travelRequest.companyCode;
    }
    if (travelRequest.alternativeDates) {
      grpTravelRequest.Alternate_Departure_date__c = Date.valueOf(
        travelRequest.alternateDepartureDate
      );
      grpTravelRequest.Alternate_Return_date__c = Date.valueOf(
        travelRequest.alternateReturnDate
      );
      grpTravelRequest.Alternate_Return_time__c = travelRequest.alternateReturnTime;
      grpTravelRequest.Alternate_Departure_time__c = travelRequest.alternateDepartureTime;
      grpTravelRequest.Alternative_Dates__c = travelRequest.alternativeDates;
    }
    if (travelRequest.proposeAlternativeDestinations) {
      grpTravelRequest.Propose_alternative_destinations__c = travelRequest.proposeAlternativeDestinations;
      grpTravelRequest.Other_destinations_of_interest__c = travelRequest.otherDestinationsOfInterest;
    }
    if (travelRequest.extraBags) {
      grpTravelRequest.Extra_Bags__c = travelRequest.extraBags;
      grpTravelRequest.Number_Of_Extra_Bags__c = travelRequest.numberOfExtraBags;
    }
    if (travelRequest.specialBaggage) {
      grpTravelRequest.Special_Baggage__c = travelRequest.specialBaggage;
      grpTravelRequest.Number_Of_Special_Baggage__c = travelRequest.numberOfSpecialBaggage;
      grpTravelRequest.Special_Baggage_Note__c = travelRequest.specialBaggageNote;
    }
    if (travelRequest.wheelchairs) {
      grpTravelRequest.Wheelchairs__c = travelRequest.wheelchairs;
      grpTravelRequest.Number_Of_Wheelchairs__c = travelRequest.numberOfWheelchairs;
    }
    if (travelRequest.visualOrHearingAssistance) {
      grpTravelRequest.Visual_or_hearing_assistance__c = travelRequest.visualOrHearingAssistance;
      grpTravelRequest.Number_Of_Travellers__c = travelRequest.numberOfTravelers;
    }
    if (travelRequest.tripType == 'Return From Another City') {
      grpTravelRequest.Trip_Type__c = travelRequest.tripType;
      grpTravelRequest.Different_Return_City_Airport__c = travelRequest.differentReturnCityAirport;
    }
    return grpTravelRequest;
  }
}