sas-core/main/default/objects/Case/fields/Initially_Provided_PNR__c.field-meta.xml
<CustomField>
    <fullName>Initially_Provided_PNR__c</fullName>
    <description>PNR provided by the customer at chat.</description>
    <inlineHelpText>PNR provided by the customer at chat.</inlineHelpText>
    <label>Initially Provided PNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Special_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Service Request</label>
    <referenceTo>Special_Service_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Contact/fields/Special_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Service Request</label>
    <referenceTo>Special_Service_Request__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/Special_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Special Service Request</label>
    <nameField>
        <label>Special Service Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Special_Service_Request__c/fields/Brings_Own_Mobility_Device__c.field-meta.xml
<CustomField>
    <fullName>Brings_Own_Mobility_Device__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brings Own Mobility Device</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Mobility_Device_Dimensions__c.field-meta.xml
<CustomField>
    <fullName>Mobility_Device_Dimensions__c</fullName>
    <label>Mobility Device Dimensions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Mobility_Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Mobility_Device_Type__c</fullName>
    <label>Mobility Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dry Battery Wheelchair (WCBD )</fullName>
            </value>
            <value>
                <fullName>Wet Battery Wheelchair (WCBW)</fullName>
            </value>
            <value>
                <fullName>Lithium Battery Wheelchair (WCLB)</fullName>
            </value>
            <value>
                <fullName>Manual Power Wheelchair (WCMP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Number_Of_Special_Baggage__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Special_Baggage__c</fullName>
    <label>Number Of Special Baggage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Passenger_Needing_Assistance__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Needing_Assistance__c</fullName>
    <label>Passenger Needing Assistance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobility</fullName>
            </value>
            <value>
                <fullName>Special Baggage</fullName>
            </value>
            <value>
                <fullName>Special Assistance</fullName>
            </value>
            <value>
                <fullName>Service Animal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Type_Of_Service_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Service_Animal__c</fullName>
    <label>Type Of Service Animal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Type_Of_Special_Assistance__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Special_Assistance__c</fullName>
    <label>Type Of Special Assistance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hearing disability</fullName>
            </value>
            <value>
                <fullName>Sight disability</fullName>
            </value>
            <value>
                <fullName>WCHR Ramp</fullName>
            </value>
            <value>
                <fullName>WCHS Steps</fullName>
            </value>
            <value>
                <fullName>WCHC Carry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Special_Service_Request__c/fields/Type_Of_Special_Baggage__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Special_Baggage__c</fullName>
    <label>Type Of Special Baggage</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/classes/services/SpecialService.cls
public class SpecialService {
  public static String createSpecialServiceForm(
    SpecialServiceJSON2Apex specialServiceForm
  ) {
    Case cse;

    try {
      SpecialServiceJSON2Apex.FormData specialServiceRequestForm = specialServiceForm.formData;

      //create Special Service Request
      Special_Service_Request__c specialServiceRequest = createSpecialServiceRequestInstance(
        specialServiceRequestForm
      );
      insert specialServiceRequest;

      // create Cases
      cse = new Case(
        SuppliedEmail = specialServiceRequestForm.email,
        SuppliedPhone = specialServiceRequestForm.phone,
        RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL,
        Special_Service_Request__c = specialServiceRequest.Id,
        Initially_Provided_PNR__c = specialServiceRequestForm.bookingReference
      );

      insert cse;

      // create contact
      Contact con = new Contact(
        FirstName = specialServiceRequestForm.FirstName,
        LastName = specialServiceRequestForm.LastName,
        Email = specialServiceRequestForm.email,
        phone = specialServiceRequestForm.phone,
        Special_Service_Request__c = specialServiceRequest.Id
      );

      insert con;
    } catch (Exception e) {
      C_Log.logException(e, 'RefundRequest', null);
      return e.getMessage();
    }

    return cse.Id;
  }

  static Special_Service_Request__c createSpecialServiceRequestInstance(
    SpecialServiceJSON2Apex.FormData formData
  ) {
    Special_Service_Request__c specialServiceRequest = new Special_Service_Request__c();
    specialServiceRequest.Type__c = formData.Type;
    specialServiceRequest.Type_Of_Special_Assistance__c = formData.typeOfSpecialAssistance;
    specialServiceRequest.Passenger_Needing_Assistance__c = formData.passengerNeedingAssistance;
    if (formData.bringsOwnMobilityDevice && formData.Type == 'Mobility') {
      specialServiceRequest.Brings_Own_Mobility_Device__c = formData.bringsOwnMobilityDevice;
      specialServiceRequest.Mobility_Device_Type__c = formData.mobilityDeviceType;
      specialServiceRequest.Mobility_Device_Dimensions__c = formData.mobilityDeviceDimensions;
    }
    if (formData.Type == 'Special Baggage') {
      specialServiceRequest.Number_Of_Special_Baggage__c = formData.numberOfSpecialBaggage;
      specialServiceRequest.Type_Of_Special_Baggage__c = formData.typeOfSpecialBaggage;
    }
    if (formData.Type == 'Service Animal') {
      specialServiceRequest.Type_Of_Service_Animal__c = formData.typeOfServiceAnimal;
    }
    return specialServiceRequest;
  }
}