sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_line_1__c</fullName>
    <label>Address line 1</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Address_line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_line_2__c</fullName>
    <label>Address line 2</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
        <controllingField>Bank_Country__c</controllingField>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/Racer_Integration_Counter__c.object-meta.xml
<CustomObject>
    <label>Racer Integration Counter</label>
    <nameField>
        <label>Racer Integration Counter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Integration Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Accounting_Verification_Number__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Verification_Number__c</fullName>
    <label>Accounting Verification Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>The currency to which these counters apply.</description>
    <inlineHelpText>The currency to which these counters apply.</inlineHelpText>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Payment_Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run_Id__c</fullName>
    <label>Payment Run Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_line_1__c</fullName>
    <label>Address line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Address_line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_line_2__c</fullName>
    <label>Address line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Customer&apos;s Bank Account Number</description>
    <inlineHelpText>Bank account number that will receive the monetary payment</inlineHelpText>
    <label>Bank Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Customer&apos;s City</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <description>Beneficiary of the settlement</description>
    <label>Payee Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Payment_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Payment_File_Name__c</fullName>
    <label>Payment File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Waiting for approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Waiting for control</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Accepted by Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Rejected by Bank</fullName>
            </value>
            <value>
                <fullName>Accepted by Bank/Done</fullName>
            </value>
            <value>
                <fullName>L2 errors by Bank</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/recordTypes/Voucher.recordType-meta.xml
<RecordType>
    <fullName>Voucher</fullName>
    <active>true</active>
    <label>Voucher</label>
</RecordType>

sas-core/main/default/objects/Settlement_Item__c/Settlement_Item__c.object-meta.xml
<CustomObject>
    <description>The combination of one customer and cost account. At settlement file can contain several passenger and each passenger several reasons for compensation.</description>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Settlement Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/fields/Accounting_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_File_Name__c</fullName>
    <label>Accounting File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount to pay for this settlement item</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Account__c.field-meta.xml
<CustomField>
    <fullName>Cost_Account__c</fullName>
    <label>Cost Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6733</fullName>
                <label>6733 - Goodwill Compensation</label>
            </value>
            <value>
                <fullName>6741</fullName>
                <label>6741 - Liability - Baggage Damaged</label>
            </value>
            <value>
                <fullName>6742</fullName>
                <label>6742 - Liability - Baggage Delayed/missing/lost</label>
            </value>
            <value>
                <fullName>6743</fullName>
                <label>6743 - Liability - Baggage Pilfered</label>
            </value>
            <value>
                <fullName>6738</fullName>
                <label>6738 - Liability - Care (Meal, Hotel, Transportation)</label>
            </value>
            <value>
                <fullName>6721</fullName>
                <label>6721 - Liability - Denied Boarding Compensation</label>
            </value>
            <value>
                <fullName>6722</fullName>
                <label>6722 - Liability - Downgrading Compensation</label>
            </value>
            <value>
                <fullName>6727</fullName>
                <label>6727 - Liability - EU 261 Compensation</label>
            </value>
            <value>
                <fullName>6735</fullName>
                <label>6735 - Liability - Other</label>
            </value>
            <value>
                <fullName>6737</fullName>
                <label>6737 - Refund of tickets and ancillary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <inlineHelpText>Settlement to which this settlement belongs to</inlineHelpText>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending L1 confirmation</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finland</fullName>
        <default>true</default>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

sas-core/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GPB</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>Currencies available</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/tests/integration/Settlements_IntegrationTest.cls
@IsTest
public with sharing class Settlements_IntegrationTest {
  @IsTest
  public static void accountingFilesShouldBeCreatedCorrectly() {
    // Given
    Racer_Integration_Counter__c counter = new Racer_Integration_Counter__c(
      Accounting_Verification_Number__c = 10000,
      Currency__c = 'SEK',
      Payment_Run_Id__c = 1000
    );
    Settlement__c settlement1 = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 600,
      Bank_Country__c = 'Sweden',
      BIC_Swift__c = 'TESTBIC',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'NOK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00100',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER
    );
    Settlement__c settlement2 = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 600,
      Bank_Country__c = 'Sweden',
      BIC_Swift__c = 'TESTBIC',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'NOK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00100',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER
    );

    insert new List<SObject>{ counter, settlement1, settlement2 };

    Settlement_Item__c settlementItemToInclude1 = new Settlement_Item__c(
      Amount__c = 50,
      Cost_Account__c = '6727',
      Currency__c = 'SEK',
      Settlement__c = settlement1.Id,
      Status__c = 'Waiting for transfer'
    );
    Settlement_Item__c settlementItemToInclude2 = new Settlement_Item__c(
      Amount__c = 60,
      Cost_Account__c = '6727',
      Currency__c = 'SEK',
      Settlement__c = settlement1.Id,
      Status__c = 'Waiting for transfer'
    );
    Settlement_Item__c settlementItemToInclude3 = new Settlement_Item__c(
      Amount__c = 70,
      Cost_Account__c = '6727',
      Currency__c = 'SEK',
      Settlement__c = settlement2.Id,
      Status__c = 'Waiting for transfer'
    );
    Settlement_Item__c settlementItemNotToInclude1 = new Settlement_Item__c(
      Amount__c = 50,
      Cost_Account__c = '6727',
      Currency__c = 'SEK',
      Settlement__c = settlement1.Id,
      Status__c = 'Pending L1 confirmation'
    );
    Settlement_Item__c settlementItemNotToInclude2 = new Settlement_Item__c(
      Amount__c = 50,
      Cost_Account__c = '6727',
      Currency__c = 'NOK',
      Settlement__c = settlement2.Id,
      Status__c = 'Waiting for transfer'
    );
    insert new List<SObject>{
      settlementItemToInclude1,
      settlementItemToInclude2,
      settlementItemToInclude3,
      settlementItemNotToInclude1,
      settlementItemNotToInclude2
    };

    // When
    Test.startTest();
    SettlementService.createAccountingFile(
      AccountingFileBuilder.PaymentCurrency.SEK
    );
    Test.stopTest();

    //Then
    Settlement_Item__c settlementItemToInclude1Afterwards = [
      SELECT Id, Status__c, Accounting_File_Name__c, Name
      FROM Settlement_Item__c
      WHERE Id = :settlementItemToInclude1.Id
    ];
    Settlement_Item__c settlementItemToInclude2Afterwards = [
      SELECT Id, Status__c, Accounting_File_Name__c, Name
      FROM Settlement_Item__c
      WHERE Id = :settlementItemToInclude2.Id
    ];
    Settlement_Item__c settlementItemToInclude3Afterwards = [
      SELECT Id, Status__c, Accounting_File_Name__c, Name
      FROM Settlement_Item__c
      WHERE Id = :settlementItemToInclude3.Id
    ];
    Settlement_Item__c settlementItemNotToInclude1Afterwards = [
      SELECT Id, Status__c, Accounting_File_Name__c, Name
      FROM Settlement_Item__c
      WHERE Id = :settlementItemNotToInclude1.Id
    ];
    Settlement_Item__c settlementItemNotToInclude2Afterwards = [
      SELECT Id, Status__c, Accounting_File_Name__c, Name
      FROM Settlement_Item__c
      WHERE Id = :settlementItemNotToInclude2.Id
    ];

    String expectedFileTitle =
      'a501' +
      String.valueOf(Date.today().dayOfYear()) +
      '0' +
      Datetime.now().format('yyyyMMdd') +
      '.sfsek';

    System.assertEquals(
      expectedFileTitle,
      settlementItemToInclude1Afterwards.Accounting_File_Name__c,
      'Accounting file name should be stored in settlement items.'
    );
    System.assertEquals(
      expectedFileTitle,
      settlementItemToInclude2Afterwards.Accounting_File_Name__c,
      'Accounting file name should be stored in settlement items.'
    );
    System.assertEquals(
      expectedFileTitle,
      settlementItemToInclude3Afterwards.Accounting_File_Name__c,
      'Accounting file name should be stored in settlement items.'
    );

    System.assertEquals(
      'Sent to Racer',
      settlementItemToInclude1Afterwards.Status__c,
      'Settlement item status should be updated to Sent to Racer.'
    );
    System.assertEquals(
      'Sent to Racer',
      settlementItemToInclude2Afterwards.Status__c,
      'Settlement item status should be updated to Sent to Racer.'
    );
    System.assertEquals(
      'Sent to Racer',
      settlementItemToInclude3Afterwards.Status__c,
      'Settlement item status should be updated to Sent to Racer.'
    );

    System.assertEquals(
      'Pending L1 confirmation',
      settlementItemNotToInclude1Afterwards.Status__c,
      'Settlement item not waiting for transfer should not be modified.'
    );
    System.assert(
      String.isEmpty(
        settlementItemNotToInclude1Afterwards.Accounting_File_Name__c
      ),
      'Settlement item not waiting for transfer should not be modified.'
    );
    System.assertEquals(
      'Waiting for transfer',
      settlementItemNotToInclude2Afterwards.Status__c,
      'Settlement item in different currency should not be modified.'
    );
    System.assert(
      String.isEmpty(
        settlementItemNotToInclude2Afterwards.Accounting_File_Name__c
      ),
      'Settlement item in different currency should not be modified.'
    );

    String comparisonText = [
        SELECT Body
        FROM StaticResource
        WHERE Name = 'RacerAccountingFileReference'
      ]
      .Body.toString()
      .replace('{-DATE-}', Datetime.now().format('yyyyMMdd'))
      .replace('{PR}', Datetime.now().format('yyMM'))
      .replace('{-S1NAME---}', settlementItemToInclude1Afterwards.Name)
      .replace('{-S2NAME---}', settlementItemToInclude2Afterwards.Name)
      .replace('{-S3NAME---}', settlementItemToInclude3Afterwards.Name);
    /**
     * When the testing option 'Independent Auto-Number Sequence' is enabled, the
     * generated autonumbers for Settlement Items are of format {YYMMDD}{000000}
     * instead of the expected {YYMMDD}{0000}. Thus the placeholder in the
     * template has to be 2 characters longer than expected. Hopefully this
     * doesn't blow up anything else.
     */

    Racer_Integration_Counter__c counterAfterwards = [
      SELECT Id, Accounting_Verification_Number__c, Payment_Run_Id__c
      FROM Racer_Integration_Counter__c
      WHERE Id = :counter.Id
    ];

    System.assertEquals(
      10001,
      counterAfterwards.Accounting_Verification_Number__c,
      'Accounting verification number should be incremented afterwards.'
    );
    System.assertEquals(
      1000,
      counterAfterwards.Payment_Run_Id__c,
      'Run Id should not be incremented after file creation.'
    );
  }

  @IsTest
  public static void paymentFilesShouldBeCreatedCorrectly() {
    // Given
    Racer_Integration_Counter__c counter = new Racer_Integration_Counter__c(
      Accounting_Verification_Number__c = 10000,
      Currency__c = 'SEK',
      Payment_Run_Id__c = 1000
    );
    Settlement__c sekToInclude1 = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 400,
      Bank_Country__c = 'Sweden',
      BIC_Swift__c = 'SBANFIHH',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'SEK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER
    );
    Settlement__c sekToInclude2 = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 500,
      Bank_Country__c = 'Sweden',
      BIC_Swift__c = 'TESTBIC',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'SEK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER
    );
    Settlement__c sekNotToInclude = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 500,
      Bank_Country__c = 'Sweden',
      BIC_Swift__c = 'TESTBIC',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'SEK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS
    );
    Settlement__c nokSettlement = new Settlement__c(
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 600,
      Bank_Country__c = 'Norway',
      BIC_Swift__c = 'TESTBIC',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'NOK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE0000000000000',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00100',
      RecordTypeId = Settlements.MONETARY_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER
    );

    insert new List<SObject>{
      counter,
      sekToInclude1,
      sekToInclude2,
      sekNotToInclude,
      nokSettlement
    };

    // When
    Test.startTest();
    SettlementService.createPaymentFile(PaymentFileBuilder.PaymentCurrency.SEK);
    Test.stopTest();

    // Then
    Settlement__c sekToInclude1Afterwards = [
      SELECT Id, Settlement_Status__c, Payment_File_Name__c, Name
      FROM Settlement__c
      WHERE Id = :sekToInclude1.Id
    ];
    Settlement__c sekToInclude2Afterwards = [
      SELECT Id, Settlement_Status__c, Payment_File_Name__c, Name
      FROM Settlement__c
      WHERE Id = :sekToInclude2.Id
    ];
    Settlement__c sekNotToIncludeAfterwards = [
      SELECT Id, Settlement_Status__c, Payment_File_Name__c
      FROM Settlement__c
      WHERE Id = :sekNotToInclude.Id
    ];
    Settlement__c nokSettlementAfterwards = [
      SELECT Id, Settlement_Status__c, Payment_File_Name__c
      FROM Settlement__c
      WHERE Id = :nokSettlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_WAITING_FOR_TRANSFER,
      nokSettlementAfterwards.Settlement_Status__c,
      'A settlement in different currency should not have been modified.'
    );
    System.assert(
      String.isEmpty(nokSettlementAfterwards.Payment_File_Name__c),
      'A settlement in different currency should not have been modified.'
    );
    System.assertEquals(
      Settlements.STATUS_IN_PROGRESS,
      sekNotToIncludeAfterwards.Settlement_Status__c,
      'A settlement in same currency but not waiting for transfer should not have been modified.'
    );
    System.assert(
      String.isEmpty(sekNotToIncludeAfterwards.Payment_File_Name__c),
      'A settlement in same currency but not waiting for transfer should not have been modified.'
    );

    System.assertEquals(
      Settlements.STATUS_SENT_TO_RACER,
      sekToInclude1Afterwards.Settlement_Status__c,
      'Status of settlements in given currency should be set to Sent to Racer.'
    );
    System.assertEquals(
      Settlements.STATUS_SENT_TO_RACER,
      sekToInclude2Afterwards.Settlement_Status__c,
      'Status of settlements in given currency should be set to Sent to Racer.'
    );

    String expectedFileTitle =
      'SF_SEB_SEK_' +
      Datetime.now().format('yyyyMMdd') +
      counter.Payment_Run_Id__c;

    System.assertEquals(
      expectedFileTitle,
      sekToInclude1Afterwards.Payment_File_Name__c,
      'Payment file name should be stored in settlements.'
    );
    System.assertEquals(
      expectedFileTitle,
      sekToInclude2Afterwards.Payment_File_Name__c,
      'Payment file name should be stored in settlements.'
    );

    ContentVersion createdFile = [
      SELECT Id, Title, VersionData
      FROM ContentVersion
      WHERE Title = :expectedFileTitle
    ];

    String comparisonText = [
        SELECT Body
        FROM StaticResource
        WHERE Name = 'RacerPaymentFileReference'
      ]
      .Body.toString()
      .replace('{-DATE-}', Datetime.now().format('yyyyMMdd'))
      .replace('{-S1NAME---}', sekToInclude1Afterwards.Name)
      .replace('{-S2NAME---}', sekToInclude2Afterwards.Name);

    /**
     * When the testing option 'Independent Auto-Number Sequence' is enabled, the
     * generated autonumbers for Settlements are of format {YYMMDD}{000000}
     * instead of the expected {YYMMDD}{0000}. Thus the placeholder in the
     * template has to be 2 characters longer than expected. Hopefully this
     * doesn't blow up anything else.
     */

    System.assertEquals(
      comparisonText,
      createdFile.VersionData.toString(),
      //comparisonText,
      'Created payment file contents should match example file.'
    );

    Racer_Integration_Counter__c counterAfterwards = [
      SELECT Id, Accounting_Verification_Number__c, Payment_Run_Id__c
      FROM Racer_Integration_Counter__c
      WHERE Id = :counter.Id
    ];

    System.assertEquals(
      10000,
      counterAfterwards.Accounting_Verification_Number__c,
      'Accounting verification number should not be incremented afterwards.'
    );
    System.assertEquals(
      1001,
      counterAfterwards.Payment_Run_Id__c,
      'Run Id should be incremented after file creation.'
    );
  }

  @IsTest
  public static void ebSettlementsShouldBeProcessedImmediatelyWhenWaitingForTransfer() {
    // Given
    User settlementSubmitter = FCS_TestDataFactory.createUsers(1)[0];
    insert settlementSubmitter;

    LIA_Claim__c claim = new LIA_Claim__c(Liability_PNR__c = '0000AA');
    insert claim;

    Settlement__c settlement = new Settlement__c(
      Claim__c = claim.Id,
      EuroBonus_Number__c = '000000000',
      EuroBonus_Points__c = 3000,
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.EUROBONUS_POINTS_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      Submitter__c = settlementSubmitter.Id
    );

    insert settlement;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    settlement.Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER;
    Test.startTest();
    update settlement;
    Test.stopTest();

    // Then
    Settlement__c settlementAfterProcessing = [
      SELECT Id, Settlement_Status__c, External_Reference__c
      FROM Settlement__c
      WHERE Id = :settlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_DONE,
      settlementAfterProcessing.Settlement_Status__c,
      'Settlement should be marked as done after successfully adding points.'
    );
    System.assertEquals(
      APIMMock.CLM_TRANSACTION_ID,
      settlementAfterProcessing.External_Reference__c,
      'Settlement should external reference set based on response.'
    );
  }

  @IsTest
  public static void ebSettlementProcessingShouldHandleDomainFailuresProperly() {
    // Given
    User settlementSubmitter = FCS_TestDataFactory.createUsers(1)[0];
    insert settlementSubmitter;

    LIA_Claim__c claim = new LIA_Claim__c(Liability_PNR__c = '0000AA');
    insert claim;

    Settlement__c settlement = new Settlement__c(
      Claim__c = claim.Id,
      EuroBonus_Number__c = APIMMock.EB_NUMBER_NOT_IN_CLM,
      EuroBonus_Points__c = 3000,
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.EUROBONUS_POINTS_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      Submitter__c = settlementSubmitter.Id
    );

    insert settlement;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    settlement.Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER;
    Test.startTest();
    update settlement;
    Test.stopTest();

    // Then
    Settlement__c settlementAfterProcessing = [
      SELECT Id, Settlement_Status__c, Error_Message__c, External_Reference__c
      FROM Settlement__c
      WHERE Id = :settlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_FAILED,
      settlementAfterProcessing.Settlement_Status__c,
      'Settlement should be marked as denied after failing to add points.'
    );
    System.assertEquals(
      'Customer does not exist.',
      settlementAfterProcessing.Error_Message__c,
      'Settlement should have error detail set to response error.'
    );
  }

  @IsTest
  public static void ebSettlementProcessingShouldHandleServiceFailuresProperly() {
    // Given
    User settlementSubmitter = FCS_TestDataFactory.createUsers(1)[0];
    insert settlementSubmitter;

    LIA_Claim__c claim = new LIA_Claim__c(Liability_PNR__c = '0000AA');
    insert claim;

    Settlement__c settlement = new Settlement__c(
      Claim__c = claim.Id,
      EuroBonus_Number__c = APIMMock.EB_NUMBER_RETURN_500,
      EuroBonus_Points__c = 3000,
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.EUROBONUS_POINTS_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      Submitter__c = settlementSubmitter.Id
    );

    insert settlement;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    settlement.Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER;
    Test.startTest();
    update settlement;
    Test.stopTest();

    // Then
    Settlement__c settlementAfterProcessing = [
      SELECT Id, Settlement_Status__c, Error_Message__c, External_Reference__c
      FROM Settlement__c
      WHERE Id = :settlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_FAILED,
      settlementAfterProcessing.Settlement_Status__c,
      'Settlement should be marked as failed after failing to add points.'
    );
    System.assert(
      settlementAfterProcessing.Error_Message__c.contains('500'),
      'Settlement should have error detail set to contain 500 error code.'
    );
  }

  @IsTest
  public static void voucherSettlementsShouldBeProcessedImmediatelyWhenWaitingForTransfer() {
    // Given
    User settlementSubmitter = FCS_TestDataFactory.createUsers(1)[0];
    insert settlementSubmitter;

    Case c = new Case();
    insert c;

    LIA_Claim__c claim = new LIA_Claim__c(
      Liability_PNR__c = '0000AA',
      Case__c = c.Id
    );
    insert claim;

    Settlement__c settlement = new Settlement__c(
      Amount__c = 1,
      Address_line_1__c = 'TestAddress',
      Claim__c = claim.Id,
      City__c = 'Test City',
      Country__c = 'Sweden',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.VOUCHER_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      Submitter__c = settlementSubmitter.Id,
      Voucher_Email__c = 'test@example.com'
    );

    insert settlement;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    settlement.Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER;
    Test.startTest();
    update settlement;
    Test.stopTest();

    // Then
    Settlement__c settlementAfterProcessing = [
      SELECT Id, Settlement_Status__c, External_Reference__c
      FROM Settlement__c
      WHERE Id = :settlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_DONE,
      settlementAfterProcessing.Settlement_Status__c,
      'Settlement should be marked as done after successfully creating a voucher.'
    );
  }

  @IsTest
  public static void voucherSettlementProcessingShouldHandleServiceFailuresProperly() {
    // Given
    User settlementSubmitter = FCS_TestDataFactory.createUsers(1)[0];
    insert settlementSubmitter;

    Case c = new Case();
    insert c;

    LIA_Claim__c claim = new LIA_Claim__c(
      Liability_PNR__c = '0000AA',
      Case__c = c.Id
    );
    insert claim;

    Settlement__c settlement = new Settlement__c(
      Amount__c = 1,
      Address_line_1__c = 'TestAddress',
      Claim__c = claim.Id,
      City__c = 'Test City',
      Country__c = 'Sweden',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00000',
      RecordTypeId = Settlements.VOUCHER_RECORD_TYPE_ID,
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      Submitter__c = settlementSubmitter.Id,
      Voucher_Email__c = APIMMock.VOUCHER_INVALID_EMAIL
    );

    insert settlement;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    settlement.Settlement_Status__c = Settlements.STATUS_WAITING_FOR_TRANSFER;
    Test.startTest();
    update settlement;
    Test.stopTest();

    // Then
    Settlement__c settlementAfterProcessing = [
      SELECT Id, Settlement_Status__c, Error_Message__c, External_Reference__c
      FROM Settlement__c
      WHERE Id = :settlement.Id
    ];

    System.assertEquals(
      Settlements.STATUS_FAILED,
      settlementAfterProcessing.Settlement_Status__c,
      'Settlement should be marked as failed after failing to create a voucher.'
    );
    System.assert(
      settlementAfterProcessing.Error_Message__c.contains('400'),
      'Settlement should have error detail set to contain 400 error code as returned from API.'
    );
  }
}