sas-core/main/default/objects/Case/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Refund_Request__c.field-meta.xml
<CustomField>
    <fullName>Refund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund Request</label>
    <referenceTo>Refund_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
	<complianceGroup>Lookup</complianceGroup>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/Refund_Request__c.object-meta.xml
<CustomObject>
    <label>Refund Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Refund Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Refund_Request__c/fields/Booked_Via__c.field-meta.xml
<CustomField>
    <fullName>Booked_Via__c</fullName>
    <label>Booked Via</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Cancel_All_Passengers__c.field-meta.xml
<CustomField>
    <fullName>Cancel_All_Passengers__c</fullName>
    <label>Cancel All Passengers</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Already Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Cancel_Direction__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Direction__c</fullName>
    <label>Cancel Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Cancel_Entire_Booking__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Entire_Booking__c</fullName>
    <label>Cancel Entire Booking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Already Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Country_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Purchase__c</fullName>
    <label>Country of Purchase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Ticket_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Numbers__c</fullName>
    <label>Ticket Numbers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/classes/services/RefundRequestService.cls
public class RefundRequestService {
  public static String createRefundForm(RefundJsonToApex form) {
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();
    Case cse;

    try {
      String notes;

      RefundJsonToApex.cls_formData refundForm = form.formData;
      // Construct list of passenger in separate line
      if (refundForm.cancelAllPassengers == 'No') {
        List<String> passengerNames = refundForm.passengerNames;
        Integer Index = 0;
        for (String psgName : passengerNames) {
          if (Index != passengerNames.size()) {
            if (Index == 0) {
              notes = psgName + '\r\n';
            } else {
              notes += psgName + '\r\n';
            }
          }
          Index++;
        }
      }
      // Refund creation
      Refund_Request__c refund = new Refund_Request__c(
        Country_of_Purchase__c = refundForm.countryOfPurchase,
        PNR__c = refundForm.pnr,
        Ticket_Numbers__c = refundForm.ticketNumber,
        Cancel_Entire_Booking__c = refundForm.cancelEntireBooking,
        cancel_All_Passengers__c = refundForm.cancelAllPassengers,
        Cancel_Direction__c = refundForm.cancelDirection,
        Booked_Via__c = refundForm.bookedTripVia,
        Note__c = notes
      );

      uow.registerNew(refund);

      // Case Creation
      cse = new Case(
        SuppliedEmail = refundForm.email,
        SuppliedPhone = refundForm.phone,
        Refund_Request__c = refund.Id,
        RecordTypeId = C_RecordTypeHelper.CASE_CHANNEL
      );

      uow.registerNew(cse);
	  

      uow.registerRelationship(cse, Case.Refund_Request__c, refund);
      uow.commitWork();
    } catch (Exception e) {
      C_Log.logException(e, 'RefundRequest', null);
      return e.getMessage();
    }

    return cse.Id;
  }
}