sas-core/main/default/objects/IRR_AutomatedMessage__mdt/IRR_AutomatedMessage__mdt.object-meta.xml
<CustomObject>
    <label>AutomatedEvent</label>
    <pluralLabel>AutomatedEvents</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_CommunicationLog__c/IRR_CommunicationLog__c.object-meta.xml
<CustomObject>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CLOG-{00000000}</displayFormat>
        <label>Communication Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_DelayLog__c/IRR_DelayLog__c.object-meta.xml
<CustomObject>
    <description>Stores a list of previously communicated delays for flights</description>
    <label>Delay Log</label>
    <nameField>
        <displayFormat>DLOG-{000000}</displayFormat>
        <label>Delay Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_EventLog__c/IRR_EventLog__c.object-meta.xml
<CustomObject>
    <label>Event Log</label>
    <nameField>
        <displayFormat>ELOG-{00000000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_ManualCommunicationTemplate__mdt/IRR_ManualCommunicationTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Manual Communication Template</label>
    <pluralLabel>Manual Communication Templates</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_ManualOverride__c/IRR_ManualOverride__c.object-meta.xml
<CustomObject>
    <label>Manual Override</label>
    <nameField>
        <displayFormat>MO-{000000}</displayFormat>
        <label>Manual Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_RecipientWhitelist__mdt/IRR_RecipientWhitelist__mdt.object-meta.xml
<CustomObject>
    <description>Provides a Recipient whitelist for Email and SMS for use in Sanbox environments</description>
    <label>Recipient Whitelist</label>
    <pluralLabel>Recipient Whitelists</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_SMSResponse__c/IRR_SMSResponse__c.object-meta.xml
<CustomObject>
    <description>Holds SMS MO (Mobile originated) forwarded from SFMC</description>
    <label>SMS Response</label>
    <nameField>
        <label>SMS Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_CommunicationLog__c.field-meta.xml
<CustomField>
    <fullName>IRR_CommunicationLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The communication log of the latest sent message to the customer at the time of the message.</description>
    <inlineHelpText>The communication log of the latest sent message to the customer at the time of the message.</inlineHelpText>
    <label>Communication Log</label>
    <referenceTo>IRR_CommunicationLog__c</referenceTo>
    <relationshipLabel>SMS Responses</relationshipLabel>
    <relationshipName>IRR_SMSResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/SFMC_SMSDefinition__mdt/SFMC_SMSDefinition__mdt.object-meta.xml
<CustomObject>
    <label>SMS Definition</label>
    <pluralLabel>SMS Definitions</pluralLabel>
</CustomObject>

sas-core/main/default/classes/IRR_Application.cls
/**
* @author Niklas Lundkvist, Deloitte
* @date 2020
*
* @description Application specific configuration for various factories.
*/

public class IRR_Application {

    public enum MessageType { SMS, Email }

    public enum IntegrationType { REST, SOAP }

    /**
     * @author Niklas Lundkvist, Deloitte
     * @date 2020
     *
     * @description Configure and create the IntegrationExecutorBuilder for this Application.
     */
    public static final C_Application.IntegrationExecutorBuilderFactory IntegrationExecutorBuilder =
            new C_Application.IntegrationExecutorBuilderFactory(
                    new Map<Object, Type> {
                            IntegrationType.REST => C_IntegrationExecutorRest.Constructor.class
                    }
            );

    public static final C_Application.MessageRendererFactory MessageRenderer =
            new C_Application.MessageRendererFactory();

    /**
     * @author Niklas Lundkvist, Deloitte
     * @date 2020
     *
     * @description Configure and create the SelectorFactory for this Application.
     */
    public static final fflib_Application.SelectorFactory Selector =
            new fflib_Application.SelectorFactory(
                    new Map<SObjectType, Type> {
                            EmailTemplate.SObjectType => IRR_SEL_EmailTemplatesSelector.class,
                            IRR_EventLog__c.SObjectType =>IRR_SEL_EventLogsSelector.class,
                            IRR_CommunicationLog__c.SObjectType => IRR_SEL_CommunicationLogsSelector.class,
                            IRR_SMSResponse__c.SObjectType => IRR_SEL_SMSResponsesSelector.class,
                            IRR_DelayLog__c.SObjectType => IRR_SEL_DelayLogsSelector.class,
                            IRR_ManualCommunicationTemplate__mdt.SObjectType => IRR_SEL_ManualTemplatesSelector.class,
                            IRR_ManualOverride__c.SObjectType => IRR_SEL_ManualOverridesSelector.class,
                            IRR_RecipientWhitelist__mdt.SObjectType => IRR_SEL_RecipientWhitelistSelector.class,
                            Organization.SObjectType => IRR_SEL_OrganizationSelector.class,
                            SFMC_SMSDefinition__mdt.SObjectType => IRR_SEL_SMSDefinitionsSelector.class,
                            ContentDocumentLink.SObjectType =>IRR_SEL_ContentDocumentLinksSelector.class,
                            IRR_AutomatedMessage__mdt.SObjectType =>IRR_SEL_AutomatedMessagesSelector.class
                    }
            );

    /**
     * @author Niklas Lundkvist, Deloitte
     * @date 2020
     *
     * @description Configure and create the DomainFactory for this Application
     */
    public static final fflib_Application.DomainFactory Domain =
            new fflib_Application.DomainFactory(
                    IRR_Application.Selector,
                    new Map<SObjectType, Type> {
                            IRR_CommunicationLog__c.SObjectType => IRR_DOM_CommunicationLogs.Constructor.class,
                            IRR_SMSResponse__c.SObjectType => IRR_DOM_SMSResponses.Constructor.class,
                            IRR_EventLog__c.SObjectType => IRR_DOM_EventLogs.Constructor.class,
                            ContentDocumentLink.SObjectType => IRR_DOM_ContentDocumentLinks.Constructor.class
                    });

    /**
     * @author Niklas Lundkvist, Deloitte
     * @date 2020
     *
     * @description Configure and create the ServiceFactory for this Application.
     */
    public static final fflib_Application.ServiceFactory Service =
            new fflib_Application.ServiceFactory(
                    new Map<Type, Type>{
                            IRR_SVC_ICommunicationService.class => IRR_SVC_CommunicationServiceImpl.class,
                            IRR_SVC_ISFMCService.class => IRR_SVC_SFMCServiceImpl.class,
                            IRR_SVC_ITedsService.class => IRR_SVC_TedsServiceImpl.class,
                            IRR_SVC_ILogsService.class => IRR_SVC_LogsServiceImpl.class
                    }
            );

    public static final C_Application.EventProcessorFactory EventProcessor =
            new C_Application.EventProcessorFactory(
                    new Map<String, C_Application.EventDefinition> {
                            'bookingItineraryUpdateSASDisruption' => new C_Application.EventDefinition(
                                    IRR_MOD_RebookInfo.class, IRR_EVT_RebookProcessor.Constructor.class),
                            'bookingItineraryUpdateSASScheduleChange' => new C_Application.EventDefinition(
                                    IRR_MOD_ScheduledChangeInfo.class, IRR_EVT_ScheduledChangeProcessor.Constructor.class),
                            'flightDelayDeparture' => new C_Application.EventDefinition(
                                    IRR_MOD_DelayInfo.class, IRR_EVT_DelayProcessor.Constructor.class),
                            'flightNewInfoDeparture' => new C_Application.EventDefinition(
                                    IRR_MOD_NewInfo.class, IRR_EVT_NewInfoProcessor.Constructor.class),
                            'flightCancellation' => new C_Application.EventDefinition(
                                    IRR_MOD_CancelInfo.class, IRR_EVT_CancelProcessor.Constructor.class),
                            'manualCommunication' => new C_Application.EventDefinition(
                                    IRR_MOD_ManualRequest.class, IRR_EVT_ManualProcessor.Constructor.class),
                            'automatedCommunication' => new C_Application.EventDefinition(
                                    IRR_MOD_AutomatedRequest.class, IRR_EVT_AutomatedProcessor.Constructor.class)
                    }
            );


    /**
     * @author Niklas Lundkvist, Deloitte
     * @date 2019
     *
     * @description Configure and create the UnitOfWorkFactory for this Application
     */
    public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
            new fflib_Application.UnitOfWorkFactory(
                    new List<SObjectType> {
                            IRR_DelayLog__c.SObjectType,
                            IRR_EventLog__c.SObjectType,
                            IRR_CommunicationLog__c.SObjectType,
                            IRR_SMSResponse__c.SObjectType
                    });
}