sas-core/main/default/objects/Bank_Account_Info__c/Bank_Account_Info__c.object-meta.xml
<CustomObject>
    <label>Bank Account Information</label>
    <nameField>
        <displayFormat>BAI-{000000}</displayFormat>
        <label>Bank Account Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Account Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Bank_Account_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should this Bank Account be excluded from control</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Bank_Account_Info__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Bank_Account_Info__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Bank_Account_Info__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Bank_Account_Info__c/fields/Claim_Firm__c.field-meta.xml
<CustomField>
    <fullName>Claim_Firm__c</fullName>
    <label>Claim Firm</label>
    <referenceTo>Claim_Firm__c</referenceTo>
    <relationshipLabel>Bank Account Information</relationshipLabel>
    <relationshipName>Bank_Account_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Bank_Account_Info__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Claim_Firm__c/Claim_Firm__c.object-meta.xml
<CustomObject>
    <label>Claim Firm</label>
    <nameField>
        <label>Claim Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/selectors/BankAccountInfosSelector.cls
public inherited sharing class BankAccountInfosSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Bank_Account_Info__c.Id,
      Bank_Account_Info__c.Active__c,
      Bank_Account_Info__c.Name,
      Bank_Account_Info__c.Bank_Account_Number__c,
      Bank_Account_Info__c.Bank_Name__c,
      Bank_Account_Info__c.BIC_Swift__c,
      Bank_Account_Info__c.Claim_Firm__c,
      Bank_Account_Info__c.Country__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Bank_Account_Info__c.SObjectType;
  }

  public static BankAccountInfosSelector newInstance() {
    return (BankAccountInfosSelector) SAS_Service_Application.Selector.newInstance(
      Bank_Account_Info__c.SObjectType
    );
  }

  public List<Bank_Account_Info__c> selectById(Set<Id> ids) {
    return (List<Bank_Account_Info__c>) selectSObjectsById(ids);
  }

  public List<Bank_Account_Info__c> selectByBankAccountNumber(
    Set<String> accountNumbers
  ) {
    return (List<Bank_Account_Info__c>) Database.query(
      newQueryFactory()
        .setCondition('Bank_Account_Number__c in :accountNumbers')
        .toSOQL()
    );
  }
}