sas-core/main/default/objects/Racer_Integration_Counter__c/Racer_Integration_Counter__c.object-meta.xml
<CustomObject>
    <label>Racer Integration Counter</label>
    <nameField>
        <label>Racer Integration Counter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Integration Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Accounting_Verification_Number__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Verification_Number__c</fullName>
    <label>Accounting Verification Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Payment_Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run_Id__c</fullName>
    <label>Payment Run Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/Settlement_Item__c.object-meta.xml
<CustomObject>
    <description>The combination of one customer and cost account. At settlement file can contain several passenger and each passenger several reasons for compensation.</description>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Settlement Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <inlineHelpText>Settlement to which this settlement belongs to</inlineHelpText>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/services/SettlementService.cls
public without sharing class SettlementService {
  private static ContentVersionsSelector contentVersions = ContentVersionsSelector.newInstance();
  private static SettlementsSelector settlementsSel = SettlementsSelector.newInstance();
  private static SettlementItemsSelector settlementItemsSel = SettlementItemsSelector.newInstance();
  private static RacerIntegrationCountersSelector racerIntegrationCounters = RacerIntegrationCountersSelector.newInstance();

  /**
   * Create a batch file from all settlements waiting for transfer to Racer
   * for the given currency.
   */
  public static void createPaymentFile(
    PaymentFileBuilder.PaymentCurrency fileCurrency
  ) {
    List<String> currencies;
    if (fileCurrency != PaymentFileBuilder.PaymentCurrency.OTH) {
      currencies = new List<String>{ fileCurrency.name() };
    } else {
      currencies = new List<String>{
        'AUD',
        'EUR',
        'GBP',
        'CAD',
        'CZK',
        'HKD',
        'JPY',
        'NZD',
        'PLN',
        'SGD',
        'CHF'
      };
    }
    List<Settlement__c> settlementsToSend = settlementsSel.selectWaitingForTransferByCurrency(
      currencies
    );

    if (settlementsToSend.isEmpty()) {
      // Nothing to process. Let's log so we know we tried and do nothing else.
      C_Log.log(
        C_Log.Severity.Info,
        'SettlementService.createPaymentFile# No settlements found for: ' +
        fileCurrency.name(),
        null,
        'RACER',
        null
      );
      return;
    }

    List<PaymentEntry> paymentEntries = new List<PaymentEntry>();
    Racer_Integration_Counter__c counter = racerIntegrationCounters.selectByCurrency(
      fileCurrency.name()
    )[0];

    for (Settlement__c s : settlementsToSend) {
      paymentEntries.add(new PaymentEntry(s));
    }
    Id textFileHandle = PaymentFileBuilder.create(
      paymentEntries,
      fileCurrency,
      counter.Payment_Run_Id__c
    );

    ContentVersion paymentFile = contentVersions.selectById(
      new Set<Id>{ textFileHandle }
    )[0];

    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();

    Settlements.newInstance(settlementsToSend) // TODO: Think about if this should be moved to the sending functions.
      .markAsSentToRacer(paymentFile.Title, uow);

    counter.Payment_Run_Id__c += 1;
    uow.registerDirty(counter);
    uow.commitWork();
  }

  /**
   * Creates a batch file for all settlement items waiting to be sent to
   * Racer for the given currency.
   */
  public static void createAccountingFile(
    AccountingFileBuilder.PaymentCurrency fileCurrency
  ) {
    Racer_Integration_Counter__c counter = racerIntegrationCounters.selectByCurrency(
      fileCurrency.name()
    )[0];

    List<String> currencies;
    if (fileCurrency != AccountingFileBuilder.PaymentCurrency.OTH) {
      currencies = new List<String>{ fileCurrency.name() };
    } else {
      currencies = new List<String>{
        'AUD',
        'EUR',
        'GBP',
        'CAD',
        'CZK',
        'HKD',
        'JPY',
        'NZD',
        'PLN',
        'SGD',
        'CHF',
        'USD'
      };
    }

    List<Settlement_Item__c> settlementItemsToSend = settlementItemsSel.selectWaitingForTransferByCurrency(
      currencies
    );

    if (settlementItemsToSend.isEmpty()) {
      // Nothing to process. Let's log so we know we tried and do nothing else.
      C_Log.log(
        C_Log.Severity.Info,
        'SettlementService.createAccountingFile# No settlement items found for: ' +
        fileCurrency.name(),
        null,
        'RACER',
        null
      );
      return;
    }

    List<AccountingEntry> accountingEntries = new List<AccountingEntry>();

    for (Settlement_Item__c s : settlementItemsToSend) {
      accountingEntries.add(new AccountingEntry(s));
    }

    Id textFileHandle = AccountingFileBuilder.create(
      accountingEntries,
      fileCurrency,
      counter.Accounting_Verification_Number__c
    );

    ContentVersion accountingFile = contentVersions.selectById(
      new Set<Id>{ textFileHandle }
    )[0];

    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();

    SettlementItems.newInstance(settlementItemsToSend) // TODO: Think about if this should be moved to the sending functions.
      .markAsSentToRacer(accountingFile.Title, uow);

    counter.Accounting_Verification_Number__c += 1;
    uow.registerDirty(counter);
    uow.commitWork();
  }

  private static void sendAccountingFile(Id fileId) {
    RacerIntegrationService.sendFile(
      RacerIntegrationService.FILE_TYPE.ACCOUNTING,
      fileId
    );
  }
  private static void sendPaymentFile(Id fileId) {
    RacerIntegrationService.sendFile(
      RacerIntegrationService.FILE_TYPE.PAYMENT,
      fileId
    );
  }
}