sas-core/main/default/objects/Racer_Integration_Counter__c/Racer_Integration_Counter__c.object-meta.xml
<CustomObject>
    <label>Racer Integration Counter</label>
    <nameField>
        <label>Racer Integration Counter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Integration Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Accounting_Verification_Number__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Verification_Number__c</fullName>
    <label>Accounting Verification Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>The currency to which these counters apply.</description>
    <inlineHelpText>The currency to which these counters apply.</inlineHelpText>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Racer_Integration_Counter__c/fields/Payment_Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run_Id__c</fullName>
    <label>Payment Run Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/classes/selectors/RacerIntegrationCountersSelector.cls
public inherited sharing class RacerIntegrationCountersSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Racer_Integration_Counter__c.Id,
      Racer_Integration_Counter__c.Accounting_Verification_Number__c,
      Racer_Integration_Counter__c.Currency__c,
      Racer_Integration_Counter__c.Payment_Run_Id__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Racer_Integration_Counter__c.SObjectType;
  }

  public static RacerIntegrationCountersSelector newInstance() {
    return (RacerIntegrationCountersSelector) SAS_Service_Application.Selector.newInstance(
      Racer_Integration_Counter__c.SObjectType
    );
  }

  public List<Racer_Integration_Counter__c> selectById(Set<Id> ids) {
    return (List<Racer_Integration_Counter__c>) selectSObjectsById(ids);
  }

  public List<Racer_Integration_Counter__c> selectByCurrency(String c) {
    return (List<Racer_Integration_Counter__c>) Database.query(
      newQueryFactory().setCondition('Currency__c =:c').toSOQL()
    );
  }

  public override String getOrderBy() {
    return 'Name';
  }
}