sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/classes/controllers/FlightDelayCertificateController.cls
public with sharing class FlightDelayCertificateController {
  public List<FlightWrapper> flightWrappers { get; set; }
  public String enteredFlight { get; set; }
  public String bookingReference { get; set; }
  public String passengerName { get; set; }
  public String caseNumber { get; set; }
  public String imageLink { get; set; }

  public FlightDelayCertificateController() {
    Id bookingId = ApexPages.currentPage().getParameters().get('bookingId') !=
      null
      ? Id.valueOf(ApexPages.currentPage().getParameters().get('bookingId'))
      : null;
    enteredFlight = ApexPages.currentPage()
      .getParameters()
      .get('enteredFlight');
    passengerName = ApexPages.currentPage()
      .getParameters()
      .get('passengerName');
    bookingReference = ApexPages.currentPage()
      .getParameters()
      .get('bookingReference');
    caseNumber = ApexPages.currentPage().getParameters().get('caseNumber');

    imageLink =
      '/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=' +
      ContentVersionsSelector.newInstance().selectByTitle('SAS-Logo_B3_RGB')[0]
        ?.Id;

    flightWrappers = new List<FlightWrapper>();
    if (bookingId != null) {
      List<Flight__c> flightsInBooking = FlightsSelector.newInstance()
        .selectByBookingIds(new Set<Id>{ bookingId });
      for (Flight__c flight : flightsInBooking) {
        String flightId = flight.TEDS_Identifier__c.substringBefore('-');
        FlightWrapper fw = new FlightWrapper();
        fw.ScheduledTimeOfDeparture = flight.Scheduled_Departure_Time__c
          ?.format('yyyy-MM-dd HH:mm');
        fw.ScheduledTimeOfArrival = flight.Scheduled_Arrival_Time__c
          ?.format('yyyy-MM-dd HH:mm');
        fw.ActualTimeOfArrival = flight.Actual_Arrival_Time__c
          ?.format('yyyy-MM-dd HH:mm');
        fw.FlightNumber = flightId;
        fw.FlightDate = flight.TEDS_Identifier__c?.substring(6, 14);
        fw.ArrivalAirport = flight.Arrival_Airport__c;
        fw.DepartureAirport = flight.Departure_Airport__c;
        fw.FlightStatus = flight.Departure_Status__c;
        flightWrappers.add(fw);
      }
    }
  }

  /**
   * Wrapper class needed to retrieve flight data in the Visualforce page
   * Data is retrieved on the page by calling the getter as a property
   */
  public class FlightWrapper {
    public String ScheduledTimeOfDeparture { get; set; }
    public String ScheduledTimeOfArrival { get; set; }
    public String ActualTimeOfArrival { get; set; }
    public String FlightNumber { get; set; }
    public String FlightDate { get; set; }
    public String ArrivalAirport { get; set; }
    public String DepartureAirport { get; set; }
    public String FlightStatus { get; set; }
  }
}