sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/FlightIrregularities__c.object-meta.xml
<CustomObject>
    <description>Holds information about delays and cancellations.</description>
    <label>FlightIrregularities</label>
    <nameField>
        <label>FlightIrregularities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlightIrregularities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FlightIrregularities__c/fields/Cancellation_Time__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Time__c</fullName>
    <label>Cancellation_Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The cancellation/delay code parsed from TEDS</description>
    <inlineHelpText>The cancellation/delay code parsed from TEDS</inlineHelpText>
    <label>Cancellation code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the irregularity defined by IATA</description>
    <inlineHelpText>A description of the irregularity defined by IATA</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Duration_minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_minutes__c</fullName>
    <description>Number of minutes for the duration (parsed from TEDS)</description>
    <inlineHelpText>Number of minutes for the duration (parsed from TEDS)</inlineHelpText>
    <label>Duration minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Eligible_For_EU261__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_EU261__c</fullName>
    <label>Eligible For EU261</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <description>The flight to which the irregularity pertains</description>
    <inlineHelpText>The flight to which the irregularity pertains</inlineHelpText>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>Flight_Irregularities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>The reason why the flight was delayed/cancelled</description>
    <inlineHelpText>The reason why the flight was delayed/cancelled</inlineHelpText>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the irregularity (cancellation/delay)</description>
    <inlineHelpText>The type of the irregularity (cancellation/delay)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/FlightIrregularitiesSelector.cls
public inherited sharing class FlightIrregularitiesSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      FlightIrregularities__c.Id,
      FlightIrregularities__c.Name,
      FlightIrregularities__c.CreatedDate,
      FlightIrregularities__c.LastModifiedDate,
      FlightIrregularities__c.Cancellation_Time__c,
      FlightIrregularities__c.Code__c,
      FlightIrregularities__c.Description__c,
      FlightIrregularities__c.Duration_minutes__c,
      FlightIrregularities__c.Eligible_For_EU261__c,
      FlightIrregularities__c.Flight__c,
      FlightIrregularities__c.Name__c,
      FlightIrregularities__c.Reason__c,
      FlightIrregularities__c.Type__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return FlightIrregularities__c.SObjectType;
  }

  public static FlightIrregularitiesSelector newInstance() {
    return (FlightIrregularitiesSelector) SAS_Service_Application.Selector.newInstance(
      FlightIrregularities__c.SObjectType
    );
  }

  public List<FlightIrregularities__c> selectById(Set<Id> ids) {
    return (List<FlightIrregularities__c>) selectSObjectsById(ids);
  }

  public List<FlightIrregularities__c> selectByFlightId(Set<Id> flightIds) {
    return (List<FlightIrregularities__c>) Database.query(
      newQueryFactory().setCondition('Flight__c IN :flightIds').toSOQL()
    );
  }

  public List<FlightIrregularities__c> selectByTEDSFlightId(
    Set<String> flightIds
  ) {
    return (List<FlightIrregularities__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'Flight__c IN (SELECT Id FROM Flight__c WHERE TEDS_Identifier__c IN :flightIds)'
        )
        .toSOQL()
    );
  }

  public List<FlightIrregularities__c> selectByFlightNumberDateAndAirports(
    String flightNumber,
    Date departureDate,
    String fromAirport,
    String toAirport
  ) {
    String flightId =
      Flight.constructTEDSFlightNumberDate(flightNumber, departureDate) +
      '-' +
      fromAirport +
      '-' +
      toAirport;

    return (List<FlightIrregularities__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'Flight__c IN (SELECT Id FROM Flight__c WHERE TEDS_Identifier__c = :flightId)'
        )
        .toSOQL()
    );
  }
}