sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Departure_Gate__c.field-meta.xml
<CustomField>
    <fullName>Departure_Gate__c</fullName>
    <label>Departure Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/tests/integration/FlightService_IntegrationTest.cls
@IsTest
public with sharing class FlightService_IntegrationTest {
  public static String flightIdFromTEDS = 'SK2569-20210410-ARN-CPH';
  public static String gateInDetailedFlightInfo = 'E135';

  @IsTest
  public static void shouldFetchFlightsByFlightId() {
    // Given
    Set<String> flightIds = new Set<String>();
    flightIds.add(flightIdFromTEDS);
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    Test.startTest();
    FlightService.newInstance().fetchFlightsByReference(flightIds, true);
    Test.stopTest();

    // Then
    Flight__c flightFromDB = FlightsSelector.newInstance()
      .selectByTEDSId(new Set<String>{ flightIdFromTEDS })[0];

    System.assertEquals(
      gateInDetailedFlightInfo,
      flightFromDB.Departure_Gate__c,
      'Flight should exist and have detailed flight info.'
    );
  }
}