sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time_Local__c</fullName>
    <label>Actual Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time__c</fullName>
    <label>Actual Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time_Local__c</fullName>
    <label>Actual Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Delayed_Minutes__c</fullName>
    <label>Arrival Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Gate__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Gate__c</fullName>
    <label>Arrival Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Status__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Arrival Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Terminal__c</fullName>
    <label>Arrival Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Departure_Delayed_Minutes__c</fullName>
    <label>Departure Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Gate__c.field-meta.xml
<CustomField>
    <fullName>Departure_Gate__c</fullName>
    <label>Departure Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Departure_Terminal__c</fullName>
    <label>Departure Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Time__c</fullName>
    <label>Estimated Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Time_Local__c</fullName>
    <label>Estimated Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_Time__c</fullName>
    <label>Estimated Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_Time_Local__c</fullName>
    <label>Estimated Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time_Local__c</fullName>
    <label>Scheduled Arrival Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time_Local__c</fullName>
    <label>Scheduled Departure Time Local</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/FlightIrregularities__c.object-meta.xml
<CustomObject>
    <description>Holds information about delays and cancellations.</description>
    <label>FlightIrregularities</label>
    <nameField>
        <label>FlightIrregularities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlightIrregularities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FlightIrregularities__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <description>The flight to which the irregularity pertains</description>
    <inlineHelpText>The flight to which the irregularity pertains</inlineHelpText>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>Flight_Irregularities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/domain/flights/Flights.cls
public without sharing class Flights extends ApplicationDomain {
  public Flights(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<Flight__c>) Records;
  }

  public List<Flight__c> instanceRecords;
  @TestVisible
  private FlightIrregularities flightIrregularities;

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Flights(records);
    }
  }

  public static Flights newInstance(List<Flight__c> sObjectList) {
    return (Flights) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  /**
   * Parses flight data in TEDSFlight format into Flight__c objects and prepares them for DB insertion.
   *
   * @param flightData List of TEDSFlight objects containing flights to create.
   * @param shouldUpsertToDB Boolean which asserts whether the records should be upserted or not
   *
   * @return The list of created Flight__c objects.
   */
  public static Flights createFromTEDSData(
    List<TEDSFlight> flightData,
    Boolean shouldUpsertToDB
  ) {
    Map<String, Flight__c> flightsProcessed = new Map<String, Flight__c>();
    Map<String, TEDSFlight.Arrival> TEDSIdToTEDSArrival = new Map<String, TEDSFlight.Arrival>{};
    Map<String, TEDSFlight.Departure> TEDSIdToTEDSDeparture = new Map<String, TEDSFlight.Departure>{};

    // Loop through each booking and create all sub objects.
    for (TEDSFlight flight : flightData) {
      // Loop through all segments in the trip and create segment and flight objects as necessary

      // Create flights
      String flightId = flight.id.trim().toUpperCase();

      // Save irregularity data for batch insert
      TEDSIdToTEDSArrival.put(flightId, flight.arrival);
      TEDSIdToTEDSDeparture.put(flightId, flight.departure);

      if (!flightsProcessed.containsKey(flightId)) {
        Datetime scheduledArrivalDate = Datetime.valueOf(
          flight.arrival.scheduledTime?.utc?.replace('T', ' ').replace('Z', '')
        );
        Datetime scheduledDepartureDate = Datetime.valueOf(
          flight.departure.scheduledTime
            ?.utc
            ?.replace('T', ' ')
            .replace('Z', '')
        );
        Datetime actualArrivalDate;
        Datetime actualDepartureDate;
        if (flight.arrival.actualTime != null) {
          actualArrivalDate = Datetime.valueOf(
            flight.arrival.actualTime?.utc?.replace('T', ' ').replace('Z', '')
          );
        }
        if (flight.departure.actualTime != null) {
          actualDepartureDate = Datetime.valueOf(
            flight.departure.actualTime?.utc?.replace('T', ' ').replace('Z', '')
          );
        }
        Datetime estimatedArrivalDate;
        Datetime estimatedDepartureDate;
        if (flight.arrival.estimatedTime != null) {
          estimatedArrivalDate = Datetime.valueOf(
            flight.arrival.estimatedTime
              ?.utc
              ?.replace('T', ' ')
              .replace('Z', '')
          );
        }
        if (flight.departure.estimatedTime != null) {
          estimatedDepartureDate = Datetime.valueOf(
            flight.departure.estimatedTime
              ?.utc
              ?.replace('T', ' ')
              .replace('Z', '')
          );
        }

        String scheduledArrivalDateLocal = flight.arrival.scheduledTime
          ?.local
          ?.replace('Z', '');
        String scheduledDepartureDateLocal = flight.departure.scheduledTime
          ?.local
          ?.replace('Z', '');

        String actualArrivalDateLocal;
        String actualDepartureDateLocal;
        if (flight.arrival.actualTime != null) {
          actualArrivalDateLocal = flight.arrival.actualTime
            ?.local
            ?.replace('Z', '');
        }
        if (flight.departure.actualTime != null) {
          actualDepartureDateLocal = flight.departure.actualTime
            ?.local
            ?.replace('Z', '');
        }
        String estimatedArrivalDateLocal;
        String estimatedDepartureDateLocal;
        if (flight.arrival.estimatedTime != null) {
          estimatedArrivalDateLocal = flight.arrival.estimatedTime
            ?.local
            ?.replace('Z', '');
        }
        if (flight.departure.estimatedTime != null) {
          estimatedDepartureDateLocal = flight.departure.estimatedTime
            ?.local
            ?.replace('Z', '');
        }

        Flight__c newFlight = new Flight__c(
          Name = flightId,
          Actual_Arrival_Time__c = actualArrivalDate,
          Actual_Arrival_Time_Local__c = actualArrivalDateLocal,
          Actual_Departure_Time__c = actualDepartureDate,
          Actual_Departure_Time_Local__c = actualDepartureDateLocal,
          Arrival_Airport__c = flight.arrival.station,
          Arrival_Delayed_Minutes__c = flight.arrival.delayedMinutes,
          Arrival_Gate__c = flight.arrival.gate,
          Arrival_Status__c = flight.arrival.status,
          Arrival_Terminal__c = flight.arrival.terminal?.id,
          Departure_Airport__c = flight.departure.station,
          Departure_Delayed_Minutes__c = flight.departure.delayedMinutes,
          Departure_Gate__c = flight.departure.gate,
          Departure_Status__c = flight.departure.status,
          Departure_Terminal__c = flight.departure.terminal?.id,
          Estimated_Arrival_Time__c = estimatedArrivalDate,
          Estimated_Arrival_Time_Local__c = estimatedArrivalDateLocal,
          Estimated_Departure_Time__c = estimatedDepartureDate,
          Estimated_Departure_Time_Local__c = estimatedDepartureDateLocal,
          Operating_Carrier__c = flight.carrier, // The carrier field from TEDS should always contain the operating carrier
          Scheduled_Arrival_Time__c = scheduledArrivalDate,
          Scheduled_Arrival_Time_Local__c = scheduledArrivalDateLocal,
          Scheduled_Departure_Time__c = scheduledDepartureDate,
          Scheduled_Departure_Time_Local__c = scheduledDepartureDateLocal,
          TEDS_Identifier__c = flightId
        );

        flightsProcessed.put(flightId, newFlight);
      }
    }

    Flights newFlights = Flights.newInstance(flightsProcessed.values());
    List<String> TEDSIds = new List<String>(flightsProcessed.keySet());

    newFlights.flightIrregularities = FlightIrregularities.createFromTEDSData(
      TEDSIds,
      TEDSIdToTEDSArrival,
      TEDSIdToTEDSDeparture
    );

    if (shouldUpsertToDB) {
      newFlights.upsertToDB();
    }

    return newFlights;
  }
  //Flights and Irregularities are stored in the same table in EDW
  public static Flights createFromEDWData(
    List<FetchEDWDataResponse.Irregularity> flightSourceData
  ) {
    Map<String, Flight__c> flightIdToRecord = new Map<String, Flight__c>();
    List<FetchEDWDataResponse.Irregularity> irregularitiesToCreate = new List<FetchEDWDataResponse.Irregularity>();
    for (FetchEDWDataResponse.Irregularity irr : flightSourceData) {
      //The input data contains different data based on if flight belongs to SK or other carrier
      String flightStatus = 'unknown';
      String arrivalStatus = 'unknown';
      String departureStatus = 'unknown';
      switch on irr.status {
        when 'DEPARTURE DELAYED' {
          flightStatus = 'delayed';
          arrivalStatus = 'ontime';
          departureStatus = 'delayed';
        }
        when 'ARRIVAL DELAYED' {
          flightStatus = 'delayed';
          arrivalStatus = 'delayed';
          departureStatus = 'ontime';
        }
        when 'DEPARTUE AND ARRIVAL DELAYED' {
          flightStatus = 'delayed';
          arrivalStatus = 'delayed';
          departureStatus = 'delayed';
        }
        when 'CANCELLED' {
          flightStatus = 'cancelled';
          arrivalStatus = 'cancelled';
          departureStatus = 'cancelled';
        }
        when 'ON TIME' {
          flightStatus = 'ontime';
          arrivalStatus = 'ontime';
          departureStatus = 'ontime';
        }
        when else {
          flightStatus = 'unknown';
          arrivalStatus = 'unknown';
          departureStatus = 'unknown';
        }
      }
      Boolean cancelledOrDelayed =
        flightStatus == 'delayed' ||
        irr.fltStatus == 'X';
      if (cancelledOrDelayed) {
        irregularitiesToCreate.add(irr);
      }
      String irrFlightId = String.format(
        '{0}-{1}-{2}-{3}',
        new List<Object>{
          irr.fltId.deleteWhitespace(),
          Datetime.newInstance(irr.depDte).format('yyyyMMdd'),
          irr.stnFrCd,
          irr.stnToCd
        }
      );
      if (flightIdToRecord.get(irrFlightId) != null) {
        continue;
      }
      Flight f = new Flight(new Flight__c(Name = irrFlightId));
      f.tedsIdentifier = irrFlightId;
      f.aircraftRegistration = irr.aircraftRegistration;
      f.arrivalAirport = irr.stnToCd;
      f.arrivalDelayedMinutes = irr.arrivalDelayMins;
      f.arrivalStatus = Flight.getStatusFromPicklistValue(arrivalStatus);
      f.departureAirport = irr.stnFrCd;
      f.departureDelayedMinutes = irr.depDelayMins;
      f.departureStatus = Flight.getStatusFromPicklistValue(departureStatus);
      f.actualArrivalTime = irr.ataTms == null
        ? null
        : Datetime.newInstance(irr.ataTms);
      f.actualDepartureTime = irr.atdTms == null
        ? null
        : Datetime.newInstance(irr.atdTms);
      f.estimatedArrivalTime = irr.etaTms == null
        ? null
        : Datetime.newInstance(irr.etaTms);
      f.estimatedDepartureTime = irr.etdTms == null
        ? null
        : Datetime.newInstance(irr.etdTms);
      f.scheduledArrivalTime = irr.staTms == null
        ? null
        : Datetime.newInstance(irr.staTms);
      f.scheduledDepartureTime = irr.stdTms == null
        ? null
        : Datetime.newInstance(irr.stdTms);
      f.updateSObjectFields();
      flightIdToRecord.put(irrFlightId, f.underlyingSObject);
    }

    Flights newFlights = Flights.newInstance(flightIdToRecord.values());
    newFlights.flightIrregularities = FlightIrregularities.createFromEDWData(
      irregularitiesToCreate
    );
    return newFlights;
  }

  public Flights upsertToDB() {
    Set<String> flightIds = new Set<String>();

    for (Flight__c f : instanceRecords) {
      flightIds.add(f.TEDS_Identifier__c);
    }

    List<FlightIrregularities__c> irregularitiesToDelete = FlightIrregularitiesSelector.newInstance()
      .selectByTEDSFlightId(flightIds);

    try {
      delete irregularitiesToDelete; // Delete and re-insert all irregularities
    } catch (DMLException e) {
      if (e.getDmlType(0) == StatusCode.ENTITY_IS_DELETED) {
        // A parallel thread may have deleted the entities. Let's just ignore.
      } else {
        throw e;
      }
    }

    // The upsert operation seems to fail due to a race condition between two threads
    // trying to upsert the records simultaneously. One thread succeeds and the other
    // fails with a duplicate value exception.
    try {
      upsert instanceRecords TEDS_Identifier__c;
    } catch (DMLException e) {
      if (e.getDmlType(0) == StatusCode.DUPLICATE_VALUE) {
        upsert instanceRecords TEDS_Identifier__c;
      }
    }

    if (flightIrregularities != null) {
      if (flightIrregularities.instanceRecords.size() > 0) {
        insert flightIrregularities.addFlightReferences(instanceRecords)
          .instanceRecords;
      }
    }

    return this;
  }
}