sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Actual_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time__c</fullName>
    <label>Actual Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Delayed_Minutes__c</fullName>
    <label>Arrival Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Gate__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Gate__c</fullName>
    <label>Arrival Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Status__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Arrival Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Terminal__c</fullName>
    <label>Arrival Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Departure_Delayed_Minutes__c</fullName>
    <label>Departure Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Gate__c.field-meta.xml
<CustomField>
    <fullName>Departure_Gate__c</fullName>
    <label>Departure Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Status__c.field-meta.xml
<CustomField>
    <fullName>Departure_Status__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Departure Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ontime</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Departure_Terminal__c</fullName>
    <label>Departure Terminal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Time__c</fullName>
    <label>Estimated Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Estimated_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_Time__c</fullName>
    <label>Estimated Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/classes/services/FlightService.cls
/**
 * Service class for managing flights in Salesforce.
 */
public without sharing class FlightService {
  /**
   * Attempts to fetch the given flights from TEDS, and create necessary DB objects.
   * Does nothing if one isn't found.
   *
   * @param flightReferences List of flights to find using the full TEDS flight Id. Maximum of 10 per call.
   *
   * @throws IntegrationError If there is a problem with the integration.
   */
  @future(callout=true)
  public static void fetchFlightsByFlightReference(String flightReferences) {
    TEDSIntegrationService TEDSService = (TEDSIntegrationService) SAS_Service_Application.Service.newInstance(
      TEDSIntegrationService.class
    );

    Map<String, String> query = new Map<String, String>();
    query.put('ids', flightReferences);
    List<TEDSFlight> flightData = TEDSService.fetchFlightsByQuery(query);

    if (flightData == null) {
      return;
    }

    List<Flight__c> newFlights = constructFlightsForDB(flightData);
    upsert newFlights TEDS_Identifier__c;
  }

  /**
   * Parses flight data in TEDSFlight format into Flight__c objects and prepares them for DB insertion.
   *
   * @param flightData List of TEDSFlight objects containing flights to create.
   * @param uow Unit of work transaction in which the booking should be committed. Must be committed by caller.
   *
   * @return The list of created Flight__c objects.
   */
  private static List<Flight__c> constructFlightsForDB(
    List<TEDSFlight> flightData
  ) {
    Map<String, Flight__c> flightsProcessed = new Map<String, Flight__c>();

    // Loop through each booking and create all sub objects.
    for (TEDSFlight flight : flightData) {
      // Loop through all segments in the trip and create segment and flight objects as necessary

      // Create flights
      String flightId = flight.id.trim().toUpperCase();

      if (!flightsProcessed.containsKey(flightId)) {
        Datetime scheduledArrivalDate = Datetime.valueOf(
          flight.arrival.scheduledTime
            ?.local
            ?.replace('T', ' ')
            .replace('Z', '')
        );
        Datetime scheduledDepartureDate = Datetime.valueOf(
          flight.departure.scheduledTime
            ?.local
            ?.replace('T', ' ')
            .replace('Z', '')
        );
        Datetime actualArrivalDate;
        Datetime actualDepartureDate;
        if (flight.arrival.actualTime != null) {
          actualArrivalDate = Datetime.valueOf(
            flight.arrival.actualTime?.local?.replace('T', ' ').replace('Z', '')
          );
        }
        if (flight.departure.actualTime != null) {
          actualDepartureDate = Datetime.valueOf(
            flight.departure.actualTime
              ?.local
              ?.replace('T', ' ')
              .replace('Z', '')
          );
        }
        Datetime estimatedArrivalDate;
        Datetime estimatedDepartureDate;
        if (flight.arrival.estimatedTime != null) {
          estimatedArrivalDate = Datetime.valueOf(
            flight.arrival.estimatedTime
              ?.local
              ?.replace('T', ' ')
              .replace('Z', '')
          );
        }
        if (flight.departure.estimatedTime != null) {
          estimatedDepartureDate = Datetime.valueOf(
            flight.departure.estimatedTime
              ?.local
              ?.replace('T', ' ')
              .replace('Z', '')
          );
        }

        Flight__c newFlight = new Flight__c(
          Name = flightId,
          Actual_Arrival_Time__c = actualArrivalDate,
          Actual_Departure_Time__c = actualDepartureDate,
          Arrival_Airport__c = flight.arrival.station,
          Arrival_Delayed_Minutes__c = flight.arrival.delayedMinutes,
          Arrival_Gate__c = flight.arrival.gate,
          Arrival_Status__c = flight.arrival.status,
          Arrival_Terminal__c = flight.arrival.terminal?.id,
          Departure_Airport__c = flight.departure.station,
          Departure_Delayed_Minutes__c = flight.departure.delayedMinutes,
          Departure_Gate__c = flight.departure.gate,
          Departure_Status__c = flight.departure.status,
          Departure_Terminal__c = flight.departure.terminal?.id,
          Estimated_Arrival_Time__c = estimatedArrivalDate,
          Estimated_Departure_Time__c = estimatedDepartureDate,
          Scheduled_Arrival_Time__c = scheduledArrivalDate,
          Scheduled_Departure_Time__c = scheduledDepartureDate,
          TEDS_Identifier__c = flightId
        );

        flightsProcessed.put(flightId, newFlight);
      }
    }
    return flightsProcessed.values();
  }
}