sas-core/main/default/objects/IRR_CommunicationLog__c/IRR_CommunicationLog__c.object-meta.xml
<CustomObject>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CLOG-{00000000}</displayFormat>
        <label>Communication Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_SMSResponse__c/IRR_SMSResponse__c.object-meta.xml
<CustomObject>
    <description>Holds SMS MO (Mobile originated) forwarded from SFMC</description>
    <label>SMS Response</label>
    <nameField>
        <label>SMS Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_CommunicationLog__c.field-meta.xml
<CustomField>
    <fullName>IRR_CommunicationLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The communication log of the latest sent message to the customer at the time of the message.</description>
    <inlineHelpText>The communication log of the latest sent message to the customer at the time of the message.</inlineHelpText>
    <label>Communication Log</label>
    <referenceTo>IRR_CommunicationLog__c</referenceTo>
    <relationshipLabel>SMS Responses</relationshipLabel>
    <relationshipName>IRR_SMSResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_SMSResponsesSelector.cls
/**
* @author Ludvig Wälimaa, Deloitte
* @date 2020
*
*/

public class IRR_SEL_SMSResponsesSelector extends fflib_SObjectSelector
        implements IRR_SEL_ISMSResponsesSelector {

    public static IRR_SEL_ISMSResponsesSelector newInstance() {
        return (IRR_SEL_ISMSResponsesSelector)
                IRR_Application.Selector.newInstance(IRR_SMSResponse__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>
        {
                IRR_SMSResponse__c.Id,
                IRR_SMSResponse__c.IRR_CommunicationLog__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return IRR_SMSResponse__c.SObjectType;
    }

    public Database.QueryLocator getGDPRLogsQueryLocator(DateTime lastRetentionDate) {
        fflib_QueryFactory queryFactory = newQueryFactory()
                .setCondition('CreatedDate <= :lastRetentionDate');
        return Database.getQueryLocator(queryFactory.toSOQL());
    }
    
    public List<IRR_SMSResponse__c> selectSMSResponsesWithCommunicationLogs(Set<Id> comIds) {
        fflib_QueryFactory queryFactory = newQueryFactory()
        .setCondition('IRR_CommunicationLog__c IN :comIds');
        System.debug(queryFactory.toSOQL());
        return Database.query(queryFactory.toSOQL());
    }
}