sas-core/main/default/objects/IRR_AutomatedNoHandBag__mdt/IRR_AutomatedNoHandBag__mdt.object-meta.xml
<CustomObject>
    <label>AutomatedNoHandBag</label>
    <pluralLabel>AutomatedNoHandBags</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_AutomatedNoHandBag__mdt/fields/IRR_Arrival_Country__c.field-meta.xml
<CustomField>
    <fullName>IRR_Arrival_Country__c</fullName>
    <label>Arrival Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_AutomatedNoHandBag__mdt/fields/IRR_Duration__c.field-meta.xml
<CustomField>
    <fullName>IRR_Duration__c</fullName>
    <label>Duration</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_AutomatedNoHandBag__mdt/fields/IRR_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>IRR_Template_Name__c</fullName>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_AutomatedNoHandBagSelector.cls
public class IRR_SEL_AutomatedNoHandBagSelector extends fflib_SObjectSelector implements IRR_SEL_IAutomatedNoHandBagSelector  {


    public static IRR_SEL_IAutomatedNoHandBagSelector newInstance() 
    {

        return (IRR_SEL_IAutomatedNoHandBagSelector) IRR_Application.Selector.newInstance(
            IRR_AutomatedNoHandBag__mdt.SObjectType);
    }
    

    public List<Schema.SObjectField> getSObjectFieldList() {

        return new List<Schema.SObjectField> 
        { 

            IRR_AutomatedNoHandBag__mdt.DeveloperName,
            IRR_AutomatedNoHandBag__mdt.MasterLabel,
            IRR_AutomatedNoHandBag__mdt.IRR_Departure_Country__c,
            IRR_AutomatedNoHandBag__mdt.IRR_Arrival_Country__C,
            IRR_AutomatedNoHandBag__mdt.IRR_Template_Name__c,
            IRR_AutomatedNoHandBag__mdt.IRR_Duration__c

        };
    }

    public Schema.SobjectType getSObjectType() {

        return IRR_AutomatedNoHandBag__mdt.SobjectType ;

    }

    public Database.QueryLocator selectAutomatedNoHandBagMessages() {

        return Database.getQueryLocator(newQueryFactory().toSOQL());
    }
}