sas-core/main/default/objects/Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/Claim_Rebooked_Flight__c.object-meta.xml
<CustomObject>
    <description>The flights to a which customer claims they were rebooked to.</description>
    <label>Claim Rebooked Flight</label>
    <nameField>
        <displayFormat>CBF-{00000000}</displayFormat>
        <label>Claim Rebooked Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Rebooked Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Rebooked Flights</relationshipLabel>
    <relationshipName>Claim_Rebooked_Flights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Claim_Rebooked_Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>E.g. SK1234</description>
    <inlineHelpText>E.g. SK1234</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/claims/ClaimRebookedFlight.cls
public without sharing class ClaimRebookedFlight extends AbstractSObjectWrapper {
  public Claim_Rebooked_Flight__c underlyingSObject { get; private set; }

  public Id parentClaimId;
  public Date departureDate;
  public String flightNumber;

  public override void updateSObjectFields() {
    this.underlyingSObject.Claim__c = this.parentClaimId;
    this.underlyingSObject.Flight_Number__c = this.flightNumber;
    this.underlyingSObject.Departure_Date__c = this.departureDate;
  }
  private ClaimRebookedFlight() {
    this.underlyingSObject = new Claim_Rebooked_Flight__c();
  }

  public ClaimRebookedFlight(Claim parentClaim) {
    this();
    this.parentClaimId = parentClaim.id;
  }

  public ClaimRebookedFlight(Claim_Rebooked_Flight__c rebookedFlight) {
    super(rebookedFlight);
    this.underlyingSObject = rebookedFlight;

    this.departureDate = rebookedFlight.Departure_Date__c;
    this.flightNumber = rebookedFlight.Flight_Number__c;
  }
}