sas-core/main/default/objects/Claim__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EU261</fullName>
            </value>
            <value>
                <fullName>Downgrading/Denied boarding</fullName>
            </value>
            <value>
                <fullName>Ticket refund, personal injury</fullName>
            </value>
            <value>
                <fullName>Unruly passenger</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>sales information</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>PRM</fullName>
            </value>
            <value>
                <fullName>UM</fullName>
            </value>
            <value>
                <fullName>Travel extras</fullName>
            </value>
            <value>
                <fullName>Care costs</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/Redeemed_Compensation_Card__c.object-meta.xml
<CustomObject>
    <label>Redeemed Compensation Card</label>
    <nameField>
        <label>Card Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Redeemed Compensation Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The claim this compensation was paid out in relation to.</description>
    <inlineHelpText>The claim this compensation was paid out in relation to.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Compensation Cards</relationshipLabel>
    <relationshipName>Compensation_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Compensation_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Card_Number__c</fullName>
    <label>Compensation Card Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Service_Class__c.field-meta.xml
<CustomField>
    <fullName>Service_Class__c</fullName>
    <label>Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDBCOMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Redeemed_Compensation_Card__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/selectors/RedeemedCompensationCardsSelector.cls
public inherited sharing class RedeemedCompensationCardsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Redeemed_Compensation_Card__c.Id,
      Redeemed_Compensation_Card__c.Amount__c,
      Redeemed_Compensation_Card__c.Booking_Reference__c,
      Redeemed_Compensation_Card__c.Currency__c,
      Redeemed_Compensation_Card__c.Email__c,
      Redeemed_Compensation_Card__c.First_Name__c,
      Redeemed_Compensation_Card__c.Flight_Date__c,
      Redeemed_Compensation_Card__c.Flight_Number__c,
      Redeemed_Compensation_Card__c.Last_Name__c,
      Redeemed_Compensation_Card__c.Phone__c,
      Redeemed_Compensation_Card__c.Service_Class__c,
      Redeemed_Compensation_Card__c.Sub_Type__c,
      Redeemed_Compensation_Card__c.Ticket_Number__c,
      Redeemed_Compensation_Card__c.Type__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Redeemed_Compensation_Card__c.SObjectType;
  }

  public static RedeemedCompensationCardsSelector newInstance() {
    return (RedeemedCompensationCardsSelector) SAS_Service_Application.Selector.newInstance(
      Redeemed_Compensation_Card__c.SObjectType
    );
  }

  public List<Redeemed_Compensation_Card__c> selectById(Set<Id> ids) {
    return (List<Redeemed_Compensation_Card__c>) selectSObjectsById(ids);
  }

  public List<Redeemed_Compensation_Card__c> selectByClaimId(Set<Id> claimIds) {
    return (List<Redeemed_Compensation_Card__c>) Database.query(
      newQueryFactory().setCondition('Claim__c IN :claimIds').toSOQL()
    );
  }

  public List<Redeemed_Compensation_Card__c> selectByCardNumberAndBookingReference(
    String cardNumber,
    String bookingReference
  ) {
    return (List<Redeemed_Compensation_Card__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'Compensation_Card_Number__c = :cardNumber AND Booking_Reference__c = :bookingReference'
        )
        .toSOQL()
    );
  }
}