sas-core/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EU261</fullName>
            </value>
            <value>
                <fullName>Downgrading/Denied boarding</fullName>
            </value>
            <value>
                <fullName>Ticket refund, personal injury</fullName>
            </value>
            <value>
                <fullName>Unruly passenger</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>sales information</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>PRM</fullName>
            </value>
            <value>
                <fullName>UM</fullName>
            </value>
            <value>
                <fullName>Travel extras</fullName>
            </value>
            <value>
                <fullName>Care costs</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/Claim_Expense__c.object-meta.xml
<CustomObject>
    <description>A single expense claimed by a customer when submitting a claim.</description>
    <label>Claim Expense</label>
    <nameField>
        <displayFormat>CEN-{00000000}</displayFormat>
        <label>Claim Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The claim this expense is linked to.</description>
    <inlineHelpText>The claim this expense is linked to.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Claim_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim_Expense_Amount_In_SEK__c.field-meta.xml
<CustomField>
    <fullName>Claim_Expense_Amount_In_SEK__c</fullName>
    <description>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</description>
    <inlineHelpText>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</inlineHelpText>
    <label>Claim Expense Amount In SEK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Phone calls</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Under_Expense_Limit__c.field-meta.xml
<CustomField>
    <fullName>Under_Expense_Limit__c</fullName>
    <formula>IF(OR(AND(Claim_Expense_Amount_In_SEK__c &lt;= 4000, ISPICKVAL(Type__c , &quot;Accommodation&quot;)),
AND(Claim_Expense_Amount_In_SEK__c &lt;= 4000, ISPICKVAL(Type__c , &quot;Transportation&quot;)),
AND(Claim_Expense_Amount_In_SEK__c &lt;= 1000, ISPICKVAL(Type__c , &quot;Food&quot;)),
AND(Claim_Expense_Amount_In_SEK__c &lt;= 500, ISPICKVAL(Type__c , &quot;Phone calls&quot;))),
IMAGE(&quot;/img/msg_icons/confirm24.png&quot;, &quot;Under&quot;, 24,24),
IMAGE(&quot;/img/msg_icons/error24.png&quot;, &quot;Above&quot;,24,24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicate whether or not the receipt is under the limit based on the type of expense</inlineHelpText>
    <label>Under Expense Limit</label>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/ClaimExpensesSelector.cls
public inherited sharing class ClaimExpensesSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Claim_Expense__c.Id,
      Claim_Expense__c.Name,
      Claim_Expense__c.CreatedDate,
      Claim_Expense__c.LastModifiedDate,
      Claim_Expense__c.Amount__c,
      Claim_Expense__c.Claim__c,
      Claim_Expense__c.Claim_Expense_Amount_In_SEK__c,
      Claim_Expense__c.Currency__c,
      Claim_Expense__c.Date_of_Exchange_Calculation__c,
      Claim_Expense__c.Type__c,
      Claim_Expense__c.Under_Expense_Limit__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Claim_Expense__c.SObjectType;
  }

  public static ClaimExpensesSelector newInstance() {
    return (ClaimExpensesSelector) SAS_Service_Application.Selector.newInstance(
      Claim_Expense__c.SObjectType
    );
  }

  public List<Claim_Expense__c> selectById(Set<Id> ids) {
    return (List<Claim_Expense__c>) selectSObjectsById(ids);
  }

  public List<Claim_Expense__c> selectByClaimId(Set<Id> claimIds) {
    return (List<Claim_Expense__c>) Database.query(
      newQueryFactory().setCondition('Claim__c IN :claimIds').toSOQL()
    );
  }
}