sas-core/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EU261</fullName>
            </value>
            <value>
                <fullName>Downgrading/Denied boarding</fullName>
            </value>
            <value>
                <fullName>Ticket refund, personal injury</fullName>
            </value>
            <value>
                <fullName>Unruly passenger</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>sales information</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>PRM</fullName>
            </value>
            <value>
                <fullName>UM</fullName>
            </value>
            <value>
                <fullName>Travel extras</fullName>
            </value>
            <value>
                <fullName>Care costs</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/Claim_Expense__c.object-meta.xml
<CustomObject>
    <description>A single expense claimed by a customer when submitting a claim.</description>
    <label>Claim Expense</label>
    <nameField>
        <displayFormat>CEN-{00000000}</displayFormat>
        <label>Claim Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The claim this expense is linked to.</description>
    <inlineHelpText>The claim this expense is linked to.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Claim_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim_Expense_Amount_In_SEK__c.field-meta.xml
<CustomField>
    <fullName>Claim_Expense_Amount_In_SEK__c</fullName>
    <description>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</description>
    <inlineHelpText>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</inlineHelpText>
    <label>Claim Expense Amount In SEK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Phone calls</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/claims/ClaimExpense.cls
public without sharing class ClaimExpense extends AbstractSObjectWrapper {
  public Claim_Expense__c underlyingSObject { get; private set; }

  public Decimal amount;
  public Id parentClaimId;
  public Decimal amountInSEK;
  public Money.CurrencyCode currencyOfAmount;
  public Type type;
  public Date dateOfExchangeCalculation;

  public override void updateSObjectFields() {
    this.underlyingSObject.Amount__c = this.amount;
    this.underlyingSObject.Claim__c = this.parentClaimId;
    this.underlyingSObject.Claim_Expense_Amount_In_SEK__c = this.amountInSEK;
    this.underlyingSObject.Currency__c = Money.CURRENCY_ENUM_TO_PICKLIST_VALUE.get(
      this.currencyOfAmount
    );
    this.underlyingSObject.Type__c = TYPE_ENUM_TO_PICKLIST_VALUE.get(this.type);
    this.underlyingSObject.Date_of_Exchange_Calculation__c = this.dateOfExchangeCalculation; // TODO: Fixme. Should this be set automatically?
  }
  @TestVisible
  private ClaimExpense() {
    this.underlyingSObject = new Claim_Expense__c();
  }

  public ClaimExpense(Claim parentClaim) {
    this();
    this.parentClaimId = parentClaim.id;
  }

  public ClaimExpense(Claim_Expense__c expense) {
    super(expense);
    this.underlyingSObject = expense;

    this.amount = expense.Amount__c;
    this.parentClaimId = expense.Claim__c;
    this.amountInSEK = expense.Claim_Expense_Amount_In_SEK__c;
    this.currencyOfAmount = Money.CURRENCY_PICKLIST_VALUE_TO_ENUM.get(
      expense.Currency__c
    );
    this.type = TYPE_PICKLIST_VALUE_TO_ENUM.get(expense.Type__c);
    this.dateOfExchangeCalculation = expense.Date_of_Exchange_Calculation__c;
  }

  public enum Type {
    Accommodation,
    Food,
    Other,
    PhoneCalls,
    Transportation
  }

  private static final Map<String, Type> TYPE_PICKLIST_VALUE_TO_ENUM = new Map<String, Type>{
    'Accommodation' => Type.Accommodation,
    'Food' => Type.Food,
    'Other' => Type.Other,
    'Phone calls' => Type.PhoneCalls,
    'Transportation' => Type.Transportation
  };

  // TODO: Make private
  public static final Map<Type, String> TYPE_ENUM_TO_PICKLIST_VALUE = new Map<Type, String>{
    Type.Accommodation => 'Accommodation',
    Type.Food => 'Food',
    Type.Other => 'Other',
    Type.PhoneCalls => 'Phone calls',
    Type.Transportation => 'Transportation'
  };
}