sas-core/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Daily exchange rates for currency conversion calculations</description>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Exchange_Rate__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date on which this exchange rate is valid</description>
    <inlineHelpText>Date on which this exchange rate is valid</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/From_Currency__c.field-meta.xml
<CustomField>
    <fullName>From_Currency__c</fullName>
    <label>From Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/To_Currency__c.field-meta.xml
<CustomField>
    <fullName>To_Currency__c</fullName>
    <label>To Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/ExchangeRatesSelector.cls
public inherited sharing class ExchangeRatesSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Exchange_Rate__c.Id,
      Exchange_Rate__c.Name,
      Exchange_Rate__c.CreatedDate,
      Exchange_Rate__c.LastModifiedDate,
      Exchange_Rate__c.From_Currency__c,
      Exchange_Rate__c.To_Currency__c,
      Exchange_Rate__c.Rate__c,
      Exchange_Rate__c.Date__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Exchange_Rate__c.SObjectType;
  }

  public static ExchangeRatesSelector newInstance() {
    return (ExchangeRatesSelector) SAS_Service_Application.Selector.newInstance(
      Exchange_Rate__c.SObjectType
    );
  }

  public List<Exchange_Rate__c> selectById(Set<Id> ids) {
    return (List<Exchange_Rate__c>) selectSObjectsById(ids);
  }

  public List<Exchange_Rate__c> selectAll() {
    return (List<Exchange_Rate__c>) Database.query(newQueryFactory().toSOQL());
  }

  public List<Exchange_Rate__c> selectByFromCurrency(String fromCurrency) {
    return (List<Exchange_Rate__c>) Database.query(
      newQueryFactory()
        .setCondition('From_Currency__c = :fromCurrency')
        .toSOQL()
    );
  }

  public List<ExchangeRate> selectByFromCurrency(
    Money.CurrencyCode fromCurrency
  ) {
    String fromCurrencyString = fromCurrency.name();
    List<Exchange_Rate__c> sObjects = (List<Exchange_Rate__c>) Database.query(
      newQueryFactory()
        .setCondition('From_Currency__c = :fromCurrencyString')
        .toSOQL()
    );

    List<ExchangeRate> toReturn = new List<ExchangeRate>();

    if (sObjects == null) {
      return toReturn;
    }

    for (Exchange_Rate__c er : sObjects) {
      toReturn.add(new ExchangeRate(er));
    }

    return toReturn;
  }

  public List<Exchange_Rate__c> selectByCurrencies(
    String fromCurrency,
    String toCurrency
  ) {
    return (List<Exchange_Rate__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'From_Currency__c = :fromCurrency AND To_Currency__c = :toCurrency'
        )
        .toSOQL()
    );
  }

  public List<Exchange_Rate__c> selectByToCurrency(String toCurrency) {
    return (List<Exchange_Rate__c>) Database.query(
      newQueryFactory().setCondition('To_Currency__c = :toCurrency').toSOQL()
    );
  }

  public override String getOrderBy() {
    return 'Name';
  }
}