sas-core/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Daily exchange rates for currency conversion calculations</description>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Exchange_Rate__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date on which this exchange rate is valid</description>
    <inlineHelpText>Date on which this exchange rate is valid</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/From_Currency__c.field-meta.xml
<CustomField>
    <fullName>From_Currency__c</fullName>
    <label>From Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/To_Currency__c.field-meta.xml
<CustomField>
    <fullName>To_Currency__c</fullName>
    <label>To Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/money/ExchangeRate.cls
public without sharing class ExchangeRate extends AbstractSObjectWrapper {
  public Exchange_Rate__c underlyingSObject { get; private set; }

  public Date dateOfExchangeCalculation;
  public Money.CurrencyCode fromCurrency;
  public Money.CurrencyCode toCurrency;
  public Decimal rate;

  public override void updateSObjectFields() {
    this.underlyingSObject.Date__c = this.dateOfExchangeCalculation;
    this.underlyingSObject.From_Currency__c = Money.CURRENCY_ENUM_TO_PICKLIST_VALUE.get(
      this.fromCurrency
    );
    this.underlyingSObject.Rate__c = this.rate;
    this.underlyingSObject.To_Currency__c = Money.CURRENCY_ENUM_TO_PICKLIST_VALUE.get(
      this.toCurrency
    );
  }

  private ExchangeRate() {
    this.underlyingSObject = new Exchange_Rate__c();
  }

  public ExchangeRate(Exchange_Rate__c er) {
    super(er);
    this.underlyingSObject = er;

    this.dateOfExchangeCalculation = er.Date__c;
    this.fromCurrency = Money.CURRENCY_PICKLIST_VALUE_TO_ENUM.get(
      er.From_Currency__c
    );
    this.rate = er.Rate__c;
    this.toCurrency = Money.CURRENCY_PICKLIST_VALUE_TO_ENUM.get(
      er.To_Currency__c
    );
  }

  public override String toString() {
    return '' +
      this.fromCurrency +
      '-' +
      this.toCurrency +
      ': ' +
      this.rate +
      ' (' +
      this.dateOfExchangeCalculation +
      ')';
  }
}