sas-core/main/default/objects/FCS_CaseTag__c/FCS_CaseTag__c.object-meta.xml
<CustomObject>
    <description>Object used to store records about case reason to be able to report on multiple reasons</description>
    <label>Case Tag</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CaseReason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseId__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseId__c</fullName>
    <description>The id of the case that the tag belong to</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Tags</relationshipLabel>
    <relationshipName>Case_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FCS_CaseTag__c/fields/FCS_CaseTag__c.field-meta.xml
<CustomField>
    <fullName>FCS_CaseTag__c</fullName>
    <description>The tag for why the customer was contacting customer support</description>
    <label>Case Tag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEM issues</fullName>
            </value>
            <value>
                <fullName>Agent Helpdesk R</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>ATC/ATC Refund</fullName>
            </value>
            <value>
                <fullName>Availability / MCT</fullName>
            </value>
            <value>
                <fullName>Back-office R</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Baggage service R</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation/refund of ticket</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Code Share</fullName>
            </value>
            <value>
                <fullName>Conditions of carriage</fullName>
            </value>
            <value>
                <fullName>Contacts-Country</fullName>
            </value>
            <value>
                <fullName>Contacts-partners</fullName>
            </value>
            <value>
                <fullName>Contacts R</fullName>
            </value>
            <value>
                <fullName>Corp Account managers (SAS for busiess)</fullName>
            </value>
            <value>
                <fullName>Corporate product</fullName>
            </value>
            <value>
                <fullName>Corporate R</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>CR requests</fullName>
            </value>
            <value>
                <fullName>Customer Care R</fullName>
            </value>
            <value>
                <fullName>Delayed/damaged baggage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/CaseTagsSelector.cls
public inherited sharing class CaseTagsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      FCS_CaseTag__c.Id,
      FCS_CaseTag__c.Name,
      FCS_CaseTag__c.FCS_CaseId__c,
      FCS_CaseTag__c.FCS_CaseTag__c,
      FCS_CaseTag__c.FCS_Type__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return FCS_CaseTag__c.SObjectType;
  }

  public List<FCS_CaseTag__c> selectById(Set<Id> ids) {
    return (List<FCS_CaseTag__c>) selectSObjectsById(ids);
  }
  public List<FCS_CaseTag__c> selectByCaseId(Set<Id> caseIds) {
     fflib_QueryFactory caseTagsQF = newQueryFactory()
      .setCondition('FCS_CaseId__c in :caseIds');
      return (List<FCS_CaseTag__c>) Database.query(caseTagsQF.toSOQL());
  }
   public List<FCS_CaseTag__c> selectByChatId(Set<Id> chatIds) {
    ChatTranscriptsSelector chatTranscripts = (ChatTranscriptsSelector) SAS_Service_Application.Selector.newInstance(
      LiveChatTranscript.SObjectType
    );

    Set<Id> caseIds = new Set<Id>();
    for (LiveChatTranscript ct : chatTranscripts.selectById(chatIds)) {
      caseIds.add(ct.caseId);
    }
      return (List<FCS_CaseTag__c>) this.selectByCaseId(caseIds);
  }
}