sas-core/main/default/objects/C_Log__c/C_Log__c.object-meta.xml
<CustomObject>
    <description>Log record to store custom logs from the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_CommunicationLog__c/IRR_CommunicationLog__c.object-meta.xml
<CustomObject>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CLOG-{00000000}</displayFormat>
        <label>Communication Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>IRR_ExternalId__c</fullName>
    <description>The external id uniquely identifying the specific message in the message log.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_LastResponseDate__c.field-meta.xml
<CustomField>
    <fullName>IRR_LastResponseDate__c</fullName>
    <description>The last date and time when a response was received from a customer.</description>
    <inlineHelpText>The last date and time when a response was received from a customer.</inlineHelpText>
    <label>Last Response Date</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_Recipient__c.field-meta.xml
<CustomField>
    <fullName>IRR_Recipient__c</fullName>
    <label>Recipient</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_Response__c.field-meta.xml
<CustomField>
    <fullName>IRR_Response__c</fullName>
    <description>The response message from the customer. Separated by comma if multiple with the most recent response first.</description>
    <inlineHelpText>The response message from the customer. Separated by comma if multiple with the most recent response first.</inlineHelpText>
    <label>Response</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>IRR_ResponseMessage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Response Message</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/IRR_CommunicationLog__c/fields/IRR_Status__c.field-meta.xml
<CustomField>
    <fullName>IRR_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_SMSResponse__c/IRR_SMSResponse__c.object-meta.xml
<CustomObject>
    <description>Holds SMS MO (Mobile originated) forwarded from SFMC</description>
    <label>SMS Response</label>
    <nameField>
        <label>SMS Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_CommunicationLog__c.field-meta.xml
<CustomField>
    <fullName>IRR_CommunicationLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The communication log of the latest sent message to the customer at the time of the message.</description>
    <inlineHelpText>The communication log of the latest sent message to the customer at the time of the message.</inlineHelpText>
    <label>Communication Log</label>
    <referenceTo>IRR_CommunicationLog__c</referenceTo>
    <relationshipLabel>SMS Responses</relationshipLabel>
    <relationshipName>IRR_SMSResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_DateUTC__c.field-meta.xml
<CustomField>
    <fullName>IRR_DateUTC__c</fullName>
    <label>Date UTC</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_InfoFrom__c.field-meta.xml
<CustomField>
    <fullName>IRR_InfoFrom__c</fullName>
    <label>Info From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_InfoMessageNouns__c.field-meta.xml
<CustomField>
    <fullName>IRR_InfoMessageNouns__c</fullName>
    <label>Info Message Nouns</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/IRR_SMSResponse__c/fields/IRR_TimeUTC__c.field-meta.xml
<CustomField>
    <fullName>IRR_TimeUTC__c</fullName>
    <label>Time UTC</label>
    <type>Time</type>
</CustomField>

sas-core/main/default/classes/IRR_DOM_SMSResponses_Test.cls
/**
 * Test class for domain class for sms responses
 * @author Peter Södergrne
 */
@isTest private class IRR_DOM_SMSResponses_Test {
    /**
     * Creates the required communication log records to test the functionality
     */
    @testSetup static void setup(){
        String msg240 = 'TEST';
        for(Integer i=4;i<240;i++){
            msg240+='A';
        }
        IRR_CommunicationLog__c[] comLog = new IRR_CommunicationLog__c[]{
            new IRR_CommunicationLog__c(IRR_Status__c='Sent',IRR_Recipient__c='46700000000',IRR_ExternalId__c='SMSResponseTest0', IRR_ResponseMessage__c=true),
            new IRR_CommunicationLog__c(IRR_Status__c='Sent',IRR_Recipient__c='46700000001',IRR_ExternalId__c='SMSResponseTest1'),
            new IRR_CommunicationLog__c(IRR_Status__c='Sent',IRR_Recipient__c='46700000002',IRR_ExternalId__c='SMSResponseTest2',IRR_Response__c=msg240, IRR_ResponseMessage__c = true)
        };
        insert comLog;
        Datetime createdTime = Datetime.now().addHours(-1);
        Test.setCreatedDate(comLog[0].Id, createdTime);
        Test.setCreatedDate(comLog[1].Id, createdTime);
        Test.setCreatedDate(comLog[2].Id, createdTime);
    }

    /**
     * Tests that the most recent log is being used when associating a response to a log
     */
    @isTest static void selectMostRecentLog(){
        insert new IRR_CommunicationLog__c(IRR_Status__c='Sent',IRR_Recipient__c='46700000000',IRR_ExternalId__c='SMSResponseTest11', IRR_ResponseMessage__c=true);
        insert new IRR_SMSResponse__c(IRR_InfoMessageNouns__c='MSG1',IRR_InfoFrom__c='46700000000',IRR_DateUTC__c=Date.newInstance(2020,05,01),IRR_TimeUTC__c=Time.newInstance(8,30,24,0));
        IRR_CommunicationLog__c comLog0 = [SELECT Id,IRR_Status__c,IRR_LastResponseDate__c,IRR_Response__c FROM IRR_CommunicationLog__c WHERE IRR_ExternalId__c='SMSResponseTest0'];
        IRR_CommunicationLog__c comLog11 = [SELECT Id,IRR_Status__c,IRR_LastResponseDate__c,IRR_Response__c FROM IRR_CommunicationLog__c WHERE IRR_ExternalId__c='SMSResponseTest11'];
        System.assertEquals('Sent', comLog0.IRR_Status__c);
        System.assertEquals(null, comLog0.IRR_LastResponseDate__c);
        System.assertEquals(null, comLog0.IRR_Response__c);
        System.assertEquals('Responded', comLog11.IRR_Status__c);
        System.assertEquals(DateTime.newInstanceGmt(2020,05,01,8,30,24), comLog11.IRR_LastResponseDate__c);
        System.assertEquals('MSG1', comLog11.IRR_Response__c);
        
        System.assertEquals(0,[SELECT Id FROM C_Log__c].size());
    }

    /**
     * Tests that a response which cannot be associated to a log does not cause an error
     */
    @isTest static void noLogPresent(){
        insert new IRR_SMSResponse__c(IRR_InfoMessageNouns__c='MSG1',IRR_InfoFrom__c='46730000000',IRR_DateUTC__c=Date.newInstance(2020,05,01),IRR_TimeUTC__c=Time.newInstance(8,30,24,0));
        
        System.assertEquals(1,[SELECT Id FROM C_Log__c WHERE Severity__c='Warning'].size());
    }

    /**
     * Tests that message is properly truncated when too long to store
     */
    @isTest static void truncateMessage(){
        insert new IRR_CommunicationLog__c(IRR_Status__c='Sent',IRR_Recipient__c='46700000002',IRR_ExternalId__c='SMSResponseTest22', IRR_ResponseMessage__c=false);
        insert new IRR_SMSResponse__c(IRR_InfoMessageNouns__c='MESSAGE LONG ENOUGH TO BREAK 255 CHARS',IRR_InfoFrom__c='46700000002',IRR_DateUTC__c=Date.newInstance(2020,05,01),IRR_TimeUTC__c=Time.newInstance(8,30,24,0));
        IRR_CommunicationLog__c comLog2 = [SELECT Id,IRR_Status__c,IRR_LastResponseDate__c,IRR_Response__c FROM IRR_CommunicationLog__c WHERE IRR_ExternalId__c='SMSResponseTest2'];
        IRR_CommunicationLog__c comLog22 = [SELECT Id,IRR_Status__c,IRR_LastResponseDate__c,IRR_Response__c FROM IRR_CommunicationLog__c WHERE IRR_ExternalId__c='SMSResponseTest22'];
        System.assertEquals('Sent', comLog22.IRR_Status__c);
        System.assertEquals(null, comLog22.IRR_LastResponseDate__c);
        System.assertEquals(null, comLog22.IRR_Response__c);
        System.assertEquals('Responded', comLog2.IRR_Status__c);
        System.assertEquals(DateTime.newInstanceGmt(2020,05,01,8,30,24), comLog2.IRR_LastResponseDate__c);
        System.assertEquals(255, comLog2.IRR_Response__c.length());
        System.assertEquals(0,[SELECT Id FROM C_Log__c].size());
    }
}