sas-core/main/default/objects/C_Log__c/C_Log__c.object-meta.xml
<CustomObject>
    <description>Log record to store custom logs from the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/C_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The logged message.</description>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/classes/batchables/ChangeCasesReadOnlyBatchable.cls
public without sharing class ChangeCasesReadOnlyBatchable implements Database.Batchable<Case>, Database.Stateful {
  public List<C_Log__c> logs;
  public ChangeCasesReadOnlyBatchable() {
    logs = new List<C_Log__c>();
  }

  public Iterable<Case> start(Database.BatchableContext bc) {
    List<Case> allCases = new List<Case>();
    for (String department : Cases.departmentToDaysInactive.keySet()) {
      allCases.addAll(
        CasesSelector.newInstance().selectInactiveByDepartment(department)
      );
    }
    return allCases;
  }

  public void execute(Database.BatchableContext bc, List<Case> caseToUpdate) {
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();

    try {
      Cases cases = Cases.newInstance(caseToUpdate);
      cases.markAsReadOnly(uow);
      uow.commitWork();
    } catch (Exception e) {
      logs.add(new C_Log__c(Message__c = e.getMessage()));
      throw e;
    }
  }

  public void finish(Database.BatchableContext BC) {
    insert logs;
  }
}