sas-core/main/default/objects/Refund_Request__c/Refund_Request__c.object-meta.xml
<CustomObject>
    <label>Refund Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Refund Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Refund_Request__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/Refund_Requests.cls
public without sharing class Refund_Requests extends ApplicationDomain {
  public Refund_Requests(List<SObject> records) {
    super(records);
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Refund_Requests(records);
    }
  }

  public override void onBeforeInsert() {
    capitalisePNR();
  }

  public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    capitalisePNR();
  }

  private void capitalisePNR() {
    for (Refund_Request__c rq : (List<Refund_Request__c>) Records) {
      if (rq.PNR__c != null) {
        rq.PNR__c = rq.PNR__c.toUpperCase();
      }
    }
  }
}