sas-core/main/default/objects/Refund_Request__c/Refund_Request__c.object-meta.xml
<CustomObject>
    <label>Refund Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Refund Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Refund_Request__c/fields/Country_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Purchase__c</fullName>
    <label>Country of Purchase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Refund_Macro__c.field-meta.xml
<CustomField>
    <fullName>Refund_Macro__c</fullName>
    <label>Refund Macro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>1 - REFUND TAX</fullName>
            </value>
            <value>
                <fullName>2 - REFUND PART</fullName>
            </value>
            <value>
                <fullName>3 - REFUND FLEX+RESTRICT</fullName>
            </value>
            <value>
                <fullName>4 - REFUNDS 24 HRS</fullName>
            </value>
            <value>
                <fullName>5 - REFUND 24/12 HRS</fullName>
            </value>
            <value>
                <fullName>6 - REFUND Residual Value</fullName>
            </value>
            <value>
                <fullName>7 - REFUND FLEX</fullName>
            </value>
            <value>
                <fullName>8 - REFUND EB</fullName>
            </value>
            <value>
                <fullName>9 - REFUND IRR</fullName>
            </value>
            <value>
                <fullName>10 - CANCELLED BY</fullName>
            </value>
            <value>
                <fullName>11 - CANCELLED ONLINE ON BEHALF OF CUSTOMER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Refund_Request__c/fields/Ticket_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Numbers__c</fullName>
    <label>Ticket Numbers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/classes/selectors/Refund_RequestsSelector.cls
public inherited sharing class Refund_RequestsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Refund_Request__c.Id,
      Refund_Request__c.Country_of_Purchase__c,
      Refund_Request__c.Note__c,
      Refund_Request__c.PNR__c,
      Refund_Request__c.Refund_Macro__c,
      Refund_Request__c.Ticket_Numbers__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Refund_Request__c.SObjectType;
  }

  public static Refund_RequestsSelector newInstance() {
    return (Refund_RequestsSelector) SAS_Service_Application.Selector.newInstance(
      Refund_Request__c.SObjectType
    );
  }

  public List<Refund_Request__c> selectById(Set<Id> ids) {
    return (List<Refund_Request__c>) selectSObjectsById(ids);
  }

  public override String getOrderBy() {
    return 'Name';
  }
}