sas-core/main/default/objects/IRR_EventLog__c/IRR_EventLog__c.object-meta.xml
<CustomObject>
    <label>Event Log</label>
    <nameField>
        <displayFormat>ELOG-{00000000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_Delayed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>IRR_Delayed_Minutes__c</fullName>
    <label>Delayed Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_Flight_Ref__c.field-meta.xml
<CustomField>
    <fullName>IRR_Flight_Ref__c</fullName>
    <label>Flight Ref</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_FlightId__c.field-meta.xml
<CustomField>
    <fullName>IRR_FlightId__c</fullName>
    <externalId>true</externalId>
    <label>Flight Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>IRR_ScheduleTime__c</fullName>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_Station_Departure__c.field-meta.xml
<CustomField>
    <fullName>IRR_Station_Departure__c</fullName>
    <label>Station Departure</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/Is_Communication_Send__c.field-meta.xml
<CustomField>
    <fullName>Is_Communication_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Communication Send</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/IRR_BCH_Scheduled_IcouponEvent.cls
global with sharing class IRR_BCH_Scheduled_IcouponEvent extends SBS_ScheduledBatch implements Schedulable {
  public Static String eventType = 'flightDelayDeparture';
    /**
     overriding the absract method to set batch class Params
     */
     global override void setVariables(
      String obj,
      Integer retentionPeriod,
      string caseField,
      String caseType,
      String batchName,
      String scheduledBatchRunComponentId
    )
    {
    }

     /**
        Iterates over all Event Logs in the queued Status for manual communication
        @param bc The batch context
    */

  global Database.QueryLocator start(Database.BatchableContext bc) {
    this.setUseTransactionControl(false);
    return IRR_SEL_EventLogsSelector.newInstance()
      .getQueuedIcouponBatchQueryLocator();
  }
  
  /**
        Processes the Event Logs for scheduled manual messages
        @param bc The batchable context of the batch job
        @param sObjScope The scheduled Event Logs to process
    */
    global override void executeScope(
        Database.BatchableContext bc,
        SObject[] sObjScope
      ) {
        List<IRR_EventLog__c>  eventLogMap = new List<IRR_EventLog__c>();
        for(SObject sObj :sObjScope){
            IRR_EventLog__c evtLog = (IRR_EventLog__c)sObj;
            evtLog.Is_Communication_Send__c = true;
            eventLogMap.add(evtLog); 
            IRR_MOD_DelayInfo delayInfo = new IRR_MOD_DelayInfo();
            delayInfo.stationDeparture = evtLog.IRR_Station_Departure__c;
            delayInfo.delayedMinutes = (Integer)evtLog.IRR_Delayed_Minutes__c;
            delayInfo.scheduledTimeOfDepartureUTC = evtLog.IRR_ScheduleTime__c;
            delayInfo.scheduledTimeOfDepartureLocal = evtLog.IRR_ScheduleTime__c;
            delayInfo.flightRef = evtLog.IRR_Flight_Ref__c;
            delayInfo.flightId = evtLog.IRR_FlightId__c;
            delayInfo.estimatedTimeOfDepartureLocal = System.now();
            IRR_SVC_CommunicationService.processEvent(eventType, delayInfo);
        }
        Update eventLogMap;
      }

      global override void finishOverridable(Database.BatchableContext bc) {
    }
  
    global void execute(SchedulableContext ctx) {
      SBS_ScheduledBatch processQueuedManual = new IRR_BCH_Scheduled_IcouponEvent();
      ID batchprocessid = Database.executeBatch(processQueuedManual, 1);
    }
}