sas-core/main/default/objects/IRR_EventLog__c/IRR_EventLog__c.object-meta.xml
<CustomObject>
    <label>Event Log</label>
    <nameField>
        <displayFormat>ELOG-{00000000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_FlightId__c.field-meta.xml
<CustomField>
    <fullName>IRR_FlightId__c</fullName>
    <externalId>true</externalId>
    <label>Flight Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_EventLog__c/fields/IRR_ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>IRR_ScheduleTime__c</fullName>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_EventLogsSelector_Test.cls
/**
* @author Chetan Singh, CoforgeTech
* @date 2020
*
* @description Test class for Event Logs selector.
*/
@isTest
private class IRR_SEL_EventLogsSelector_Test {
    
    @isTest
    static void testGetQueuedCheckinQueryLocator(){

        //Given
        List<IRR_EventLog__c> eventLogs = new List<IRR_EventLog__c>{
            new IRR_EventLog__c(IRR_FlightId__c='TEST_FLIGHT', IRR_ScheduleTime__c=System.Now().addDays(-1))
        };

        insert eventLogs;

        //when
        Database.QueryLocator queryResult = IRR_SEL_EventLogsSelector.newInstance().getQueuedCheckinQueryLocator();
        // Get an iterator
        Database.QueryLocatorIterator i =  queryResult.iterator();
    
        //then
        System.assert(i.hasNext(),'Expected to find 1 record hence hasnext to be true');
    }

}