sas-core/main/default/objects/Claim_Expense__c/Claim_Expense__c.object-meta.xml
<CustomObject>
    <description>A single expense claimed by a customer when submitting a claim.</description>
    <label>Claim Expense</label>
    <nameField>
        <displayFormat>CEN-{00000000}</displayFormat>
        <label>Claim Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Claim_Expense__c/fields/Claim_Expense_Amount_In_SEK__c.field-meta.xml
<CustomField>
    <fullName>Claim_Expense_Amount_In_SEK__c</fullName>
    <description>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</description>
    <inlineHelpText>Shows the claim expense amount converted to SEK. Useful when generating reports and comparing expenses.</inlineHelpText>
    <label>Claim Expense Amount In SEK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Claim_Expense__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Daily exchange rates for currency conversion calculations</description>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Exchange_Rate__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date on which this exchange rate is valid</description>
    <inlineHelpText>Date on which this exchange rate is valid</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/From_Currency__c.field-meta.xml
<CustomField>
    <fullName>From_Currency__c</fullName>
    <label>From Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/classes/domain/claims/ClaimExpenses.cls
public without sharing class ClaimExpenses extends ApplicationDomain {
  public ClaimExpenses(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<Claim_Expense__c>) Records;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new ClaimExpenses(records);
    }
  }

  public static ClaimExpenses newInstance(List<Claim_Expense__c> sObjectList) {
    return (ClaimExpenses) SAS_Service_Application.Domain.newInstance(
      sObjectList
    );
  }

  public override void onBeforeInsert() {
    updateAmountInSEK();
  }

  public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    updateAmountInSEK();
  }

  public List<Claim_Expense__c> instanceRecords;

  /**
   * Handles currency conversion calculation to SEK for the Claim_Expense_amount_in_SEK__c field.
   */
  public void updateAmountInSEK() {
    ExchangeRatesSelector exchangeRateSel = ExchangeRatesSelector.newInstance();
    Map<String, Exchange_Rate__c> exchangeRatesToSEK = new Map<String, Exchange_Rate__c>();

    for (Exchange_Rate__c er : exchangeRateSel.selectByToCurrency('SEK')) {
      exchangeRatesToSEK.put(er.From_Currency__c, er);
    }

    for (Claim_Expense__c claimExpense : instanceRecords) {
      if (claimExpense.Currency__c == 'SEK') {
        claimExpense.Claim_Expense_Amount_In_SEK__c = claimExpense.Amount__c;
        claimExpense.Date_of_Exchange_Calculation__c = Date.today();
      } else {
        Exchange_Rate__c exchangeRateToSEK = exchangeRatesToSEK.get(
          claimExpense.Currency__c
        );

        if (exchangeRateToSEK != null) {
          claimExpense.Claim_Expense_Amount_In_SEK__c =
            claimExpense.Amount__c * exchangeRateToSEK.Rate__c;
          claimExpense.Date_of_Exchange_Calculation__c = exchangeRateToSEK.Date__c;
        }
      }
    }
  }
}