sas-core/main/default/objects/CARE_Claim__c/CARE_Claim__c.object-meta.xml
<CustomObject>
    <description>A claim which has been handled in CARE.</description>
    <label>CARE Claim</label>
    <nameField>
        <label>CARE Claim Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CARE_Claim__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Customer_Claim_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Claim_Category__c</fullName>
    <formula>TEXT(LIA_Claim__r.Customer_Claim_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Claim Category</label>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Customer_Claim_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Claim_Category__c</fullName>
    <label>Customer Claim Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Travel extras bought not rendered</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
            <value>
                <fullName>Airport experience</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Accident &amp; injury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <description>Passenger Irregularity Report</description>
    <label>PIR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/recordTypes/CustomerClaim.recordType-meta.xml
<RecordType>
    <fullName>CustomerClaim</fullName>
    <active>true</active>
    <description>Record type to differentiate the customer claims</description>
    <label>CustomerClaim</label>
</RecordType>

sas-core/main/default/classes/controllers/SimilarCasesControllerTest.cls
@IsTest
public with sharing class SimilarCasesControllerTest {
  @IsTest
  public static void gettingSimilarCasesShouldFetchSFCasesAndCARECases() {
    // Given
    String sharedBookingReference = 'ABC123';

    TestDataFactories.CasesClaims similar = TestDataFactories.createCasesWithClaims(
      2,
      null,
      new Map<Schema.SObjectField, Object>{
        LIA_Claim__c.Liability_PNR__c => sharedBookingReference,
        LIA_Claim__c.Flight_Number__c => 'SK1',
        LIA_Claim__c.Flight_Date__c => Date.today(),
        LIA_Claim__c.Customer_Claim_Category__c => 'Flight disruptions',
        LIA_Claim__c.RecordTypeId => Claim.getRecordTypeIdByEnum(
          Claim.RecordType.CustomerClaim
        )
      }
    );
    TestDataFactories.CasesClaims different = TestDataFactories.createCasesWithClaims(
      1,
      null,
      new Map<Schema.SObjectField, Object>{
        LIA_Claim__c.Liability_PNR__c => '123ABC',
        LIA_Claim__c.Flight_Number__c => 'LH2',
        LIA_Claim__c.Flight_Date__c => Date.today().addDays(1),
        LIA_Claim__c.Customer_Claim_Category__c => 'Flight disruptions',
        LIA_Claim__c.RecordTypeId => Claim.getRecordTypeIdByEnum(
          Claim.RecordType.CustomerClaim
        )
      }
    );

    Case thisCase = similar.cases[0];
    Case similarCase = similar.cases[1];
    Case differentCase = different.cases[0];

    LIA_Claim__c cl = similar.claims[1];
    cl.PIR__c = 'ARNSK12456';
    cl.Liability_PNR__c = '12345D';
    cl.Flight_Number__c = 'SK2';
    cl.Flight_Date__c = Date.today().addDays(2);
    update cl;

    CARE_Claim__c similarCAREClaim = new CARE_Claim__c(
      Booking_Reference__c = sharedBookingReference
    );
    insert similarCAREClaim;

    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    // When
    List<SimilarCasesController.SimilarCasesJSON> foundCases = SimilarCasesController.getSimilarCasesForCase(
      thisCase.Id
    );
    Test.stopTest();

    // Then
    System.assertEquals(
      3, // CARE claim + Similar case + the case itself
      foundCases.size(),
      'Similar SF case and CARE case should have been found.'
    );

    Case foundSFCase;
    CARE_Claim__c foundCARECase;

    for (SimilarCasesController.SimilarCasesJSON c : foundCases) {
      if (c.type == 'Case' && c.caseData.Id != thisCase.Id) {
        foundSFCase = c.caseData;
      } else {
        foundCARECase = c.claimData;
      }
    }

    System.assertNotEquals(null, foundSFCase, 'Should have found a SF case.');
    System.assertNotEquals(
      null,
      foundCARECase,
      'Should have found a CARE case.'
    );
  }
}