sas-core/main/default/objects/CARE_Claim__c/CARE_Claim__c.object-meta.xml
<CustomObject>
    <description>A claim which has been handled in CARE.</description>
    <label>CARE Claim</label>
    <nameField>
        <label>CARE Claim Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CARE_Claim__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <externalId>true</externalId>
    <label>Case Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Customers__c.field-meta.xml
<CustomField>
    <fullName>Customers__c</fullName>
    <label>Customers</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Date_Closed_In_CARE__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed_In_CARE__c</fullName>
    <label>Date Closed In CARE</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Date_Created_In_CARE__c.field-meta.xml
<CustomField>
    <fullName>Date_Created_In_CARE__c</fullName>
    <label>Date Created In CARE</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Decisions__c.field-meta.xml
<CustomField>
    <fullName>Decisions__c</fullName>
    <label>Decisions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Last_Modified_In_CARE__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_In_CARE__c</fullName>
    <label>Last Modified In CARE</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Settlements__c.field-meta.xml
<CustomField>
    <fullName>Settlements__c</fullName>
    <label>Settlements</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

sas-core/main/default/classes/domain/CAREClaims.cls
public without sharing class CAREClaims extends ApplicationDomain {
  public CAREClaims(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<CARE_Claim__c>) Records;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new CAREClaims(records);
    }
  }

  public static CAREClaims newInstance(List<CARE_Claim__c> sObjectList) {
    return (CAREClaims) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  public List<CARE_Claim__c> instanceRecords;

  public override void onApplyDefaults() {
    for (CARE_Claim__c claim : instanceRecords) {
      if (claim.Name == null) {
        claim.Name = claim.Case_Id__c;
      }
    }
  }

  public CAREClaims upsertToDB() {
    // The upsert operation seems to fail due to a race condition between two threads
    // trying to upsert the records simultaneously. One thread succeeds and the other
    // fails with a duplicate value exception. Retrying fixes this because then
    // the records are simply updated.
    try {
      upsert instanceRecords Case_Id__c;
    } catch (DMLException e) {
      if (e.getDmlType(0) == StatusCode.DUPLICATE_VALUE) {
        upsert instanceRecords Case_Id__c;
      }
    }

    return this;
  }

  public static CAREClaims create(FetchCAREClaimsResponse claimsResponse) {
    if (claimsResponse == null || claimsResponse.response.cases.size() == 0) {
      return null;
    }

    List<CARE_Claim__c> toCreate = new List<CARE_Claim__c>();

    for (FetchCAREClaimsResponse.Cases claim : claimsResponse.response.cases) {
      toCreate.add(parseResponseToSObject(claim));
    }

    return new CAREClaims(toCreate);
  }

  private static CARE_Claim__c parseResponseToSObject(
    FetchCAREClaimsResponse.Cases responseCase
  ) {
    String parsedSettlements = '';
    String parsedNotes = '';
    String parsedDecisions = '';
    String parsedCustomers = '';
    String parsedCategories = '';

    Map<String, String> customerIdToName = new Map<String, String>();
    Map<String, String> dictionary = new Map<String, String>{
      '841' => 'Refund of tickets and ancillary',
      '842' => 'Goodwill Compensation',
      '846' => 'Liability - Other',
      '849' => 'Liability - Care (Meal, Hotel, Transportation)',
      '850' => 'Liability - Downgrading Compensation',
      '851' => 'Liability - EU 261 Compensation',
      '852' => 'Liability - Denied Boarding Compensation',
      '854' => 'Liability - Baggage Pilfered',
      '855' => 'Liability - Baggage Delayed/missing/lost',
      '856' => 'Liability - Baggage Damaged',
      '1066' => 'SEK',
      '1067' => 'DKK',
      '1068' => 'NOK',
      '1069' => 'EUR',
      '1070' => 'AUD',
      '1071' => 'CAD',
      '1072' => 'CZK',
      '1073' => 'HKD',
      '1074' => 'JPY',
      '1075' => 'NZD',
      '1076' => 'PLN',
      '1077' => 'SGD',
      '1078' => 'CHF',
      '1079' => 'GBP',
      '1080' => 'USD',
      '1966' => 'CNY',
      '1967' => 'RUB',
      '1968' => 'THB'
    };

    for (FetchCAREClaimsResponse.Customers customer : responseCase.customers) {
      String name = customer.cusFirstname + ' ' + customer.cusLastname;
      customerIdToName.put(customer.customerId, name);

      parsedCustomers += name + '<br>';
    }

    for (FetchCAREClaimsResponse.Notes note : responseCase.notes) {
      String toAdd =
        '<b>Note ' +
        note.noteSeq +
        ' for ' +
        customerIdToName.get(note.customerId) +
        '</b><br>' +
        note.noteValue +
        '<br><br>';

      parsedNotes += toAdd;
    }

    Set<String> uniqueCategoryNames = new Set<String>();
    for (
      FetchCAREClaimsResponse.Categories category : responseCase.categories
    ) {
      uniqueCategoryNames.add(category.CatName);
    }
    for (String name : uniqueCategoryNames) {
      parsedCategories += name + '<br>';
    }

    for (FetchCAREClaimsResponse.Decisions decision : responseCase.decisions) {
      parsedDecisions += decision.dicName + '<br>';
    }

    for (
      FetchCAREClaimsResponse.Settlements settlement : responseCase.settlements
    ) {
      if (settlement.amount != null) {
        String toAdd = '<b>Settlement</b><br>';
        toAdd +=
          'Total: ' +
          settlement.amount +
          ' ' +
          dictionary.get(settlement.settlementCurrency) +
          '<br>';

        toAdd +=
          'Created: ' +
          settlement.dateCreated +
          '<br>Approved: ' +
          settlement.dateApproved +
          '<br>';

        if (
          settlement.settlementItems != null &&
          !settlement.settlementItems.isEmpty()
        ) {
          toAdd += '<b>Items</b><br>';
          for (
            FetchCAREClaimsResponse.SettlementItems item : settlement.settlementItems
          ) {
            String settlementItem = '* ';
            if (
              item.stiEurobonusPoints != null &&
              item.stiEurobonusPoints > 0
            ) {
              settlementItem +=
                item.stiEurobonusPoints +
                ' points for ' +
                customerIdToName.get(item.stiCusId) +
                '. Comments: ' +
                item.stiComments +
                '<br><br>';
            } else {
              settlementItem +=
                item.stiAmount +
                ' ' +
                dictionary.get(settlement.settlementCurrency) +
                ' for ' +
                customerIdToName.get(item.stiCusId) +
                '. Cost Acc: ' +
                dictionary.get(item.stiCostAcc) +
                '. Comments: ' +
                item.stiComments +
                '<br><br>';
            }
            toAdd += settlementItem;
          }
        }

        toAdd += '<br><br>';

        parsedSettlements += toAdd;
      }
    }

    return new CARE_Claim__c(
      Case_Id__c = responseCase.caseId,
      Booking_Reference__c = responseCase.pnr,
      Customers__c = parsedCustomers,
      Categories__c = parsedCategories,
      Decisions__c = parsedDecisions,
      Departure_Date__c = responseCase.flightDate != null
        ? Date.newInstance(
            responseCase.flightDate.year(),
            responseCase.flightDate.month(),
            responseCase.flightDate.day()
          )
        : null,
      Flight_Number__c = responseCase.flightNumber,
      Name = responseCase.caseId,
      Notes__c = parsedNotes,
      Date_Closed_In_CARE__c = responseCase.dateClosed,
      Date_Created_In_CARE__c = responseCase.dateCreated,
      Last_Modified_In_CARE__c = responseCase.lastModified,
      PIR__c = responseCase.pir,
      Settlements__c = parsedSettlements
    );
  }
}