sas-core/main/default/objects/CARE_Claim__c/CARE_Claim__c.object-meta.xml
<CustomObject>
    <description>A claim which has been handled in CARE.</description>
    <label>CARE Claim</label>
    <nameField>
        <label>CARE Claim Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CARE_Claim__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <label>Booking Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <externalId>true</externalId>
    <label>Case Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Date_Created_In_CARE__c.field-meta.xml
<CustomField>
    <fullName>Date_Created_In_CARE__c</fullName>
    <label>Date Created In CARE</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/CARE_Claim__c/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <description>Passenger Irregularity Report</description>
    <label>PIR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/CAREClaimsSelector.cls
public inherited sharing class CAREClaimsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      CARE_Claim__c.Id,
      CARE_Claim__c.Booking_Reference__c,
      CARE_Claim__c.Case_Id__c,
      CARE_Claim__c.Date_Created_In_CARE__c,
      CARE_Claim__c.Flight_Number__c,
      CARE_Claim__c.Name,
      CARE_Claim__c.PIR__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return CARE_Claim__c.SObjectType;
  }

  public static CAREClaimsSelector newInstance() {
    return (CAREClaimsSelector) SAS_Service_Application.Selector.newInstance(
      CARE_Claim__c.SObjectType
    );
  }

  public List<CARE_Claim__c> selectById(Set<Id> ids) {
    return (List<CARE_Claim__c>) selectSObjectsById(ids);
  }

  public List<CARE_Claim__c> selectSimilarCasesById(Id caseId) {
    List<LIA_Claim__c> claims = ClaimsSelector.newInstance()
      .selectByCaseIdWithCustomers(new Set<Id>{ caseId });
    if (claims == null || claims.size() == 0) {
      return new List<CARE_Claim__c>();
    }

    LIA_Claim__c claimForCase = claims[0];

    String bankAccountNumber = claimForCase.Bank_Account_Number__c;
    String bookingReference = claimForCase.Liability_PNR__c;
    String pirNumber = claimForCase.PIR__c;

    String whereQuery = '';

    if (!String.isBlank(bookingReference)) {
      whereQuery += 'Booking_Reference__c = :bookingReference';
    }

    if (!String.isBlank(pirNumber)) {
      if (String.isBlank(whereQuery)) {
        whereQuery += 'PIR__c = :pirNumber';
      } else {
        whereQuery += ' OR PIR__c = :pirNumber';
      }
    }

    return (List<CARE_Claim__c>) Database.query(
      newQueryFactory().setCondition(whereQuery).toSOQL()
    );
  }
}