sas-core/main/default/objects/FlightIrregularities__c/FlightIrregularities__c.object-meta.xml
<CustomObject>
    <description>Holds information about delays and cancellations.</description>
    <label>FlightIrregularities</label>
    <nameField>
        <label>FlightIrregularities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlightIrregularities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FlightIrregularities__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The cancellation/delay code parsed from TEDS</description>
    <inlineHelpText>The cancellation/delay code parsed from TEDS</inlineHelpText>
    <label>Cancellation code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Eligible_For_EU261__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_EU261__c</fullName>
    <label>Eligible For EU261</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>The reason why the flight was delayed/cancelled</description>
    <inlineHelpText>The reason why the flight was delayed/cancelled</inlineHelpText>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the irregularity (cancellation/delay)</description>
    <inlineHelpText>The type of the irregularity (cancellation/delay)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/flights/FlightIrregularity_Test.cls
@IsTest
public with sharing class FlightIrregularity_Test {
  @IsTest
  public static void WEATwithEUYesShouldBeEligible() {
    FlightIrregularities__c EUYesWEAT = new FlightIrregularities__c(
      Code__c = 'WEAT',
      Reason__c = '',
      Type__c = 'Cancellation (departure)',
      Eligible_For_EU261__c = 'Yes'
    );

    Boolean isWithinSASControl = new FlightIrregularity(EUYesWEAT)
      .isWithinSASControl();

    System.assert(
      isWithinSASControl,
      'An irregularity which is not normally within SAS control with Eligible_For_EU261__c = "YES" should be in SAS control.'
    );
  }
  @IsTest
  public static void WEATwithEUTentativeShouldNotBeEligible() {
    FlightIrregularities__c EUTentativeWEAT = new FlightIrregularities__c(
      Code__c = 'WEAT',
      Reason__c = '',
      Type__c = 'Cancellation (departure)',
      Eligible_For_EU261__c = 'Tentative'
    );

    Boolean isWithinSASControl = new FlightIrregularity(EUTentativeWEAT)
      .isWithinSASControl();

    System.assert(
      !isWithinSASControl,
      'An irregularity which is not normally within SAS control with Eligible_For_EU261__c = "Tentativ" should not be in SAS control.'
    );
  }
  @IsTest
  public static void TECHwithEUNoShouldNotBeEligible() {
    FlightIrregularities__c EUNoTECH = new FlightIrregularities__c(
      Code__c = 'TECH',
      Reason__c = '',
      Type__c = 'Cancellation (departure)',
      Eligible_For_EU261__c = 'No'
    );

    Boolean isWithinSASControl = new FlightIrregularity(EUNoTECH)
      .isWithinSASControl();

    System.assert(!isWithinSASControl, 'An irregularity which is normally within SAS control with Eligible_For_EU261__c = "NO" should not be in SAS control.');
  }
}