sas-core/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <description>For all the cases related to a voice call</description>
    <label>Call</label>
</RecordType>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/ManagedSocialAccounts__mdt.object-meta.xml
<CustomObject>
    <description>Setting used to identify weather the post/tweet had been posted by SAS or by other account</description>
    <label>Managed Social Account</label>
    <pluralLabel>Managed Social Accounts</pluralLabel>
</CustomObject>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the social account corresponding to the Social Handle</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/ManagedSocialAccounts__mdt/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Represents the provider of the page which name is represented in Name field</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/CaseCreated__c.field-meta.xml
<CustomField>
    <fullName>CaseCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post has a case created from it</description>
    <label>CaseCreated</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/Done__c.field-meta.xml
<CustomField>
    <fullName>Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post fulfills the criteria of being handled</description>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/ParentCommentMessage__c.field-meta.xml
<CustomField>
    <fullName>ParentCommentMessage__c</fullName>
    <description>If the post is a reply the parent(comment) is stored in this field</description>
    <label>Parent Comment Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/ParentMessage__c.field-meta.xml
<CustomField>
    <fullName>ParentMessage__c</fullName>
    <label>Parent Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/PostHidden__c.field-meta.xml
<CustomField>
    <fullName>PostHidden__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is hidden from its source e.g Facebook or Twitter</description>
    <inlineHelpText>Checked if the post is hidden from its source e.g Facebook or Twitter</inlineHelpText>
    <label>Hidden</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/PostIgnored__c.field-meta.xml
<CustomField>
    <fullName>PostIgnored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the action taken on the post is ignore</description>
    <label>Ignored</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/PostLiked__c.field-meta.xml
<CustomField>
    <fullName>PostLiked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is liked from SF e.g Facebook or Twitter</description>
    <label>Liked</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/PostReplied__c.field-meta.xml
<CustomField>
    <fullName>PostReplied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the post is replied to from SF to  e.g Facebook or Twitter</description>
    <label>Replied</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/SASPost__c.field-meta.xml
<CustomField>
    <fullName>SASPost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAS Post</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/SocialPost/fields/SASPostComment__c.field-meta.xml
<CustomField>
    <fullName>SASPostComment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comment on SAS Post</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/SocialPostHandler.cls
/**
 * @author Sanna Sörberg
 * @date 2019-12-20
 * @description Handler class for operations performed on social post object.
 */


public class SocialPostHandler extends C_TriggerHandler {

    /**
Static variable for the review status "Reviewed"
*/
    @TestVisible private static final String STATUS_REVIEWED= 'Reviewed';

    /**
Static variable for the review status "Ignored"
*/
    @TestVisible private static final String STATUS_IGNORE= 'Ignore';

    /**
Static variable for the status "HIDDEN"
*/
    @TestVisible private static final String STATUS_NEEDED= 'Needed';

    /**
Static variable for the status "HIDDEN"
*/
    @TestVisible private static final String STATUS_HIDDEN= 'HIDDEN';


    /**
    Trigger variables
    */
    private List<SocialPost> newSocialPostList;
    private List<SocialPost> oldSocialPostList;
    /**
   Set variables
   */
    public SocialPostHandler() {
        this.newSocialPostList = (List <SocialPost>) Trigger.new;
        this.oldSocialPostList = (List <SocialPost>) Trigger.old;

    }

    /**
   Used to call the trigger in the before insert context
   */
    public override void beforeInsert() {
        SetFieldsOnCreate(newSocialPostList);
    }

    /**
   Used to call the trigger in the before insert context
   */
    public override void afterInsert() {
        UpdatePostStatusOnParent(newSocialPostList, oldSocialPostList);
    }

    /**
  Used to call the trigger in the before update context
  */
    public override void beforeUpdate() {
        UpdatePostStatus(newSocialPostList, oldSocialPostList);
    }


    /**
       Method to set default fields on update on Social Post
       @param newSocialPost list of new version of the social post i.e. the Trigger.new variable
       */
    private static void UpdatePostStatus(List<SocialPost> newSocialPostList, List<SocialPost> oldSocialPostList) {
        Integer sz = newSocialPostList.size();
        List<SocialPost> updatedSocialPosts = new List<SocialPost> ();
        for(Integer i=0;i<sz;i++){
            Boolean handled;
            SocialPost newSp = newSocialPostList[i];
            SocialPost oldSp = oldSocialPostList[i];

            //If post is updated to hidden - the status is updated to hidden and marked as reviewed
            if(newSp.Status!=oldSp.Status && newSp.Status==STATUS_HIDDEN){
                newSp.PostHidden__c= true;
                handled= true;
            }

            //If post is updated to unhidden and unmark done if not other action is taken
            if(newSp.Status!=oldSp.Status && oldSp.Status==STATUS_HIDDEN) {
                newSp.PostHidden__c = false;
                if (!newSp.PostIgnored__c && !newSp.CaseCreated__c && !newSp.PostReplied__c && !newSp.PostLiked__c) {
                    handled = false;
                }
            }

            //If post is updated to ignore - the status is ignored and marked as reviewed
            if(newSp.ReviewedStatus!= oldSp.ReviewedStatus && newSp.ReviewedStatus== STATUS_IGNORE){
                newSp.PostIgnored__c= true;
                handled=true;
            }


            //If parent case is deleted - updated checkbox case created and unmark Done if no other action is taken
            if(newSp.ParentId!=oldSp.ParentId && newSp.ParentId==null) {
                newSp.CaseCreated__c = false;
                system.debug('Här i case');
                if (!newSp.PostIgnored__c && !newSp.PostHidden__c && !newSp.PostReplied__c && !newSp.PostLiked__c) {
                    handled = false;
                    system.debug('Här');
                }
            }

            //If post is updated to liked - The status is updated to liked and marked as reviewed

            if(newSp.Recipient == newSp.LikedBy && newSp.LikedBy!=oldSp.LikedBy){
                newSp.PostLiked__c=true;
                handled=true;
            }

            if(handled!=null && handled){
                newSp.ReviewedStatus=STATUS_REVIEWED;
                newSp.Done__c= true;
            }

            if(handled!= null && !handled){
                newSp.ReviewedStatus=STATUS_NEEDED;
                newSp.Done__c= false;
            }


        }

    }

/**
       Method to set default fields on insert on Social Post
       @param newSocialPost list of new version of the social post i.e. the Trigger.new variable
       */
    private static void UpdatePostStatusOnParent(List<SocialPost> newSocialPostList, List<SocialPost> oldSocialPostList) {
        // Generate set of parentIds to use in query
        Set<Id> parentIds = new Set<Id>();
        List<SocialPost> spRecords = newSocialPostList != null ? newSocialPostList : oldSocialPostList;

        if (spRecords != null) {
            for (SocialPost sp : spRecords) {
                if (sp.IsOutbound && sp.ReplyToId != null) {
                    parentIds.add(sp.ReplyToId);
                }
            }
        }
        if (parentIds != null) {
            List<SocialPost> parentPosts = [SELECT Id, Status FROM SocialPost Where Id = :parentIds];
            List<SocialPost> updatedSocialPosts = new List<SocialPost> ();

            for (SocialPost sp : parentPosts) {
                if (oldSocialPostList == null) {
                    sp.PostReplied__c = true;
                    sp.ReviewedStatus = STATUS_REVIEWED;
                    sp.Done__c = true;
                    updatedSocialPosts.add(sp);
                }
                if (newSocialPostList == null) {
                    sp.PostReplied__c = false;
                    if (!sp.PostIgnored__c && !sp.PostHidden__c && !sp.PostLiked__c && !sp.PostReplied__c) {
                        sp.ReviewedStatus = STATUS_NEEDED;
                        updatedSocialPosts.add(sp);
                    }
                }
            }

            update updatedSocialPosts;
        }
    }


    /**
       Method to set default fields on insert on Social Post
       @param newSocialPost list of new version of the social post i.e. the Trigger.new variable
       */
    private static void SetFieldsOnCreate(List<SocialPost> newSocialPostList) {
        List<ManagedSocialAccounts__mdt> socialAccs = [SELECT Id, DeveloperName, Name__c, Provider__c From ManagedSocialAccounts__mdt];
        List<Group> soMeQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'GlobalSupportSoMe'];
        Map<String, String> socialPageByProvider = new Map<String, String> ();

        if(socialAccs.size() > 0) {
            for (ManagedSocialAccounts__mdt msa : socialAccs) {
                socialPageByProvider.put(msa.Provider__c, msa.Name__c);
            }
        }
        List<Id> parentIds = new List<Id> ();
        List<Id> parentIdsNext = new List<Id> ();

        for(SocialPost sp : newSocialPostList){
            parentIds.add(sp.ReplyToId);
            if(socialPageByProvider.containsKey(sp.Provider) &&  sp.Handle == socialPageByProvider.get(sp.Provider)){
                sp.IsOutbound = true;
                sp.SASPost__c = true;
                sp.ReviewedStatus = null;
            }
            sp.OwnerId=soMeQueue[0].Id;
        }
        List<SocialPost> parentPosts = [SELECT Id, ReplyToId, Content, Provider, Handle FROM SocialPost Where Id=: parentIds];

        for(SocialPost sp : parentPosts){
            parentIdsNext.add(sp.ReplyToId);
        }
        List<SocialPost> parentPostsNext = [SELECT Id, ReplyToId, Content, Provider, Handle FROM SocialPost Where Id=: parentIdsNext];

        for(Integer i=0,sz=parentPosts.size();i<sz;i++){
            if(parentIds[i]!=null) {
                if(socialPageByProvider.containsKey(parentPosts[i].Provider) && parentPosts[i].Handle == socialPageByProvider.get(newSocialPostList[i].Provider)){
                    newSocialPostList[i].SASPostComment__c = true;
                }
                // newSocialPostList[i].ParentPost__c = parentIds[i];
                newSocialPostList[i].ParentMessage__c =   parentPosts[i].Content;

            }
            if(parentIdsNext[i] != null){
                if(socialPageByProvider.containsKey(parentPostsNext[i].Provider) && parentPostsNext[i].Handle == socialPageByProvider.get(newSocialPostList[i].Provider)){
                    newSocialPostList[i].SASPostComment__c = true;
                }
                //  newSocialPostList[i].ParentPost__c = parentIdsNext[i];
                newSocialPostList[i].ParentMessage__c =   parentPostsNext[i].Content;
                newSocialPostList[i].ParentCommentMessage__c =   parentPosts[i].Content;
            }
        }
    }

}