sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/rest-api/EU261ClaimPNRResponse.cls
global with sharing class EU261ClaimPNRResponse {
  global List<EU261ClaimInfo> pnrList;
  public EU261ClaimPNRResponse(List<LIA_Claim__c> toReturn) {
    this.pnrList = new List<EU261ClaimInfo>();
    for (LIA_Claim__c cl : toReturn) {
      this.pnrList.add(new EU261ClaimInfo(cl));
    }
  }

  global class EU261ClaimInfo {
    global Id claimId;
    global String pnr;
    global String flightNumber;
    global Date flightDate;
    public EU261ClaimInfo(LIA_Claim__c claim) {
      this.claimId = claim.Id;
      this.pnr = claim.Liability_PNR__c;
      this.flightNumber = claim.Flight_Number__c;
      this.flightDate = claim.Flight_Date__c;
    }
  }
}