sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Customer_Claim_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Claim_Category__c</fullName>
    <label>Customer Claim Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Flight disruptions</fullName>
            </value>
            <value>
                <fullName>Travel extras bought not rendered</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
            <value>
                <fullName>Airport experience</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Accident &amp; injury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Customer_Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Claim_Type__c</fullName>
    <label>Customer Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Claim_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baggage damaged</fullName>
            </value>
            <value>
                <fullName>Baggage delayed/lost</fullName>
            </value>
            <value>
                <fullName>Booking error</fullName>
            </value>
            <value>
                <fullName>Cabin environment</fullName>
            </value>
            <value>
                <fullName>Complaint about a refund</fullName>
            </value>
            <value>
                <fullName>Denied boarding</fullName>
            </value>
            <value>
                <fullName>Downgrading</fullName>
            </value>
            <value>
                <fullName>Extra baggage</fullName>
            </value>
            <value>
                <fullName>Flight cancellation</fullName>
            </value>
            <value>
                <fullName>Flight delay</fullName>
            </value>
            <value>
                <fullName>Gate issues</fullName>
            </value>
            <value>
                <fullName>In-flight meal</fullName>
            </value>
            <value>
                <fullName>In-flight service</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Meals/Drinks</fullName>
            </value>
            <value>
                <fullName>Missed connection</fullName>
            </value>
            <value>
                <fullName>Personal injury</fullName>
            </value>
            <value>
                <fullName>Prepaid seat</fullName>
            </value>
            <value>
                <fullName>Regression</fullName>
            </value>
            <value>
                <fullName>Special assistance</fullName>
            </value>
            <value>
                <fullName>Travel document control</fullName>
            </value>
            <value>
                <fullName>WiFi</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/EU261_Handling_Status__c.field-meta.xml
<CustomField>
    <fullName>EU261_Handling_Status__c</fullName>
    <label>EU261 Handling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unhandled</fullName>
                <default>true</default>
                <label>Unhandled</label>
            </value>
            <value>
                <fullName>Eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation</fullName>
            </value>
            <value>
                <fullName>Unable to handle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/External_Data_Retrieve_Count__c.field-meta.xml
<CustomField>
    <fullName>External_Data_Retrieve_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many times data retrieval has been attempted</description>
    <label>External Data Retrieve Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/External_Data_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Data_Status__c</fullName>
    <description>Status to show availability of data in external systems such as EDW.</description>
    <label>External Data Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/recordTypes/CustomerClaim.recordType-meta.xml
<RecordType>
    <fullName>CustomerClaim</fullName>
    <active>true</active>
    <description>Record type to differentiate the customer claims</description>
    <label>CustomerClaim</label>
</RecordType>

sas-core/main/default/classes/tests/EU261Scheduling_Test.cls
@IsTest
public with sharing class EU261Scheduling_Test {
  private static ClaimsSelector claimsSel = ClaimsSelector.newInstance();
  @IsTest
  static void itIsPossibleToUpdateExternalDataStatus() {
    TestDataFactories.CasesClaims casesWithClaims = TestDataFactories.createCasesWithClaims(
      2,
      null,
      new Map<Schema.SObjectField, Object>{
        LIA_Claim__c.Liability_PNR__c => 'ABC123',
        LIA_Claim__c.Flight_Number__c => 'SK1',
        LIA_Claim__c.Flight_Date__c => Date.today(),
        LIA_Claim__c.Customer_Claim_Category__c => 'Flight disruptions',
        LIA_Claim__c.Customer_Claim_Type__c => 'Flight cancellation - compensation',
        LIA_Claim__c.RecordTypeId => Claim.getRecordTypeIdByEnum(
          Claim.RecordType.CustomerClaim
        )
      }
    );
    casesWithClaims.claims[1].Customer_Claim_Type__c = 'Flight cancellation';
    update casesWithClaims.claims[1];

    Test.startTest();
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();
    System.enqueueJob(
      new Claims.UpdateExternalDataStatusAsync(
        claimsSel.selectUnhandledEU261ClaimsByDataStatus('Not Started'),
        Claim.ExternalDataStatus.InProgress
      )
    );
    Test.stopTest();
    Set<Id> claimIds = new Map<Id, LIA_Claim__c>(casesWithClaims.claims)
      .keySet();
    List<LIA_Claim__c> claimsAfterUpdate = claimsSel.selectById(claimIds);
    System.assertEquals(
      'In Progress',
      claimsAfterUpdate[0].External_Data_Status__c,
      'External Data Status should have been updated'
    );
    System.assertEquals(
      'Not Started',
      claimsAfterUpdate[1].External_Data_Status__c,
      'External Data Status should not have been updated'
    );
  }

  @IsTest
  static void fetchingBookingThatExistsInEDWShouldUpdateDataStatus() {
    TestDataFactories.CasesClaims casesWithClaims = TestDataFactories.createCasesWithClaims(
      1,
      null,
      new Map<Schema.SObjectField, Object>{
        LIA_Claim__c.Liability_PNR__c => APIMMock.EDW_SINGLE_PNR,
        LIA_Claim__c.Flight_Number__c => 'SK1',
        LIA_Claim__c.Flight_Date__c => Date.today(),
        LIA_Claim__c.Customer_Claim_Category__c => 'Flight disruptions',
        LIA_Claim__c.Customer_Claim_Type__c => 'Flight cancellation - compensation',
        LIA_Claim__c.RecordTypeId => Claim.getRecordTypeIdByEnum(
          Claim.RecordType.CustomerClaim
        ),
        LIA_Claim__c.External_Data_Status__c => 'In Progress'
      }
    );
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Database.executeBatch(new FetchEDWBookingsForEU261ClaimsBatch(), 2);
    Test.stopTest();
    LIA_Claim__c cl = claimsSel.selectById(
      new Set<Id>{ casesWithClaims.claims[0].Id }
    )[0];
    System.assertEquals(
      1,
      cl.External_Data_Retrieve_Count__c,
      'Retrieve Count should be updated'
    );
    System.assertEquals(
      'Completed',
      cl.External_Data_Status__c,
      'External Data Status should have been updated'
    );
  }
  @IsTest
  static void fetchingBookingThatDoesNotExistsInEDWShouldFailGracefully() {
    TestDataFactories.CasesClaims casesWithClaims = TestDataFactories.createCasesWithClaims(
      2,
      null,
      new Map<Schema.SObjectField, Object>{
        LIA_Claim__c.Liability_PNR__c => 'ABC123',
        LIA_Claim__c.Flight_Number__c => 'SK1',
        LIA_Claim__c.Flight_Date__c => Date.today(),
        LIA_Claim__c.Customer_Claim_Category__c => 'Flight disruptions',
        LIA_Claim__c.Customer_Claim_Type__c => 'Flight cancellation - compensation',
        LIA_Claim__c.RecordTypeId => Claim.getRecordTypeIdByEnum(
          Claim.RecordType.CustomerClaim
        ),
        LIA_Claim__c.External_Data_Status__c => 'In Progress'
      }
    );
    casesWithClaims.claims[1].External_Data_Retrieve_Count__c = 3;
    update casesWithClaims.claims[1];
    Test.setMock(HttpCalloutMock.class, new APIMMock());
    Test.startTest();
    Database.executeBatch(new FetchEDWBookingsForEU261ClaimsBatch(), 2);
    Test.stopTest();
    Set<Id> claimIds = new Map<Id, LIA_Claim__c>(casesWithClaims.claims)
      .keySet();
    List<LIA_Claim__c> claimsAfterUpdate = claimsSel.selectById(claimIds);
    System.assertEquals(
      1,
      claimsAfterUpdate[0].External_Data_Retrieve_Count__c,
      'Retrieve Count should be updated'
    );
    System.assertEquals(
      'In Progress',
      claimsAfterUpdate[0].External_Data_Status__c,
      'External Data Status should still be In Progress'
    );
    System.assertEquals(
      4,
      claimsAfterUpdate[1].External_Data_Retrieve_Count__c,
      'Retrieve Count should be updated'
    );
    System.assertEquals(
      'Unavailable',
      claimsAfterUpdate[1].External_Data_Status__c,
      'External Data Status should set to Unavailable'
    );
    System.assertEquals(
      'Unable to handle',
      claimsAfterUpdate[1].EU261_Handling_Status__c,
      'EU261 Handling Status should set to Unable to handle'
    );
  }
}