sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Preferred_Compensation_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Compensation_Method__c</fullName>
    <label>Preferred Compensation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroBonus Points</fullName>
            </value>
            <value>
                <fullName>Monetary</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/async/salesforce/RunEU261AutomationScheduler.cls
public with sharing class RunEU261AutomationScheduler implements Schedulable {
  public void execute(SchedulableContext jobId) {
    List<LIA_Claim__c> allClaimsToAutomate = ClaimsSelector.newInstance()
      .selectUnhandledEU261ClaimsByDataStatus('Completed');
    Set<Id> claimIdsWithMonetary = new Set<Id>();
    Set<Id> claimIdsWithEBPointsOrVoucher = new Set<Id>();
    for (LIA_Claim__c cl : allClaimsToAutomate) {
      if (cl.Preferred_Compensation_Method__c == 'Monetary') {
        claimIdsWithMonetary.add(cl.Id);
      } else {
        claimIdsWithEBPointsOrVoucher.add(cl.Id);
      }
    }
    EU261Service.newInstance().batchProcessEU261Claims(claimIdsWithMonetary);
    EU261Service.newInstance()
      .batchProcessEU261Claims(claimIdsWithEBPointsOrVoucher);
  }
}