sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_line_1__c</fullName>
    <label>Address line 1</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Address_line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_line_2__c</fullName>
    <label>Address line 2</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
        <controllingField>Bank_Country__c</controllingField>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private customer</fullName>
            </value>
            <value>
                <fullName>Corporate customer</fullName>
            </value>
            <value>
                <fullName>Travel agency</fullName>
            </value>
            <value>
                <fullName>Other representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_line_1__c</fullName>
    <label>Address line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Address_line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_line_2__c</fullName>
    <label>Address line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Customer&apos;s Bank Account Number</description>
    <inlineHelpText>Bank account number that will receive the monetary payment</inlineHelpText>
    <label>Bank Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/BIC_Swift__c.field-meta.xml
<CustomField>
    <fullName>BIC_Swift__c</fullName>
    <label>BIC/Swift</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Customer&apos;s City</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability or Customer Claim</description>
    <inlineHelpText>This settlement is related to this Liability or Customer claim</inlineHelpText>
    <label>Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/EuroBonus_Number__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Number__c</fullName>
    <label>EuroBonus Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/EuroBonus_Points__c.field-meta.xml
<CustomField>
    <fullName>EuroBonus_Points__c</fullName>
    <label>EuroBonus Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Payee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_First_Name__c</fullName>
    <inlineHelpText>For vouchers, use only latin characters (A-Z).</inlineHelpText>
    <label>Payee First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Payee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Last_Name__c</fullName>
    <inlineHelpText>For vouchers, use only latin characters (A-Z).</inlineHelpText>
    <label>Payee Last Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <description>Beneficiary of the settlement</description>
    <label>Payee Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Waiting for approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Waiting for control</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Accepted by Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Rejected by Bank</fullName>
            </value>
            <value>
                <fullName>Accepted by Bank/Done</fullName>
            </value>
            <value>
                <fullName>L2 errors by Bank</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Voucher_Email__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Email__c</fullName>
    <label>Voucher Email</label>
    <type>Email</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/recordTypes/Cheque.recordType-meta.xml
<RecordType>
    <fullName>Cheque</fullName>
    <active>true</active>
    <description>Record type for cheque settlements in US</description>
    <label>Cheque</label>
</RecordType>

sas-core/main/default/objects/Settlement__c/recordTypes/Monetary.recordType-meta.xml
<RecordType>
    <fullName>Monetary</fullName>
    <active>true</active>
    <label>Monetary</label>
</RecordType>

sas-core/main/default/objects/Settlement__c/recordTypes/Voucher.recordType-meta.xml
<RecordType>
    <fullName>Voucher</fullName>
    <active>true</active>
    <label>Voucher</label>
</RecordType>

sas-core/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finland</fullName>
        <default>true</default>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

sas-core/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GPB</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>Currencies available</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/invocableMethods/ValidateSettlements_Test.cls
@IsTest
private class ValidateSettlements_Test {
  @IsTest
  static void invalidSettlementValidationTest() {
    // Given
    LIA_Claim__c privateClaim = new LIA_Claim__c(
      Liability_PNR__c = '0000AA',
      Type_of_Customer__c = 'Private Customer'
    );
    LIA_Claim__c otherClaim = new LIA_Claim__c(
      Liability_PNR__c = '0000AA',
      Type_of_Customer__c = 'Claim firm'
    );

    insert new List<LIA_Claim__c>{ privateClaim, otherClaim };

    Settlement__c validSettlement = new Settlement__c(
      Claim__c = privateClaim.Id,
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 600,
      BIC_Swift__c = 'AAAAAABB123',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'NOK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE7280000810340009783242',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00100',
      Settlement_Status__c = Settlements.STATUS_SENT_TO_BANK,
      RecordTypeId = Settlements.getRecordTypeId(
        Settlements.RecordType.Monetary
      ),
      Bank_Country__c = 'Sweden'
    );

    Settlement__c invalidSettlement1 = validSettlement.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c invalidSettlement2 = validSettlement.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c invalidSettlement3 = validSettlement.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c invalidSettlement4 = validSettlement.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c invalidSettlement5 = validSettlement.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c invalidSettlement6 = validSettlement.clone(
      false,
      true,
      false,
      false
    );

    invalidSettlement1.Amount__c = 0;
    invalidSettlement2.City__c = null;
    invalidSettlement3.Bank_Account_Number__c = 'SE738000081034000978324';
    invalidSettlement4.Claim__c = otherClaim.Id;
    invalidSettlement5.Address_line_1__c = null;

    invalidSettlement6.RecordTypeId = Settlements.getRecordTypeId(
      Settlements.RecordType.EBPoints
    );
    invalidSettlement6.EuroBonus_Number__c = '1234';
    invalidSettlement6.EuroBonus_Points__c = 1000;

    insert new List<Settlement__c>{
      invalidSettlement1,
      invalidSettlement2,
      invalidSettlement3,
      invalidSettlement4,
      invalidSettlement5
    };

    // When
    Boolean singleError = false;
    Boolean largeError = false;

    ValidateSettlements.ValidationStatus statusSingle = ValidateSettlements.validate(
      new List<List<Settlement__c>>{
        new List<Settlement__c>{ invalidSettlement1 }
      }
    )[0];
    if (!statusSingle.isValid) {
      singleError = true;
    }

    ValidateSettlements.ValidationStatus statusMulti = ValidateSettlements.validate(
      new List<List<Settlement__c>>{
        new List<Settlement__c>{
          invalidSettlement1,
          invalidSettlement2,
          invalidSettlement3,
          invalidSettlement4,
          invalidSettlement5
        }
      }
    )[0];
    if (!statusMulti.isValid) {
      largeError = true;
    }

    // Then
    System.assert(singleError, 'A settlement with one error was validated.');
    System.assert(
      largeError,
      'A settlement with multiple errors was validated.'
    );
  }
  @IsTest
  static void validSettlementValidationTest() {
    // Given
    LIA_Claim__c privateClaim = new LIA_Claim__c(
      Liability_PNR__c = '0000AA',
      Type_of_Customer__c = 'Private Customer'
    );

    insert new List<LIA_Claim__c>{ privateClaim };

    Settlement__c validSettlement1 = new Settlement__c(
      Claim__c = privateClaim.Id,
      Address_line_1__c = 'Frösundaviks allé 1',
      Address_line_2__c = 'Line 2',
      Amount__c = 600,
      BIC_Swift__c = 'AAAAAABB123',
      City__c = 'Stockholm',
      Country__c = 'Sweden',
      Currency__c = 'SEK',
      Date_of_Exchange_Calculation__c = Date.today(),
      Bank_Account_Number__c = 'SE7280000810340009783242',
      Payee_Name__c = 'Test Testsson',
      Postal_Code__c = '00100',
      Settlement_Status__c = Settlements.STATUS_IN_PROGRESS,
      RecordTypeId = Settlements.getRecordTypeId(
        Settlements.RecordType.Monetary
      ),
      Bank_Country__c = 'Sweden'
    );

    Settlement__c validSettlement2 = validSettlement1.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c validSettlement3 = validSettlement1.clone(
      false,
      true,
      false,
      false
    );
    Settlement__c validSettlement4 = validSettlement1.clone(
      false,
      true,
      false,
      false
    );

    validSettlement2.RecordTypeId = Settlements.getRecordTypeId(
      Settlements.RecordType.Voucher
    );
    validSettlement2.Voucher_Email__c = 'Test@example.com';
    validSettlement2.Payee_First_Name__c = 'Test';
    validSettlement2.Payee_Last_Name__c = 'Testsson';
    validSettlement2.Bank_Account_Number__c = null;
    validSettlement2.Bank_Country__c = null;
    validSettlement2.Country__c = null;

    validSettlement3.RecordTypeId = Settlements.getRecordTypeId(
      Settlements.RecordType.Cheque
    );
    validSettlement3.Country__c = 'United States';
    validSettlement3.Bank_Country__c = 'United States';
    validSettlement3.Currency__c = 'USD';
    validSettlement3.Postal_Code__c = '90801';
    validSettlement3.State__c = UsStateUtils.getStateFromPostalCode('90801');

    validSettlement4.RecordTypeId = Settlements.getRecordTypeId(
      Settlements.RecordType.EBPoints
    );
    validSettlement4.Address_line_1__c = null;
    validSettlement4.EuroBonus_Number__c = '000000000';
    validSettlement4.EuroBonus_Points__c = 1;
    validSettlement4.Bank_Country__c = null;
    validSettlement4.Country__c = null;

    Test.setMock(HttpCalloutMock.class, new APIMMock());

    insert new List<Settlement__c>{
      validSettlement1,
      validSettlement2,
      validSettlement3,
      validSettlement4
    };

    // When
    Boolean noError = false;

    Test.startTest();
    ValidateSettlements.ValidationStatus status;
    try {
      status = ValidateSettlements.validate(
        new List<List<Settlement__c>>{
          new List<Settlement__c>{
            validSettlement1,
            validSettlement2,
            validSettlement3,
            validSettlement4
          }
        }
      )[0];
    } catch (Exception e) {
      status = new ValidateSettlements.ValidationStatus('Error');
    }

    if (status.isValid) {
      noError = true;
    }

    Test.stopTest();

    // Then
    System.assertEquals(status.errorMessage, '');
    System.assert(noError, 'A valid settlement was invalidated');
  }
}