sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case related to this claim</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/EU261_Handling_Status__c.field-meta.xml
<CustomField>
    <fullName>EU261_Handling_Status__c</fullName>
    <label>EU261 Handling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unhandled</fullName>
                <default>true</default>
                <label>Unhandled</label>
            </value>
            <value>
                <fullName>Eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation</fullName>
            </value>
            <value>
                <fullName>Unable to handle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/External_Data_Retrieve_Count__c.field-meta.xml
<CustomField>
    <fullName>External_Data_Retrieve_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many times data retrieval has been attempted</description>
    <label>External Data Retrieve Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/External_Data_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Data_Status__c</fullName>
    <description>Status to show availability of data in external systems such as EDW.</description>
    <label>External Data Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>Liability PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/batchables/FetchEDWBookingsForEU261ClaimsBatch.cls
public with sharing class FetchEDWBookingsForEU261ClaimsBatch implements Database.Batchable<LIA_Claim__c>, Database.AllowsCallouts, Database.Stateful {
  private static final Decimal MAX_RETRIEVE_COUNT = 3.0;
  private Set<Id> caseIdsToManualHandling;

  public Iterable<LIA_Claim__c> start(Database.BatchableContext jobId) {
    this.caseIdsToManualHandling = new Set<Id>();
    return ClaimsSelector.newInstance()
      .selectUnhandledEU261ClaimsByDataStatus('In Progress');
  }

  public void execute(
    Database.BatchableContext bc,
    List<LIA_Claim__c> claimsToFetch
  ) {
    fflib_ISObjectUnitOfWork uowUpsert = SAS_Service_Application.UnitOfWork.newInstance();
    fflib_ISObjectUnitOfWork uowDelete = SAS_Service_Application.UnitOfWork.newInstance();
    for (LIA_Claim__c c : claimsToFetch) {
      Bookings b = BookingService.fetchEDWBookingByBookingReference(
        c.Liability_PNR__c,
        uowUpsert,
        uowDelete
      );
      Decimal newRetrieveCount = c.External_Data_Retrieve_Count__c + 1;
      if (b == null) {
        if (newRetrieveCount > MAX_RETRIEVE_COUNT) {
          c.EU261_Handling_Status__c = 'Unable to handle';
          c.External_Data_Status__c = 'Unavailable';
          caseIdsToManualHandling.add(c.Case__c);
        }
      } else {
        c.External_Data_Status__c = 'Completed';
      }
      c.External_Data_Retrieve_Count__c = newRetrieveCount;
      uowUpsert.registerDirty(c);
    }
    uowDelete.commitWork();
    uowUpsert.commitWork();
  }

  public void finish(Database.BatchableContext jobId) {
    if (caseIdsToManualHandling.size() > 0) {
      CaseService.assignPriorityAndRouteToQueue(caseIdsToManualHandling);
    }
  }
}