sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Claims_Exist_In_CARE_For_PNR__c.field-meta.xml
<CustomField>
    <fullName>Claims_Exist_In_CARE_For_PNR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether claims exist in CARE for this claim&apos;s PNR.</description>
    <inlineHelpText>Whether claims exist in CARE for this claim&apos;s PNR.</inlineHelpText>
    <label>Claims Exist In CARE For PNR</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Last_Checked_Claims_From_CARE__c.field-meta.xml
<CustomField>
    <fullName>Last_Checked_Claims_From_CARE__c</fullName>
    <description>Timestamp for when the existence of claims with the same PNR as this one in CARE was checked.</description>
    <inlineHelpText>Timestamp for when the existence of claims with the same PNR as this one in CARE was checked.</inlineHelpText>
    <label>Last Checked Claims From CARE</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/classes/selectors/ClaimsSelector.cls
public inherited sharing class ClaimsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LIA_Claim__c.Id,
      LIA_Claim__c.Claims_Exist_In_CARE_For_PNR__c,
      LIA_Claim__c.Last_Checked_Claims_From_CARE__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return LIA_Claim__c.SObjectType;
  }

  public static ClaimsSelector newInstance() {
    return (ClaimsSelector) SAS_Service_Application.Selector.newInstance(
      LIA_Claim__c.SObjectType
    );
  }

  public List<LIA_Claim__c> selectById(Set<Id> ids) {
    return (List<LIA_Claim__c>) selectSObjectsById(ids);
  }
}