sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/FCS_EBNumber__c.field-meta.xml
<CustomField>
    <fullName>FCS_EBNumber__c</fullName>
    <description>EuroBonus number of customer</description>
    <label>EuroBonus Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Proactivity__c.field-meta.xml
<CustomField>
    <fullName>Proactivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use to manually link a case to a proactivity</description>
    <inlineHelpText>Use to manually link a case to a proactivity</inlineHelpText>
    <label>Proactivity</label>
    <referenceTo>Proactivity__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/FlightIrregularities__c.object-meta.xml
<CustomObject>
    <description>Holds information about delays and cancellations.</description>
    <label>FlightIrregularities</label>
    <nameField>
        <label>FlightIrregularities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlightIrregularities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FlightIrregularities__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The cancellation/delay code parsed from TEDS</description>
    <inlineHelpText>The cancellation/delay code parsed from TEDS</inlineHelpText>
    <label>Cancellation code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <description>The flight to which the irregularity pertains</description>
    <inlineHelpText>The flight to which the irregularity pertains</inlineHelpText>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>Flight_Irregularities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the irregularity (cancellation/delay)</description>
    <inlineHelpText>The type of the irregularity (cancellation/delay)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case related to this claim</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/Proactivity__c.object-meta.xml
<CustomObject>
    <description>Information notice to be shown when a claim matches the criteria defined for the proactivity.</description>
    <label>Proactivity</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Proactivity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proactivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Proactivity__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <description>Match all flights arriving to and/or departing the airport.</description>
    <inlineHelpText>Match all flights arriving to and/or departing the airport.</inlineHelpText>
    <label>Airport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Cancellation_Code__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Code__c</fullName>
    <label>Cancellation Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CancellationCode</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address to match on.</description>
    <inlineHelpText>Email address to match on.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <description>Date when the proactivity becomes relevant</description>
    <inlineHelpText>Date when the proactivity becomes relevant</inlineHelpText>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Match_Flights_Arriving_To_Airport__c.field-meta.xml
<CustomField>
    <fullName>Match_Flights_Arriving_To_Airport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the proactivity should match flights arriving to the airport</description>
    <inlineHelpText>If the proactivity should match flights arriving to the airport</inlineHelpText>
    <label>Match Flights Arriving To Airport</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Match_Flights_Departing_Airport__c.field-meta.xml
<CustomField>
    <fullName>Match_Flights_Departing_Airport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the proactivity should match flights departing the airport</description>
    <inlineHelpText>If the proactivity should match flights departing the airport</inlineHelpText>
    <label>Match Flights Departing Airport</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <description>The message to be displayed for matching claims.</description>
    <inlineHelpText>The message to be displayed for matching claims.</inlineHelpText>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number to match on.</description>
    <inlineHelpText>Phone number to match on.</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <description>Date when the proactivity stops being relevant</description>
    <inlineHelpText>Date when the proactivity stops being relevant</inlineHelpText>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>For differentiating between the different types of proactivities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Major Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/globalValueSets/CancellationCode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AIRS</fullName>
    </customValue>
    <customValue>
        <fullName>AUTH</fullName>
    </customValue>
    <customValue>
        <fullName>ARPT</fullName>
    </customValue>
    <customValue>
        <fullName>COMM</fullName>
    </customValue>
    <customValue>
        <fullName>CREW</fullName>
    </customValue>
    <customValue>
        <fullName>DAMA</fullName>
    </customValue>
    <customValue>
        <fullName>EQUI</fullName>
    </customValue>
    <customValue>
        <fullName>FUEL</fullName>
    </customValue>
    <customValue>
        <fullName>HDLG</fullName>
    </customValue>
    <customValue>
        <fullName>HOLI</fullName>
    </customValue>
    <customValue>
        <fullName>INDU</fullName>
    </customValue>
    <customValue>
        <fullName>NODE</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>OPCO</fullName>
    </customValue>
    <customValue>
        <fullName>OPER</fullName>
    </customValue>
    <customValue>
        <fullName>PERF</fullName>
    </customValue>
    <customValue>
        <fullName>POLI</fullName>
    </customValue>
    <customValue>
        <fullName>REPO</fullName>
    </customValue>
    <customValue>
        <fullName>ROTA</fullName>
    </customValue>
    <customValue>
        <fullName>RTNS</fullName>
    </customValue>
    <customValue>
        <fullName>RUNW</fullName>
    </customValue>
    <customValue>
        <fullName>TECH</fullName>
    </customValue>
    <customValue>
        <fullName>WEAT</fullName>
    </customValue>
    <masterLabel>CancellationCode</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/controllers/ProactivitiesController_Test.cls
@IsTest
private class ProactivitiesController_Test {
  private static ProactivitiesSelector proactivites = ProactivitiesSelector.newInstance();

  @testSetup
  static void setup() {
    Date today = Date.today();

    Proactivity__c normalProactivity = new Proactivity__c(
      Note__c = 'Test 1',
      Type__c = 'Normal',
      Email__c = 'test@test.com'
    );
    Proactivity__c majorEventProactivity = new Proactivity__c(
      Note__c = 'Test 2',
      Type__c = 'Major Event',
      Email__c = 'test@test.com',
      Phone_Number__c = '0000000000'
    );
    Proactivity__c airportMatcherProactivity = new Proactivity__c(
      Note__c = 'Test 3',
      Type__c = 'Normal',
      Airport__c = 'ARN',
      Match_Flights_Arriving_To_Airport__c = true,
      Match_Flights_Departing_Airport__c = false,
      From_Date__c = today,
      To_Date__c = today
    );
    Proactivity__c cancellationCodeProactivity = new Proactivity__c(
      Note__c = 'Test 4',
      Type__c = 'Normal',
      Cancellation_Code__c = 'AIRS',
      From_Date__c = today,
      To_Date__c = today
    );
    Proactivity__c airportMatcherAndCancellationCodeProactivity = new Proactivity__c(
      Note__c = 'Test 4',
      Type__c = 'Normal',
      Cancellation_Code__c = 'AIRS',
      Airport__c = 'ARN',
      Match_Flights_Arriving_To_Airport__c = true,
      Match_Flights_Departing_Airport__c = false,
      From_Date__c = today,
      To_Date__c = today
    );

    Case caseWithOneProactivityRegularMatcher = new Case(
      FCS_EBNumber__c = '000000001'
    );
    Case caseWithTwoProactivitiesRegularMatcher = new Case(
      FCS_EBNumber__c = '000000002'
    );
    Case caseWithOneProactivityAirportMatcher = new Case(
      FCS_EBNumber__c = '000000003'
    );
    Case caseWithOneProactivityCancellationCodeMatcher = new Case(
      FCS_EBNumber__c = '000000004'
    );

    insert new List<Case>{
      caseWithOneProactivityRegularMatcher,
      caseWithTwoProactivitiesRegularMatcher,
      caseWithOneProactivityAirportMatcher,
      caseWithOneProactivityCancellationCodeMatcher
    };

    LIA_Claim__c claimWithOneProactivityRegularMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityRegularMatcher.Id,
      Phone_Number__c = '0000000000'
    );
    LIA_Claim__c claimWithTwoProactivitiesRegularMatcher = new LIA_Claim__c(
      Case__c = caseWithTwoProactivitiesRegularMatcher.Id,
      Contact_Email__c = 'test@test.com'
    );
    LIA_Claim__c claimWithOneProactivityAirportMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityAirportMatcher.Id,
      Flight_Number__c = Flight.normalizeFlightNumber('SK1'),
      Flight_Date__c = today
    );
    LIA_Claim__c claimWithOneProactivityCancellationCodeMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityCancellationCodeMatcher.Id,
      Flight_Number__c = Flight.normalizeFlightNumber('SK2'),
      Flight_Date__c = today
    );

    String flightIdentifier1 =
      Flight.constructTEDSFlightNumberDate('SK1', today) + '-ARN-UME';
    String flightIdentifier2 =
      Flight.constructTEDSFlightNumberDate('SK2', today) + '-UME-ARN';

    Flight__c flight1 = new Flight__c(
      Arrival_Airport__c = 'ARN',
      Departure_Airport__c = 'UME',
      Scheduled_Arrival_Time__c = today,
      Scheduled_Departure_Time__c = today,
      TEDS_Identifier__c = flightIdentifier1
    );

    Flight__c flight2 = new Flight__c(
      Arrival_Airport__c = 'UME',
      Departure_Airport__c = 'ARN',
      Scheduled_Arrival_Time__c = today,
      Scheduled_Departure_Time__c = today,
      TEDS_Identifier__c = flightIdentifier2
    );

    insert new List<Flight__c>{ flight1, flight2 };

    FlightIrregularities__c flightIrregularity = new FlightIrregularities__c(
      Flight__c = flight2.Id,
      Code__c = 'AIRS'
    );

    insert new List<SObject>{
      flightIrregularity,
      normalProactivity,
      majorEventProactivity,
      airportMatcherProactivity,
      cancellationCodeProactivity,
      claimWithOneProactivityRegularMatcher,
      claimWithTwoProactivitiesRegularMatcher,
      claimWithOneProactivityAirportMatcher,
      claimWithOneProactivityCancellationCodeMatcher,
      airportMatcherAndCancellationCodeProactivity
    };
  }

  @IsTest
  static void shouldSelectNormalProactivityByCaseIdTest() {
    // Given (setup)
    Case caseWithOneProactivityRegularMatcher = [
      SELECT Id
      FROM Case
      WHERE FCS_EBNumber__c = '000000001'
    ][0];

    // When
    List<ProactivitiesController.Proactivity> proactivitiesWithMatchingReason = ProactivitiesController.getProactivitiesForRecord(
      String.valueOf(caseWithOneProactivityRegularMatcher.Id),
      String.valueOf('Case')
    );

    // Then
    System.assertEquals(
      1,
      proactivitiesWithMatchingReason.size(),
      'Incorrect amount of matches for proactivity/case match'
    );
    System.assertEquals(
      'Phone',
      proactivitiesWithMatchingReason[0].matchingReasons,
      'Incorrect matching reason(s) for proactivity/case match'
    );
  }

  @IsTest
  static void shouldSelectMajorEventProactivityByCaseIdTest() {
    // Given (setup)
    Case caseWithTwoProactivitiesRegularMatcher = [
      SELECT Id
      FROM Case
      WHERE FCS_EBNumber__c = '000000002'
    ][0];
    // When
    List<ProactivitiesController.Proactivity> proactivitiesWithMatchingReason = ProactivitiesController.getProactivitiesForRecord(
      String.valueOf(caseWithTwoProactivitiesRegularMatcher.Id),
      String.valueOf('Case')
    );

    // Then
    System.assertEquals(
      2,
      proactivitiesWithMatchingReason.size(),
      'Incorrect amount of matches for proactivity/case match'
    );
    System.assertEquals(
      'Email',
      proactivitiesWithMatchingReason[0].matchingReasons,
      'Incorrect matching reason(s) for proactivity/case match'
    );
  }

  @IsTest
  static void shouldSelectAirportMatcherProactivityByCaseIdTest() {
    // Given (setup)
    Case caseWithOneProactivityAirportMatcher = [
      SELECT Id
      FROM Case
      WHERE FCS_EBNumber__c = '000000003'
    ][0];
    // When
    List<ProactivitiesController.Proactivity> proactivitiesWithMatchingReason = ProactivitiesController.getProactivitiesForRecord(
      String.valueOf(caseWithOneProactivityAirportMatcher.Id),
      String.valueOf('Case')
    );

    // Then
    System.assertEquals(
      1,
      proactivitiesWithMatchingReason.size(),
      'Incorrect amount of matches for proactivity/case match'
    );
    System.assertEquals(
      'SK0001: (Arrival airport)',
      proactivitiesWithMatchingReason[0].matchingReasons,
      'Incorrect matching reason(s) for proactivity/case match'
    );
  }

  @IsTest
  static void shouldSelectCancellationCodeProactivityByCaseIdTest() {
    // Given (setup)
    Case caseWithOneProactivityCancellationCodeMatcher = [
      SELECT Id
      FROM Case
      WHERE FCS_EBNumber__c = '000000004'
    ][0];
    // When
    List<ProactivitiesController.Proactivity> proactivitiesWithMatchingReason = ProactivitiesController.getProactivitiesForRecord(
      String.valueOf(caseWithOneProactivityCancellationCodeMatcher.Id),
      String.valueOf('Case')
    );

    // Then
    System.assertEquals(
      1,
      proactivitiesWithMatchingReason.size(),
      'Incorrect amount of matches for proactivity/case match'
    );
    System.assertEquals(
      'SK0002: (Code "AIRS")',
      proactivitiesWithMatchingReason[0].matchingReasons,
      'Incorrect matching reason(s) for proactivity/case match'
    );
  }
}