sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the airport is located in.</description>
    <inlineHelpText>The city the airport is located in.</inlineHelpText>
    <label>City</label>
    <length>58</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of the country the airport is located in.</description>
    <inlineHelpText>The country code of the country the airport is located in.</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The country the airport is located in.</description>
    <inlineHelpText>The country the airport is located in.</inlineHelpText>
    <label>Country Name</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Is_EU261_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Is_EU261_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Asserts whether the airport is within the territory of the European Union or in Norway, Switzerland or Iceland.</description>
    <inlineHelpText>Asserts whether the airport is within the territory of the European Union or in Norway, Switzerland or Iceland.</inlineHelpText>
    <label>Is EU261 Applicable</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>The latitude of the airport.</description>
    <inlineHelpText>The latitude of the airport.</inlineHelpText>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>The longitude of the airport.</description>
    <inlineHelpText>The longitude of the airport.</inlineHelpText>
    <label>Longitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/tests/fixtures/TestAirportFixture.cls
@IsTest
public with sharing class TestAirportFixture {
  public static Map<String, Airport> codeToAirport = new Map<String, Airport>{
    'HEL' => new Airport(
      new Airport__c(
        City__c = 'Helsinki',
        Country_Code__c = 'FI',
        Country_Name__c = 'Finland',
        TEDS_Identifier__c = 'HEL',
        Is_EU261_Applicable__c = true,
        Latitude__c = 60.317199707031,
        Longitude__c = 24.963300704956
      )
    ),
    'ARN' => new Airport(
      new Airport__c(
        City__c = 'Stockholm',
        Country_Code__c = 'SE',
        Country_Name__c = 'Sweden',
        TEDS_Identifier__c = 'ARN',
        Is_EU261_Applicable__c = true,
        Latitude__c = 59.651901245117,
        Longitude__c = 17.918600082397
      )
    ),
    'CPH' => new Airport(
      new Airport__c(
        City__c = 'Copenhagen',
        Country_Code__c = 'DK',
        Country_Name__c = 'Denmark',
        TEDS_Identifier__c = 'CPH',
        Is_EU261_Applicable__c = true,
        Latitude__c = 55.617900848389,
        Longitude__c = 12.656000137329
      )
    ),
    'JFK' => new Airport(
      new Airport__c(
        City__c = 'New York',
        Country_Code__c = 'US',
        Country_Name__c = 'United States',
        TEDS_Identifier__c = 'JFK',
        Is_EU261_Applicable__c = false,
        Latitude__c = 40.639801,
        Longitude__c = -73.7789
      )
    ),
    'LAX' => new Airport(
      new Airport__c(
        City__c = 'Los Angeles',
        Country_Code__c = 'US',
        Country_Name__c = 'United States',
        TEDS_Identifier__c = 'LAX',
        Is_EU261_Applicable__c = false,
        Latitude__c = 33.942501,
        Longitude__c = -118.407997
      )
    )
  };
}