sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the airport is located in.</description>
    <inlineHelpText>The city the airport is located in.</inlineHelpText>
    <label>City</label>
    <length>58</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of the country the airport is located in.</description>
    <inlineHelpText>The country code of the country the airport is located in.</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The country the airport is located in.</description>
    <inlineHelpText>The country the airport is located in.</inlineHelpText>
    <label>Country Name</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Is_EU261_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Is_EU261_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Asserts whether the airport is within the territory of the European Union or in Norway, Switzerland or Iceland.</description>
    <inlineHelpText>Asserts whether the airport is within the territory of the European Union or in Norway, Switzerland or Iceland.</inlineHelpText>
    <label>Is EU261 Applicable</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>The latitude of the airport.</description>
    <inlineHelpText>The latitude of the airport.</inlineHelpText>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>The longitude of the airport.</description>
    <inlineHelpText>The longitude of the airport.</inlineHelpText>
    <label>Longitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference__c</fullName>
    <description>The six character reference for this booking. Not necessarily unique.</description>
    <inlineHelpText>The six character reference for this booking.</inlineHelpText>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</description>
    <inlineHelpText>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DayReturn</fullName>
            </value>
            <value>
                <fullName>MultiCity</fullName>
            </value>
            <value>
                <fullName>OneWay</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <description>Two character IATA airline designator of the flight&apos;s operating carrier.</description>
    <inlineHelpText>Two character IATA airline designator of the flight&apos;s operating carrier.</inlineHelpText>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_Time__c</fullName>
    <label>Scheduled Arrival Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Scheduled_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Departure_Time__c</fullName>
    <label>Scheduled Departure Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/bookings/Trip_Test.cls
@IsTest
private class Trip_Test {
  private static String oneWayBookingReference = 'ONTIME';
  private static String roundTripBookingReference = 'ROUNDT';
  private static String dayReturnBookingReference = 'DAYRET';
  private static String multiCityBookingReference = 'MULTIC';
  private static String unknownBookingReference = 'UNKNOW';

  @TestSetup
  static void makeBookings() {
    Booking__c oneWayBooking = new Booking__c(
      Booking_Reference__c = oneWayBookingReference,
      TEDS_Identifier__c = 'uniqueBooking1',
      Type__c = 'OneWay'
    );
    Booking__c dayReturnBooking = new Booking__c(
      Booking_Reference__c = dayReturnBookingReference,
      TEDS_Identifier__c = 'uniqueBooking2',
      Type__c = 'DayReturn'
    );
    Booking__c multiCityBooking = new Booking__c(
      Booking_Reference__c = multiCityBookingReference,
      TEDS_Identifier__c = 'uniqueBooking3',
      Type__c = 'MultiCity'
    );
    Booking__c roundTripBooking = new Booking__c(
      Booking_Reference__c = roundTripBookingReference,
      TEDS_Identifier__c = 'uniqueBooking4',
      Type__c = 'RoundTrip'
    );
    Booking__c unknownBooking = new Booking__c(
      Booking_Reference__c = unknownBookingReference,
      TEDS_Identifier__c = 'uniqueBooking5',
      Type__c = 'Unknown'
    );
    Flight__c flight1 = new Flight__c(
      Arrival_Airport__c = 'ARN',
      Departure_Airport__c = 'HEL',
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK0001-20220817',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 17, 0, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 17, 2, 1, 0),
      Actual_Arrival_Time__c = DateTime.newInstance(2022, 8, 17, 4, 11, 0)
    );
    Flight__c flight2 = new Flight__c(
      Arrival_Airport__c = 'HEL',
      Departure_Airport__c = 'ARN',
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK0002-20220817',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 17, 10, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 17, 12, 1, 0)
    );
    Flight__c flight3 = new Flight__c(
      Arrival_Airport__c = 'HEL',
      Departure_Airport__c = 'CPH',
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK0003-20220818',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 18, 0, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 18, 2, 1, 0),
      Actual_Arrival_Time__c = DateTime.newInstance(2022, 8, 18, 4, 11, 0)
    );
    Flight__c flight4 = new Flight__c(
      Arrival_Airport__c = 'CPH',
      Departure_Airport__c = 'ARN',
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK0004-20220818',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 17, 4, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 17, 6, 1, 0),
      Actual_Arrival_Time__c = DateTime.newInstance(2022, 8, 18, 4, 11, 0)
    );
    Flight__c flight5 = new Flight__c(
      Arrival_Airport__c = 'CDG',
      Departure_Airport__c = 'CPH',
      Operating_Carrier__c = 'SK',
      TEDS_Identifier__c = 'SK0005-20220818',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 19, 0, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 19, 2, 1, 0),
      Actual_Arrival_Time__c = DateTime.newInstance(2022, 8, 18, 4, 11, 0)
    );
    Flight__c flightRoundtripReturn = new Flight__c(
      Arrival_Airport__c = 'HEL',
      Departure_Airport__c = 'ARN',
      TEDS_Identifier__c = 'SK0004-20220819',
      Operating_Carrier__c = 'SK',
      Scheduled_Departure_Time__c = DateTime.newInstance(2022, 8, 19, 0, 1, 0),
      Scheduled_Arrival_Time__c = DateTime.newInstance(2022, 8, 19, 2, 1, 0)
    );
    Airport__c airportHEL = new Airport__c(
      City__c = 'Helsinki',
      Country_Code__c = 'FI',
      Country_Name__c = 'Finland',
      TEDS_Identifier__c = 'HEL',
      Is_EU261_Applicable__c = true,
      Latitude__c = 60.317199707031,
      Longitude__c = 24.963300704956
    );
    Airport__c airportARN = new Airport__c(
      City__c = 'Stockholm',
      Country_Code__c = 'SE',
      Country_Name__c = 'Sweden',
      TEDS_Identifier__c = 'ARN',
      Is_EU261_Applicable__c = true,
      Latitude__c = 59.651901245117,
      Longitude__c = 17.918600082397
    );
    Airport__c airportCPH = new Airport__c(
      City__c = 'Copenhagen',
      Country_Code__c = 'DK',
      Country_Name__c = 'Denmark',
      TEDS_Identifier__c = 'CPH',
      Is_EU261_Applicable__c = true,
      Latitude__c = 55.617900848389,
      Longitude__c = 12.656000137329
    );
    Airport__c airportCDG = new Airport__c(
      City__c = 'Paris',
      Country_Code__c = 'FR',
      Country_Name__c = 'France',
      TEDS_Identifier__c = 'CDG',
      Is_EU261_Applicable__c = true,
      Latitude__c = 49.012798,
      Longitude__c = 2.55
    );
    Airport__c airportJFK = new Airport__c(
      City__c = 'New York',
      Country_Code__c = 'US',
      Country_Name__c = 'United States',
      TEDS_Identifier__c = 'JFK',
      Is_EU261_Applicable__c = false,
      Latitude__c = 40.639801,
      Longitude__c = -73.7789
    );

    insert new List<SObject>{
      oneWayBooking,
      dayReturnBooking,
      multiCityBooking,
      roundTripBooking,
      unknownBooking,
      flight1,
      flight2,
      flight3,
      flight4,
      flight5,
      flightRoundtripReturn,
      airportHEL,
      airportARN,
      airportCPH,
      airportCDG,
      airportJFK
    };

    Segment__c oneWaySegment = new Segment__c(
      Booking__c = oneWayBooking.Id,
      Flight__c = flight1.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c dayReturnSegment1 = new Segment__c(
      Booking__c = dayReturnBooking.Id,
      Flight__c = flight1.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c dayReturnSegment2 = new Segment__c(
      Booking__c = dayReturnBooking.Id,
      Flight__c = flight2.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Inbound'
    );
    Segment__c roundTripSegment1 = new Segment__c(
      Booking__c = roundTripBooking.Id,
      Flight__c = flight1.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c roundTripSegment2 = new Segment__c(
      Booking__c = roundTripBooking.Id,
      Flight__c = flightRoundtripReturn.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Inbound'
    );
    Segment__c multiCitySegment1 = new Segment__c(
      Booking__c = multiCityBooking.Id,
      Flight__c = flight1.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c multiCitySegment2 = new Segment__c(
      Booking__c = multiCityBooking.Id,
      Flight__c = flight4.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c multiCitySegment3 = new Segment__c(
      Booking__c = multiCityBooking.Id,
      Flight__c = flight5.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Outbound'
    );
    Segment__c unknownSegment = new Segment__c(
      Booking__c = unknownBooking.Id,
      Flight__c = flight1.Id,
      Seat__c = '1A',
      Trip_Type__c = 'Unknown'
    );

    insert new List<SObject>{
      oneWaySegment,
      dayReturnSegment1,
      dayReturnSegment2,
      roundTripSegment1,
      roundTripSegment2,
      multiCitySegment1,
      multiCitySegment2,
      multiCitySegment3,
      unknownSegment
    };
  }

  @IsTest
  static void oneWayShouldBeDividedIntoOneTrip() {
    Booking__c bc = BookingsSelector.newInstance()
      .selectByBookingReference(oneWayBookingReference)[0];
    Booking b = new Booking(bc);
    b.setAirports(getAirports());
    List<Trip> trips = Trip.createFromBooking(b, System.now());

    System.assertEquals(
      1,
      trips.size(),
      'Should divide booking into a single trip'
    );

    System.assertEquals(
      trips[0].originAirport.tedsIdentifier,
      'HEL',
      'Origin airport should be HEL'
    );

    System.assertEquals(
      trips[0].destinationAirport.tedsIdentifier,
      'ARN',
      'Destination airport should be ARN'
    );
  }

  @IsTest
  static void roundTripShouldBeDividedIntoTwoTrips() {
    Booking__c bc = BookingsSelector.newInstance()
      .selectByBookingReference(roundTripBookingReference)[0];
    Booking b = new Booking(bc);
    b.setAirports(getAirports());
    List<Trip> trips = Trip.createFromBooking(b, System.now());

    System.assertEquals(
      2,
      trips.size(),
      'Should divide booking into two trips'
    );

    System.assertEquals(
      trips[0].originAirport.tedsIdentifier,
      'HEL',
      'Origin airport of the first trip should be HEL'
    );

    System.assertEquals(
      trips[0].destinationAirport.tedsIdentifier,
      'ARN',
      'Destination airport of the first trip should be ARN'
    );

    System.assertEquals(
      trips[1].originAirport.tedsIdentifier,
      'ARN',
      'Origin airport of the second trip should be ARN'
    );

    System.assertEquals(
      trips[1].destinationAirport.tedsIdentifier,
      'HEL',
      'Destination airport of the second trip should be HEL'
    );
  }

  @IsTest
  static void dayReturnShouldBeDividedIntoTwoTrips() {
    Booking__c bc = BookingsSelector.newInstance()
      .selectByBookingReference(dayReturnBookingReference)[0];
    Booking b = new Booking(bc);
    b.setAirports(getAirports());

    Boolean isSupported = true;
    try {
      List<Trip> trips = Trip.createFromBooking(b, System.now());
    } catch (Trip.BookingTypeNotSupportedException e) {
      isSupported = false;
    }

    System.assert(!isSupported, 'Dayreturn bookings should not be supported');
  }

  @IsTest
  static void multiCityTwoCitiesShouldBeDividedIntoTwoTrips() {
    Booking__c bc = BookingsSelector.newInstance()
      .selectByBookingReference(multiCityBookingReference)[0];
    Booking b = new Booking(bc);
    b.setAirports(getAirports());

    List<Trip> trips = Trip.createFromBooking(b, System.now());

    System.assertEquals(
      2,
      trips.size(),
      'Should divide booking into two trips'
    );

    System.assertEquals(
      trips[0].originAirport.tedsIdentifier,
      'HEL',
      'Origin airport of the first trip should be HEL'
    );

    System.assertEquals(
      trips[0].destinationAirport.tedsIdentifier,
      'CPH',
      'Destination airport of the first trip should be CPH'
    );

    System.assertEquals(
      trips[1].originAirport.tedsIdentifier,
      'CPH',
      'Origin airport of the second trip should be CPH'
    );

    System.assertEquals(
      trips[1].destinationAirport.tedsIdentifier,
      'CDG',
      'Destination airport of the second trip should be CDG'
    );
  }

  private static Map<String, Airport> getAirports() {
    List<Airport__c> allAirports = AirportsSelector.newInstance()
      .selectByIATACode(new Set<String>{ 'HEL', 'ARN', 'CPH', 'JFK', 'CDG' });
    Map<String, Airport> airportCodeToAirport = new Map<String, Airport>{};
    for (Airport__c a : allAirports) {
      airportCodeToAirport.put(a.TEDS_Identifier__c, new Airport(a));
    }

    return airportCodeToAirport;
  }
}