sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the airport is located in.</description>
    <inlineHelpText>The city the airport is located in.</inlineHelpText>
    <label>City</label>
    <length>58</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of the country the airport is located in.</description>
    <inlineHelpText>The country code of the country the airport is located in.</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The country the airport is located in.</description>
    <inlineHelpText>The country the airport is located in.</inlineHelpText>
    <label>Country Name</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Is_In_European_Union__c.field-meta.xml
<CustomField>
    <fullName>Is_In_European_Union__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean which asserts whether the airport is within the territory of a country which is part of the european union.</description>
    <inlineHelpText>A boolean which asserts whether the airport is within the territory of a country which is part of the european union.</inlineHelpText>
    <label>Is In European Union</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>The latitude of the airport.</description>
    <inlineHelpText>The latitude of the airport.</inlineHelpText>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>The longitude of the airport.</description>
    <inlineHelpText>The longitude of the airport.</inlineHelpText>
    <label>Longitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/selectors/AirportsSelector.cls
public inherited sharing class AirportsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Airport__c.Id,
      Airport__c.Name,
      Airport__c.City__c,
      Airport__c.Country_Code__c,
      Airport__c.Country_Name__c,
      Airport__c.Latitude__c,
      Airport__c.Longitude__c,
      Airport__c.Is_In_European_Union__c,
      Airport__c.TEDS_Identifier__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Airport__c.SObjectType;
  }

  public static AirportsSelector newInstance() {
    return (AirportsSelector) SAS_Service_Application.Selector.newInstance(
      Airport__c.SObjectType
    );
  }

  public List<Airport__c> selectById(Set<Id> ids) {
    return (List<Airport__c>) selectSObjectsById(ids);
  }

  public List<Airport__c> selectByTEDSId(Set<String> airportIds) {
    return (List<Airport__c>) Database.query(
      newQueryFactory()
        .setCondition('TEDS_Identifier__c IN :airportIds')
        .toSOQL()
    );
  }

  // Todo:
  // Examine: Should we really fetch these dynamically or could we just have a cronjob running once every week and store all airports in the db (about 3000)?
  public List<Airport__c> selectAndOrFetchByTEDSId(Set<String> airportIds) {
    List<Airport__c> airportsInDb = (List<Airport__c>) Database.query(
      newQueryFactory()
        .setCondition('TEDS_Identifier__c IN :airportIds')
        .toSOQL()
    );

    // If records not in database, fetch them from TEDS
    if (airportsInDb.size() < airportIds.size()) {
      for (Airport__c airportInDb : airportsInDb) {
        airportIds.remove(airportInDb.Id);
      }

      if (Test.isRunningTest()) {
        // Deal with DML + callout issues
        airportsInDb.addAll(
          AirportService.newInstance()
            .fetchAirportsByReference(airportIds, false)
            .instanceRecords
        );
      } else {
        airportsInDb.addAll(
          AirportService.newInstance()
            .fetchAirportsByReference(airportIds, true)
            .instanceRecords
        );
      }
    }

    return airportsInDb;
  }

  public override String getOrderBy() {
    return 'TEDS_Identifier__c';
  }
}