sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>A single booking containing possible several segments and passengers. 

Bookings are identified uniquely by a booking identifier, and mostly uniquely the 6 character booking reference.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Booking__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this booking. Six character PNR followed by date.</description>
    <externalId>true</externalId>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</description>
    <inlineHelpText>Booking type, one of DayReturn, MultiCity, OneWay, RoundTrip or Unknown.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DayReturn</fullName>
            </value>
            <value>
                <fullName>MultiCity</fullName>
            </value>
            <value>
                <fullName>OneWay</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <description>Flight date supplied by customer for feedback cases.</description>
    <inlineHelpText>Flight date supplied by customer for feedback cases.</inlineHelpText>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>Flight number supplied by customer for a feedback case.</description>
    <inlineHelpText>Flight number supplied by customer for a feedback case.</inlineHelpText>
    <label>Flight Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Case/fields/LIA_Claim__c.field-meta.xml
<CustomField>
    <fullName>LIA_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liability Claim linked to the current case</description>
    <inlineHelpText>Liability Claim related to this case</inlineHelpText>
    <label>Liability Claim</label>
    <referenceTo>LIA_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/fields/Proactivity__c.field-meta.xml
<CustomField>
    <fullName>Proactivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use to manually link a case to a proactivity</description>
    <inlineHelpText>Use to manually link a case to a proactivity</inlineHelpText>
    <label>Proactivity</label>
    <referenceTo>Proactivity__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Liability</businessProcess>
    <description>Use for claim related cases</description>
    <label>Claim</label>
</RecordType>

sas-core/main/default/objects/CaseToBooking__c/CaseToBooking__c.object-meta.xml
<CustomObject>
    <label>CaseToBooking</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CaseToBooking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CasesToBookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/CaseToBooking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/CaseToBooking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <label>Arrival Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>Unique identifier of this flight.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier of this flight.</inlineHelpText>
    <label>TEDS Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/FlightIrregularities__c.object-meta.xml
<CustomObject>
    <description>Holds information about delays and cancellations.</description>
    <label>FlightIrregularities</label>
    <nameField>
        <label>FlightIrregularities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlightIrregularities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/FlightIrregularities__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The cancellation/delay code parsed from TEDS</description>
    <inlineHelpText>The cancellation/delay code parsed from TEDS</inlineHelpText>
    <label>Cancellation code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <description>The flight to which the irregularity pertains</description>
    <inlineHelpText>The flight to which the irregularity pertains</inlineHelpText>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>Flight_Irregularities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/FlightIrregularities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the irregularity (cancellation/delay)</description>
    <inlineHelpText>The type of the irregularity (cancellation/delay)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/LIA_Claim__c.object-meta.xml
<CustomObject>
    <description>Contains the detailed information about a claim</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sas-core/main/default/objects/LIA_Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case related to this claim</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/Proactivity__c.object-meta.xml
<CustomObject>
    <description>Information notice to be shown when a claim matches the criteria defined for the proactivity.</description>
    <label>Proactivity</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Proactivity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proactivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Proactivity__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <description>Match all flights arriving to and/or departing the airport.</description>
    <inlineHelpText>Match all flights arriving to and/or departing the airport.</inlineHelpText>
    <label>Airport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Cancellation_Code__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Code__c</fullName>
    <label>Cancellation Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CancellationCode</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address to match on.</description>
    <inlineHelpText>Email address to match on.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <description>Date when the proactivity becomes relevant</description>
    <inlineHelpText>Date when the proactivity becomes relevant</inlineHelpText>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Match_Flights_Arriving_To_Airport__c.field-meta.xml
<CustomField>
    <fullName>Match_Flights_Arriving_To_Airport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the proactivity should match flights arriving to the airport</description>
    <inlineHelpText>If the proactivity should match flights arriving to the airport</inlineHelpText>
    <label>Match Flights Arriving To Airport</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Match_Flights_Departing_Airport__c.field-meta.xml
<CustomField>
    <fullName>Match_Flights_Departing_Airport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the proactivity should match flights departing the airport</description>
    <inlineHelpText>If the proactivity should match flights departing the airport</inlineHelpText>
    <label>Match Flights Departing Airport</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <description>The message to be displayed for matching claims.</description>
    <inlineHelpText>The message to be displayed for matching claims.</inlineHelpText>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number to match on.</description>
    <inlineHelpText>Phone number to match on.</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <description>Date when the proactivity stops being relevant</description>
    <inlineHelpText>Date when the proactivity stops being relevant</inlineHelpText>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>For differentiating between the different types of proactivities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Major Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Segment__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/globalValueSets/CancellationCode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AIRS</fullName>
    </customValue>
    <customValue>
        <fullName>AUTH</fullName>
    </customValue>
    <customValue>
        <fullName>ARPT</fullName>
    </customValue>
    <customValue>
        <fullName>COMM</fullName>
    </customValue>
    <customValue>
        <fullName>CREW</fullName>
    </customValue>
    <customValue>
        <fullName>DAMA</fullName>
    </customValue>
    <customValue>
        <fullName>EQUI</fullName>
    </customValue>
    <customValue>
        <fullName>FUEL</fullName>
    </customValue>
    <customValue>
        <fullName>HDLG</fullName>
    </customValue>
    <customValue>
        <fullName>HOLI</fullName>
    </customValue>
    <customValue>
        <fullName>INDU</fullName>
    </customValue>
    <customValue>
        <fullName>NODE</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>OPCO</fullName>
    </customValue>
    <customValue>
        <fullName>OPER</fullName>
    </customValue>
    <customValue>
        <fullName>PERF</fullName>
    </customValue>
    <customValue>
        <fullName>POLI</fullName>
    </customValue>
    <customValue>
        <fullName>REPO</fullName>
    </customValue>
    <customValue>
        <fullName>ROTA</fullName>
    </customValue>
    <customValue>
        <fullName>RTNS</fullName>
    </customValue>
    <customValue>
        <fullName>RUNW</fullName>
    </customValue>
    <customValue>
        <fullName>TECH</fullName>
    </customValue>
    <customValue>
        <fullName>WEAT</fullName>
    </customValue>
    <masterLabel>CancellationCode</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/selectors/ClaimsSelector_Test.cls
/**
 * To run tests manually:
 * 1. Run the code within "setup()"
 * 2. To connect a proactivity with a claim you need a Segment and a CaseToBooking, these can be created like this:
 * ----------------------------
 * List<Booking__c> bookings = [SELECT Id, TEDS_Identifier__c FROM Booking__c WHERE TEDS_Identifier = ?];
 * List<Flight__c> lf = [SELECT Id, TEDS_Identifier__c FROM Flight__c WHERE TEDS_Identifier__c = ?];
 * List<Case> lc = [SELECT Id FROM Case WHERE CaseNumber = ?];
 * Id fid = lf[0].Id;
 * Id cid = lc[0].Id;
 * Id bid = bookings[0];
 * Segment__c s = new Segment__c(Booking__c = bid, Flight__c = fid);
 * CaseToBooking__c c = new CaseToBooking__c(Booking__c = bid, Case__c = cid);
 * insert new List<sObject>{s, c};
 * ----------------------------
 * Replace "?" with the identifiers for the Bookings, Flights and Cases you wish to connect.
 */
@IsTest
private class ClaimsSelector_Test {
  private static ClaimsSelector claims = ClaimsSelector.newInstance();

  @testSetup
  static void setup() {
    Date today = Date.today();

    Proactivity__c normalProactivity = new Proactivity__c(
      Note__c = 'Test 1',
      Type__c = 'Normal',
      Email__c = 'test@test.com'
    );
    Proactivity__c majorEventProactivity = new Proactivity__c(
      Note__c = 'Test 2',
      Type__c = 'Major Event',
      Phone_Number__c = '0000000000'
    );
    Proactivity__c airportMatcherProactivity = new Proactivity__c(
      Note__c = 'Test 3',
      Type__c = 'Normal',
      Airport__c = 'ARN',
      Match_Flights_Arriving_To_Airport__c = true,
      Match_Flights_Departing_Airport__c = false,
      From_Date__c = today,
      To_Date__c = today
    );
    Proactivity__c cancellationCodeProactivity = new Proactivity__c(
      Note__c = 'Test 4',
      Type__c = 'Normal',
      Cancellation_Code__c = 'AIRS',
      From_Date__c = today,
      To_Date__c = today
    ); // TODO: Change to real cancellation codes
    Proactivity__c airportMatcherAndCancellationCodeProactivity = new Proactivity__c(
      Note__c = 'Test 5',
      Type__c = 'Normal',
      Cancellation_Code__c = 'AIRS',
      Airport__c = 'ARN',
      Match_Flights_Arriving_To_Airport__c = true,
      Match_Flights_Departing_Airport__c = false,
      From_Date__c = today,
      To_Date__c = today
    );
    Proactivity__c directlyMatchedProactivity = new Proactivity__c(
      Note__c = 'Test 6',
      Type__c = 'Normal'
    );

    insert directlyMatchedProactivity;

    Case caseWithOneProactivityRegularMatcher = new Case();
    Case caseWithTwoProactivitiesRegularMatcher = new Case();
    Case caseWithOneProactivityAirportMatcher = new Case();
    Case caseWithOneProactivityCancellationCodeMatcher = new Case();
    Case caseWithThreeProactivitiesCancellationCodeAndAirportMatcher = new Case();
    Case caseWithDirectMatch = new Case(
      Proactivity__c = directlyMatchedProactivity.Id
    );

    insert new List<Case>{
      caseWithOneProactivityRegularMatcher,
      caseWithTwoProactivitiesRegularMatcher,
      caseWithOneProactivityAirportMatcher,
      caseWithOneProactivityCancellationCodeMatcher,
      caseWithThreeProactivitiesCancellationCodeAndAirportMatcher,
      caseWithDirectMatch
    };

    LIA_Claim__c claimWithOneProactivityRegularMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityRegularMatcher.Id,
      Phone_Number__c = '0000000000'
    );
    LIA_Claim__c claimWithTwoProactivitiesRegularMatcher = new LIA_Claim__c(
      Case__c = caseWithTwoProactivitiesRegularMatcher.Id,
      Contact_Email__c = 'test@test.com',
      Phone_Number__c = '0000000000'
    );
    LIA_Claim__c claimWithOneProactivityAirportMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityAirportMatcher.Id,
      Flight_Number__c = 'SK1',
      Flight_Date__c = today
    );
    LIA_Claim__c claimWithOneProactivityCancellationCodeMatcher = new LIA_Claim__c(
      Case__c = caseWithOneProactivityCancellationCodeMatcher.Id,
      Flight_Number__c = 'SK2',
      Flight_Date__c = today
    );
    LIA_Claim__c claimWithThreeProactivitesCancellationCodeAndAirportMatcher = new LIA_Claim__c(
      Case__c = caseWithThreeProactivitiesCancellationCodeAndAirportMatcher.Id,
      Flight_Number__c = 'SK3',
      Flight_Date__c = today
    );
    LIA_Claim__c claimWithDirectMatch = new LIA_Claim__c(
      Case__c = caseWithDirectMatch.Id,
      Phone_Number__c = '0000000001'
    );

    String flightIdentifier1 =
      Flight.constructTEDSFlightNumberDate('SK1', today) + '-UME-ARN';
    String flightIdentifier2 =
      Flight.constructTEDSFlightNumberDate('SK2', today) + '-ARN-UME';
    String flightIdentifier3 =
      Flight.constructTEDSFlightNumberDate('SK3', today) + '-UME-ARN';

    Flight__c flight1 = new Flight__c(
      Arrival_Airport__c = 'ARN',
      Departure_Airport__c = 'UME',
      Scheduled_Arrival_Time__c = today,
      Scheduled_Departure_Time__c = today,
      TEDS_Identifier__c = flightIdentifier1
    );

    Flight__c flight2 = new Flight__c(
      Arrival_Airport__c = 'UME',
      Departure_Airport__c = 'ARN',
      Scheduled_Arrival_Time__c = today,
      Scheduled_Departure_Time__c = today,
      TEDS_Identifier__c = flightIdentifier2
    );

    Flight__c flight3 = new Flight__c(
      Arrival_Airport__c = 'ARN',
      Departure_Airport__c = 'UME',
      Scheduled_Arrival_Time__c = today,
      Scheduled_Departure_Time__c = today,
      TEDS_Identifier__c = flightIdentifier3
    );

    insert new List<Flight__c>{ flight1, flight2, flight3 };

    FlightIrregularities__c flightIrregularity1 = new FlightIrregularities__c(
      Flight__c = flight1.Id,
      Code__c = 'AUTH'
    );

    FlightIrregularities__c flightIrregularity2 = new FlightIrregularities__c(
      Flight__c = flight2.Id,
      Code__c = 'AIRS'
    );

    FlightIrregularities__c flightIrregularity3 = new FlightIrregularities__c(
      Flight__c = flight3.Id,
      Code__c = 'AIRS'
    );

    Booking__c bookingAirportMatcher = new Booking__c(
      TEDS_Identifier__c = 'ABC123'
    );
    Booking__c booking2CancellationCodeMatcher = new Booking__c(
      TEDS_Identifier__c = 'ABC321'
    );
    Booking__c booking2CancellationCodeAndAirportMatcher = new Booking__c(
      TEDS_Identifier__c = 'ABC000'
    );

    insert new List<Booking__c>{
      bookingAirportMatcher,
      booking2CancellationCodeMatcher,
      booking2CancellationCodeAndAirportMatcher
    };

    Segment__c segmentAirportMatcher = new Segment__c(
      Booking__c = bookingAirportMatcher.Id,
      Flight__c = flight1.Id
    );
    Segment__c segmentCancellationCodeMatcher = new Segment__c(
      Booking__c = booking2CancellationCodeMatcher.Id,
      Flight__c = flight2.Id
    );
    Segment__c segmentCancellationCodeAndAirportMatcher = new Segment__c(
      Booking__c = booking2CancellationCodeAndAirportMatcher.Id,
      Flight__c = flight3.Id
    );

    CaseToBooking__c ctbAirportMatcher = new CaseToBooking__c(
      Booking__c = bookingAirportMatcher.Id,
      Case__c = caseWithOneProactivityAirportMatcher.Id
    );

    CaseToBooking__c ctbCancellationCodeMatcher = new CaseToBooking__c(
      Booking__c = booking2CancellationCodeMatcher.Id,
      Case__c = caseWithOneProactivityCancellationCodeMatcher.Id
    );

    CaseToBooking__c ctbCancellationCodeAndAirportMatcher = new CaseToBooking__c(
      Booking__c = booking2CancellationCodeAndAirportMatcher.Id,
      Case__c = caseWithThreeProactivitiesCancellationCodeAndAirportMatcher.Id
    );

    insert new List<SObject>{
      segmentAirportMatcher,
      segmentCancellationCodeMatcher,
      segmentCancellationCodeAndAirportMatcher,
      ctbAirportMatcher,
      ctbCancellationCodeMatcher,
      ctbCancellationCodeAndAirportMatcher,
      normalProactivity,
      majorEventProactivity,
      airportMatcherProactivity,
      cancellationCodeProactivity,
      claimWithOneProactivityRegularMatcher,
      claimWithTwoProactivitiesRegularMatcher,
      claimWithOneProactivityAirportMatcher,
      claimWithOneProactivityCancellationCodeMatcher,
      claimWithThreeProactivitesCancellationCodeAndAirportMatcher,
      claimWithDirectMatch,
      airportMatcherAndCancellationCodeProactivity,
      flightIrregularity1,
      flightIrregularity2,
      flightIrregularity3
    };
  }

  @IsTest
  static void shouldSelectClaimWithNormalProactivity() {
    // Given (setup)
    Proactivity__c normalProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 1'
    ][0];
    LIA_Claim__c correctClaim = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Contact_Email__c = 'test@test.com'
    ][0];

    // When
    List<LIA_Claim__c> oneClaimNormalMatcher = claims.selectByProactivityId(
      normalProactivity.ID
    );

    // Then
    System.assertEquals(
      1,
      oneClaimNormalMatcher.size(),
      'Should select a single claim from proactivity ID correctly (too many/few matches)'
    );
    System.assertEquals(
      correctClaim.Id,
      oneClaimNormalMatcher[0].Id,
      'Should select a single claim from proactivity ID correctly (wrong claim)'
    );
  }
  @IsTest
  static void shouldSelectClaimWithMajorEventProactivity() {
    // Given (setup)
    Proactivity__c majorEventProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 2'
    ][0];
    List<LIA_Claim__c> claimList = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Phone_Number__c = '0000000000'
    ];

    LIA_Claim__c correctClaim1 = claimList[0];
    LIA_Claim__c correctClaim2 = claimList[1];

    // When
    List<LIA_Claim__c> twoClaimsMajorEventMatcher = claims.selectByProactivityId(
      majorEventProactivity.ID
    );

    // Then
    Integer correctlyMatched = 0;
    for (LIA_Claim__c c : twoClaimsMajorEventMatcher) {
      if (c.id == correctClaim1.Id || c.id == correctClaim2.Id) {
        correctlyMatched += 1;
      }
    }

    System.assertEquals(
      2,
      twoClaimsMajorEventMatcher.size(),
      'Should select two proactivities from case ID correctly (too many/few matches)'
    );
    System.assertEquals(
      2,
      correctlyMatched,
      'Should select two proactivities from case ID correctly (wrong proactivity)'
    );
  }
  @IsTest
  static void shouldSelectClaimWithAirportMatcherProactivity() {
    // Given (setup)
    Proactivity__c airportProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 3'
    ][0];
    LIA_Claim__c correctClaim1 = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Flight_Number__c = 'SK0001'
    ][0];
    LIA_Claim__c correctClaim2 = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Flight_Number__c = 'SK0003'
    ][0];

    // When
    List<LIA_Claim__c> twoClaimsAirportMatcher = claims.selectByProactivityId(
      airportProactivity.ID
    );

    // Then
    Integer correctlyMatched = 0;
    for (LIA_Claim__c c : twoClaimsAirportMatcher) {
      if (c.id == correctClaim1.Id || c.id == correctClaim2.Id) {
        correctlyMatched += 1;
      }
    }

    System.assertEquals(
      2,
      twoClaimsAirportMatcher.size(),
      'Should select two proactivities with airport matcher from case ID correctly (too many/few matches)'
    );
    System.assertEquals(
      2,
      correctlyMatched,
      'Should select two proactivities with airport matcher from case ID correctly (wrong proactivity)'
    );
  }

  @IsTest
  static void shouldSelectClaimWithCancellationCodeProactivity() {
    // Given (setup)
    Proactivity__c cancellationCodeProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 4'
    ][0];
    LIA_Claim__c correctClaim1 = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Flight_Number__c = 'SK0002'
    ][0];
    LIA_Claim__c correctClaim2 = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Flight_Number__c = 'SK0003'
    ][0];

    // When
    List<LIA_Claim__c> twoClaimsCancellationCodeMatcher = claims.selectByProactivityId(
      cancellationCodeProactivity.ID
    );

    // Then
    Integer correctlyMatched = 0;
    for (LIA_Claim__c c : twoClaimsCancellationCodeMatcher) {
      if (c.id == correctClaim1.Id || c.id == correctClaim2.Id) {
        correctlyMatched += 1;
      }
    }

    System.assertEquals(
      2,
      twoClaimsCancellationCodeMatcher.size(),
      'Should select two proactivities with cancellation code matcher from case ID correctly (too many/few matches)'
    );
    System.assertEquals(
      2,
      correctlyMatched,
      'Should select two proactivities with cancellation code matcher from case ID correctly (wrong proactivity)'
    );
  }

  @IsTest
  static void shouldSelectClaimWithCancellationCodeAndAirportProactivity() {
    // Given (setup)
    Proactivity__c cancellationCodeAndAirportProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 5'
    ][0];
    LIA_Claim__c correctClaim = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Flight_Number__c = 'SK0003'
    ][0];

    // When
    List<LIA_Claim__c> oneClaimCancellationCodeAndAirportMatcher = claims.selectByProactivityId(
      cancellationCodeAndAirportProactivity.ID
    );

    // Then
    System.assertEquals(
      1,
      oneClaimCancellationCodeAndAirportMatcher.size(),
      'Should select a single claim from proactivity ID correctly (too many/few matches)'
    );
    System.assertEquals(
      correctClaim.Id,
      oneClaimCancellationCodeAndAirportMatcher[0].Id,
      'Should select a single claim from proactivity ID correctly (wrong claim)'
    );
  }

  @IsTest
  static void shouldSelectClaimWithDirectMatch() {
    // Given (setup)
    Proactivity__c directMatchProactivity = [
      SELECT Id
      FROM Proactivity__c
      WHERE Note__c = 'Test 6'
    ][0];
    LIA_Claim__c correctClaim = [
      SELECT Id
      FROM LIA_Claim__c
      WHERE Phone_Number__c = '0000000001'
    ][0];

    // When
    List<LIA_Claim__c> oneClaimDirectMatch = claims.selectByProactivityId(
      directMatchProactivity.ID
    );

    // Then
    System.assertEquals(
      1,
      oneClaimDirectMatch.size(),
      'Should select a single claim from proactivity ID correctly (too many/few matches)'
    );
    System.assertEquals(
      correctClaim.Id,
      oneClaimDirectMatch[0].Id,
      'Should select a single claim from proactivity ID correctly (wrong claim)'
    );
  }
}