sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the airport is located in.</description>
    <inlineHelpText>The city the airport is located in.</inlineHelpText>
    <label>City</label>
    <length>58</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of the country the airport is located in.</description>
    <inlineHelpText>The country code of the country the airport is located in.</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The country the airport is located in.</description>
    <inlineHelpText>The country the airport is located in.</inlineHelpText>
    <label>Country Name</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>The latitude of the airport.</description>
    <inlineHelpText>The latitude of the airport.</inlineHelpText>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>The longitude of the airport.</description>
    <inlineHelpText>The longitude of the airport.</inlineHelpText>
    <label>Longitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/tests/integration/AirportService_IntegrationTest.cls
// Todo: move to test folder
@IsTest
public with sharing class AirportService_IntegrationTest {
  public static String airportIdFromTEDS = 'ARN';
  public static String specialTerriroryAirportIdFromTEDS = 'RUN';
  public static Set<String> airportIdsFromTEDS = new Set<String>{
    'ARN',
    'HEL'
  };
  public static String cityInDetailedAirportInfo = 'Stockholm';

  @IsTest
  public static void shouldFetchAirportsByAirportId() {
    // Given
    Set<String> airportIds = new Set<String>();
    airportIds.add(airportIdFromTEDS);
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    Test.startTest();
    AirportService.newInstance().fetchAirportsByReference(airportIds, true);
    Test.stopTest();

    // Then
    Airport__c airportFromDB = AirportsSelector.newInstance()
      .selectByTEDSId(new Set<String>{ airportIdFromTEDS })[0];

    System.assertEquals(
      'Stockholm-Arlanda Airport',
      airportFromDB.Name,
      'Airport should exist and have the correct name.'
    );
    System.assertEquals(
      cityInDetailedAirportInfo,
      airportFromDB.City__c,
      'Airport should exist and have the correct city.'
    );

    System.assertEquals(
      'SE',
      airportFromDB.Country_Code__c,
      'Airport should exist and have the correct country code.'
    );
    System.assertEquals(
      'Sweden',
      airportFromDB.Country_Name__c,
      'Airport should exist and have the correct country name.'
    );
    System.assertEquals(
      59.651901245117,
      airportFromDB.Latitude__c,
      'Airport should exist and have the correct latitude.'
    );
    System.assertEquals(
      17.918600082397,
      airportFromDB.Longitude__c,
      'Airport should exist and have the correct longitude.'
    );
    System.assertEquals(
      'ARN',
      airportFromDB.TEDS_Identifier__c,
      'Airport should exist and have the correct TEDS Identifier.'
    );
  }

  @IsTest
  public static void shouldBatchFetchAirportsByAirportId() {
    // Given
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    Test.startTest();
    AirportService.newInstance()
      .fetchAirportsByReference(airportIdsFromTEDS, true);
    Test.stopTest();

    // Then
    List<Airport__c> airportsFromDB = AirportsSelector.newInstance()
      .selectByTEDSId(airportIdsFromTEDS);

    List<String> correctAirportIdentifiers = new List<String>{ 'ARN', 'HEL' };
    List<String> airportIdentifiers = new List<String>{};
    for (Airport__c a : airportsFromDB) {
      airportIdentifiers.add(a.TEDS_Identifier__c);
    }

    airportIdentifiers.sort();
    for (Integer i = 0; i < airportsFromDB.size(); i++) {
      System.assertEquals(
        airportIdentifiers[i],
        correctAirportIdentifiers[i],
        'Should fetch and insert all airports.'
      );
    }

    System.assertEquals(
      2,
      airportsFromDB.size(),
      'Should fetch and insert the correct amount of airports.'
    );
  }

  @IsTest
  public static void shouldFetchSpecialTerritoryAirportsByAirportId() {
    // Given
    Set<String> airportIds = new Set<String>();
    airportIds.add(specialTerriroryAirportIdFromTEDS);
    Test.setMock(HttpCalloutMock.class, new APIMMock());

    // When
    Test.startTest();
    AirportService.newInstance().fetchAirportsByReference(airportIds, true);
    Test.stopTest();

    // Then
    Airport__c airportFromDB = AirportsSelector.newInstance()
      .selectByTEDSId(new Set<String>{ specialTerriroryAirportIdFromTEDS })[0];

    System.assertEquals(
      'Roland Garros Airport',
      airportFromDB.Name,
      'Special territory airport should exist and have the right name.'
    );
  }
}