sas-core/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <description>Information about an airport fetched from TEDS. Contains info about the name and location.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the airport is located in.</description>
    <inlineHelpText>The city the airport is located in.</inlineHelpText>
    <label>City</label>
    <length>58</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of the country the airport is located in.</description>
    <inlineHelpText>The country code of the country the airport is located in.</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The country the airport is located in.</description>
    <inlineHelpText>The country the airport is located in.</inlineHelpText>
    <label>Country Name</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Is_In_European_Union__c.field-meta.xml
<CustomField>
    <fullName>Is_In_European_Union__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean which asserts whether the airport is within the territory of a country which is part of the european union.</description>
    <inlineHelpText>A boolean which asserts whether the airport is within the territory of a country which is part of the european union.</inlineHelpText>
    <label>Is In European Union</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>The latitude of the airport.</description>
    <inlineHelpText>The latitude of the airport.</inlineHelpText>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>The longitude of the airport.</description>
    <inlineHelpText>The longitude of the airport.</inlineHelpText>
    <label>Longitude</label>
    <precision>14</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Airport__c/fields/TEDS_Identifier__c.field-meta.xml
<CustomField>
    <fullName>TEDS_Identifier__c</fullName>
    <description>The IATA Airport identifier.</description>
    <externalId>true</externalId>
    <inlineHelpText>The IATA Airport identifier.</inlineHelpText>
    <label>TEDS_Identifier</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/Airports.cls
public without sharing class Airports extends fflib_SObjectDomain {
  public Airports(List<SObject> records) {
    super(records);
    Configuration.disableTriggerCRUDSecurity();
    this.instanceRecords = (List<Airport__c>) Records;
  }

  public List<Airport__c> instanceRecords;

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new Airports(records);
    }
  }

  public static Airports newInstance(List<Airport__c> sObjectList) {
    return (Airports) SAS_Service_Application.Domain.newInstance(sObjectList);
  }

  /**
   * Parses airport data in TEDSAirport format into Airport__c objects and prepares them for DB insertion.
   *
   * @param airportData List of TEDSAirport objects containing Airports to create.
   * @param shouldUpsertToDB Boolean which asserts whether the records should be upserted or not
   *
   * @return The list of created Airport__c objects.
   */
  public static Airports createFromTEDSData(
    List<TEDSAirport> airportData,
    Boolean shouldUpsertToDB
  ) {
    Map<String, Airport__c> airportsProcessed = new Map<String, Airport__c>();

    for (TEDSAirport airport : airportData) {
      String airportId = airport.id.trim().toUpperCase();

      // TODO: Examine if we can manually set the id some way (Id = airportId)
      if (!airportsProcessed.containsKey(airportId)) {
        Airport__c newairport = new Airport__c(
          Name = airport.name,
          City__c = airport.city,
          Country_Code__c = airport.country.code,
          Country_Name__c = airport.country.name,
          Latitude__c = Decimal.valueOf(airport.coordinates.latitude)
            .setScale(12),
          Longitude__c = Decimal.valueOf(airport.coordinates.longitude)
            .setScale(12),
          Is_In_European_Union__c = CountryUtils.isInEU(airport.country.code),
          TEDS_Identifier__c = airportId
        );

        airportsProcessed.put(airportId, newairport);
      }
    }

    Airports newAirports = Airports.newInstance(airportsProcessed.values());
    List<String> TEDSIds = new List<String>(airportsProcessed.keySet());

    if (shouldUpsertToDB) {
      newAirports.upsertToDB();
    }

    return newAirports;
  }

  public Airports upsertToDB() {
    try {
      upsert instanceRecords TEDS_Identifier__c;
    } catch (DMLException e) {
      if (e.getDmlType(0) == StatusCode.DUPLICATE_VALUE) {
        upsert instanceRecords TEDS_Identifier__c;
      }
    }

    return this;
  }

  public class AirportException extends Exception {
  }
}