sas-core/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Individual passenger in a booking.

Related to accounts through EB number if one is included in a booking.</description>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Passenger__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this passenger in this booking. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this passenger in this booking. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>Individual segment, corresponding to a single flight, within a booking.</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</description>
    <inlineHelpText>A constant identifier to identify this segment in this booking. Smaller number also means this segment is earlier within the trip. Unique within the booking.</inlineHelpText>
    <label>Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Segment_Event__c/Segment_Event__c.object-meta.xml
<CustomObject>
    <description>Updates to a specific segment</description>
    <label>Segment Event</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Segment Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Segment_Event__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Segment Events</relationshipLabel>
    <relationshipName>Segment_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/domain/bookings/SegmentEvents.cls
public without sharing class SegmentEvents extends ApplicationDomain {
  public SegmentEvents(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<Segment_Event__c>) Records;
  }

  public List<Segment_Event__c> instanceRecords;
  //public Map<String, List<Segment_Event__c>> segmentIdToEvents = new Map<String, List<Segment_Event__c>>();
  public Map<String, Map<String, List<Segment_Event__c>>> segmentIdToEventsPerPassenger = new Map<String, Map<String, List<Segment_Event__c>>>();

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new SegmentEvents(records);
    }
  }

  public static SegmentEvents newInstance(List<Segment_Event__c> sObjectList) {
    return (SegmentEvents) SAS_Service_Application.Domain.newInstance(
      sObjectList
    );
  }

  /**
   * Creates lookup relationships for all Segment Events per passenger
   * @param segments List of all segments in the booking
   * @param passengersInBooking List of all passengers in the booking
   */
  public SegmentEvents addSegmentReferences(
    List<Segment__c> segments,
    List<Passenger__c> passengersInBooking
  ) {
    for (Passenger__c passenger : passengersInBooking) {
      for (Segment__c segment : segments) {
        List<Segment_Event__c> segmentEvents = segmentIdToEventsPerPassenger.get(
            passenger.Identifier__c
          )
          ?.get(segment.Name);
        if (segmentEvents != null) {
          for (Segment_Event__c segmentEvent : segmentEvents) {
            if (segment.Identifier__c.contains(passenger.Identifier__c)) {
              segmentEvent.Segment__c = segment.Id;
            }
          }
        }
      }
    }
    return this;
  }
}