sas-core/main/default/objects/Travel_Pass_Product__c/Travel_Pass_Product__c.object-meta.xml
<CustomObject>
    <label>Travel Pass Product</label>
    <nameField>
        <label>Travel Pass Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Pass Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account whose product this is.</description>
    <inlineHelpText>The account whose product this is.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Travel Pass Products</relationshipLabel>
    <relationshipName>Travel_Pass_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <label>Category Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAYF</fullName>
            </value>
            <value>
                <fullName>CLIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Category_Name__c</fullName>
    <label>Category Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Punches</fullName>
            </value>
            <value>
                <fullName>Pay-As-You-Fly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/External_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Name__c</fullName>
    <label>External Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Type_Code__c</fullName>
    <label>Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TMP</fullName>
            </value>
            <value>
                <fullName>TPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Travel Pass Corporate</fullName>
            </value>
            <value>
                <fullName>Travel Pass Multiple Punch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/services/TravelPassService.cls
public without sharing class TravelPassService {
  static TravelPassProductsSelector travelPassProducts = (TravelPassProductsSelector) SAS_Service_Application.Selector.newInstance(
    Travel_Pass_Product__c.SObjectType
  );

  /**
   * Fetches travel pass account information from C-Shark, creates travel pass products
   * and associates them with the corresponding account in SF.
   */
  @future(callout=true)
  public static void fetchTravelPassAccount(
    String tpAccountNumber,
    Id accountId
  ) {
    TPAccount tpAccount = CSharkIntegrationService.getTPAccount(
      tpAccountNumber
    );

    if (
      tpAccount == null ||
      tpAccount.products == null ||
      tpAccount.products.size() == 0
    ) {
      return;
    }

    List<Travel_Pass_Product__c> oldProductsToDelete = travelPassProducts.selectByAccountId(
      new Set<Id>{ accountId }
    );
    List<Travel_Pass_Product__c> productsToInsert = new List<Travel_Pass_Product__c>();

    // Get existing products and remove them.

    for (TPAccount.Product product : tpAccount.products) {
      productsToInsert.add(
        new Travel_Pass_Product__c(
          Account__c = accountId,
          Category_Code__c = product.categoryCode,
          Category_Name__c = product.categoryName,
          External_Name__c = product.externalName,
          Internal_Name__c = product.internalName,
          Name = product.externalName,
          Type_Code__c = product.typeCode,
          Type_Name__c = product.typeName
        )
      );
    }

    if (oldProductsToDelete != null && oldProductsToDelete.size() > 0) {
      delete oldProductsToDelete;
    }

    insert productsToInsert;
  }
}