sas-core/main/default/objects/Travel_Pass_Product__c/Travel_Pass_Product__c.object-meta.xml
<CustomObject>
    <label>Travel Pass Product</label>
    <nameField>
        <label>Travel Pass Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Pass Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account whose product this is.</description>
    <inlineHelpText>The account whose product this is.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Travel Pass Products</relationshipLabel>
    <relationshipName>Travel_Pass_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <label>Category Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAYF</fullName>
            </value>
            <value>
                <fullName>CLIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Category_Name__c</fullName>
    <label>Category Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Punches</fullName>
            </value>
            <value>
                <fullName>Pay-As-You-Fly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/External_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Name__c</fullName>
    <label>External Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Type_Code__c</fullName>
    <label>Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TMP</fullName>
            </value>
            <value>
                <fullName>TPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Travel_Pass_Product__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Travel Pass Corporate</fullName>
            </value>
            <value>
                <fullName>Travel Pass Multiple Punch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/selectors/TravelPassProductsSelector.cls
public inherited sharing class TravelPassProductsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Travel_Pass_Product__c.Id,
      Travel_Pass_Product__c.Account__c,
      Travel_Pass_Product__c.Category_Code__c,
      Travel_Pass_Product__c.Category_Name__c,
      Travel_Pass_Product__c.External_Name__c,
      Travel_Pass_Product__c.Internal_Name__c,
      Travel_Pass_Product__c.LastModifiedDate,
      Travel_Pass_Product__c.Type_Code__c,
      Travel_Pass_Product__c.Type_Name__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Travel_Pass_Product__c.SObjectType;
  }

  public static TravelPassProductsSelector newInstance() {
    return (TravelPassProductsSelector) SAS_Service_Application.Selector.newInstance(
      Travel_Pass_Product__c.SObjectType
    );
  }

  public List<Travel_Pass_Product__c> selectById(Set<Id> ids) {
    return (List<Travel_Pass_Product__c>) selectSObjectsById(ids);
  }

  public List<Travel_Pass_Product__c> selectByAccountId(Set<Id> accountIds) {
    return (List<Travel_Pass_Product__c>) Database.query(
      newQueryFactory().setCondition('Account__c in :accountIds').toSOQL()
    );
  }
}