sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/SBS_ScheduledBatchComponent__mdt.object-meta.xml
<CustomObject>
    <description>Contains the classes which are included in the scheduled batch runs. The components can be filtered to only be included in certain batch runs and have a priority in order to enforce an order of the batches.</description>
    <label>Scheduled Batch Component</label>
    <pluralLabel>Scheduled Batch Components</pluralLabel>
</CustomObject>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The class name of the batch class</description>
    <label>Class</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/DayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>DayOfMonth__c</fullName>
    <description>The batch will run during the supplied day of the month.</description>
    <inlineHelpText>Only applicable for schedule: Day Of Month</inlineHelpText>
    <label>Day Of Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/DayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>DayOfWeek__c</fullName>
    <description>The batch will only run during the specified day of the week.</description>
    <inlineHelpText>Only applicable for schedule: Day Of Week</inlineHelpText>
    <label>Day Of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monday</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Tuesday</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Wednesday</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Thursday</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Friday</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Saturday</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Sunday</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>The group which the component belongs to. A component in a given group will only run if all other previously run components in the group ran successfully.</description>
    <inlineHelpText>The group which the component belongs to. A component in a given group will only run if all other previously run components in the group ran successfully.</inlineHelpText>
    <label>Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>The priority of the batch. Batches with lower priority will run before batches with a higher priority value.</description>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>The schedule for which days should include the given batch in the batch run.</description>
    <label>Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Day Of Week</fullName>
            </value>
            <value>
                <fullName>Day Of Month</fullName>
            </value>
            <value>
                <fullName>Last Day Of Month</fullName>
            </value>
            <value>
                <fullName>Day Of Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/ScopeSize__c.field-meta.xml
<CustomField>
    <fullName>ScopeSize__c</fullName>
    <defaultValue>200</defaultValue>
    <description>The size of the execution scope for each batch.</description>
    <label>Scope Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/TimeSegment__c.field-meta.xml
<CustomField>
    <fullName>TimeSegment__c</fullName>
    <description>The name of the time segment of the scheduled batch run which this batch should run within.</description>
    <label>Time Segment</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchComponent__mdt/fields/WorkingDayOffset__c.field-meta.xml
<CustomField>
    <fullName>WorkingDayOffset__c</fullName>
    <description>The number of working days which monthly or weekly daily should be offset by in relation to working day. A weekly batch which executes the first working day on mondays will execute on wednesday if both monday and tuesday were holidays wereas the second working day would have executes on thursdays. Working days does not include registered holidays as well as saturdays and sundays.</description>
    <label>Working Day Offset</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>First Working Day</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Second Working Day</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRun__c/SBS_ScheduledBatchRun__c.object-meta.xml
<CustomObject>
    <description>Object which stores information about scheduled batch runs. Scheduled batch runs are scheduled jobs with batches defined in schedule batch component custom metadata.</description>
    <label>Scheduled Batch Run</label>
    <nameField>
        <displayFormat>SBR-{000000}</displayFormat>
        <label>Schedule Batch Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Batch Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/SBS_ScheduledBatchRun__c/fields/FinishTime__c.field-meta.xml
<CustomField>
    <fullName>FinishTime__c</fullName>
    <description>The date and time when the batch run was finished.</description>
    <label>Finish Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRun__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>The date and time when the batch run was started.</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRun__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the batch run. The status is set to started when the batch run starts and success/fail when the batch ruin has completed. The batch run will only be in status success if none of its components failed.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRun__c/fields/TimeSegment__c.field-meta.xml
<CustomField>
    <fullName>TimeSegment__c</fullName>
    <description>The time segment of the batches included in this batch run. Time segments are used to run batches in groups at different points in time.</description>
    <label>Time Segment</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/SBS_ScheduledBatchRunComponent__c.object-meta.xml
<CustomObject>
    <description>Represents a batch process within a scheduled batch run.</description>
    <label>Scheduled Batch Run Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Batch Run Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/ApexJobId__c.field-meta.xml
<CustomField>
    <fullName>ApexJobId__c</fullName>
    <description>The id of the apex batch job.</description>
    <label>Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Error message, in case it can be established.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/FinishTime__c.field-meta.xml
<CustomField>
    <fullName>FinishTime__c</fullName>
    <description>The date and time when this batch process was finished.</description>
    <label>Finish Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/RunOrder__c.field-meta.xml
<CustomField>
    <fullName>RunOrder__c</fullName>
    <description>The order of this batch process within the scheduled batch run.</description>
    <label>Run Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/ScheduledBatchRun__c.field-meta.xml
<CustomField>
    <fullName>ScheduledBatchRun__c</fullName>
    <description>The scheduled batch run under which this batch process run.</description>
    <label>Scheduled Batch Run</label>
    <referenceTo>SBS_ScheduledBatchRun__c</referenceTo>
    <relationshipLabel>Scheduled Batch Run Components</relationshipLabel>
    <relationshipName>ScheduledBatchRunComponents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>The date and time when this batch process was started.</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this batch process within the scheduled batch run. Batches starts as scheduled and should move from started to success. In cases where failure occurs when initializing the batch the batches receive the init error status and in the case where one or several of its batches fails the status is set to fail.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Init Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/TotalBatches__c.field-meta.xml
<CustomField>
    <fullName>TotalBatches__c</fullName>
    <description>The total number of batches within this batch process.</description>
    <label>Total Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunComponent__c/fields/TotalErrors__c.field-meta.xml
<CustomField>
    <fullName>TotalErrors__c</fullName>
    <description>The total number of batches within this batch process which resulted in an error.</description>
    <label>Total Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunTxnError__c/SBS_ScheduledBatchRunTxnError__c.object-meta.xml
<CustomObject>
    <description>Represents a caught error for a scheduled batch component.</description>
    <label>Scheduled Batch Run Txn Error</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Batch Run Txn Errors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/SBS_ScheduledBatchRunTxnError__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>The error message explaining the error.</description>
    <label>Error Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunTxnError__c/fields/ScheduledBatchRunComponent__c.field-meta.xml
<CustomField>
    <fullName>ScheduledBatchRunComponent__c</fullName>
    <description>The scheduled batch run component under which this error occurred.</description>
    <label>Scheduled Batch Run Component</label>
    <referenceTo>SBS_ScheduledBatchRunComponent__c</referenceTo>
    <relationshipLabel>Errors</relationshipLabel>
    <relationshipName>ScheduledBatchRunTxnErrors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunTxnError__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>The scope of records which generated the error.</description>
    <label>Scope</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/SBS_ScheduledBatchRunTxnError__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>The stack trace of the exception generating the error.</description>
    <label>Stack Trace</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/classes/SBS_ScheduledBatchService_Test.cls
/** 
    Test class testing daily batch service from scheduling 
    to running the batches.
*/
@isTest
global class SBS_ScheduledBatchService_Test {

    /**
        Tests running a successful batch
    */
    @isTest static void testSuccessfulBatch(){
        String timeSegment = 'testSuccessfulBatch';
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_SUCCESS,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_SUCCESS,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(0,errList.size());
    }

    /**
        Tests running a successful batch using a batch without a finish method
    */
    @isTest static void testSuccessfulBatchVariant(){
        String timeSegment = 'testSuccessfulBatch';
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch2_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_SUCCESS,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_SUCCESS,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(0,errList.size());
    }

    /**
        Tests running a batch which generates an exception
    */
    @isTest static void testExceptionBatch(){
        String timeSegment = 'testExceptionBatch';
        SBS_ScheduledBatch_Test.THROW_EXCEPTION = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(1,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(1,errList.size());
        SBS_ScheduledBatchRunTxnError__c err = errList[0];
        System.assertEquals('TEST EXCEPTION',err.ErrorMessage__c);
        System.assertNotEquals(null,err.Scope__c);
        System.assertNotEquals(null,err.StackTrace__c);
    }

    /**
        Tests running a batch which generates a custom error
    */
    @isTest static void testCustomErrorBatch(){
        String timeSegment = 'testCustomErrorBatch';
        SBS_ScheduledBatch_Test.CUSTOM_ERROR = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(1,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(1,errList.size());
        SBS_ScheduledBatchRunTxnError__c err = errList[0];
        System.assertEquals('ERROR MESSAGE',err.ErrorMessage__c);
        System.assertNotEquals(null,err.Scope__c);
        System.assertEquals(null,err.StackTrace__c);
    }


    /**
        Tests running a batch which generates an exception on init
    */
    @isTest static void testInitExceptionBatch(){
        String timeSegment = 'testInitExceptionBatch';
        SBS_ScheduledBatch_Test.THROW_INIT_EXCEPTION = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_INIT_ERROR,sbrc.Status__c);
        System.assertEquals(null,sbrc.TotalBatches__c);
        System.assertEquals(null,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(0,errList.size());
    }

    /**
        Tests running a batch which generates an exception on finish
    */
    @isTest static void testFinishExceptionBatch(){
        String timeSegment = 'testFinishExceptionBatch';
        SBS_ScheduledBatch_Test.THROW_FINISH_EXCEPTION = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(0,errList.size());
    }


    /**
        Tests running a successful batch for a batch part of a group
    */
    @isTest static void testSuccessfulGroupBatch(){
        String timeSegment = 'testSuccessfulGroupBatch';
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G1'),
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH2',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G1')
        };
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList) ORDER BY RunOrder__c];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_SUCCESS,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(2,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_SUCCESS,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);
        sbrc = sbrcList[1];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(2,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_SUCCESS,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);


        System.assertEquals(0,errList.size());
    }

    /**
        Tests running a batch which generates an exception for a batch part of a group
    */
    @isTest static void testExceptionGroupBatch(){
        String timeSegment = 'testExceptionGroupBatch';
        SBS_ScheduledBatch_Test.THROW_EXCEPTION = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G1'),
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH2',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G1')
        };
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList) ORDER BY RunOrder__c];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(2,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(1,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);
        sbrc = sbrcList[1];
        System.assertEquals(null,sbrc.ApexJobId__c);
        System.assertEquals(null,sbrc.StartTime__c);
        System.assertEquals(null,sbrc.FinishTime__c);
        System.assertEquals(2,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_INIT_ERROR,sbrc.Status__c);
        System.assertEquals(null,sbrc.TotalBatches__c);
        System.assertEquals(null,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);


        System.assertEquals(1,errList.size());
    }

    /**
        Tests running a batch which generates an exception for a batch but is not part of the same group as the next batch
    */
    @isTest static void testExceptionNonGroupBatch(){
        String timeSegment = 'testExceptionNonGroupBatch';
        SBS_ScheduledBatch_Test.THROW_EXCEPTION = true;
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G1'),
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH2',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G2')
        };
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList) ORDER BY RunOrder__c];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(2,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(1,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);
        sbrc = sbrcList[1];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(2,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_FAIL,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(1,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);


        System.assertEquals(2,errList.size());
    }


    /**
        Tests that the batch is included with day of week schedule
    */
    @isTest static void testDayOfWeekInclude(){
        String timeSegment = 'testDayOfWeekInclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Week',DayOfWeek__c='5',WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,16);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(1,sbrcList.size());
    }

    /**
        Tests that the batch is excluded with day of week schedule
    */
    @isTest static void testDayOfWeekExclude(){
        String timeSegment = 'testDayOfWeekExclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Week',DayOfWeek__c='5',WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,13);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(0,sbrcList.size());
    }


    /**
        Tests that the batch is included with day of month schedule
    */
    @isTest static void testDayOfMonthInclude(){
        String timeSegment = 'testDayOfMonthInclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Month',DayOfWeek__c=null,DayOfMonth__c=13,WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,16);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(1,sbrcList.size());
    }

    /**
        Tests that the batch is excluded with day of month schedule
    */
    @isTest static void testDayOfMonthExclude(){
        String timeSegment = 'testDayOfMonthExclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Month',DayOfWeek__c=null,DayOfMonth__c=13,WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,13);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(0,sbrcList.size());
    }

    /**
        Tests that the batch is included with day of year schedule
    */
    @isTest static void testDayOfYearInclude(){
        String timeSegment = 'testDayOfYearInclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Year',DayOfWeek__c=null,DayOfMonth__c=13,MonthOfYear__c='12',WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,16);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(1,sbrcList.size());
    }

    /**
        Tests that the batch is excluded with day of year schedule
    */
    @isTest static void testDayOfYearExclude(){
        String timeSegment = 'testDayOfYearExclude';
        Test.startTest();
        //Batch scheduled for first working day starting with a friday (which is marked as a holiday)
        C_CalendarUtil.holidayList = new Holiday[]{new Holiday(Name='T_Date1',ActivityDate=Date.newInstance(2019,12,13),IsAllDay=true,IsRecurrence=false,RecurrenceDayOfMonth=null,RecurrenceDayOfWeekMask=null,RecurrenceStartDate=null,RecurrenceEndDateOnly=null,RecurrenceInstance=null,RecurrenceInterval=null,RecurrenceMonthOfYear=null,RecurrenceType=null)};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Year',DayOfWeek__c=null,DayOfMonth__c=13,MonthOfYear__c='12',WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,13);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(0,sbrcList.size());
    }


    /**
        Tests that the batch is included with last day of month schedule
    */
    @isTest static void testLastDayOfMonthInclude(){
        String timeSegment = 'testLastDayOfMonthInclude';
        Test.startTest();
        //Batch scheduled for last day of month in november which is a saturday
        C_CalendarUtil.holidayList = new Holiday[]{};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Last Day Of Month',DayOfWeek__c=null,DayOfMonth__c=null,MonthOfYear__c=null,WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,2);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(1,sbrcList.size());
    }

    /**
        Tests that the batch is excluded with last day of month schedule
    */
    @isTest static void testLastDayOfMonthExclude(){
        String timeSegment = 'testLastDayOfMonthExclude';
        Test.startTest();
        //Batch scheduled for last day of month in november which is a saturday
        C_CalendarUtil.holidayList = new Holiday[]{};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Last Day Of Month',DayOfWeek__c=null,DayOfMonth__c=null,MonthOfYear__c=null,WorkingDayOffset__c='1',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,11,30);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(0,sbrcList.size());
    }

    /**
        Tests that the batch is should only run during working days is included
    */
    @isTest static void testOnlyWorkingDaysInclude(){
        String timeSegment = 'testOnlyWorkingDaysInclude';
        Test.startTest();
        C_CalendarUtil.holidayList = new Holiday[]{};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',DayOfWeek__c=null,DayOfMonth__c=null,MonthOfYear__c=null,OnlyExecuteOnWorkingDays__c=true,ScopeSize__c=200,Priority__c=1)};
        //A monday
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,16);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(1,sbrcList.size());
    }

    /**
        Tests that the batch is should only run during working days is excluded
    */
    @isTest static void testOnlyWorkingDaysExclude(){
        String timeSegment = 'testOnlyWorkingDaysExclude';
        Test.startTest();
        C_CalendarUtil.holidayList = new Holiday[]{};
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',DayOfWeek__c=null,DayOfMonth__c=null,MonthOfYear__c=null,OnlyExecuteOnWorkingDays__c=true,ScopeSize__c=200,Priority__c=1)};
        //A sunday
        SBS_ScheduledBatchService.CURRENT_DATE_OVERRIDE = Date.newInstance(2019,12,15);
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        System.assertEquals(0,sbrcList.size());
    }

    /**
        Tests that having a batch with bad configuration causes only the poorly configured batch to fail
    */
    @isTest static void testBadConfiguration(){
        String timeSegment = 'testBadConfiguration';
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Day Of Week',DayOfWeek__c='BAD VALUE',ScopeSize__c=200,Priority__c=1,Group__c='G1'),
            new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH2',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1,Group__c='G2')
        };
        SBS_ScheduledBatchService.run(timeSegment);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList) ORDER BY RunOrder__c];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_STATUS_FAIL,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertNotEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(2,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertEquals(null,sbrc.ApexJobId__c);
        System.assertEquals(null,sbrc.StartTime__c);
        System.assertEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_INIT_ERROR,sbrc.Status__c);
        System.assertEquals(null,sbrc.TotalBatches__c);
        System.assertEquals(null,sbrc.TotalErrors__c);
        System.assertNotEquals(null,sbrc.ErrorMessage__c);
        sbrc = sbrcList[1];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertNotEquals(null,sbrc.FinishTime__c);
        System.assertEquals(2,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_SUCCESS,sbrc.Status__c);
        System.assertEquals(1,sbrc.TotalBatches__c);
        System.assertEquals(0,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);


        System.assertEquals(0,errList.size());
    }

    /**
        Tests creating a successful batch run defined using code
    */
    @isTest static void testDynamicBatchSuccess(){
        Test.startTest();
        List<SBS_ScheduledBatchService.BatchExecution> batches = new List<SBS_ScheduledBatchService.BatchExecution>();
		batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
		batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
		SBS_ScheduledBatchService.ScheduledBatchRun sbr = new SBS_ScheduledBatchService.ScheduledBatchRun(batches);
		SBS_ScheduledBatchService.run(sbr);
        Test.stopTest();
        System.assertEquals(2,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(2,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(2,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests batch run defined using code with an exception
    */
    @isTest static void testDynamicBatchException(){
        SBS_ScheduledBatch_Test.THROW_EXCEPTION = true;
        Boolean error = false;
        try{
            Test.startTest();
            List<SBS_ScheduledBatchService.BatchExecution> batches = new List<SBS_ScheduledBatchService.BatchExecution>();
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            SBS_ScheduledBatchService.ScheduledBatchRun sbr = new SBS_ScheduledBatchService.ScheduledBatchRun(batches);
            SBS_ScheduledBatchService.run(sbr);
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        //Real error will run all batches but test logic causes the exception to stop the processing
        System.assertEquals(true,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(0,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests batch run defined using code with a custom error
    */
    @isTest static void testDynamicBatchCustomError(){
        SBS_ScheduledBatch_Test.CUSTOM_ERROR = true;
        Boolean error = false;
        try{
            Test.startTest();
            List<SBS_ScheduledBatchService.BatchExecution> batches = new List<SBS_ScheduledBatchService.BatchExecution>();
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            SBS_ScheduledBatchService.ScheduledBatchRun sbr = new SBS_ScheduledBatchService.ScheduledBatchRun(batches);
            SBS_ScheduledBatchService.run(sbr);
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        //Real error will run all batches but test logic causes the exception to stop the processing
        System.assertEquals(true,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(0,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests batch run defined using code with an exception in the finish method
    */
    @isTest static void testDynamicBatchFinishException(){
        SBS_ScheduledBatch_Test.THROW_FINISH_EXCEPTION = true;
        Boolean error = false;
        try{
            Test.startTest();
            List<SBS_ScheduledBatchService.BatchExecution> batches = new List<SBS_ScheduledBatchService.BatchExecution>();
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            batches.add(new SBS_ScheduledBatchService.BatchExecution(SBS_ScheduledBatch_Test.class,200,null));
            SBS_ScheduledBatchService.ScheduledBatchRun sbr = new SBS_ScheduledBatchService.ScheduledBatchRun(batches);
            SBS_ScheduledBatchService.run(sbr);
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        System.assertEquals(false,error);
        System.assertEquals(2,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(2,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(2,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests running a batch outside of scheduled batch service
    */
    @isTest static void testExternalBatchRunSuccess(){
        Boolean error = false;
        try{
            Test.startTest();
            SBS_ScheduledBatch_Test.DISABLE_TRANSACTION_CONTROL = true;
            Database.executeBatch(new SBS_ScheduledBatch_Test());
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        System.assertEquals(false,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }


    /**
        Tests running a batch outside of scheduled batch service with an execute exception
    */
    @isTest static void testExternalBatchRunException(){
        Boolean error = false;
        try{
            Test.startTest();
            SBS_ScheduledBatch_Test.DISABLE_TRANSACTION_CONTROL = true;
            SBS_ScheduledBatch_Test.THROW_EXCEPTION = true;
            Database.executeBatch(new SBS_ScheduledBatch_Test());
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        System.assertEquals(true,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(0,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests running a batch outside of scheduled batch service with a custom error
    */
    @isTest static void testExternalBatchRunCustomError(){
        Boolean error = false;
        try{
            Test.startTest();
            SBS_ScheduledBatch_Test.DISABLE_TRANSACTION_CONTROL = true;
            SBS_ScheduledBatch_Test.CUSTOM_ERROR = true;
            Database.executeBatch(new SBS_ScheduledBatch_Test());
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        System.assertEquals(true,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(0,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests running a batch outside of scheduled batch service with an finish exception
    */
    @isTest static void testExternalBatchRunFinishException(){
        Boolean error = false;
        try{
            Test.startTest();
            SBS_ScheduledBatch_Test.DISABLE_TRANSACTION_CONTROL = true;
            SBS_ScheduledBatch_Test.THROW_FINISH_EXCEPTION = true;
            Database.executeBatch(new SBS_ScheduledBatch_Test());
            Test.stopTest();
        }
        catch(Exception e){
            error = true;
        }
        System.assertEquals(true,error);
        System.assertEquals(1,SBS_ScheduledBatch_Test.START_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.EXECUTE_COUNT);
        System.assertEquals(1,SBS_ScheduledBatch_Test.FINISH_COUNT);
    }

    /**
        Tests that the batch can be correctly initated using the scheduleable job
        Note: Testing a scheduleable job which schedules a batch does not execute a batch
        This is in contrast to batch chaining in tests which execute the cahined batch as well
    */
    @isTest static void testSchedulableJob(){
        String timeSegment = 'testSchedulableJob';
        Test.startTest();
        SBS_ScheduledBatchService.BATCH_CMP_LIST_OVERRIDE = new SBS_ScheduledBatchComponent__mdt[]{new SBS_ScheduledBatchComponent__mdt(DeveloperName='TEST_BATCH',Class__c='SBS_ScheduledBatch_Test',Schedule__c='Daily',ScopeSize__c=200,Priority__c=1)};
        SBS_ScheduledBatchService_Schedulable s = new SBS_ScheduledBatchService_Schedulable(timeSegment);
        System.schedule('TEST SCHEDULED BATCH SERVICE', '0 0 0 * * ?', s);
        Test.stopTest();

        SBS_ScheduledBatchRun__c[] sbrList = [SELECT Id,Status__c,StartTime__c,FinishTime__c,TimeSegment__c FROM SBS_ScheduledBatchRun__c];
        SBS_ScheduledBatchRunComponent__c[] sbrcList = [SELECT Id,ApexJobId__c,RunOrder__c,StartTime__c,FinishTime__c,Status__c,TotalBatches__c,TotalErrors__c,ErrorMessage__c FROM SBS_ScheduledBatchRunComponent__c WHERE ScheduledBatchRun__c IN :getIds(sbrList)];
        SBS_ScheduledBatchRunTxnError__c[] errList = [SELECT Id,ErrorMessage__c,Scope__c,StackTrace__c FROM SBS_ScheduledBatchRunTxnError__c WHERE ScheduledBatchRunComponent__c IN :getIds(sbrcList)];

        System.assertEquals(1,sbrList.size());
        SBS_ScheduledBatchRun__c sbr = sbrList[0];
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_STARTED,sbr.Status__c);
        System.assertNotEquals(null,sbr.StartTime__c);
        System.assertEquals(null,sbr.FinishTime__c);
        System.assertEquals(timeSegment,sbr.TimeSegment__c);

        System.assertEquals(1,sbrcList.size());
        SBS_ScheduledBatchRunComponent__c sbrc = sbrcList[0];
        System.assertNotEquals(null,sbrc.ApexJobId__c);
        System.assertNotEquals(null,sbrc.StartTime__c);
        System.assertEquals(null,sbrc.FinishTime__c);
        System.assertEquals(1,sbrc.RunOrder__c);
        System.assertEquals(SBS_ScheduledBatchService.BATCH_RUN_CMP_STATUS_STARTED,sbrc.Status__c);
        System.assertEquals(null,sbrc.TotalBatches__c);
        System.assertEquals(null,sbrc.TotalErrors__c);
        System.assertEquals(null,sbrc.ErrorMessage__c);

        System.assertEquals(0,errList.size());
    }

    /**
        Retrieves the set of ids for the provided list of sobjects
        @param sObjList The list of SObjects from which to extract the ids
        @return The set of ids
    */
    private static Set<Id> getIds(SObject[] sObjList){
        Set<Id> idSet = new Set<Id>();
        for(SObject so : sObjList)idSet.add(so.Id);
        return idSet;
    }
}