sas-core/main/default/objects/Fetch_Flight__e/Fetch_Flight__e.object-meta.xml
<CustomObject>
    <description>Event for fetching flights from TEDS.</description>
    <label>Fetch Flight</label>
    <pluralLabel>Fetch Flights</pluralLabel>
</CustomObject>

sas-core/main/default/objects/Fetch_Flight__e/fields/Flight_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Flight_Identifiers__c</fullName>
    <description>Comma separated list of TEDS flight identifiers to fetch. E.g. &quot;SK2569-20210410-ARN-CPH,SK0402-20210420-CPH-ARN&quot;. Maximum of 10 entries.</description>
    <label>Flight Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>An individual real world flight. E.g. flight record SK712-20201222-ARN-HEL is the flight which departed 14:05 from Stockholm Arlanda to Helsinki-Vantaa on 22.12.2020.</description>
    <label>Flight</label>
    <nameField>
        <label>Flight ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Flight__c/fields/Departure_Gate__c.field-meta.xml
<CustomField>
    <fullName>Departure_Gate__c</fullName>
    <label>Departure Gate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/tests/integration/FlightEvents_IntegrationTest.cls
@IsTest
public with sharing class FlightEvents_IntegrationTest {
  public static String flightIdFromTEDS = 'SK2569-20210410-ARN-CPH';
  public static String gateInDetailedFlightInfo = 'E135';

  public static FlightsSelector flights = (FlightsSelector) SAS_Service_Application.Selector.newInstance(
    Flight__c.SObjectType
  );

  @IsTest
  public static void publishingAFlightEventShouldFetchDataFromTEDS() {
    // Given
    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new TEDSBookingSingleAndFlightSuccessMock()
    );

    List<String> flightIds = new List<String>();
    flightIds.add(flightIdFromTEDS);

    List<Fetch_Flight__e> flightEvents = new List<Fetch_Flight__e>();
    flightEvents.add(
      new Fetch_Flight__e(Flight_Identifiers__c = String.join(flightIds, ','))
    );

    // When
    EventBus.publish(flightEvents);
    Test.getEventBus().deliver();
    Test.stopTest();

    // Then
    Flight__c flightFromDB = flights.selectByTEDSId(
      new Set<String>{ flightIdFromTEDS }
    )[0];

    System.assertEquals(
      gateInDetailedFlightInfo,
      flightFromDB.Departure_Gate__c,
      'Flight should exist and have detailed flight info.'
    );
  }
}