sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/recordTypes/Cheque.recordType-meta.xml
<RecordType>
    <fullName>Cheque</fullName>
    <active>true</active>
    <description>Record type for cheque settlements in US</description>
    <label>Cheque</label>
</RecordType>

sas-core/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sas-core/main/default/classes/services/integration/racer/PaymentEntry_Test.cls
@IsTest
public with sharing class PaymentEntry_Test {
  @IsTest
  public static void genericPaymentMethodsShouldBeSetCorrectly() {
    Settlement__c s1 = new Settlement__c(
      Currency__c = 'USD',
      Bank_Country__c = 'United States'
    );

    PaymentEntry p1 = new PaymentEntry(s1);

    System.assertEquals(
      'NORDEA US DOM EDI',
      p1.data.get('accountData').get('EDIPaymentMethod'),
      'USD payments to US should have NORDEA US DOM EDI as payment method.'
    );

    Settlement__c s2 = new Settlement__c(
      Currency__c = 'USD',
      Bank_Country__c = 'Sweden'
    );

    PaymentEntry p2 = new PaymentEntry(s2);

    System.assertEquals(
      'NORDEA CROSS BORDER EDI',
      p2.data.get('accountData').get('EDIPaymentMethod'),
      'USD payments to outside of US should have NORDEA CROSS BORDER EDI as payment method.'
    );

    Settlement__c s3 = new Settlement__c(
      Currency__c = 'EUR',
      Bank_Country__c = 'United States'
    );

    PaymentEntry p3 = new PaymentEntry(s3);

    System.assertEquals(
      'CROSS BORDER EDI',
      p3.data.get('accountData').get('EDIPaymentMethod'),
      'Non-USD payments to US should have CROSS BORDER EDI as payment method.'
    );

    Settlement__c s4 = new Settlement__c(
      Currency__c = 'USD',
      Bank_Country__c = 'United States',
      RecordTypeId = Settlements.getRecordTypeId(Settlements.RecordType.Cheque)
    );

    PaymentEntry p4 = new PaymentEntry(s4);

    System.assertEquals(
      'NORDEA US DOM CHEQUE',
      p4.data.get('accountData').get('EDIPaymentMethod'),
      'Check payments should have NORDEA US DOM CHEQUE as payment method.'
    );
  }

  @IsTest
  public static void countryExtensionShouldBeSetCorrectly() {
    Settlement__c s1 = new Settlement__c(
      Bank_Country__c = 'Sweden',
      Currency__c = 'SEK'
    );

    PaymentEntry p1 = new PaymentEntry(s1);

    System.assertEquals(
      'SE',
      p1.data.get('supplierSiteData').get('countryExt'),
      'Country should be set to bank country if contact country does not exist.'
    );

    Settlement__c s2 = new Settlement__c(
      Bank_Country__c = 'Sweden',
      Country__c = 'Finland',
      Currency__c = 'SEK'
    );

    PaymentEntry p2 = new PaymentEntry(s2);

    System.assertEquals(
      'FI',
      p2.data.get('supplierSiteData').get('countryExt'),
      'Country should be set to contact country over bank country if both exist.'
    );
  }
}