sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Waiting for approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Waiting for control</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Accepted by Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Rejected by Bank</fullName>
            </value>
            <value>
                <fullName>Accepted by Bank/Done</fullName>
            </value>
            <value>
                <fullName>L2 errors by Bank</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/domain/Settlements_Test.cls
@IsTest
private class Settlements_Test {
  @IsTest
  static void itShouldNotBePossibleToUpdateFailedSettlementToDone() {
    Settlement__c s = new Settlement__c(
      Settlement_Status__c = Settlements.STATUS_FAILED
    );
    insert s;
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance(); // needs to be passed in but tests works without committing.
    Settlements.newInstance(new List<Settlement__c>{ s })
      .markAsDone('done', uow);

    System.assertEquals(
      Settlements.STATUS_FAILED,
      s.Settlement_Status__c,
      'Settlement status should not have been updated.'
    );
  }
}