sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/Settlement_Item__c.object-meta.xml
<CustomObject>
    <description>The combination of one customer and cost account. At settlement file can contain several passenger and each passenger several reasons for compensation.</description>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Settlement Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/fields/Accounting_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_File_Name__c</fullName>
    <label>Accounting File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount to pay for this settlement item</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Amount_in_SEK__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_SEK__c</fullName>
    <label>Amount in SEK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Account__c.field-meta.xml
<CustomField>
    <fullName>Cost_Account__c</fullName>
    <label>Cost Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6733</fullName>
                <label>6733 - Goodwill Compensation</label>
            </value>
            <value>
                <fullName>6741</fullName>
                <label>6741 - Liability - Baggage Damaged</label>
            </value>
            <value>
                <fullName>6742</fullName>
                <label>6742 - Liability - Baggage Delayed/missing/lost</label>
            </value>
            <value>
                <fullName>6743</fullName>
                <label>6743 - Liability - Baggage Pilfered</label>
            </value>
            <value>
                <fullName>6738</fullName>
                <label>6738 - Liability - Care (Meal, Hotel, Transportation)</label>
            </value>
            <value>
                <fullName>6721</fullName>
                <label>6721 - Liability - Denied Boarding Compensation</label>
            </value>
            <value>
                <fullName>6722</fullName>
                <label>6722 - Liability - Downgrading Compensation</label>
            </value>
            <value>
                <fullName>6727</fullName>
                <label>6727 - Liability - EU 261 Compensation</label>
            </value>
            <value>
                <fullName>6735</fullName>
                <label>6735 - Liability - Other</label>
            </value>
            <value>
                <fullName>6737</fullName>
                <label>6737 - Refund of tickets and ancillary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90801</fullName>
                <default>true</default>
                <label>90801</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Name of customer for this settlement item</description>
    <label>Customer Name</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Deductible_Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Insurance_Amount__c</fullName>
    <label>Deductible Insurance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Is_Insured__c.field-meta.xml
<CustomField>
    <fullName>Is_Insured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the settlement item covered by SAS's insurance.</description>
    <label>Is Insured</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Net_Amount_After_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_After_Deductible__c</fullName>
    <description>The amount which SAS can claim from our insurance companyin the same currency as the settlement item. Set only for claim types against which SAS is insured.</description>
    <inlineHelpText>The amount which SAS can claim from our insurance companyin the same currency as the settlement item. Set only for claim types against which SAS is insured.</inlineHelpText>
    <label>Net Amount After Deductible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <inlineHelpText>Settlement to which this settlement belongs to</inlineHelpText>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending L1 confirmation</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/recordTypes/DefaultRecordType.recordType-meta.xml
<RecordType>
    <fullName>DefaultRecordType</fullName>
    <active>true</active>
    <description>When the case Record Type is other then Emergency</description>
    <label>Default Record Type</label>
</RecordType>

sas-core/main/default/objects/Settlement_Item__c/recordTypes/Emergency.recordType-meta.xml
<RecordType>
    <fullName>Emergency</fullName>
    <active>true</active>
    <description>When the case Record Type is Emergency</description>
    <label>Emergency</label>
</RecordType>

sas-core/main/default/classes/domain/settlements/SettlementItem.cls
public without sharing class SettlementItem extends AbstractSObjectWrapper {
  public Settlement_Item__c underlyingSObject { get; private set; }
  public RecordType recordType;

  public Id parentSettlementId;
  public String accountingFileName;
  public Decimal amount;
  public Decimal amountInSEK;
  public String comments;
  public CostAccount costAccount;
  public CostCenter costCenter;
  public String itemCurrency;
  public String customerName;
  public Date dateOfExchangeCalculation;
  public Decimal deductibleInsuranceAmount;
  public String errorMessage;
  public Boolean isInsured = false;
  public Decimal netAmountAfterDeductible;
  public Status status;

  public enum CostAccount {
    CA6721,
    CA6722,
    CA6727,
    CA6730,
    CA6731,
    CA6732,
    CA6733,
    CA6734,
    CA6735,
    CA6736,
    CA6737,
    CA6738,
    CA6739,
    CA6740,
    CA6741,
    CA6742,
    CA6743,
    CA6744
  }

  public enum CostCenter {
    CC90801,
    CC71470
  }

  public enum Status {
    Draft,
    PendingL1Confirmation,
    WaitingForTransfer,
    SentToRacer,
    RejectedByRacer,
    Done,
    SettlementFailed
  }

  public enum RecordType {
    Emergency,
    DefaultRecordType
  }

  public override void updateSObjectFields() {
    this.underlyingSObject.Accounting_File_Name__c = this.accountingFileName;
    this.underlyingSObject.Amount__c = this.amount;
    this.underlyingSObject.Amount_in_SEK__c = this.amountInSEK;
    this.underlyingSObject.Comments__c = this.comments;
    this.underlyingSObject.Cost_Account__c = COST_ACCOUNT_ENUM_TO_PICKLIST_VALUE.get(
      this.costAccount
    );
    this.underlyingSObject.Cost_Center__c = COST_CENTER_ENUM_TO_PICKLIST_VALUE.get(
      this.costCenter
    );
    this.underlyingSObject.Currency__c = this.itemCurrency;
    this.underlyingSObject.Customer_Name__c = this.customerName;
    this.underlyingSObject.Date_of_Exchange_Calculation__c = this.dateOfExchangeCalculation;
    this.underlyingSObject.Deductible_Insurance_Amount__c = this.deductibleInsuranceAmount;
    this.underlyingSObject.Error_Message__c = this.errorMessage;
    this.underlyingSObject.Is_Insured__c = this.isInsured;
    this.underlyingSObject.Net_Amount_After_Deductible__c = this.netAmountAfterDeductible;
    this.underlyingSObject.Settlement__c = this.parentSettlementId;
    this.underlyingSObject.Status__c = STATUS_ENUM_TO_PICKLIST_VALUE.get(
      this.status
    );
    this.underlyingSObject.RecordTypeId = getRecordTypeIdByEnum(
      this.recordType
    );
  }

  public SettlementItem() {
    this.underlyingSObject = new Settlement_Item__c();
  }

  public SettlementItem(Settlement_Item__c si) {
    this.underlyingSObject = si;
    this.accountingFileName = si.Accounting_File_Name__c;
    this.amount = si.Amount__c;
    this.amountInSEK = si.Amount_in_SEK__c;
    this.comments = si.Comments__c;
    this.costAccount = COST_ACCOUNT_PICKLIST_VALUE_TO_ENUM.get(
      si.Cost_Account__c
    );
    this.costCenter = COST_CENTER_PICKLIST_VALUE_TO_ENUM.get(si.Cost_Center__c);
    this.itemCurrency = si.Currency__c;
    this.customerName = si.Customer_Name__c;
    this.dateOfExchangeCalculation = si.Date_of_Exchange_Calculation__c;
    this.deductibleInsuranceAmount = si.Deductible_Insurance_Amount__c;
    this.errorMessage = si.Error_Message__c;
    this.isInsured = si.Is_Insured__c;
    this.netAmountAfterDeductible = si.Net_Amount_After_Deductible__c;
    this.parentSettlementId = si.Settlement__c;
    this.status = STATUS_PICKLIST_VALUE_TO_ENUM.get(si.Status__c);
    this.recordType = getRecordTypeEnumById(si.RecordTypeId);
  }

  private static final Map<String, CostAccount> COST_ACCOUNT_PICKLIST_VALUE_TO_ENUM = new Map<String, CostAccount>{
    '6721' => CostAccount.CA6721,
    '6722' => CostAccount.CA6722,
    '6727' => CostAccount.CA6727,
    '6730' => CostAccount.CA6730,
    '6731' => CostAccount.CA6731,
    '6732' => CostAccount.CA6732,
    '6733' => CostAccount.CA6733,
    '6734' => CostAccount.CA6734,
    '6735' => CostAccount.CA6735,
    '6736' => CostAccount.CA6736,
    '6737' => CostAccount.CA6737,
    '6738' => CostAccount.CA6738,
    '6739' => CostAccount.CA6739,
    '6740' => CostAccount.CA6740,
    '6741' => CostAccount.CA6741,
    '6742' => CostAccount.CA6742,
    '6743' => CostAccount.CA6743,
    '6744' => CostAccount.CA6744
  };

  private static final Map<CostAccount, String> COST_ACCOUNT_ENUM_TO_PICKLIST_VALUE = new Map<CostAccount, String>{
    CostAccount.CA6721 => '6721',
    CostAccount.CA6722 => '6722',
    CostAccount.CA6727 => '6727',
    CostAccount.CA6730 => '6730',
    CostAccount.CA6731 => '6731',
    CostAccount.CA6732 => '6732',
    CostAccount.CA6733 => '6733',
    CostAccount.CA6734 => '6734',
    CostAccount.CA6735 => '6735',
    CostAccount.CA6736 => '6736',
    CostAccount.CA6737 => '6737',
    CostAccount.CA6738 => '6738',
    CostAccount.CA6739 => '6739',
    CostAccount.CA6740 => '6740',
    CostAccount.CA6741 => '6741',
    CostAccount.CA6742 => '6742',
    CostAccount.CA6743 => '6743',
    CostAccount.CA6744 => '6744'
  };

  private static final Map<String, CostCenter> COST_CENTER_PICKLIST_VALUE_TO_ENUM = new Map<String, CostCenter>{
    '90801' => CostCenter.CC90801,
    '71470' => CostCenter.CC71470
  };

  private static final Map<CostCenter, String> COST_CENTER_ENUM_TO_PICKLIST_VALUE = new Map<CostCenter, String>{
    CostCenter.CC90801 => '90801',
    CostCenter.CC71470 => '71470'
  };

  private static final Map<String, Status> STATUS_PICKLIST_VALUE_TO_ENUM = new Map<String, Status>{
    'Draft' => Status.Draft,
    'Pending L1 confirmation' => Status.PendingL1Confirmation,
    'Waiting for transfer' => Status.WaitingForTransfer,
    'Sent to Racer' => Status.SentToRacer,
    'Rejected by Racer' => Status.RejectedByRacer,
    'Done' => Status.Done,
    'Settlement failed' => Status.SettlementFailed
  };

  private static final Map<Status, String> STATUS_ENUM_TO_PICKLIST_VALUE = new Map<Status, String>{
    Status.Draft => 'Draft',
    Status.PendingL1Confirmation => 'Pending L1 confirmation',
    Status.WaitingForTransfer => 'Waiting for transfer',
    Status.SentToRacer => 'Sent to Racer',
    Status.RejectedByRacer => 'Rejected by Racer',
    Status.Done => 'Done',
    Status.SettlementFailed => 'Settlement failed'
  };

  private static Map<RecordType, String> recordTypeToEnumToDeveloperName = new Map<RecordType, String>{
    RecordType.Emergency => 'Emergency',
    RecordType.DefaultRecordType => 'Default Record Type'
  };

  private static Map<String, RecordType> recordTypeDeveloperNameToEnum = new Map<String, RecordType>{
    'Emergency' => RecordType.Emergency,
    'Default Record Type' => RecordType.DefaultRecordType
  };
  private static Map<RecordType, Id> recordTypeEnumToId = new Map<RecordType, Id>();
  private static Map<Id, RecordType> recordTypeIdToEnum = new Map<Id, RecordType>();

  public static Id getRecordTypeIdByEnum(RecordType rt) {
    Id rtId = recordTypeEnumToId.get(rt);
    if (rtId == null) {
      rtId = Schema.SObjectType.Settlement_Item__c.getRecordTypeInfosByName()
        .get(recordTypeToEnumToDeveloperName.get(rt))
        .getRecordTypeId();
      recordTypeEnumToId.put(rt, rtId);
      recordTypeIdToEnum.put(rtId, rt);
    }
    return rtId;
  }

  private static RecordType getRecordTypeEnumById(Id rtId) {
    if (rtId == null) {
      return null;
    }

    RecordType rt = recordTypeIdToEnum.get(rtId);
    if (rt == null) {
      rt = recordTypeDeveloperNameToEnum.get(
        Schema.SObjectType.Settlement_Item__c.getRecordTypeInfosById()
          .get(rtId)
          .getName()
      );
      recordTypeEnumToId.put(rt, rtId);
      recordTypeIdToEnum.put(rtId, rt);
    }
    return rt;
  }
}