sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/Settlement_Item__c.object-meta.xml
<CustomObject>
    <description>The combination of one customer and cost account. At settlement file can contain several passenger and each passenger several reasons for compensation.</description>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Settlement Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount to pay for this settlement item</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Account__c.field-meta.xml
<CustomField>
    <fullName>Cost_Account__c</fullName>
    <label>Cost Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6733</fullName>
                <label>6733 - Goodwill Compensation</label>
            </value>
            <value>
                <fullName>6741</fullName>
                <label>6741 - Liability - Baggage Damaged</label>
            </value>
            <value>
                <fullName>6742</fullName>
                <label>6742 - Liability - Baggage Delayed/missing/lost</label>
            </value>
            <value>
                <fullName>6743</fullName>
                <label>6743 - Liability - Baggage Pilfered</label>
            </value>
            <value>
                <fullName>6738</fullName>
                <label>6738 - Liability - Care (Meal, Hotel, Transportation)</label>
            </value>
            <value>
                <fullName>6721</fullName>
                <label>6721 - Liability - Denied Boarding Compensation</label>
            </value>
            <value>
                <fullName>6722</fullName>
                <label>6722 - Liability - Downgrading Compensation</label>
            </value>
            <value>
                <fullName>6727</fullName>
                <label>6727 - Liability - EU 261 Compensation</label>
            </value>
            <value>
                <fullName>6735</fullName>
                <label>6735 - Liability - Other</label>
            </value>
            <value>
                <fullName>6737</fullName>
                <label>6737 - Refund of tickets and ancillary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <inlineHelpText>Settlement to which this settlement belongs to</inlineHelpText>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/classes/ConstructTextAccountFileTest.cls
@isTest
public class ConstructTextAccountFileTest {
  public static testMethod void testConstructAccFiles() {
    List<AccountFile> lstAccFiles = new List<AccountFile>();
    
    Settlement__c sett = new Settlement__c();
    sett.Currency__c = 'SEK';
    sett.Date_of_Exchange_Calculation__c = date.Today().addDays(-3);
    insert sett;
    
    Settlement_Item__c settItem = new Settlement_Item__c ();
    settItem.Cost_Account__c = '6727';
    settItem.Amount__c = 234;
    settItem.Settlement__c = sett.Id;
    
    insert settItem;
    
   String accFile = ConstructTextAccountFileController.getAccountFileText('SEK');
   System.debug('accFile**'+accFile);
  }
}