sas-core/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Settlement is a single payment to a customer about a specific claim, and a single claim can have several settlements made related to it.</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Settlement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the Settlement</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement__c/fields/Date_of_Exchange_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Exchange_Calculation__c</fullName>
    <label>Date of Exchange Calculation</label>
    <type>Date</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/Settlement_Item__c.object-meta.xml
<CustomObject>
    <description>The combination of one customer and cost account. At settlement file can contain several passenger and each passenger several reasons for compensation.</description>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Settlement Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sas-core/main/default/objects/Settlement_Item__c/fields/Accounting_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_File_Name__c</fullName>
    <label>Accounting File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount to pay for this settlement item</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Account__c.field-meta.xml
<CustomField>
    <fullName>Cost_Account__c</fullName>
    <label>Cost Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6733</fullName>
                <label>6733 - Goodwill Compensation</label>
            </value>
            <value>
                <fullName>6741</fullName>
                <label>6741 - Liability - Baggage Damaged</label>
            </value>
            <value>
                <fullName>6742</fullName>
                <label>6742 - Liability - Baggage Delayed/missing/lost</label>
            </value>
            <value>
                <fullName>6743</fullName>
                <label>6743 - Liability - Baggage Pilfered</label>
            </value>
            <value>
                <fullName>6738</fullName>
                <label>6738 - Liability - Care (Meal, Hotel, Transportation)</label>
            </value>
            <value>
                <fullName>6721</fullName>
                <label>6721 - Liability - Denied Boarding Compensation</label>
            </value>
            <value>
                <fullName>6722</fullName>
                <label>6722 - Liability - Downgrading Compensation</label>
            </value>
            <value>
                <fullName>6727</fullName>
                <label>6727 - Liability - EU 261 Compensation</label>
            </value>
            <value>
                <fullName>6735</fullName>
                <label>6735 - Liability - Other</label>
            </value>
            <value>
                <fullName>6737</fullName>
                <label>6737 - Refund of tickets and ancillary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90801</fullName>
                <default>true</default>
                <label>90801</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Name of customer for this settlement item</description>
    <label>Customer Name</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Is_Insured__c.field-meta.xml
<CustomField>
    <fullName>Is_Insured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the settlement item covered by SAS's insurance.</description>
    <label>Is Insured</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Net_Amount_After_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_After_Deductible__c</fullName>
    <description>The amount which SAS can claim from our insurance companyin the same currency as the settlement item. Set only for claim types against which SAS is insured.</description>
    <inlineHelpText>The amount which SAS can claim from our insurance companyin the same currency as the settlement item. Set only for claim types against which SAS is insured.</inlineHelpText>
    <label>Net Amount After Deductible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <inlineHelpText>Settlement to which this settlement belongs to</inlineHelpText>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sas-core/main/default/objects/Settlement_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending L1 confirmation</fullName>
            </value>
            <value>
                <fullName>Waiting for transfer</fullName>
            </value>
            <value>
                <fullName>Sent to Racer</fullName>
            </value>
            <value>
                <fullName>Rejected by Racer</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/selectors/SettlementItemsSelector.cls
public inherited sharing class SettlementItemsSelector extends fflib_SObjectSelector {
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Settlement_Item__c.Id,
      Settlement_Item__c.Name,
      Settlement_Item__c.CreatedDate,
      Settlement_Item__c.LastModifiedDate,
      Settlement_Item__c.Accounting_File_Name__c,
      Settlement_Item__c.Amount__c,
      Settlement_Item__c.Comments__c,
      Settlement_Item__c.Cost_Account__c,
      Settlement_Item__c.Cost_Center__c,
      Settlement_Item__c.Currency__c,
      Settlement_Item__c.Customer_Name__c,
      Settlement_Item__c.Is_Insured__c,
      Settlement_Item__c.Net_Amount_After_Deductible__c,
      Settlement_Item__c.Settlement__c,
      Settlement_Item__c.Status__c,
      Settlement_Item__c.RecordTypeId
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Settlement_Item__c.SObjectType;
  }

  public static SettlementItemsSelector newInstance() {
    return (SettlementItemsSelector) SAS_Service_Application.Selector.newInstance(
      Settlement_Item__c.SObjectType
    );
  }

  public List<Settlement_Item__c> selectById(Set<Id> ids) {
    return (List<Settlement_Item__c>) selectSObjectsById(ids);
  }

  public List<Settlement_Item__c> selectByAccountingFileName(
    String accountingFileName
  ) {
    return (List<Settlement_Item__c>) Database.query(
      newQueryFactory()
        .setCondition('Accounting_File_Name__c =:accountingFileName')
        .toSOQL()
    );
  }

  public List<Settlement_Item__c> selectBySettlementIds(Set<Id> settlementIds) {
    return (List<Settlement_Item__c>) Database.query(
      newQueryFactory().setCondition('Settlement__c in :settlementIds').toSOQL()
    );
  }

  public List<Settlement_Item__c> selectWaitingForTransferByCurrency(
    List<String> currencies
  ) {
    String statusToTake = 'Waiting for transfer';

    return (List<Settlement_Item__c>) Database.query(
      newQueryFactory()
        .selectField('Settlement__r.Date_of_Exchange_Calculation__c')
        .setCondition(
          'Status__c = :statusToTake AND Currency__c in :currencies'
        )
        .toSOQL()
    );
  }

  public override String getOrderBy() {
    return 'Name';
  }
}